### PR TITLE
Validate Lamas Finance - LMF

### PR DESCRIPTION
**Pull request by maxheisenberg22**
# Validate [LMF](https://solscan.io/token/LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/lamasfinance/status/1733075103494406637 The quoted tweet provides significant evidence of community support.
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/lamas-finance

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by vennluu-mq** [comment]
I can hereby attest that the provided information is accurate and the token is valid.

- [x] Mint address: LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- [x] Symbol: LMF  
- [x] Token Decimals: 9  
- [x] Token icon: https://www.lamas.co/resource/lmf_token.png  
- [x] On-chain metadata matches: https://solscan.io/token/LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- [x] No duplication on Jupiter's strict list  
- [x] Coingecko URL: https://www.coingecko.com/en/coins/lamas-finance

**Comment by chrisnebo2** [comment]
I hereby confirm the accuracy of the provided details and the validity of the token.

- [x] Mint address: LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- [x] Token Symbol: LMF  
- [x] Token Decimals: 9  
- [x] Token Icon: https://www.lamas.co/resource/lmf_token.png  
- [x] On-chain metadata verification: https://solscan.io/token/LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- [x] Not listed in Jupiter's strict list of duplication  
- [x] Coingecko URL: https://www.coingecko.com/en/coins/lamas-finance

**Comment by cakrakahn** [comment]
I can hereby attest that the provided information is accurate and the token is valid.

 Mint address: LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU
 Symbol: LMF
 Token Decimals: 9
 Token icon: https://www.lamas.co/resource/lmf_token.png
 On-chain metadata matches: https://solscan.io/token/LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU
 No duplication on Jupiter's strict list
 Coingecko URL: https://www.coingecko.com/en/coins/lamas-finance

**Comment by charles101-44** [comment]
I can hereby attest that the provided information is accurate and the token is valid.

- [x] Mint address: LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- [x] Symbol: LMF  
- [x] Token Decimals: 9  
- [x] Token icon: https://www.lamas.co/resource/lmf_token.png  
- [x] On-chain metadata matches: https://solscan.io/token/LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- [x] No duplication on Jupiter's strict list  
- [x] Coingecko URL: https://www.coingecko.com/en/coins/lamas-finance

**Comment by lavensoft** [comment]
Dear folks, please help us push the Jupiter validation process by commenting on this pull request: https://github.com/jup-ag/token-list/pull/498

Sample comment:

I can hereby attest that the provided information is accurate and the token is valid.

- [x] Mint address: LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- [x] Symbol: LMF  
- [x] Token Decimals: 9  
- [x] Token icon: https://www.lamas.co/resource/lmf_token.png  
- [x] On-chain metadata matches: https://solscan.io/token/LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- [x] No duplication on Jupiter's strict list  
- [x] Coingecko URL: https://www.coingecko.com/en/coins/lamas-finance

**Comment by nwalineme** [comment]
I can hereby attest that the provided information is accurate and the token is valid.

- [x] Mint address: LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- [x] Symbol: LMF  
- [x] Token Decimals: 9  
- [x] Token icon: https://www.lamas.co/resource/lmf_token.png  
- [x] On-chain metadata matches: https://solscan.io/token/LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- [x] No duplication on Jupiter's strict list  
- [x] Coingecko URL: https://www.coingecko.com/en/coins/lamas-finance

**Comment by ngocgiang99** [comment]
I can hereby attest that the provided information is accurate and the token is valid.

- [x] Mint address: LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- [x] Symbol: LMF  
- [x] Token Decimals: 9  
- [x] Token icon: https://www.lamas.co/resource/lmf_token.png  
- [x] On-chain metadata matches: https://solscan.io/token/LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- [x] No duplication on Jupiter's strict list  
- [x] Coingecko URL: https://www.coingecko.com/en/coins/lamas-finance

**Comment by Haykaydedon** [comment]
Good project 😍

**Comment by chenklut** [comment]
leetsgoo lmf

**Comment by shaggy131** [comment]
I can hereby attest that the provided information is accurate and the token is valid.

- Mint address: LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- Symbol: LMF  
- Token Decimals: 9  
- Token icon: https://www.lamas.co/resource/lmf_token.png  
- On-chain metadata matches: https://solscan.io/token/LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- No duplication on Jupiter's strict list  
- Coingecko URL: https://www.coingecko.com/en/coins/lamas-finance

**Comment by nuvoheo** [comment]
Dear folks, please help us push the Jupiter validation process by commenting on this pull request: https://github.com/jup-ag/token-list/pull/498

Sample comment:

I can hereby attest that the provided information is accurate and the token is valid.

- [x] Mint address: LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- [x] Symbol: LMF  
- [x] Token Decimals: 9  
- [x] Token icon: https://www.lamas.co/resource/lmf_token.png  
- [x] On-chain metadata matches: https://solscan.io/token/LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- [x] No duplication on Jupiter's strict list  
- [x] Coingecko URL: https://www.coingecko.com/en/coins/lamas-finance

**Review by Timoon21 — APPROVED** [review]

**Comment by js303u** [comment]
I can hereby attest that the provided information is accurate and the token is valid.

 Mint address: LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU
 Symbol: LMF
 Token Decimals: 9
 Token icon: https://www.lamas.co/resource/lmf_token.png
 On-chain metadata matches: https://solscan.io/token/LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU
 No duplication on Jupiter's strict list
 Coingecko URL: https://www.coingecko.com/en/coins/lamas-finance

**Comment by leeCSC** [comment]
I can hereby attest that the provided information is accurate and the token is valid.

- [x] Mint address: LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU  
- [x] Symbol: LMF  
- [x] Token Decimals: 9  
- [x] Token icon: lamas.co/resource/lmf_t…  
- [x] On-chain metadata matches: solscan.io/token/LMFzmYL6…  
- [x] No duplication on Jupiter's strict list  
- [x] Coingecko URL: coingecko.com/en/coins/lamas…

**Comment by ConFluxDefi** [comment]
I can hereby attest that the provided information is accurate and the token is valid.

Mint address: LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU
Symbol: LMF
Token Decimals: 9
Token icon: https://www.lamas.co/resource/lmf_token.png
On-chain metadata matches: https://solscan.io/token/LMFzmYL6y1FX8HsEmZ6yNKNzercBmtmpg2ZoLwuUboU
No duplication on Jupiter's strict list
Coingecko URL: https://www.coingecko.com/en/coins/lamas-finance

**Pull request merged**
