### PR TITLE
PJ

### PR DESCRIPTION
**Pull request by pjdevsol**
# Validate [PJ](https://solscan.io/token/CSSFYjzNYM8GnSwqbEbKpB4dHicaQynHMhza87p5anaN)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/PJonSOL/status/1793547112078291153
- Coingecko/ CMC URL (If available): Applied but not yet verified

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
token is too new, please come back in 10 days

**Comment by pinguvip69** [comment]
This was to bump our original PR can you please check it? https://github.com/jup-ag/token-list/pull/4015

**Comment by pjdevsol** [comment]
> token is too new, please come back in 10 days

This was bumping our original PR can you please check it? https://github.com/jup-ag/token-list/pull/4015

**Comment by pjdevsol** [comment]
@Jymfletzfur

**Pull request closed without merging**
