### PR TITLE
Validate Token - TTIGER

### PR DESCRIPTION
**Pull request by TysonsTiger**
# Validate Token [TTIGER](https://solscan.io/token/H1C5T6BnmbkBacLCaYoczxFQ7qB5Ggx85hJFAL2HHNBj)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/tysonstiger69/status/1781739090104172578

- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

On Coinranking.com and coinpaprika.com

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by JohnRM992** [comment]
Bro change the Main tittle to Validate TOKEN or something, i got rejected for that...also delete the space in the X on the checkmarks, otherwise it won't get recognized as check

**Comment by TysonsTiger** [comment]
> Bro change the Main tittle to Validate TOKEN or something, i got rejected for that...also delete the space in the X on the checkmarks, otherwise it won't get recognized as check

I deleted the spaces by the x's and fixed the decimals in the csv to resolve that... how do I change the title to "Validate Token"?

**Comment by TysonsTiger** [comment]
Is THAT ok for Title "Validate Token TTIGER" ? The template tells you to put in the ticker name...

**Comment by JohnRM992** [comment]
> Is THAT ok for Title "Validate Token TTIGER" ? The template tells you to put in the ticker name...

You might found it already but....on the right sid of the "main" title should be a edit button or something

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
