### PR TITLE
pani - pani

### PR DESCRIPTION
**Pull request by Fossilite**
# Validate [pani](https://solscan.io/token/7cvxhhATeo9k5NoP7aPh9o8QCJb56WsXbzvfT9Ejr7J9)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Pani_onsol/status/1790822114112483475- Coingecko/ CMC URL (If available):

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Mechwv — COMMENTED** [review]
ok

**Comment by Defavl** [comment]
Greta community $pani on top

**Review by Mechwv — COMMENTED** [review]
ok2

**Review by Theantijeet — COMMENTED** [review]
Looks good

**Comment by RXMysteryHunter** [comment]
Lets get it

**Review by Defavl — COMMENTED** [review]
Honestly the best and strongest community of people that strive to better what they participate in. $pani is objectively the best coin out there

**Review by RXMysteryHunter — COMMENTED** [review]
Pani on top

**Comment by Mclovincrypto101** [comment]
Amazing $pani

**Comment by Jymfletzfur** [comment]
token is too new and does not appear to meet any exemptions, please come back in 2 weeks

**Comment by Fossilite** [comment]
Hi I would like to request another request for Strict list. It is
absolutely paramount as there are many copy tokens. We have an active
community, and the delay of this submission is hurting the reputation of
our project.

Please if you can verify this pr request it would help tremendously.

Pani Team

**Review by Fossilite — COMMENTED** [review]
Hi I was informed to return two weeks after the initial pull request. I am hoping our project merits consideration for Jupiter Strict List..

**Comment by Fossilite** [comment]
> token is too new and does not appear to meet any exemptions, please come back in 2 weeks

We are back! What are next steps for consideration? Thanks :)

**Pull request closed without merging**
