### PR TITLE
PEW for BOME and PEPE = PEW

### PR DESCRIPTION
**Pull request by LukeOrDrake**
# Validate [PEW] (https://solscan.io/token/5zgTYTDK836G2Fc4ZLQp4rsyi78pAbuDr4qaQUE1pump)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/pew4sol/status/1797914590098915397
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/pew4sol  /  https://coinmarketcap.com/dexscan/solana/3gG9aTPX9vRgMvKnby5EBjLPAPSHbzX7ub3NbidTYF3B/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by LukeOrDrake — COMMENTED** [review]
Looks good

**Comment by Jymfletzfur** [comment]
please come into discord

**Comment by Jymfletzfur** [comment]
Please use the image in the metadata:

https://ipfs.io/ipfs/QmaTn8rE2b2kf1tz5AJHGKokLkxQe4BZaqJRwYXQStkPxz

**Comment by LukeOrDrake** [comment]
Doing new PR

**Pull request closed without merging**
