### PR TITLE
HELLO Labs validation token listing

### PR DESCRIPTION
**Pull request by dutchsociety**
# Validate [HELLO](https://solscan.io/token/4h49hPGphLNJNDRyiBwzvKoasR3rw1WJCEv19PhUbSS4)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/thehellolabs/status/1799190311325053393?s=46&t=sRCYMSwr8l-hFGBr0vHbwQ
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/hello-labs / https://www.coingecko.com/en/coins/hello

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
the name is Hello Token

can you please amend to match that

**Comment by dutchsociety** [comment]
Update done, can you guys please revisit the merge? Thank you.

**Comment by dutchsociety** [comment]
@Jymfletzfur can you please revisit the updates? Thank you and have an amazing weekend.

**Comment by Jymfletzfur** [comment]
Hello Token

not HELLO Token

feel free to ping me in the discord as well once you amend this

**Comment by dutchsociety** [comment]
@Jymfletzfur just committed the update, thank you for your quick response; just wondering where Hello Token is coming from because we have submitted it as HELLO Labs, and ticker HELLO, atleast on CMC though.

**Comment by dutchsociety** [comment]
@Jymfletzfur can we please complete the validation? Thank you in advance

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Comment by 9yoi** [comment]
merged here: https://github.com/jup-ag/token-list/pull/4733

**Pull request closed without merging**
