### PR TITLE
Picasso

### PR DESCRIPTION
**Pull request by doradelta**
# Validate [PICA](https://solscan.io/token/966vsqwoS3ZBrHesTyAvE7esFV2kaHaDFLLXs4asPdLJ)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/Picasso_Network/status/1793302088027410670
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/picasso

## Validation (Please check off boxes):
- [✅] The metadata provided in the PR matches what is on-chain (Mandatory)
- [✅] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [✅] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [✅] My change matches the format in the file (no spaces between fields).
- [✅] My token is already live and trading on Jupiter.
- [✅] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [✅] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by doradelta** [comment]
Mint address: 966vsqwoS3ZBrHesTyAvE7esFV2kaHaDFLLXs4asPdLJ
Symbol: PICA
Token Decimals: 9
Token icon: https://arweave.net/ZwYqSsMDWenrJd20uNAj-lGrgoNF0rGuYSIF_EYgwxg?ext=png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
PR inappropriately attempts to alter files other than the token csv

**Comment by doradelta** [comment]
I created a new PR, lmk to close this and sorry for the inconveniences:
https://github.com/jup-ag/token-list/pull/3925

**Comment by doradelta** [comment]
> PR inappropriately attempts to alter files other than the token csv
I created a new PR, lmk to close this and sorry for the inconveniences:
https://github.com/jup-ag/token-list/pull/3925

**Pull request closed without merging**
