### PR TITLE
Validate HAMWTR

### PR DESCRIPTION
**Pull request by YouKnowEno**
# Validate [HAMWTR](https://solscan.io/token/HSwR3tZuxQKq8ddz9YxR4BX65Znm6MNdWGURw3x5FJQi)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/lovehamwater/status/1784546398064595444?s=46&t=8Y86nNEKBv_0c1M-CIwPXA
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/dexscan/solana/5LAWwqGL9m3CnS5P6CTG2QUaeCNLzzVdv8G8u1Qvpo62/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by renji78 — COMMENTED** [review]
I verified the information provided here is accurate. The token is valid.

[v]  Mint address: HSwR3tZuxQKq8ddz9YxR4BX65Znm6MNdWGURw3x5FJQi
[v]  Symbol: HAMWTR
[v]  Token Decimals: 9
[v]  Token icon:https://raw.githubusercontent.com/YouKnowEno/token-imgs/main/HAMWTR.jpeg
[v]  On-chain metadata matches
[v]  No duplication on Jupiter's strict list

**Review by slatticus11 — COMMENTED** [review]
I can hereby attest that the provided information is accurate, and the token is valid. 

Template:

[x]  Mint address: HSwR3tZuxQKq8ddz9YxR4BX65Znm6MNdWGURw3x5FJQi
[x]  Symbol: HAMWTR
[x]  Token Decimals: 9
[x]  Token icon:https://raw.githubusercontent.com/YouKnowEno/token-imgs/main/HAMWTR.jpeg
[x]  On-chain metadata matches
[x]  No duplication on Jupiter's strict list

**Review by renji788 — COMMENTED** [review]
I hereby certify that the provided information are accurate, and the token is valid.

[v] Mint address: HSwR3tZuxQKq8ddz9YxR4BX65Znm6MNdWGURw3x5FJQi
[v] Symbol: HAMWTR
[v] Token Decimals: 9
[v] Token icon:https://raw.githubusercontent.com/YouKnowEno/token-imgs/main/HAMWTR.jpeg
[v] On-chain metadata matches
[v] No duplication on Jupiter's strict list

**Comment by slatticus11** [comment]
I can hereby attest that the provided information is accurate, and the token is valid. 

Template:

[x]  Mint address: HSwR3tZuxQKq8ddz9YxR4BX65Znm6MNdWGURw3x5FJQi
[x]  Symbol: HAMWTR
[x]  Token Decimals: 9
[x]  Token icon:https://raw.githubusercontent.com/YouKnowEno/token-imgs/main/HAMWTR.jpeg
[x]  On-chain metadata matches
[x]  No duplication on Jupiter's strict list

**Comment by Dominik123hun** [comment]
I verified the info, its accurate. The token is valid.

[v] Mint address: HSwR3tZuxQKq8ddz9YxR4BX65Znm6MNdWGURw3x5FJQi
[v] Symbol: HAMWTR
[v] Token Decimals: 9
[v] Token icon:https://raw.githubusercontent.com/YouKnowEno/token-imgs/main/HAMWTR.jpeg
[v] On-chain metadata matches
[v] No duplication on Jupiter's strict list

**Review by Dominik123hun — COMMENTED** [review]
I can hereby attest that the provided information is accurate, and the token is valid. 

Template:

[x]  Mint address: HSwR3tZuxQKq8ddz9YxR4BX65Znm6MNdWGURw3x5FJQi
[x]  Symbol: HAMWTR
[x]  Token Decimals: 9
[x]  Token icon:https://raw.githubusercontent.com/YouKnowEno/token-imgs/main/HAMWTR.jpeg
[x]  On-chain metadata matches
[x]  No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
please use the exact image link from the metadata

**Comment by slatticus11** [comment]
https://node1.irys.xyz/tYbgasKcMQhtUNQ-wjrpGLrD2C6ylEzkuqN-vzTJ-L4

**Comment by slatticus11** [comment]
> please use the exact image link from the metadata

https://node1.irys.xyz/tYbgasKcMQhtUNQ-wjrpGLrD2C6ylEzkuqN-vzTJ-L4

**Comment by YouKnowEno** [comment]
Image has been updated! Muchos gracias

**Comment by renji78** [comment]
I can hereby attest that the provided updated information is accurate, and the token is valid.

[x] Mint address: HSwR3tZuxQKq8ddz9YxR4BX65Znm6MNdWGURw3x5FJQi
[x] Symbol: HAMWTR
[x] Token Decimals: 9
[x] Token icon:https://raw.githubusercontent.com/YouKnowEno/token-imgs/main/HAMWTR.jpeg
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by slatticus11** [comment]
I can hereby attest that the provided updated information is accurate, and the token is valid.

[x] Mint address: HSwR3tZuxQKq8ddz9YxR4BX65Znm6MNdWGURw3x5FJQi
[x] Symbol: HAMWTR
[x] Token Decimals: 9
[x] Token icon:https://raw.githubusercontent.com/YouKnowEno/token-imgs/main/HAMWTR.jpeg
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by Dominik123hun** [comment]
I can hereby attest that the provided updated information is accurate, and the token is valid.

[x] Mint address: HSwR3tZuxQKq8ddz9YxR4BX65Znm6MNdWGURw3x5FJQi
[x] Symbol: HAMWTR
[x] Token Decimals: 9
[x] Token icon:https://raw.githubusercontent.com/YouKnowEno/token-imgs/main/HAMWTR.jpeg
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
This is the image:

https://node1.irys.xyz/tYbgasKcMQhtUNQ-wjrpGLrD2C6ylEzkuqN-vzTJ-L4

**Comment by renji78** [comment]
I can hereby attest that the provided updated information is accurate, and the token is valid.

[x] Mint address: HSwR3tZuxQKq8ddz9YxR4BX65Znm6MNdWGURw3x5FJQi
[x] Symbol: HAMWTR
[x] Token Decimals: 9
[x] Token icon:https://node1.irys.xyz/tYbgasKcMQhtUNQ-wjrpGLrD2C6ylEzkuqN-vzTJ-L4
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
