### PR TITLE
Validate $noosum

### PR DESCRIPTION
**Pull request by alex-awin**
# Validate [$NOOSUM](https://solscan.io/token/7YHPdtmjuEmgEA9bTWAWNSULacbjADxEKENL3XWL1RXC)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/noosumsol/status/1808339374020428131?s=46&t=IZMgQqQuR61sNaCs-CQjZA
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/gabin-noosum

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by alex-awin** [comment]
- [x] Mint Address: 7YHPdtmjuEmgEA9bTWAWNSULacbjADxEKENL3XWL1RXC
- [x] Symbol: NOOSUM
- [x] Token Decimals: 6
- [x] Token icon: https://pbs.twimg.com/profile_images/1800276772296306688/2rTBSveS_400x400.jpg\
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
PR inappropriately attempts to alter files other than the token csv

**Comment by alex-awin** [comment]
Hi, where is the token csv file? I don't see it

**Comment by alex-awin** [comment]
Hi, I made a new request. I reverted the template and added NOOSUM info into the token csv
https://github.com/jup-ag/token-list/pull/4892

**Pull request closed without merging**
