### PR TITLE
Validate KIWI

### PR DESCRIPTION
**Pull request by bryon-cryptoconsults**
# Validate [KIWI](https://solscan.io/token/66Qq2qS67K4L5xQ3xUTinCyxzdPeZQG1R1ipK8jrY7gc)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/playtheheist/status/1755755160377123029
- Coingecko/ CMC URL (If available): N/A

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by bryon-cryptoconsults** [comment]
Tweet attestation will be added at launch

**Review by 9yoi — DISMISSED** [review]

**Comment by 9yoi** [comment]
pre approved, pending attestation tweet for the address

**Comment by bryon-cryptoconsults** [comment]
> Attestations

Attestation tweet posted and linked.

**Comment by bryon-cryptoconsults** [comment]
The CA changed. Updated PR and Tweet.

**Review by 9yoi — APPROVED** [review]

**Comment by bozocode** [comment]
Hey @9yoi can you please take a look at my PR at https://github.com/jup-ag/token-list/pull/1228. It fulfils all criteria. Not sure why are you guys keeping us hanging. Not a good look for Jupiter

**Pull request merged**
