### PR TITLE
Validate DYOR

### PR DESCRIPTION
**Pull request by doug-andrade**
# Validate [DYOR](https://solscan.io/token/DidjvEEFLk31yEjTkxf6CfNi6RcsUjPS6qHNTVzhApNU)

## Attestations (Please provide links):

- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/BookOfDYOR/status/1782822844755259535
- Coingecko/ CMC URL (If available): https://www.geckoterminal.com/solana/pools/9daL7v7sYGRVEYKPJiwhRSLWbayefpc47hBev1b4ZsrE

## Validation (Please check off boxes):

- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)

## Acknowledgement (Please check off boxes)

- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by doug-andrade** [comment]
[x] Mint address: DidjvEEFLk31yEjTkxf6CfNi6RcsUjPS6qHNTVzhApNU
[x] Symbol: DYOR
[x] Token Decimals: 9
[x] Token icon: https://cf-ipfs.com/ipfs/QmTuJ5RsgS65a2zMQyrgeXZnePgwzmR4pmwHH8Q9TpTC8a
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by akame1939** [comment]
[x] Mint address: DidjvEEFLk31yEjTkxf6CfNi6RcsUjPS6qHNTVzhApNU
[x] Symbol: DYOR
[x] Token Decimals: 9
[x] Token icon: https://cf-ipfs.com/ipfs/QmTuJ5RsgS65a2zMQyrgeXZnePgwzmR4pmwHH8Q9TpTC8a
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by hdristerfloat27** [comment]
[x] Mint address: DidjvEEFLk31yEjTkxf6CfNi6RcsUjPS6qHNTVzhApNU
[x] Symbol: DYOR
[x] Token Decimals: 9
[x] Token icon: https://cf-ipfs.com/ipfs/QmTuJ5RsgS65a2zMQyrgeXZnePgwzmR4pmwHH8Q9TpTC8a
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by immortalofaeg1** [comment]
[x] Mint address: DidjvEEFLk31yEjTkxf6CfNi6RcsUjPS6qHNTVzhApNU
[x] Symbol: DYOR
[x] Token Decimals: 9
[x] Token icon: https://cf-ipfs.com/ipfs/QmTuJ5RsgS65a2zMQyrgeXZnePgwzmR4pmwHH8Q9TpTC8a
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by matgoskee** [comment]
[x] Mint address: DidjvEEFLk31yEjTkxf6CfNi6RcsUjPS6qHNTVzhApNU
[x] Symbol: DYOR
[x] Token Decimals: 9
[x] Token icon: https://cf-ipfs.com/ipfs/QmTuJ5RsgS65a2zMQyrgeXZnePgwzmR4pmwHH8Q9TpTC8a
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by caldwell11dav** [comment]
[x] Mint address: DidjvEEFLk31yEjTkxf6CfNi6RcsUjPS6qHNTVzhApNU
[x] Symbol: DYOR
[x] Token Decimals: 9
[x] Token icon: https://cf-ipfs.com/ipfs/QmTuJ5RsgS65a2zMQyrgeXZnePgwzmR4pmwHH8Q9TpTC8a
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by doug-andrade** [comment]
**Update from the $DYOR Team:**
image

**Comment by doug-andrade** [comment]
Another Attestation Tweet:

https://x.com/_solanabull/status/1782899762330501451?s=46&t=qbsWtcgtXJ31nXPohOoplw

**Pull request closed without merging**
