### PR TITLE
Validate ISC

### PR DESCRIPTION
**Pull request by theISCTeam**
# Validate [ISC](https://solscan.io/token/J9BcrQfX4p9D1bvLzRNCbMDv8f44a9LFdeqNE4Yk2WMD)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/TheISCTeam/status/1655267396637306880
- Coingecko/ CMC URL (If available): Still working to get on CoinGecko/CMC

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by 0xSoju1** [comment]
[x] On-chain metadata matches the PR 
[x] Token address matches the tweet : J9BcrQfX4p9D1bvLzRNCbMDv8f44a9LFdeqNE4Yk2WMD
[x] No duplication on Jupiter's strict list
[x] Community validation -- idk, if you consider me community validation

**Comment by fluctlight-kayaba** [comment]
[x] Mint address: J9BcrQfX4p9D1bvLzRNCbMDv8f44a9LFdeqNE4Yk2WMD
[x] Symbol: ISC
[x] Token Decimals: 6
[x] Token icon: https://raw.githubusercontent.com/theISCTeam/isc_meta/master/logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by theISCTeam** [comment]
Community tweets:
https://twitter.com/0xSoju/status/1655399861058150402
https://twitter.com/cm_monstre/status/1655407712065421314

**Comment by meowmeof** [comment]
[x] Mint address: J9BcrQfX4p9D1bvLzRNCbMDv8f44a9LFdeqNE4Yk2WMD
[x] Symbol: ISC
[x] Token Decimals: 6
[x] Token icon: https://raw.githubusercontent.com/theISCTeam/isc_meta/master/logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by cutemonstersnft** [comment]
[x] Mint address: J9BcrQfX4p9D1bvLzRNCbMDv8f44a9LFdeqNE4Yk2WMD
[x] Symbol: ISC
[x] Token Decimals: 6
[x] Token icon: https://raw.githubusercontent.com/theISCTeam/isc_meta/master/logo.png
[x] Matches on-chain metadata
[x] There was no duplication on Jupiter's strict list.
[x] Community validation -- I am part of Solana community that is!

Link to tweet:
https://twitter.com/cm_monstre/status/1655407712065421314?s=20

**Comment by eugene-chen** [comment]
verified mint address, symbol, and decimals in this PR match what is on-chain.

**Review by Timoon21 — DISMISSED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] No duplication on CMC/CoinGecko
- [x] Community validation

**Review by meijiao — APPROVED** [review]

**Comment by devjohn58** [comment]
[x] Mint address: J9qyPtHnS4FJSfJ8Xok5oSv8JtyiMEBZTZD44xSJxUae
[x] Symbol: BULLANA
[x] Token Decimals: 0
[x] Token icon: https://node1.irys.xyz/y469EiR1DkzTrpjmtpeSRBOruchMYMWqGYHtrSZtuM4
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by nyether** [comment]
[x] Mint address: A2zmhp9g8Ybck3jc4oUqP2cVLiszUvzVeSB14C4iET7V
[x] Symbol: NYETHER
[x] Token Decimals: 9
[x] Token icon: : https://bafkreieblvb6x3ddtv3e6mqkhdnr2akxpfpz4yjnzbduhulbekkowvrhxu.ipfs.nftstorage.link/
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by nstein77** [comment]
[x] On-chain metadata matches the PR https://x.com/BeachClubSolana/status/1748158421604471143?s=20
[x] Mint address: Ho2FQgg65oM1zpYuEnC8fULpBnWtqRCTrXRP56AeyCci
[x] Symbol: SOLANA
[x] Token Decimals: 9
[x] Token icon: : https://pbs.twimg.com/media/GJ8HeIJakAA0EB3?format=jpg&name=medium
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

CMC Listing: https://coinmarketcap.com/currencies/solana-beach/

https://twitter.com/BeachClubSolana

https://x.com/BeachClubSolana/status/1748158421604471143?s=20

**Comment by apokalipsx** [comment]
[x] On-chain metadata matches the PR https://twitter.com/Simurg2024/status/1775317302214619536
[x] Mint address: UGTZrWMXc22cBeTxs4xVcShGcQmRwrQNmPMZufeqS65
[x] Symbol: SI
[x] Token Decimals: 9
[x] Token icon: https://drive.google.com/file/d/1Y2In9nz4pdDCCC5Ddd_Zj1zTfdDTyJ4C/view?usp=drive_link
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

https://twitter.com/Simurg2024

**Comment by hectorkeen** [comment]
[x] On-chain metadata matches the PR https://x.com/ai_techtrends2/status/1775433052983857600?s=20
[x] Mint address: 3iG5NRc36xaVnWKdFKw9HwDjG2Bf58YitCJmGUm7hrFJ
[x] Symbol: SOLANA
[x] Token Decimals: 6
[x] Token icon: : https://pbs.twimg.com/profile_images/1774927961252048896/5AcCKkOQ_400x400.jpg
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list


https://twitter.com/OrcatCommunity >>>

**Comment by Tristarcoin** [comment]
x] On-chain metadata matches the PR https://x.com/BeachClubSolana/status/1748158421604471143?s=20
[x] Mint : Bk87ydHHrC8wvgoGF6LcNTLcaNSQ1tLYYnU7boM4ZgRF
[x] Symbol: TRISTAR
[x] Token Decimals: 9
[x] Token icon: : https://bafkreiekpcazwv7t4h7ml6u4xw327bcorpq6xfmhti4mpuhrlu3djov4f4.ipfs.nftstorage.link/
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by GatotKaca-token** [comment]
# **Validate [Gatot Kaca Token](https://solscan.io/token/B44PqeTXGY3NaKhBupvNuEhQhjdNw2ko6Q5oFpHLCshM)**
## **Attestations :**

- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/KacaGkc28615/status/1802374913833218110?t=prOlpNmI2nhd90XhtBlvWg&s=19
- Coingecko/ CMC URL (If available): Still working to get on Coingecko/CMC

## **Validation :**

✅  The metadata provided in the PR matches what is on-chain (Mandatory)
✅  Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
✅ Mint : B44PqeTXGY3NaKhBupvNuEhQhjdNw2ko6Q5oFpHLCshM
✅ Symbol : GKC
✅ Token Decimals: 9
✅ Token icon: : https://d29fhpw069ctt2.cloudfront.net/clipart/88045/preview/wayang_Gatotkaca_preview_1a8f.png
✅ On-chain metadata matches
✅ No duplication on Jupiter's strict list
🗳️ Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)

## **Acknowledgement**
 ✅ My change matches the format in the file (no spaces between fields).
 ✅ My token is already live and trading on Jupiter.
 ✅ !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

**Pull request merged**
