### PR TITLE
Validate SOLNIC

### PR DESCRIPTION
**Pull request by SolnicCoin**
# Validate [SOLNIC](https://solscan.io/token/DeaKMzAeZja3Mh5okZE6WUvygLP3Lfuvm6Rg78HqXTz9)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/solniccoin/status/1768721783950106758
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/solnic/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Cryptomanc7** [comment]
Please add SOLNIC to the strict list. Thanks

**Comment by Kingisaacd1st** [comment]
add solnic to strict list

**Comment by Salty-OG** [comment]
The community is building and the token is legit! You can check all links here:

- [✅] Website: Solniccoin.io
- [✅] Twitter: https://x.com/solniccoin
- [✅] SolScan: https://solscan.io/token/DeaKMzAeZja3Mh5okZE6WUvygLP3Lfuvm6Rg78HqXTz9
- [✅] CMC: https://coinmarketcap.com/currencies/solnic/
- [✅] Telegram: https://t.me/+JveTq371yXoyMjFh

**Comment by Unommaicurios** [comment]
Please add SOLNIC to the strict list.

**Comment by SueGondese** [comment]
There's a solid community behind Solnic. Everyone is working hard on the project and we're waiting for the recognition that Solnic deserves! Looking at potential exchange listings in the near future!

**Comment by Trowelie** [comment]
Community is one of a kind We are strong, We are building each day!  
Come check us out SOLNIC 
[✅] Website: http://solniccoin.io/
[✅] Twitter: https://x.com/solniccoin
[✅] CMC: https://coinmarketcap.com/currencies/solnic/
[✅] Telegram: https://t.me/+JveTq371yXoyMjFh

**Comment by Humble1ON** [comment]
Salutations from Solnic loyal holder, let's get in that strict list. Thank you & cheers

**Comment by dupont122** [comment]
please add SOLNIC to the strict list Jupiter, we would really appreciate it. 🚀

**Comment by Sprip89** [comment]
Please add solnic to the strict list. We have a strong, honest, open community! Thanks for your time!

**Comment by Sikari00120** [comment]
Can you please add solnic to strict list we are a growing community,  that are here to stay thanks hope you have a wonderful day 😊

**Comment by Windwalkerrr** [comment]
As part of the growing Solnic community, we want to be part of the strict list.

**Comment by Phelvijs** [comment]
SOLNIC community is One of the strongest i have ever seen. Big plans ahead of us. SOLNIC should be on Jupiter exchange strict list!

**Comment by SolnicSavage** [comment]
Updated TG:

https://t.me/SolnicCoin

**Comment by Phelvijs** [comment]
Add solnic to strict list. We believe un SOLNIC Savage community 🔥🔥🔥. We will lift the roof off the house 💥💥💥💪

**Review by Jymfletzfur — APPROVED** [review]

**Comment by dupont122** [comment]
Thank you for the validation, we are growing strong everyday, kindly help us with the other approval, thank you so much for your consideration of this project $SOLNIC WILL MOON🚀🚀

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
