### PR TITLE
Validate Kitty (Hello Kitty) on Solana

### PR DESCRIPTION
**Pull request by hellokittyadmin**
# Validate [KITTY](https://solscan.io/token/FWAyhDQwGczixbQigkE26A4UYwfCeoqRD5qSxJ8XH9aS)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/hellokittyxmeme/status/1805286330366312854
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/dexscan/solana/4sFYTPFKJCtkJX7X5jFLc2XhTRp2hKTcRUiumdCDqHwv/
not yet on Coingecko

## Validation (Please check off boxes):
- [X ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [ X] My change matches the format in the file (no spaces between fields).
- [X ] My token is already live and trading on Jupiter.
- [X ] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [ X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by rhino88888888** [comment]
all that information is correct

**Comment by ValValiant** [comment]
Change the > # Validate KITTY https://solscan.io/token/FWAyhDQwGczixbQigkE26A4UYwfCeoqRD5qSxJ8XH9aS

to > # Validate [KITTY](https://solscan.io/token/FWAyhDQwGczixbQigkE26A4UYwfCeoqRD5qSxJ8XH9aS)

**Comment by ValValiant** [comment]
verified mint address, symbol, and decimals in this PR match what is on-chain.

**Comment by TOFF33COFF33** [comment]
The verified mint address, symbol, and decimals in this PR match what is on-chain!

**Comment by memewerkz** [comment]
The verified mint address, symbol, and decimals in this PR match what is on-chain!

**Comment by Jymfletzfur** [comment]
insufficient mcap

**Pull request closed without merging**
