### PR TITLE
Validate WSBS

### PR DESCRIPTION
**Pull request by Jay-Clouds**
# Validate [WSBS](https://solscan.io/token/5RDHUiwLChkKfusxeu9kEDUtRfxsDWV8etoopnZMwVM7)

## Attestations:
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/WSBSOnSOL/status/1768222691390345384?s=20
- Coingecko/ CMC URL: Currently not applicable (CMC Application ID below)

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Application CMC: [ID 869746](https://x.com/WSBSOnSOL/status/1767392077971587539?s=20)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers) 

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by kaijuz** [comment]
Kaijuz confirms that the information provided is accurate.
- [x] Mint address: 5RDHUiwLChkKfusxeu9kEDUtRfxsDWV8etoopnZMwVM7
- [x] Symbol: WSBS
- [x] Token Decimals: 6
- [x] Token icon: https://bafybeibvap6pkovsxqf2jpkbh4faaz7cifefmvcozs3v4ev475zv5m2mjq.ipfs.nftstorage.link/
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by MaxSolBets** [comment]
MaxSolBets confirms that the information provided is accurate.
- [x] Mint address: 5RDHUiwLChkKfusxeu9kEDUtRfxsDWV8etoopnZMwVM7
- [x] Symbol: WSBS
- [x] Token Decimals: 6
- [x] Token icon: https://bafybeibvap6pkovsxqf2jpkbh4faaz7cifefmvcozs3v4ev475zv5m2mjq.ipfs.nftstorage.link/
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by FuckingG345676899975tgudchgdcb43** [comment]
FuckingG345676899975tgudchgdcb43 confirms that the information provided is accurate.

 Mint address: 5RDHUiwLChkKfusxeu9kEDUtRfxsDWV8etoopnZMwVM7
 Symbol: WSBS
 Token Decimals: 6
 Token icon: https://bafybeibvap6pkovsxqf2jpkbh4faaz7cifefmvcozs3v4ev475zv5m2mjq.ipfs.nftstorage.link/
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by Spotswad** [comment]
Spotswad confirms that the information provided is accurate.

 Mint address: 5RDHUiwLChkKfusxeu9kEDUtRfxsDWV8etoopnZMwVM7
 Symbol: WSBS
 Token Decimals: 6
 Token icon: https://bafybeibvap6pkovsxqf2jpkbh4faaz7cifefmvcozs3v4ev475zv5m2mjq.ipfs.nftstorage.link/
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by wsbsolana** [comment]
Shaun confirms that the information provided is accurate.

- [x] Mint address: 5RDHUiwLChkKfusxeu9kEDUtRfxsDWV8etoopnZMwVM7
- [x] Symbol: WSBS
- [x] Token Decimals: 6
- [x] Token icon: https://bafybeibvap6pkovsxqf2jpkbh4faaz7cifefmvcozs3v4ev475zv5m2mjq.ipfs.nftstorage.link/
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by webjedi79** [comment]
WebJedi79 confirms that the information provided is accurate.
- [x] Mint address: 5RDHUiwLChkKfusxeu9kEDUtRfxsDWV8etoopnZMwVM7
- [x] Symbol: WSBS
- [x] Token Decimals: 6
- [x] Token icon: https://bafybeibvap6pkovsxqf2jpkbh4faaz7cifefmvcozs3v4ev475zv5m2mjq.ipfs.nftstorage.link/
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Review by 0xSoju2 — APPROVED** [review]

**Pull request merged**
