### PR TITLE
Mao

### PR DESCRIPTION
**Pull request by jshiz**
# Validate [MAO](https://solscan.io/token/EokVz9yWqGj8jGobr8VZqf5tVJKjS1fU9AUZHq4Gjmum)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/feelsgood_mao/status/1782985014738653280
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Jymfletzfur — APPROVED** [review]

**Comment by Jymfletzfur** [comment]
is that image the exact link that is in your metadata?

**Comment by jshiz** [comment]
> is that image the exact link that is in your metadata?

Yes it is. Should I have a different link there? Ending in a .png?

**Comment by jshiz** [comment]
If it needs to be another image with a .png I have one here we can use

https://i.ibb.co/wKD4qdp/200x200.png

**Comment by Jymfletzfur** [comment]
please use this for your image link:

https://bafkreicbwsa3qrtzyelnws4yvwy5x7mbuirhjbqavevzybfpb6uh3rkal4.ipfs.w3s.link/

**Review by jshiz — COMMENTED** [review]
Fixed Mao spelling for token name to "MAO"

**Comment by Jymfletzfur** [comment]
insufficient volume/mcap

**Pull request closed without merging**
