### PR TITLE
peanie

### PR DESCRIPTION
**Pull request by company8**
# Validate [peanie](https://solscan.io/token/dekNoN3D8mXa4JHLwTbVXz8aPAyJUkk443UjcSpJKi4)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/peaniebaby/status/1786927949696110892
- Coingecko/ CMC URL (If available):  https://www.coingecko.com/en/coins/peanie

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by company8** [comment]
UPDATE COINGECKO LISTED
https://www.coingecko.com/en/coins/peanie

**Comment by company8** [comment]
@Jymfletzfur any update ? All love <3

**Comment by Jymfletzfur** [comment]
use this as the image link please

https://bafybeigdlwglyry5q3y547rqg4jwagzbvx66byg7hotw4xz2bgjnzpb2oy.ipfs.cf-ipfs.com/

**Comment by company8** [comment]
@Jymfletzfur All set, thank you so much <3

**Review by Jymfletzfur — APPROVED** [review]

**Comment by company8** [comment]
@9yoi Can I please get some love <3

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
