### PR TITLE
Validate INBRED CAT

### PR DESCRIPTION
**Pull request by DiamondBallzZ**
# Validate $INBRED (https://solscan.io/token/EjzzyCSiLqjFDprpZj8e1zjXmcTG5HPGFRSEoWcJWHh9)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/INBREDCATONSOL/status/1769817371638636571
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/dexscan/solana/B3NePqc5WyWLzm3LWp5BaBKXRByZ52cksTvFARpYt4PV/

## Validation (Please check off boxes):
- [X ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X ] My change matches the format in the file (no spaces between fields).
- [X ] My token is already live and trading on Jupiter.
- [X ] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X ] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
The metadata is in all caps INBRED CAT

please amend so it matches exactly

**Comment by DiamondBallzZ** [comment]
changed Inbred Cat to INBRED CAT, thank you.

**Comment by DiamondBallzZ** [comment]
Mint address: EjzzyCSiLqjFDprpZj8e1zjXmcTG5HPGFRSEoWcJWHh99
Symbol: INBRED
Token Decimals: 9
Token icon: https://arweave.net/iVf74QkkM6G7JfKjwkl37xbFEq0FCU4o5PLGH3--i2o
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by CCatinbred** [comment]
Mint address: EjzzyCSiLqjFDprpZj8e1zjXmcTG5HPGFRSEoWcJWHh99
Symbol: INBRED
Token Decimals: 9
Token icon: https://arweave.net/iVf74QkkM6G7JfKjwkl37xbFEq0FCU4o5PLGH3--i2o
On-chain metadata matches
No duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
