### PR TITLE
SOLONG The Dragon

### PR DESCRIPTION
**Pull request by SOLONGTheDragon**
# Validate [SOLONG](https://solscan.io/token/4MBEqrtgabZ9G5EmKm7XTrcknZ1nWg3TrvFHZMrENgrd)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SOLONGthedragon/status/1740734739613352435?s=20}
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/solong-the-dragon}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by DevilsCrypto** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

**Comment by DevilsCrypto** [comment]
@0xSoju2

**Comment by SOLONGTheDragon** [comment]
@0xSoju2

**Comment by SOLONGTheDragon** [comment]
@0xSoju2 can you please have a look at our pull request? Thank you

**Review by DevilsCrypto — COMMENTED** [review]
Code has been fixed

**Comment by DevilsCrypto** [comment]
Could someone merge this PR, code has been updated, and conflicts resolved.

@0xSoju2 can you look into this? PR is already a month old.

**Comment by SOLONGTheDragon** [comment]
@0xSoju2 Can you please have a look at our request ? thank you

**Comment by DevilsCrypto** [comment]
Who is able to review this PR. It's just a small task. Maybe for the future change the process since this it clearly not the fastest way.

**Comment by Jymfletzfur** [comment]
insufficient mcap and volume

**Comment by DevilsCrypto** [comment]
@Jymfletzfur how much are the requirements for this?

**Pull request closed without merging**
