### PR TITLE
Validate AI

### PR DESCRIPTION
**Pull request by doctadog**
# Validate [{AI}](https://solscan.io/token/99ouK5YUK3JPGCPX9joNtHsMU7NPpU7w91JN4kdQ97po)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/theai_coin/status/1737548460415385715?s=46&t=M8uOIKSIonyKCAdqVsNfTA
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by wgmidiot** [comment]
I validate that this info is correct!

Name: AI
Symbol: AI
Mint Address: 99ouK5YUK3JPGCPX9joNtHsMU7NPpU7w91JN4kdQ97po
Decimals: 9
LogoURI: https://gateway.irys.xyz/wywZMCQqp4pOMyO6AjmBS6VWTqCE2AzsAvNxPTYp9WU
Community Validated: true

**Comment by joaomendoncaa** [comment]
lgtm! excited to see AI on Jupiter

**Comment by joaomendoncaa** [comment]
LGTM. Excited to see $AI on Jupiter.

Name: AI
Symbol: AI
Mint Address: 99ouK5YUK3JPGCPX9joNtHsMU7NPpU7w91JN4kdQ97po
Decimals: 9
LogoURI: https://gateway.irys.xyz/wywZMCQqp4pOMyO6AjmBS6VWTqCE2AzsAvNxPTYp9WU
Community Validated: true

**Comment by david-green-420** [comment]
LGTM. Excited to see $AI on Jupiter.

Name: AI
Symbol: AI
Mint Address: 99ouK5YUK3JPGCPX9joNtHsMU7NPpU7w91JN4kdQ97po
Decimals: 9
LogoURI: https://gateway.irys.xyz/wywZMCQqp4pOMyO6AjmBS6VWTqCE2AzsAvNxPTYp9WU
Community Validated: true

**Comment by wgmidiot** [comment]
> I validate that this info is correct!
> 
> Name: AI Symbol: AI Mint Address: 99ouK5YUK3JPGCPX9joNtHsMU7NPpU7w91JN4kdQ97po Decimals: 9 LogoURI: https://gateway.irys.xyz/wywZMCQqp4pOMyO6AjmBS6VWTqCE2AzsAvNxPTYp9WU Community Validated: true

Image URI has been updated by the team:

https://gateway.irys.xyz/HnDwG54RZvJhTD2PX-mmrD2jwC9MIdxKjW2hL3M8jQc

**Review by benlvb — DISMISSED** [review]

**Review by Timoon21 — APPROVED** [review]

**Review by Timoon21 — APPROVED** [review]

**Comment by Timoon21** [comment]
Hey @doctadog Yours commits are not signed.
It's cause an issue on github, check the "merging is blocked" error message:

The base branch requires all commits to be signed. [Learn more about signing commits.](https://docs.github.com/articles/about-gpg/)

**Comment by doctadog** [comment]
> Hey @doctadog Yours commits are not signed. It's cause an issue on github, check the "merging is blocked" error message:
> 
> The base branch requires all commits to be signed. [Learn more about signing commits.](https://docs.github.com/articles/about-gpg/)

Got it. I'm on ARM mac M1, i think this download will work?

https://sourceforge.net/projects/gpgosx/

Will get that done right now.

**Comment by Timoon21** [comment]
> > Hey @doctadog Yours commits are not signed. It's cause an issue on github, check the "merging is blocked" error message:
> > The base branch requires all commits to be signed. [Learn more about signing commits.](https://docs.github.com/articles/about-gpg/)
> 
> Got it. I'm on ARM mac M1, i think this download will work?
> 
> https://sourceforge.net/projects/gpgosx/
> 
> Will get that done right now.
> 
> Edit: Merged and Signed commits. Thank you.

Hey, still blocked, coz old commit not signed. Not sure if you can sign it.
If you need to create a new PR, just tag me in the comment and I will verify asap.
Thanks

**Comment by wgmidiot** [comment]
Okay, I’ll do that. Thanks

**Comment by Timoon21** [comment]
Duplicate: https://github.com/jup-ag/token-list/pull/805/

**Pull request closed without merging**
