### PR TITLE
Validate Memecoin Printer

### PR DESCRIPTION
**Pull request by 0xZangetsudev**
# Validate [MP](https://solscan.io/token/tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/0xZang/status/1754251509213106389
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Bambiclart** [comment]
- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by Zxrecrown** [comment]
- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by Rengon0x** [comment]
I confirm that the following  informations are accurate and the token is valid.

- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by J-a-m-e-s-o-n** [comment]
Hey fellas!
 
 Long time builder on SOL, and can confirm that the following is accurate:

- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by sltcgoto** [comment]
I validate the accuracy of the information provided:

- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by Djulo** [comment]
The provided information is accurate.

- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by Kazuma201** [comment]
The following information is accurate. Looks great to me

- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by BITCONEEEEEEEECT** [comment]
I am part of the $MP community and can confirm that the following is accurate:

- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by milton9891** [comment]
I am part of the $MP community and can confirm that the following is accurate:

- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by itsmikeoday** [comment]
Hi there! I’m a MP supporter and part of the community. 

Can confirm the following to be accurate:

 Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
 Symbol: MP
 Token Decimals: 6
 Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by willfromuk** [comment]
I confirm this info below is accurate.

- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by bitness247** [comment]
Details below are legit 👇

 🌍Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
☮️ Symbol: MP
 🌍Token Decimals: 6
☮️Tokenicon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
 🌍On-chain metadata matches
 ☮️No duplication on Jupiter's strict list

**Comment by missiongains** [comment]
100% agree and confirm that the information provided is all correct and legitimate
 

- [x]  Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x]  Symbol: MP
- [x]  Token Decimals: 6
- [x]  Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by radko313** [comment]
Yo guys I am in MP community and I am here to show support 

Can confirm the following to be accurate:


- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by II187** [comment]
Meow Meow Meow

I am part of the $MP community and can confirm that the following is accurate:

 Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
 Symbol: MP
 Token Decimals: 6
 Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by Serpenttrading** [comment]
I attest that the following information is accurate and up to date.

- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by skizzell** [comment]
$MP community member here. I can confirm the following is accurate:

- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by ModeGrau** [comment]
I’m an active MP supporter and part of the community.

Can confirm the following to be accurate:

Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
Symbol: MP
Token Decimals: 6
Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by aSwift141** [comment]
I am part of the $MP community and can confirm the following is accurate:

- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by bullsy** [comment]
I am part of the $MP community and can confirm the following is accurate:

- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by MementoMori7777** [comment]
I am part of the $MP community and can confirm the following is accurate:

- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by BlockchainBosco** [comment]
I can't confirm that all these are accurate. I am a $MP holder

**Review by BlockchainBosco — COMMENTED** [review]
I am a MP holder and I can confirm all things things are accurate

**Review by BlockchainBosco — COMMENTED** [review]
I am a MP holder and I can confirm that everything is accurate

**Review by BlockchainBosco — COMMENTED** [review]
I am MP holder and everything just accurate

**Comment by Sharozekhan** [comment]
The provided information is accurate.

 Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
 Symbol: MP
 Token Decimals: 6
 Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by csorokoporso** [comment]
The provided information is accurate.

- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Review by II187 — COMMENTED** [review]
Ready to go!

**Review by Rengon0x — COMMENTED** [review]
- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Review by J-a-m-e-s-o-n — COMMENTED** [review]
Verified

**Review by Licachi — COMMENTED** [review]
I am part of the $MP community and can confirm the following is accurate:

- [x] Mint address: tomVoRnF8Z4yjnvCmU6SMbHhDijZ9RvvSdxipCApFm8
- [x] Symbol: MP
- [x] Token Decimals: 6
- [x] Token icon: https://i.postimg.cc/gcVnJ0sS/MP.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by robbestad** [comment]
Use a decentralized storage network for the token image (arweave or ipfs)

**Pull request closed without merging**
