### PR TITLE
Validate DEGENS

### PR DESCRIPTION
**Pull request by mflanagan1041**
# Validate [DEGENS](https://solscan.io/token/DEGENsATq3PfyBG6P2aXMrHVAVX5TqPFDYzHxhxf5x6t)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: [Here](https://twitter.com/DEGENS_Token/status/1744593497594700273) & [Here](https://twitter.com/crypto_flan/status/1744595101064556799)
- Coingecko/ CMC URL (If available): Not Available ATM

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by web3jsdev** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [ ] Mint address: DEGENsATq3PfyBG6P2aXMrHVAVX5TqPFDYzHxhxf5x6t
- [ ] Symbol: DEGENS
- [ ] Token Decimals: 6
- [ ] Token icon: https://shdw-drive.genesysgo.net/CEGJeB4tbaKkDoyM2YHzS8NvKtmrsDqu2KUXvGTNfADW/DeGenius.png
- [ ] On-chain metadata matches
- [ ] No duplication on Jupiter's strict list

**Comment by cointilt** [comment]
The DEGENS token PR is accurate!

- [ ] Mint address: DEGENsATq3PfyBG6P2aXMrHVAVX5TqPFDYzHxhxf5x6t
- [ ] Symbol: DEGENS
- [ ] Token Decimals: 6
- [ ] Token icon: https://shdw-drive.genesysgo.net/CEGJeB4tbaKkDoyM2YHzS8NvKtmrsDqu2KUXvGTNfADW/DeGenius.png
- [ ] On-chain metadata matches
- [ ] No duplication on Jupiter's strict list

**Comment by PuppyGamingDev** [comment]
I can confirm information provided is correct! 

 Mint address: DEGENsATq3PfyBG6P2aXMrHVAVX5TqPFDYzHxhxf5x6t

 Symbol: DEGENS

 Token Decimals: 6

 Token icon: https://shdw-drive.genesysgo.net/CEGJeB4tbaKkDoyM2YHzS8NvKtmrsDqu2KUXvGTNfADW/DeGenius.png

 On-chain metadata matches

 No duplication on Jupiter's strict list

**Comment by husky-696** [comment]
The DEGENS token PR is accurate!

- [x] Mint address: DEGENsATq3PfyBG6P2aXMrHVAVX5TqPFDYzHxhxf5x6t
- [x] Symbol: DEGENS
- [x] Token Decimals: 6
- [x] Token icon: https://shdw-drive.genesysgo.net/CEGJeB4tbaKkDoyM2YHzS8NvKtmrsDqu2KUXvGTNfADW/DeGenius.png
- [x] On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
insufficient mcap, volume

**Comment by web3jsdev** [comment]
> insufficient mcap, volume

@Jymfletzfur Why would you close this based on mcap?

**Pull request closed without merging**
