### PR TITLE
Add SEX token

### PR DESCRIPTION
**Pull request by NotoriousPyro**
# Validate [SEX](https://solscan.io/token/DARpE2GaVrazeh6mopWXbTT1hV3EbNNvHrJMMqJXUm6i)

This is a meme token, a managed liquidity ETF meme cryptoasset.

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SexOnSolana/status/1744718749599756747
- Coingecko/ CMC URL (If available): Not get available

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by ahmadpriv365** [comment]
Yess, I support SEX to be listed!!👍❤️

**Comment by Joshuashin97** [comment]
Yes! I support the listing of SEX!!

**Comment by KingKAPOW** [comment]
I want SEX so much to be listed!

**Comment by NotoriousPyro** [comment]
@benchow any chance this can be validated please?

**Comment by Jymfletzfur** [comment]
insufficient volume, mcap

**Comment by NotoriousPyro** [comment]
@Jymfletzfur so because this token isn't wash-traded unlike similar ticker $SEX and one that hasn't been on Solana for as long as us, they are more likely to be approved than us, even though we raised this prior to the change in rules...

So Jupiter is approving only wash-traded tokens now???

**Pull request closed without merging**
