### PR TITLE
Validate Snork

### PR DESCRIPTION
**Pull request by SnorkOwner**
# Validate [SNORK](https://solscan.io/token/8S24pfgvhdkDQCTReLoP71xxfbKp98iTWAsvYRuEyEBM)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/Snork_Coin/status/1778573881927938319
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/snork/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by SnorkOwner** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

- [x] Mint address: 8S24pfgvhdkDQCTReLoP71xxfbKp98iTWAsvYRuEyEBM
- [x] Symbol: SNORK
- [x] Token Decimals: 9
- [x] Token icon: https://pbs.twimg.com/profile_images/1783468940091662336/Dam71Dtz_400x400.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by kreyda** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

- [x]  Mint address: 8S24pfgvhdkDQCTReLoP71xxfbKp98iTWAsvYRuEyEBM
- [x]  Symbol: SNORK
- [x]  Token Decimals: 9
- [x]  Token icon: https://pbs.twimg.com/profile_images/1783468940091662336/Dam71Dtz_400x400.jpg
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by web3devux** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

- [x]  Mint address: 8S24pfgvhdkDQCTReLoP71xxfbKp98iTWAsvYRuEyEBM
- [x]  Symbol: SNORK
- [x]  Token Decimals: 9
- [x]  Token icon: https://pbs.twimg.com/profile_images/1783468940091662336/Dam71Dtz_400x400.jpg
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by GraphTechJS** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

- [x]  Mint address: 8S24pfgvhdkDQCTReLoP71xxfbKp98iTWAsvYRuEyEBM
- [x]  Symbol: SNORK
- [x]  Token Decimals: 9
- [x]  Token icon: https://pbs.twimg.com/profile_images/1783468940091662336/Dam71Dtz_400x400.jpg
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by Naytin** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

- [x]  Mint address: 8S24pfgvhdkDQCTReLoP71xxfbKp98iTWAsvYRuEyEBM
- [x]  Symbol: SNORK
- [x]  Token Decimals: 9
- [x]  Token icon: https://pbs.twimg.com/profile_images/1783468940091662336/Dam71Dtz_400x400.jpg
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by EvgeniyShvetss** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

- [x]  Mint address: 8S24pfgvhdkDQCTReLoP71xxfbKp98iTWAsvYRuEyEBM
- [x]  Symbol: SNORK
- [x]  Token Decimals: 9
- [x]  Token icon: https://pbs.twimg.com/profile_images/1783468940091662336/Dam71Dtz_400x400.jpg
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by SnorkOwner** [comment]
We really need this Strict list completed ASAP, we are dealing with 5 x Snork/SOL imposter scammers. See attached image. 
Screenshot 2024-05-23 at 10 37 28 AM

**Comment by SnorkOwner** [comment]
Request 2 reviews for Merging

**Comment by SnorkOwner** [comment]
Please ban the fake $SNORK, trying to draw users by using the real tokens CA in it's name

real CA: 8S24pfgvhdkDQCTReLoP71xxfbKp98iTWAsvYRuEyEBM

This fake token's names: 
Snork / 4X5eexV9tZppz7YQFMZ6CYzEEHKiCv7RuBs4KDz2Bgg2
Snork / 3oBGzndCZWGbBKCimm56bRY5Y8USp7yoBcKuPp1QStmm
Snork / Bm1NxaM5LFcqK96egRTwvvt4rc3pPPdRwaVU68D8RMMm
Snork / 8cFSWoH93PxbJCMjtQYc5bbSGxBE98HvnneVtaZggFEt
Snork / EtZqHANiexwsvXzzaMso663poryKKkonYp99ZmZ51mKx
Snork / dGhT2pVNS9b5xZ9qiQWbF9iGubmaGRvAKcfzcd8orb5

**Comment by SnorkOwner** [comment]
Request 2 reviews for Merging

**Pull request closed without merging**
