### PR TITLE
Validate BONK2.0

### PR DESCRIPTION
**Pull request by Bonk20**
# Validate [BONK2.0](https://solscan.io/token/6yiDKPDbqWLGAEBkDvVg6UNrKsLsPVkLbA1TJo4KCdzP)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/bonk2coinsol/status/1766188332789211533
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/bonk-2-0-sol
https://coinmarketcap.com/currencies/bonk-2/
- Website: https://bonk20.com/
- Telegram: https://t.me/Bonk20Portal
- twitter: https://twitter.com/bonk2coinsol
- Audit: https://coinsult.net/projects/bonk-2-0/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Bonk20** [comment]
update please

**Comment by Bonk20** [comment]
Website:  https://bonk20.com/
Telegram: https://t.me/Bonk20Portal
twitter: https://twitter.com/bonk2coinsol
audit: https://coinsult.net/projects/bonk-2-0/
Coingecko:
https://www.coingecko.com/en/coins/bonk-2-0-sol
Coinmarketcap:
https://coinmarketcap.com/currencies/bonk-2/

**Comment by Bonk20** [comment]
listed on 3cex
📈Lbank
https://lbank.com/trade/bonk2_usdt
📈Bitmart
https://bitmart.com/trade/en-US?symbol=BONK2.0_USDT
📈Toobit
https://toobit.com/en-US/spot/BONK2_USDT
DEX
📈Jupiter
https://jup.ag/swap/SOL-6yiDKPDbqWLGAEBkDvVg6UNrKsLsPVkLbA1TJo4KCdzP
📈Raydium
https://raydium.io/swap/?inputCurrency=sol&outputCurrency=6yiDKPDbqWLGAEBkDvVg6UNrKsLsPVkLbA1TJo4KCdzP

Website: https://bonk20.com/
Telegram: https://t.me/Bonk20Portal
twitter: https://twitter.com/bonk2coinsol
audit: https://coinsult.net/projects/bonk-2-0/
Coingecko:
https://www.coingecko.com/en/coins/bonk-2-0-sol
Coinmarketcap:
https://coinmarketcap.com/currencies/bonk-2/

**Comment by Bonk20** [comment]
wait for update ?

**Comment by Bonk20** [comment]
waiting for update !

**Comment by Bonk20** [comment]
listed on 4cex
📈Mexc
https://www.mexc.com/exchange/BONK2SOL_USDT
📈Lbank
https://lbank.com/trade/bonk2_usdt
📈Bitmart
https://bitmart.com/trade/en-US?symbol=BONK2.0_USDT
📈Toobit
https://toobit.com/en-US/spot/BONK2_USDT
3 DEX
📈Jupiter
https://jup.ag/swap/SOL-6yiDKPDbqWLGAEBkDvVg6UNrKsLsPVkLbA1TJo4KCdzP
📈Raydium
https://raydium.io/swap/?inputCurrency=sol&outputCurrency=6yiDKPDbqWLGAEBkDvVg6UNrKsLsPVkLbA1TJo4KCdzP
📈orca

Website: https://bonk20.com/
Telegram: https://t.me/Bonk20Portal
twitter: https://twitter.com/bonk2coinsol
audit: https://coinsult.net/projects/bonk-2-0/
Coingecko:
https://www.coingecko.com/en/coins/bonk-2-0-sol
Coinmarketcap:
https://coinmarketcap.com/currencies/bonk-2/

**Comment by Bonk20** [comment]
listed on 4cex
📈Mexc
https://www.mexc.com/exchange/BONK2SOL_USDT
📈Lbank
https://lbank.com/trade/bonk2_usdt
📈Bitmart
https://bitmart.com/trade/en-US?symbol=BONK2.0_USDT
📈Toobit
https://toobit.com/en-US/spot/BONK2_USDT
3 DEX
📈Jupiter
https://jup.ag/swap/SOL-6yiDKPDbqWLGAEBkDvVg6UNrKsLsPVkLbA1TJo4KCdzP
📈Raydium
https://raydium.io/swap/?inputCurrency=sol&outputCurrency=6yiDKPDbqWLGAEBkDvVg6UNrKsLsPVkLbA1TJo4KCdzP
📈orca

Website: https://bonk20.com/
Telegram: https://t.me/Bonk20Portal
twitter: https://twitter.com/bonk2coinsol
audit: https://coinsult.net/projects/bonk-2-0/
Coingecko:
https://www.coingecko.com/en/coins/bonk-2-0-sol
Coinmarketcap:
https://coinmarketcap.com/currencies/bonk-2/

**Comment by Jymfletzfur** [comment]
token too closely resembles bonk

**Comment by Bonk20** [comment]
is like pepe 2.0 and all meme token
whats wrong in that ?
the logo is not same 
that is unfair .....
logooo

token is listed on many cex and dex
cmc and cg 
that is unfair .....

**Pull request closed without merging**
