### PR TITLE
Update validated-tokens.csv

### PR DESCRIPTION
**Pull request by el-buku**
# Validate [UFOC](https://solscan.io/token/C4yE42tg6ybGwyELdGHaP2E8UchwygcCLBxuE8VRsJjd)
## Attestations (Please provide links):
Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/UFOCashX/status/1795277248825889016

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Reginaldberrifield** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.  
  
 Mint address: C4yE42tg6ybGwyELdGHaP2E8UchwygcCLBxuE8VRsJjd  
 Symbol: UFOC  
 Token Decimals: 8  
 Token icon: https://statics.solscan.io/cdn/imgs/s60?ref=68747470733a2f2f6261666b7265696179743271323769646c7135336136633668327169797671657a6465736e796d746569626c676e7864726f65337a6576726173792e697066732e6e667473746f726167652e6c696e6b 
 On-chain metadata matches  
 No duplication on Jupiter's strict list

**Comment by Reginaldberrifield** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.  
  
 Mint address: C4yE42tg6ybGwyELdGHaP2E8UchwygcCLBxuE8VRsJjd  
 Symbol: UFOC  
 Token Decimals: 8  
 Token icon: https://statics.solscan.io/cdn/imgs/s60?ref=68747470733a2f2f6261666b7265696179743271323769646c7135336136633668327169797671657a6465736e796d746569626c676e7864726f65337a6576726173792e697066732e6e667473746f726167652e6c696e6b

**Comment by bmaslowski** [comment]
$UFOC is LIVE and ready to launch the UFOCASH community to the moon!
CA:
C4yE42tg6ybGwyELdGHaP2E8UchwygcCLBxuE8VRsJjd
@JupiterExchange

#UFOCASH #tothemoon #ufo #Memecoinseason #solana #bullish #Organic #Cash #JoeRogan #Conspiracy #Community #HODL

**Comment by bmaslowski** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.  
  
 Mint address: C4yE42tg6ybGwyELdGHaP2E8UchwygcCLBxuE8VRsJjd  
 Symbol: UFOC  
 Token Decimals: 8  
 Token icon: https://statics.solscan.io/cdn/imgs/s60?ref=68747470733a2f2f6261666b7265696179743271323769646c7135336136633668327169797671657a6465736e796d746569626c676e7864726f65337a6576726173792e697066732e6e667473746f726167652e6c696e6b 
 On-chain metadata matches  
 No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
