### PR TITLE
Validate Baby Bonk

### PR DESCRIPTION
**Pull request by julesdamasta**
# Validate [{Token Symbol}](https://solscan.io/token/Dx1Lq5FjangW5ifRMEogAiakm24LyB5AoHmQifepvNjV)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/Baby_BonkonSOL/status/1731309455646876147?s=20
- Coingecko/ CMC URL (If available): N/A

## Validation (Please check off boxes):
- [y] The metadata provided in the PR matches what is on-chain (Mandatory)
- [y] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [n] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [y] My change matches the format in the file (no spaces between fields).
- [y] My token is already live and trading on Jupiter.
- [y] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by Timoon21** [comment]
Hey, please add your token on the last line, not on the middle of the list.
Thanks to update the PR.

**Comment by julesdamasta** [comment]
Hello - If the provide image file/URL does not suffice please use the following: 

https://pbs.twimg.com/profile_images/1728448039550099456/Y64FBvzB_400x400.jpg

**Comment by 9yoi** [comment]
Not sure if we can validate this to the strict list so soon-- it has very similar name and icon to Bonk. In the meantime, your token is still tradeable on the 'All' list

**Comment by julesdamasta** [comment]
This is a very unprofessional response because BONK has been around for close to a year now. Everyone on Solana is very familiar w/ BONK's name, icon and even their CA. So I am not sure how adding Baby Bonk to the strict list is "so soon". If JUP wait's too long a "Baby Bonk" token will be verified on some other block chain that is not Solana and then where do you think ppl that have an appetite to buy "Baby Bonk" will flock too? Our strong, unique and rapidly growing community that consists of SOL, JUP, Bonk holders and lovers believe that Baby Bonk belongs on Solana. It's well known that every successful meme token has a "Baby", Doge, Shiba, Elon, etc. etc. Baby Bonk is thus a complement to the success of Bonk and the reason why the Bonk community has embraced "Baby Bonk". Everyday we hear countless stories on twitter and TG about communities members that left ETH, BNB and other chains and made Baby Bonk their first token purchased on Solana. We implore you to please reconsider your current stance on Baby Bonk's verification. Thank you.

**Review by 0xSoju2 — APPROVED** [review]

**Pull request merged**
