### PR TITLE
Validate SEC

### PR DESCRIPTION
**Pull request by whaleen**
# Validate [SEC](https://solscan.io/token/8t5FggSQmHR8Q3xKg6dpopdYQRMGjWmqD2k7cb2HmguX)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/sectaskforce/status/1790909435352846667
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by SECTaskForce — COMMENTED** [review]
[x] Mint address: 8t5FggSQmHR8Q3xKg6dpopdYQRMGjWmqD2k7cb2HmguX
[x] Symbol: SEC
[x] Token Decimals: 6
[x] Token icon: https://ibb.co/jV2fWYn
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Review by bobbygreenland — COMMENTED** [review]
[x] Mint address: 8t5FggSQmHR8Q3xKg6dpopdYQRMGjWmqD2k7cb2HmguX
[x] Symbol: SEC
[x] Token Decimals: 6
[x] Token icon: https://ibb.co/jV2fWYn
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Review by alejandropascual12 — COMMENTED** [review]
[x] Mint address: 8t5FggSQmHR8Q3xKg6dpopdYQRMGjWmqD2k7cb2HmguX
[x] Symbol: SEC
[x] Token Decimals: 6
[x] Token icon: https://ibb.co/jV2fWYn
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by rmeeker109** [comment]
Extremely effective product, nothing but good things to say here with a strong developer team and even stronger community.

**Comment by Gmoney6999** [comment]
Very professional 👏 
Huge community already 
Dev is amazing 👏

**Comment by Jymfletzfur** [comment]
token is too new and does not appear to meet any exemptions, please come back in 2 weeks

**Pull request closed without merging**
