### PR TITLE
Validate FABS

### PR DESCRIPTION
**Pull request by metasal1**
# Validate [FABS](https://solscan.io/token/ErbakSHZWeLnq1hsqFvNz8FvxSzggrfyNGB6TEGSSgNE)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/FABSonSOL/status/1764738723680280630
- Coingecko/ CMC URL (If available): n/a

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by metasal1** [comment]
@Jymfletzfur

**Comment by robbestad** [comment]
✅ Mint address: ErbakSHZWeLnq1hsqFvNz8FvxSzggrfyNGB6TEGSSgNE
✅ Symbol: FABS 
✅ Token Decimals: 5
✅ Token icon: https://bafybeig2niwqgufjmlqfccwehnf3hracp6j23zwkdf26ihxcegkzs7jexi.ipfs.nftstorage.link/
✅ On-chain metadata matches 
✅ No duplication on Jupiter's strict list

**Comment by metasal1** [comment]
@siong1987 please review

**Comment by metasal1** [comment]
Please review @9yoi

**Comment by Jymfletzfur** [comment]
tokens fails to meet multiple criteria necessary to get onto strict list

**Comment by metasal1** [comment]
You fail to explain anything again @Jymfletzfur 

You are wasting people's time here.

**Pull request closed without merging**
