### PR TITLE
Monkey

### PR DESCRIPTION
**Pull request by jrollgaex**
Validate [MONKEY](https://solscan.io/token/921MoB1U7VprQfWw5D37a38LCBgB3nareT7rNffk66BG)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/MonkeyS0L/status/1790755751058673832?t=qteOYfJwNCJKj7ChwX__FQ&s=19) and showing community support: https://twitter.com/@MonkeySOL/status/YOUR_TWEET_ID_HERE
- Coingecko/ CMC URL (cmc29923): https://www.coingecko.com/en/coins/monkey-2

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
please come into discord

**Comment by jrollgaex** [comment]
I entered Discord but I'm not sure what the next steps are?

**Comment by jrollgaex** [comment]
> please come into discord

Ok I'm in Discord. But I'm not sure what the next step is? Thanks in advance

**Comment by Jymfletzfur** [comment]
Change name to Monkey

Change image file to https://i.ibb.co/ckNxCz8/photo-2024-02-07-17-12-39.jpg

**Comment by jrollgaex** [comment]
> Change name to Monkey
> 
> Change image file to https://i.ibb.co/ckNxCz8/photo-2024-02-07-17-12-39.jpg

ok is this the file on jupiter itself and I need to tell the owner to do or is this something I sent in the pull request?

**Comment by jrollgaex** [comment]
ok is this the file on Jupiter itself and I need to tell the owner to do or is this something I sent in the pull request?

**Comment by jrollgaex** [comment]
Also where does the name MONKEY need to be changed to Monkey?

**Comment by jrollgaex** [comment]
If its something I need to do on the request please let me know and if so how i edit all the info.. Sorry its my first time and Im just helping the owner from Italy. Thanks

**Comment by jrollgaex** [comment]
I believe I edited the Monkey correct but now I cant seem to edit it again for the image.. Im sorry mate to be a pain, but after this one I will be better going forward for the other projects

**Pull request closed without merging**
