### PR TITLE
Validate TurboMoon

### PR DESCRIPTION
**Pull request by TurboMoon**
# Validate [TMOON](https://solscan.io/token/{7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6})

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/turbomoonsol/status/1756830009338040603?s=52&t=VuUCEZ7II7EMYe9IqR25HQ
- Coingecko/ CMC URL (If available): (https://www.coingecko.com/en/coins/turbomoon)

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by lionz4lyf** [comment]
Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link
On-chain metadata matches sol scan
No duplication on Jupiter's strict list

**Comment by Cryptoholic1** [comment]
I Cryptoholic1 can confirm the below:

Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link
On-chain metadata matches sol scan
No duplication on Jupiter's strict list

**Review by sunfloweroglfg — COMMENTED** [review]
Reviewed. Agreed. Good to go

Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: 

https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link
On-chain metadata matches sol scan
No duplication on Jupiter's strict list

**Comment by Theofficialdman** [comment]
I @theofficialdman can confirm the below

Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link/
On-chain metadata matches sol scan
No duplication on Jupiter's strict list

**Review by Cryptoholic1 — COMMENTED** [review]
Reviewed, Agreed

Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link
On-chain metadata matches Sol scan
No duplication on Jupiter's strict list

**Comment by sweetblossom** [comment]
Definitely, i agree 💯

Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link
On-chain metadata matches Sol scan
No duplication on Jupiter's strict list

**Comment by Timboslice2** [comment]
I Timboslice2 confirm the below

Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link
On-chain metadata matches sol scan
No duplication on Jupiter's strict list

**Comment by Pokemondundee** [comment]
I Pokemondundee confirm the following to be 100% accurate!


Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link
On-chain metadata matches sol scan
No duplication on Jupiter's strict list

**Comment by SexySraka** [comment]
1000% confirm:

Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link

On-chain metadata matches sol scan
No duplication on Jupiter's strict list

**Comment by Stonecod** [comment]
I Stonecod can confirm the below

Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link
On-chain metadata matches sol scan
No duplication on Jupiter's strict list

**Comment by Aimed042** [comment]
I Aimed042 can confirm the below 👇

Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link
On-chain metadata matches sol scan
No duplication on Jupiter's strict list

**Comment by GuyTrader** [comment]
Confirmed and verified.

Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link
On-chain metadata matches sol scan
No duplication on Jupiter's strict list

**Comment by jwilliams436** [comment]
I can confirm.

Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link/
On-chain metadata matches sol scan
No duplication on Jupiter's strict list

**Comment by cryptophantoem** [comment]
I ligma357780 can confirm the below

Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link
On-chain metadata matches sol scan
No duplication on Jupiter's strict list

**Comment by cryptophantoem** [comment]
I josheeboyi can confirm the below

Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link
On-chain metadata matches sol scan
No duplication on Jupiter's strict list

**Comment by cryptophantoem** [comment]
I cryptoeefantasm can confirm the below

Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link
On-chain metadata matches sol scan
No duplication on Jupiter's strict list

**Comment by JustinCuff** [comment]
Turbo engaged. Confirmation 100% x 1000. I have added TMOON to my Phantom wallet, and am receiving reflection yeilds/deposits regularly. This s**t works Gary!

**Comment by SexySraka** [comment]
> Turbo engaged. Confirmation 100% x 1000. I have added TMOON to my Phantom wallet, and am receiving reflection yeilds/deposits regularly. This s**t works Gary!

Ahaha.. 100% x 1000 is pretty accurate 😂
It works, Gary! 🦸‍♂️

**Comment by jakobjan** [comment]
Mint address: 7Cx1fMabGWgm86xvv73WzSAcwtLppKf39Ywe8e6Qq4T6
Symbol: TMOON
Token Decimals: 5
Token icon: https://bafkreiewiizqruspm2uongbfl46mfw6thj75rpk2qp55kyhrixztweszza.ipfs.nftstorage.link
On-chain metadata matches sol scan
No duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Pull request merged**
