### PR TITLE
Validate PEPEWIFQ

### PR DESCRIPTION
**Pull request by mrpepsterq**
# Validate [PEPEWIFQ](https://solscan.io/token/5E8Q9gHj8DRJGuJ3k5WJHmbh5Gms967PrDokNk5W38j)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/pepewifq/status/1788093711064113317
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by GermanyOnSol** [comment]
Hey @mrpepsterq 

Make sure your Pull Request Title has the Name of your token,
in your case: "Validate PEPEWIFQ" for example.

You ticked off the box, but it is not the case.
So change that Pull Request Title before it gets closed because of that!

Have a great day.

**Comment by mrpepsterq** [comment]
thanks @GermanyOnSol

**Comment by Jymfletzfur** [comment]
insufficient volume

**Comment by mrpepsterq** [comment]
what volume is required to approve this?

**Pull request closed without merging**
