### PR TITLE
ZAZU

### PR DESCRIPTION
**Pull request by ZazuSOL**
# Validate [ZAZU](https://solscan.io/token/n7EksMkvk3WT5FjQ3HBMLm9XYU3EnoXUSJ7PoWpxsoG)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/zazucoin/status/1787837473105527283?s=46&t=mhPJaHTGQd4UbdcAT_eu_A
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/zazu

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by KeanuCoin** [comment]
Super project run by Wif Founder Patrick Bateman. Approved

**Comment by benlvb** [comment]
@ZazuSOL wrong image link

**Comment by ZazuSOL** [comment]
> @ZazuSOL wrong image link

Updating

**Review by benlvb — APPROVED** [review]

**Comment by Jymfletzfur** [comment]
Your PR attempts to overwrite existing tokens in the list

**Comment by ZazuSOL** [comment]
> Your PR attempts to overwrite existing tokens in the list

it wa saying t resolve conflict while i already updated logo link ... i dont mean to do that but it says merge. should i delete that.

**Comment by ZazuSOL** [comment]
> Your PR attempts to overwrite existing tokens in the list

please let me know what to do.

**Review by 0xSoju2 — APPROVED** [review]

**Pull request merged**
