### PR TITLE
Validate Advocat

### PR DESCRIPTION
**Pull request by WildThingCrypto**
# Validate [Advocat](https://solscan.io/token/FxwbKC8s3dq8kkwJyHN5KEwDuhzawgfTmWRnfnX6jBho)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/NotACatCoin/status/1787629433806799289
- Coingecko/ CMC URL (If available): 

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by WildThingCrypto** [comment]
Let me know if I need to do anything differently.

**Comment by Jymfletzfur** [comment]
insufficient mcap

**Comment by WildThingCrypto** [comment]
What is the threshold for sufficient market cap? Our locked liquidity is 90% of the market cap. We will stop burning supply and submit again when we meet the threshold.


________________________________

**Comment by WildThingCrypto** [comment]
Thank you for letting me know why we didn't get on the list.  The community is still growing, and as part of our mantra for helping community projects, we wanted to be sure that people don't purchase fake versions of the token when we start our Advocacy campaign.  When can I resubmit? I don't want to waste anyone's time.

**Pull request closed without merging**
