### PR TITLE
Validate MILEI

### PR DESCRIPTION
**Pull request by SrMessiETH**
# Validate [MILEI](https://solscan.io/token/43N5UGr3mnfhJFzpBPNM7ZdnobghiYBtHTaQfZQv65mh)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/mileisolcoin/status/1789121616514887834
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/milei-solana

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by SrMessiETH** [comment]
Hi! There is something more I need to do for verification? 

Thank you!

**Review by webpov — COMMENTED** [review]
The structure matches the format 👍

**Review by 3dunoabraham — COMMENTED** [review]
Looks good, image and data fit the criteria

**Comment by SrMessiETH** [comment]
I sent another commit to change the link of the image for a ipfs one

**Comment by SrMessiETH** [comment]
3rd commited created to change decimals and again the ipfs image. Please review, thank you!

**Comment by Jymfletzfur** [comment]
Token is still a bit too new and does not appear to meet any of the exemptions

Please come back in 1 week

**Pull request closed without merging**
