### PR TITLE
Validate DLP8

### PR DESCRIPTION
**Pull request by victordlp8**
# Validate [DLP8](https://solscan.io/token/9AGm8DWXiB4PwvH1V2r31ChsTE2f2TDySvDbfJmfaMBq)

## Attestations:
- Tweet from your Twitter Account attesting the Mint address: https://twitter.com/dlp8coin/status/1625809909186002944
- Coingecko/ CMC URL (If available): Not available

## Validation (Additonal material for reviewers):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will take longer)
- [ ] Is Listed on Coingecko / CMC (Optional, but is helpful for reviewers to check for duplicates)  

## Acknowledgement
- [x] Acknowleged that I did not modify unrelated code.
- [x] Acknowledged that my change matches the format of other lines in the file (no spaces between fields).

### CODE REVIEW

**Review by ThorTuwy — COMMENTED** [review]
- [x] On-chain metadata matches the PR
 - [x] Token address matches the tweet / official website
 - [x] No duplicate on CoinGecko / CMC
 - [x] No duplicate on Jupiter's strict list

**Review by OkabeGG — COMMENTED** [review]
- [x] On-chain metadata matches the PR
 - [x] Token address matches the tweet / official website
 - [x] No duplicate on CoinGecko / CMC
 - [x] No duplicate on Jupiter's strict list

**Review by agusferro29 — COMMENTED** [review]
- [x] On-chain metadata matches the PR
 - [x] Token address matches the tweet / official website
 - [x] No duplicate on CoinGecko / CMC
 - [x] No duplicate on Jupiter's strict list

**Comment by Azalga** [comment]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet / official website
- [x] No duplicate on CoinGecko / CMC
- [x] No duplicate on Jupiter's strict list

**Review by Azalga — COMMENTED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet / official website
- [x] No duplicate on CoinGecko / CMC
- [x] No duplicate on Jupiter's strict list

**Comment by LJQZZZ123** [comment]
- [ ] On-chain metadata matches the PR
- [ ] Token address matches the tweet
- [ ] No duplication on CoinGecko/ CMC
- [ ] No duplication on Jupiter's strict list

**Review by LJQZZZ123 — APPROVED** [review]

**Review by Timoon21 — APPROVED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the official website
- [x] Not on CoinGecko, no duplication
- [x] No duplication on the Jupiter's strict list

**Review by benlvb — APPROVED** [review]
- [x]  On-chain metadata matches the PR
- [ ] Token address matches the official website
- [ ] Not on CoinGecko, no duplication
- [ ] No duplication on the Jupiter's strict list

**Pull request merged**
