### PR TITLE
Update validated-BCOCO

### PR DESCRIPTION
**Pull request by Pinguim306**
# Validate [BCOCO](https://solscan.io/token/8xfxzPV8HoxhyMBLSJwjmYP6xQ4MWwAzVYEv3izNBMvm)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/BabyCocoonsol/status/1692716626955694358
- Coingecko/ CMC URL (If available): Working to setup CG and CMC for BCOCO

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by Timoon21** [comment]
"the baby of The Heist season 2 token" as I can read on your Twitter description account.

This is misleading for user as your are not related to the Coco token.

**Comment by Pinguim306** [comment]
> 

But we do not claim to be an official token related to Coco.

**Comment by Timoon21** [comment]
Kittens claim to become cats. I don't make the rules.

**Comment by Timoon21** [comment]
to avoid misleading users, it is not allowed to ask to be added to the strict-list if the token uses the name (or similarly named) of an existing token

**Pull request closed without merging**
