### PR TITLE
Validate CUY

### PR DESCRIPTION
**Pull request by cuycto**
# Validate [CUY](https://solscan.io/token/8MD6dV7B8Tgwo72WyPmfsXiXpt1G1y2u9ohhNrt3LVwX)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/Cuy_CTO/status/1797916250762584074
- Coingecko/ CMC URL (If available): 

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by cuycto** [comment]
I changed the Logo address from solscan link to our website link

**Comment by Jymfletzfur** [comment]
please come into discord

**Comment by cuycto** [comment]
@Jymfletzfur Jymfletzfur

The discord link does not work on JUP socials.

**Comment by Jymfletzfur** [comment]
the ticker is also Cuy

the image link is https://ipfs.io/ipfs/QmU62kzW5662SoGrRGu3jH6skmtDmNem4sXiFvkhEdg8hb

**Comment by cuycto** [comment]
Yes please, The ticker is also Cuy. I have added the image link to the commit. Please check and confirm if we are good to proceed

**Pull request closed without merging**
