### PR TITLE
validate Fuddles Shiba Inu FUDSI

### PR DESCRIPTION
**Pull request by FuddlesNFT**
# Validate [FUDSI}](https://solscan.io/token/91Fv8PztVLsf4S49RANPGW92veJ2oL6BjwsP9i666Wxu)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/FuddlesNFT/status/1731340243503092097
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
insufficient volume

**Comment by FuddlesNFT** [comment]
@Jymfletzfur - We were alaready approved: https://birdeye.so/token/91Fv8PztVLsf4S49RANPGW92veJ2oL6BjwsP9i666Wxu/3J33DQccDE6CQZvh2QF8RQ1pio2m2uawtdJikxaNUmuR?chain=solana

We just need to get our TAG updated from $FUD to $FUDSI

**Comment by FuddlesNFT** [comment]
https://github.com/jup-ag/token-list/pull/469

**Comment by 0xSoju2** [comment]
Make a PR that updates your old token on the token-list. 

this PR looks like its a new token completely.

**Comment by 9yoi** [comment]
moved here: https://github.com/jup-ag/token-list/pull/2223

**Pull request closed without merging**
