### PR TITLE
Uber Jeets - UberJeets

### PR DESCRIPTION
**Pull request by uberjeetscto**
# Validate [UberJeets](https://solscan.io/token/G2ShfTkHaPgY1YUqZzB611coeFpbhyGirzgGmyW5fEhV)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/UberJeetsCTO/status/1798158494467833858
- Coingecko/ CMC URL (If available): 

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by uberjeetscto — COMMENTED** [review]
We do have noticed some tokens getting denied for image not matching on chain data.
As we are a community take over and the original developer inserted a GIF as image for chain, we have been avoiding to use that on our listings, but as Jupiter Exchange, pulls data from chain, it was probably a mistake to add new image on validated-tokens.csv, instead of what we have on solscan. Either way, this is the link for the on chain image UBERJEETS has: https://statics.solscan.io/cdn/imgs/s60?ref=68747470733a2f2f63662d697066732e636f6d2f697066732f516d586f6f7772566a4a47624a77753850634e7252726b67614d766d52535768744a7a586763746f6f6b71726a66

**Comment by Jymfletzfur** [comment]
please come into discord

**Comment by uberjeetscto** [comment]
> please come into discord

Which channel should I hop in specifically and to discuss what manner?

**Comment by Jymfletzfur** [comment]
use UberJeets as the name, case sensitive

also use this as your image

https://ipfs.io/ipfs/QmXoowrVjJGbJwu8PcNrRrkgaMvmRSWhtJzXgctookqrjf

**Comment by uberjeetscto** [comment]
New commit submitted. Changes made.

**Review by Jymfletzfur — APPROVED** [review]

**Comment by 9yoi** [comment]
Merged here https://github.com/jup-ag/token-list/pull/4404

**Pull request closed without merging**
