### PR TITLE
Validate Coko

### PR DESCRIPTION
**Pull request by cesarinus**
# Validate CoKo https://solscan.io/token/Hw9NzpmQhZzdt1JaDm5Z7g6MdE1tatdP2epKPeQW7XLA

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging and showing community support: 
https://twitter.com/CoKoTheRunner/status/1785073031246758210
- 
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X  My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
pr inappropriately attempts to alter files other than the csv

**Comment by cesarinus** [comment]
I am not trying to change any file, other than validate my token. Please,
advise how to do it right.

**Comment by cesarinus** [comment]
> pr inappropriately attempts to alter files other than the csv

I am not trying to change any file, other than validate my token. Please,
advise how to do it right

**Comment by cesarinus** [comment]
> pr inappropriately attempts to alter files other than the csv
I can see the following message. Some of the PR that you see on my account are from Synk and not from me:

This PR was automatically created by Snyk using the credentials of a real user.


Snyk has created this PR to upgrade node-downloader-helper from 2.1.6 to 2.1.9.

**Pull request closed without merging**
