### PR TITLE
validate Albärt

### PR DESCRIPTION
**Pull request by Jesuslikex**
# Validate [ALBART](https://solscan.io/token/FXdEk9gaoTsT5wnBpga5NvwrPnQyqq69CyFRaCkU1WKC)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/ALBART_TOKEN/status/1797961068725371263
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by HoriApesSol** [comment]
Please act with caution. A lot of wallets sold more tokens than bought. Check "traders" tab on dexscreener.

https://dexscreener.com/solana/e94reahywmdlj7zurzpbnrs4uf4eug57ste7hau3p41r

**Comment by AidenCze** [comment]
Dev sold a lot with airdropped wallets. Looks like a soft rug

**Comment by Hyarr** [comment]
It isn't normal. One of many wallets with weird activity. Sent in 7,785 mln tokens 29 days ago so at launch. He bought today 159k of tokens to cover the trace as "buyer". 30 min later started to sell the tokens, after 29 days. Everything is on blockchain. Just worth to consider it before even listing this farm. Many people will lose money for sure.

https://solscan.io/account/EQ5xK3oNLWK8yPLJJFndBuin4Hq3amZCYt5pLqqvt3vG#splTransfers

**Comment by Spargelcrypto** [comment]
Looking like a farm. Top 20 wallets all are airdropped and keep selling on each pump.

Seems like the dev and team are slowly farming this coin.

VERY SUSPICIOUS! BE CAREFULL AND DYOR!

**Comment by Jymfletzfur** [comment]
PR inappropriately attempts to add multiple tokens

**Pull request closed without merging**
