### PR TITLE
validate MUMU

### PR DESCRIPTION
**Pull request by mumu-sol**
# Validate [MUMU](https://solscan.io/token/5LafQUrVco6o7KMz42eqVEJ9LW31StPyGjeeu5sKoMtA)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/mumu_bull/status/1768795746193813923
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/mumu-the-bull-3

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by oasis-cover-band** [comment]
dis is gud tek. appppproooof it.

**Comment by oasis-cover-band** [comment]
I can hereby attest that the provided information are accurate, and the token is valid. The token has had $36 million in volume since launch and has the support of some of the biggest names in SOL. For instance: https://twitter.com/The__Solstice/status/1767265406446940488
The token has also been listed on Poloniex already: https://twitter.com/Poloniex/status/1768187376759873813

 
* [x]   Mint address: 5LafQUrVco6o7KMz42eqVEJ9LW31StPyGjeeu5sKoMtA
* [x]   Symbol: MUMU
* [x]   Name: Mumu the Bull
* [x]   Token Decimals: 6
* [x]   Token icon: https://bafkreihszutctvdmdlyjtzfmj7rgvdorpc7jchj2td3feypc7veidbkpsu.ipfs.nftstorage.link
* [x]   On-chain metadata matches
* [x]   No duplication on Jupiter's strict list

**Comment by mumu-sol** [comment]
FYI the token has already been listed on Poloniex: https://twitter.com/Poloniex/status/1768187376759873813
And we have had $36 million in trading volume since launch

**Comment by evm-developer** [comment]
I can hereby attest that the provided information are accurate, and the token is valid. The token has a very strong community, with many well-known influencers supporting it:
https://twitter.com/XMaximist/status/1768697887200874656
https://twitter.com/SolJakey/status/1768735514431987786

Token is already on Poloniex: https://twitter.com/Poloniex/status/1768187376759873813
 
* [x]   Mint address: 5LafQUrVco6o7KMz42eqVEJ9LW31StPyGjeeu5sKoMtA
* [x]   Symbol: MUMU
* [x]   Name: Mumu the Bull
* [x]   Token Decimals: 6
* [x]   Token icon: https://bafkreihszutctvdmdlyjtzfmj7rgvdorpc7jchj2td3feypc7veidbkpsu.ipfs.nftstorage.link
* [x]   On-chain metadata matches
* [x]   No duplication on Jupiter's strict list

**Comment by markeesma** [comment]
I can hereby attest that the provided information are accurate, and the token is valid. The token has had $36 million in volume since launch and has the support of some of the biggest names in SOL. For instance: https://twitter.com/The__Solstice/status/1767265406446940488
The token has also been listed on Poloniex already: https://twitter.com/Poloniex/status/1768187376759873813

Mint address: 5LafQUrVco6o7KMz42eqVEJ9LW31StPyGjeeu5sKoMtA
Symbol: MUMU
Name: Mumu the Bull
Token Decimals: 6
Token icon: https://bafkreihszutctvdmdlyjtzfmj7rgvdorpc7jchj2td3feypc7veidbkpsu.ipfs.nftstorage.link/
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by MeechiCalls** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.
 • Mint address: 5LafQUrVco6o7KMz42eqVEJ9LW31StPyGjeeu5sKoMtA
 • Symbol: MUMU
 • Name: Mumu the Bull
 • Token Decimals: 6
 • Token icon: https://bafkreihszutctvdmdlyjtzfmj7rgvdorpc7jchj2td3feypc7veidbkpsu.ipfs.nftstorage.link/
 • On-chain metadata matches
 • No duplication on Jupiter's strict list

**Comment by Machiyaaa** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.
• Mint address: 5LafQUrVco6o7KMz42eqVEJ9LW31StPyGjeeu5sKoMtA
• Symbol: MUMU
• Name: Mumu the Bull
• Token Decimals: 6
• Token icon: https://bafkreihszutctvdmdlyjtzfmj7rgvdorpc7jchj2td3feypc7veidbkpsu.ipfs.nftstorage.link/
• On-chain metadata matches
• No duplication on Jupiter's strict list

**Comment by mumu-sol** [comment]
FYI we are now also listed on MEXC (in addition to Poloniex): https://twitter.com/MEXC_Official/status/1768911379380252873

**Review by Jymfletzfur — APPROVED** [review]

**Comment by tranceypants** [comment]
MUMU has launching a validator in partnership with HelloMoon

Toly approved: [https://x.com/aeyakovenko/status/1771283187995443483?s=20](https://x.com/aeyakovenko/status/1771283187995443483?s=20)

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
