### PR TITLE
validate oof

### PR DESCRIPTION
**Pull request by turtlejooce**
# Validate [oof](https://solscan.io/token/FSM8TmWxGFUjM7Rs6Wt9DHx3ZQAMX6vC4bN8r5PjSvE8)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: [@oof_solana](https://x.com/oof_solana/status/1734630003973775836?s=20)
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by turtlejooce** [comment]
Mint address: FSM8TmWxGFUjM7Rs6Wt9DHx3ZQAMX6vC4bN8r5PjSvE8
Symbol: oof
Token Decimals: 4
Token icon: https://ih0.redbubble.net/image.1543649450.5330/raf,360x360,075,t,fafafa:ca443f4786.jpg
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by AiCrypto08** [comment]
Mint address: FSM8TmWxGFUjM7Rs6Wt9DHx3ZQAMX6vC4bN8r5PjSvE8
Symbol: oof
Token Decimals: 4
Token icon: https://ih0.redbubble.net/image.1543649450.5330/raf,360x360,075,t,fafafa:ca443f4786.jpg
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Ox2c** [comment]
this looks great

**Review by Ox2c — COMMENTED** [review]
OOF!

**Comment by prickles53** [comment]
Mint address: FSM8TmWxGFUjM7Rs6Wt9DHx3ZQAMX6vC4bN8r5PjSvE8
Symbol: oof
Token Decimals: 4
Token icon: https://ih0.redbubble.net/image.1543649450.5330/raf,360x360,075,t,fafafa:ca443f4786.jpg
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by startom1** [comment]
oooooooof

**Review by Austimized — COMMENTED** [review]
Looks solid.

**Review by startom1 — COMMENTED** [review]
oofs good

**Comment by Timoon21** [comment]
Hey @turtlejooce 

Please make change only on the validated-tokens.csv file.
Not other file.
I close the PR.
Please reopen with only change on the validated-tokens.csv file.

**Pull request closed without merging**
