### PR TITLE
Validate GIGS

### PR DESCRIPTION
**Pull request by Belacosaur**
# Validate [GIGS](https://solscan.io/token/9U8Bn6zAf6Wyp1YHdXtLyfbN7yMvdvW1qQY475iZ5ftZ)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/GigaDAOio/status/1723558083346268369
- Coingecko coming soon. CoinGecko: https://www.coingecko.com/en/coins/gigadao - CMC: https://coinmarketcap.com/dexscan/solana/HWPeHd2SsjTUnjrQ1PBTcff2gNRsQXhqHhcEmkMsrm6v/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC 

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Review by nauriculus — COMMENTED** [review]
I can confirm that the symbol, name, image and mint address match with the on-chain data.

**Comment by meijiao** [comment]
Please check your changes -- only change your line and not the rest, and include the final boolean.

**Comment by Belacosaur** [comment]
Hi @meijiao the only line I have edited in 803.

I have updated the boolean now - This means I have to wait another 7 days?

**Comment by Belacosaur** [comment]
New PR opened here - https://github.com/jup-ag/token-list/pull/409

**Comment by meijiao** [comment]
> Hi @meijiao the only line I have edited in 803.
> 
> I have updated the boolean now - This means I have to wait another 7 days?

no you don't have to, i'll pick up the new PR asap. but could you please undo your autoformatter changes in your new pr that's changing all the lines above yours?

**Pull request closed without merging**
