### PR TITLE
Validate BORK

### PR DESCRIPTION
**Pull request by anondevsol**
# Validate [BORK](https://solscan.io/token/4jZXkSNgTQKCDb36ECZ6a2aNzcUniGcDeXgTdtM2HxAX)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/BorkSOL/status/1742607847060283684?s=20 The quoted tweet provides significant evidence of community support.
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/bork-token/ 
https://www.coingecko.com/en/coins/bork-2

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by anondevsol** [comment]
Hi team, what conflicts need to be resolved exactly?

**Comment by bkellgren** [comment]
Anything still required here?

**Comment by anondevsol** [comment]
Need to be approved all the required info is there.

**Comment by anondevsol** [comment]
> Anything still required here?

just needs to be approved all the required info is there.

**Review by 0xSoju2 — APPROVED** [review]

**Pull request merged**
