### PR TITLE
Validate Green (Phthalocyanine Green) on sol

### PR DESCRIPTION
**Pull request by phthalogreendev**
# Validate [Green](https://solscan.io/token/4iEkSPpXxjsD6fRY9UmCGX73NJch5yakPzYt6McLpump)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/green_on_sol/status/1800274929985765386?s=46&t=8-2sT8jTTkDOO2zr57jD6A
- Coingecko/ CMC URL (If available): Not on coingecko yet

## Validation (Please check off boxes):
- [x ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed) (there is another green but with a lower case g)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [ x] My change matches the format in the file (no spaces between fields).
- [ x] My token is already live and trading on Jupiter.
- [ x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [ x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Jymfletzfur — APPROVED** [review]

**Comment by omaidf** [comment]
APED GREEN

POCKETS OBSCENE

**Comment by zivox** [comment]
GREEEEEEN ✅

**Comment by BigFatGreenNuggets** [comment]
I’m not sure how any of this nerd shit works!!! But yo Jupiter free the green man!!! It doesn’t even show up in the drop down as one of my holdings 

cmon Jupiter please

**Comment by dev-private** [comment]
Jo @Jymfletzfur hey again; pls approve 😘

Greenland need ya

**Comment by Ghostcloakdev** [comment]
Legit project with Legit team, adding this to the Jupiter exchange can only bring more exposure to the goal they are trying to achieve.

**Comment by Ghostcloakdev** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

 Mint address: 4iEkSPpXxjsD6fRY9UmCGX73NJch5yakPzYt6McLpump
 Symbol: GREEN
 Token Decimals: 9
 Token icon: https://img.fotofolio.xyz/?url=https%3A%2F%2Fcf-ipfs.com%2Fipfs%2FQmPskLKKjHTcnJTwMr9iaRup5wrCBLhAwdRGzgUAZdsv7S
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Review by 9yoi — APPROVED** [review]

**Comment by psychoticbaklava** [comment]
Approve this, Green is legit.

**Pull request merged**
