### PR TITLE
PJ-PJ

### PR DESCRIPTION
**Pull request by PJonSOL**
# Validate [PJ](https://solscan.io/token/CSSFYjzNYM8GnSwqbEbKpB4dHicaQynHMhza87p5anaN)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/PJonSOL/status/1793547112078291153
- Coingecko/ CMC URL (If available): https://www.geckoterminal.com/solana/pools/8CGA8bLnh1791G7D8vzKrzh17hbNBjbsFVedLYZvNUia?utm_source=coingecko&utm_medium=referral&utm_campaign=searchresults

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by pinguvip69** [comment]
$PJ devs are one of the hardest working teams out here right now. Had the pleasure of working with them in the past and they are unrelentless. Here for the long haul!

**Comment by pjdevsol** [comment]
@Jymfletzfur Bumping this. Let me know if you need anything to get this approved.

**Comment by Jymfletzfur** [comment]
token is a bit too new, please come back in 1 week

**Comment by PJonSOL** [comment]
Hey @Jymfletzfur Circling back here I believe it has been a week. Let me know if you need anything on our end.

**Comment by pinguvip69** [comment]
> token is a bit too new, please come back in 1 week

Bumping this, team is legit and still building. Please approve the PR if possible.

**Comment by VenoM100x** [comment]
> token is a bit too new, please come back in 1 week

The PJ community has been working hard!  Please approve us. Thank you :-)

**Comment by tush97** [comment]
Please approve us! this team is legit!

**Comment by Overhung** [comment]
Wen strict list ?

**Comment by Kitz18** [comment]
Please approve PR ! thank you

**Comment by Kat061434** [comment]
Please approve PR! its been a week or so , this  should be approve! thank you

**Comment by Josh161992** [comment]
Please approve us! PJ community is waiting

**Comment by Billybob1111** [comment]
GitHub this is a credible project. We have a strong community and devs. Extremely legit. Please approve us!

**Comment by Billybob1111** [comment]
@Jymfletzfur please approve

**Pull request closed without merging**
