### PR TITLE
Validate YOURAI

### PR DESCRIPTION
**Pull request by thijmenFR**
# Validate YOURAI (https://solscan.io/token/FjK6rqU6QzUeNtmK6QQ78cCuS5AHAhcm4HgJkdsvXaep)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/yourtokens/status/1772997843747234173
- Coingecko/ CMC URL (If available): 
   - https://www.coingecko.com/en/coins/your-ai
   - https://coinmarketcap.com/currencies/your/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
in the metadata the token is called 
YOUR AI (Wormhole)

please amend

**Comment by thijmenFR** [comment]
> in the metadata the token is called YOUR AI (Wormhole)
> 
> please amend

Done

**Comment by thijmenFR** [comment]
@Jymfletzfur what can we do to make my pull request final? is there any additional information needed?

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Comment by 9yoi** [comment]
moved here https://github.com/jup-ag/token-list/pull/2960

**Pull request closed without merging**
