### PR TITLE
go to bed old man - LEDGER

### PR DESCRIPTION
**Pull request by ledgersol**
# Validate [LEDGER](https://solscan.io/token/4gkvFD2SFKjR266heEc4XxWd7oPVxesLtAh5uRXdN2vt)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/ledgeronsolana/status/1794158772845482489
- Coingecko/ CMC URL (If available): 

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by jmnemonick123** [comment]
We need to tweet our address with $LEDGER and  tag @JupiterExchange

**Comment by Holafa** [comment]
Is this gold? no it's a diamond

**Comment by nonsenseeth** [comment]
$ledger is hidden gem

**Comment by Kirill-cpu** [comment]
total gem

**Comment by Stokarat** [comment]
I am all in Ledger!

**Comment by Jymfletzfur** [comment]
insufficient mcap

**Comment by pableoo** [comment]
lfg to ze moon $ledger

**Pull request closed without merging**
