### PR TITLE
added $ASS token

### PR DESCRIPTION
**Pull request by ash-ve25**
# Validate [$ASS](https://solscan.io/token/EeSSpFMqEsgjFVMWBiTXkdAiJwWNSSkkZsmHeg8nEUiM)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/ApeSkullSociety/status/1750782526166294807?t=rh1HSqlr9Wc_A39RBJ3Jnw&s=19
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by KidPaddle591** [comment]
Mint address: EeSSpFMqEsgjFVMWBiTXkdAiJwWNSSkkZsmHeg8nEUiM
 Symbol: $ASS Token
 Token Decimals: 9
 Token icon: https://www.apeskullsociety.com/static/media/logo.db828b139c1502bdb577.PNG
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by papidevcrypto** [comment]
Mint address: EeSSpFMqEsgjFVMWBiTXkdAiJwWNSSkkZsmHeg8nEUiM
 Symbol: $ASS Token
 Token Decimals: 9
 Token icon: https://www.apeskullsociety.com/static/media/logo.db828b139c1502bdb577.PNG
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by 0xCyberghostWeb3** [comment]
Mint address: EeSSpFMqEsgjFVMWBiTXkdAiJwWNSSkkZsmHeg8nEUiM
 Symbol: $ASS Token
 Token Decimals: 9
 Token icon: https://www.apeskullsociety.com/static/media/logo.db828b139c1502bdb577.PNG
 On-chain metadata matches
 No duplication on Jupiter's strict list

Dear Jupiter team, please verify and list $ASS 
With love from Cyber

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
