### PR TITLE
Validate CHAD

### PR DESCRIPTION
**Pull request by palinko91**
# Validate [CHAD](https://solscan.io/token/G7rwEgk8KgQ4RUTnMy2W2i7dRDq4hXHD4CSp9PSmSbRW)

## Attestations:
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/ChadOnSolana/status/1716703437541245310

## Validation:
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by Ifezko** [comment]
- [x] Mint address: G7rwEgk8KgQ4RUTnMy2W2i7dRDq4hXHD4CSp9PSmSbRW
- [x] Symbol: CHAD
- [x] Token decimals: 9
- [x] Token icon: https://bafybeicl7hj53czkh3vqclya2tltuuj3f4r7acwbchwjjajfv3jvff62iu.ipfs.nftstorage.link/
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list
```

**Comment by KeyboardWarrior22** [comment]
[x] Mint address: G7rwEgk8KgQ4RUTnMy2W2i7dRDq4hXHD4CSp9PSmSbRW
- [x] Symbol: CHAD
- [x] Token decimals: 9
- [x] Token icon: https://bafybeicl7hj53czkh3vqclya2tltuuj3f4r7acwbchwjjajfv3jvff62iu.ipfs.nftstorage.link/
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by Stefan8019** [comment]
[x] Mint address: G7rwEgk8KgQ4RUTnMy2W2i7dRDq4hXHD4CSp9PSmSbRW
[x] Symbol: CHAD
[x] Token decimals: 9
[x] Token icon: https://bafybeicl7hj53czkh3vqclya2tltuuj3f4r7acwbchwjjajfv3jvff62iu.ipfs.nftstorage.link/
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by fellu** [comment]
- [x] Mint address: G7rwEgk8KgQ4RUTnMy2W2i7dRDq4hXHD4CSp9PSmSbRW
- [x] Symbol: CHAD
- [x] Token decimals: 9
- [x] Token icon: https://bafybeicl7hj53czkh3vqclya2tltuuj3f4r7acwbchwjjajfv3jvff62iu.ipfs.nftstorage.link/
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Review by meijiao — APPROVED** [review]

**Pull request merged**
