### PR TITLE
Update validated-tokens.csv

### PR DESCRIPTION
**Pull request by cesarinus**
# Validate $CoKo https://solscan.io/token/Hw9NzpmQhZzdt1JaDm5Z7g6MdE1tatdP2epKPeQW7XLA

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/CoKoTheRunner/status/1787539273702392049
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
insufficient volume

**Comment by cesarinus** [comment]
I need to validate this token to add funds to my meteora LP

**Review by cesarinus — COMMENTED** [review]
I need to validate this token to add funds to my meteora LP. Meteora LP is asking me to get it validated on Jupiter to start trading it

**Comment by cesarinus** [comment]
This is from Meteora LP:

Pool Contains Unknown Tokens
This permissionless pool comprises one or more tokens that have yet to be verified or listed on the Jupiter token list.

**Comment by cesarinus** [comment]
> insufficient volume

I need to validate this token to start trading it. The comment below is from Meterora LP. I've been trying to validate it for a while.

Pool Contains Unknown Tokens
This permissionless pool comprises one or more tokens that have yet to be verified or listed on the Jupiter token list.

**Comment by cesarinus** [comment]
> I need to validate this token to add funds to my meteora LP. Meteora LP is asking me to get it validated on Jupiter to start trading it

See below from Meteora LP: 

This pool may not have be trading. Deposit $600 to connect this pool to Jupiter. You may lose some value to arbs if the pool price is far from the market price. Once the pool is trading with[Jupiter](https://jup.ag/), you will be able to safely deposit more liquidity.

**Pull request closed without merging**
