### PR TITLE
Validate Blockasset

### PR DESCRIPTION
**Pull request by soroshansari**
# Validate [BLOCK](https://solscan.io/token/NFTUkR4u7wKxy9QLaX2TGvd9oZSWoMo4jqSJqdMb7Nk)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/blockassetco/status/1777416948072247682
- Coingecko URL: https://www.coingecko.com/en/coins/blockasset

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by benlvb** [comment]
Can you check the token image. This is what shown to me when i load the URL. 
Screenshot 2024-04-11 at 11 40 52

**Comment by soroshansari** [comment]
Hey, @benlvb, have you had a chance to check this again?

**Comment by benlvb** [comment]
Apologies for the late reply. But the token logo reflecting on the explorer is different. 
https://solscan.io/token/NFTUkR4u7wKxy9QLaX2TGvd9oZSWoMo4jqSJqdMb7Nk

**Comment by Jymfletzfur** [comment]
Please come into the Discord

**Pull request closed without merging**
