### PR TITLE
Validate REJECT

### PR DESCRIPTION
**Pull request by tonyzheng11**
# Validate [REJECT](https://solscan.io/token/4F2yutcbkabE5MJoDvrDLa5U2re5HPABSCVKA7vqrKcH)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/MonkeRejects/status/1665541772699656192
- Coingecko/ CMC URL (If available): pending review

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Review by Timoon21 — DISMISSED** [review]
- [ ] No on-chain metadata, but matches on SolScan data
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] No duplication on CMC/CoinGecko

**Comment by tonyzheng11** [comment]
`No on-chain metadata`

Is it possible to do this if we got rid of the update-auth key (so we wouldn't be able to add more supply)?

**Comment by Timoon21** [comment]
> `No on-chain metadata`
> 
> Is it possible to do this if we got rid of the update-auth key (so we wouldn't be able to add more supply)?

https://docs.metaplex.com/programs/token-metadata/instructions#create-a-metadata-account

**Review by Timoon21 — APPROVED** [review]

**Review by meijiao — DISMISSED** [review]
Please pull latest from main

**Review by Timoon21 — APPROVED** [review]

**Comment by tonyzheng11** [comment]
> Please pull latest from main

done

**Comment by tonyzheng11** [comment]
@Timoon21 is there somebody else we can get to approval?

**Review by meijiao — APPROVED** [review]

**Pull request merged**
