### PR TITLE
Validate Pepe

### PR DESCRIPTION
**Pull request by PepeSPL**
# Validate [Pepe](https://solscan.io/token/B5WTLaRwaUQpKk7ir1wniNB6m5o8GgMrimhKMYan2R6B)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/pepesolanacomm/status/1795522759294063061
- Coingecko/ CMC URL (If available): 
- CMC - https://coinmarketcap.com/dexscan/solana/FCEnSxyJfRSKsz6tASUENCsfGwKgkH6YuRn1AMmyHhZn/ 
- Coingecko - https://www.coingecko.com/en/coins/pepe-sol

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by timmaycastags — COMMENTED** [review]
[x] On-chain metadata matches the PR
[x] Token address matches the tweet : B5WTLaRwaUQpKk7ir1wniNB6m5o8GgMrimhKMYan2R6B
[x] Community validation: I attest
[x] CoinGecko link: https://www.coingecko.com/en/coins/pepe-sol
[x] Symbol: Pepe
[x] Token Decimals: 6

**Comment by Jymfletzfur** [comment]
Please come into discord

**Comment by Jymfletzfur** [comment]
use this  as your image file

https://ipfs.io/ipfs/QmZMTnCNYincJTTtNvxptHGEnB36F336C544Re5Zjo2QLj

**Comment by PepeSPL** [comment]
Created a new pull request as advised by previous reviewers.

> use this as your image file
> 
> https://ipfs.io/ipfs/QmZMTnCNYincJTTtNvxptHGEnB36F336C544Re5Zjo2QLj

Thank you! Done!

**Review by Jymfletzfur — APPROVED** [review]

**Review by timmaycastags — COMMENTED** [review]
looks good to me

**Review by Vladimir110386 — COMMENTED** [review]
[x] On-chain metadata matches the PR
[x] Token address matches the tweet : B5WTLaRwaUQpKk7ir1wniNB6m5o8GgMrimhKMYan2R6B
[x] Community validation: I attest
[x] CoinGecko link: https://www.coingecko.com/en/coins/pepe-sol
[x] Symbol: Pepe
[x] Token Decimals: 6

**Comment by timmaycastags** [comment]
plz gib approval
https://x.com/phantom/status/1797737784330924116

**Comment by timmaycastags** [comment]
any update?
pepe ticker

**Comment by shponglecoinsol** [comment]
Even don't know why it takes so long 🤦‍♂️

**Comment by timmaycastags** [comment]
https://x.com/SlorgoftheSlugs/status/1798398799104073977 @9yoi some attention please and thank you

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
