### PR TITLE
Validate OPH

### PR DESCRIPTION
**Pull request by openheimercoin**
# Validate [OPH](https://solscan.io/token/Hhv7VD8q2YdLHCGWQxbEfNJYvYr8MapSvhifRRsTkhwn)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/openheimersol/status/1692432150807929125
- Coingecko/ CMC URL (If available): 

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by openheimercoin** [comment]
@Timoon21 
 Mint address: upC8Grw6Kwsm9Y5B44oemwP1hHDTCcVGWVD7jQ3Ju7H
 Symbol: OPH
 Token Decimals: 2
 Token icon: https://arweave.net/fJau0K4Q9vFveI7Fd13FydHd9W0tbhrMVc7OprRddrM
 On-chain metadata matches
 No duplication on Jupiter's strict list
please support Our Token

**Comment by seiwhaleclub** [comment]
> > * [x]    Mint address: upC8Grw6Kwsm9Y5B44oemwP1hHDTCcVGWVD7jQ3Ju7H
> > * [x]    Symbol: OPH
> > * [x]    Token Decimals: 2
> > * [x]    Token icon: https://arweave.net/fJau0K4Q9vFveI7Fd13FydHd9W0tbhrMVc7OprRddrM
> > * [x]    On-chain metadata matches
> > * [x]    No duplication on Jupiter's strict list
> 
> Please Support Our Validate Request Thank's

Please Verified

**Comment by andrira209** [comment]
> # Validate [OPH](https://solscan.io/token/%7BupC8Grw6Kwsm9Y5B44oemwP1hHDTCcVGWVD7jQ3Ju7H%7D)
> ## Attestations (Please provide links):
> * Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/openheimersol/status/1692339509579645421
> * Coingecko/ CMC URL (If available):
> 
> ## Validation (Please check off boxes):
> * [x]  The metadata provided in the PR matches what is on-chain (Mandatory)
> * [x]  Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
> * [ ]  Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)
> 
> ## Acknowledgement (Please check off boxes)
> * [x]  My change matches the format in the file (no spaces between fields).
> * [ ]  My token is already live and trading on Jupiter.
> * [x]  !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

**Comment by andrira209** [comment]
> > > * [x]     Mint address: upC8Grw6Kwsm9Y5B44oemwP1hHDTCcVGWVD7jQ3Ju7H
> > > * [x]     Symbol: OPH
> > > * [x]     Token Decimals: 2
> > > * [x]     Token icon: https://arweave.net/fJau0K4Q9vFveI7Fd13FydHd9W0tbhrMVc7OprRddrM
> > > * [x]     On-chain metadata matches
> > > * [x]     No duplication on Jupiter's strict list
> > 
> > 
> > Please Support Our Validate Request Thank's
> 
> Please Verified

**Comment by openheimercoin** [comment]
@meijiao 🥰

**Pull request closed without merging**
