### PR TITLE
Wojak change of logo URL

### PR DESCRIPTION
**Pull request by Dh1988**
# Validate [Wojak](https://solscan.io/token/4MPA8WbyYtKiufXDSdckEoMPdN5XK1Xw9S9LSLMjK5Y4)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: (https://twitter/Wojak_Coin_Sol/status/1769838255002804346?s=20)- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x ] My token is already live and trading on Jupiter.
- [x ] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Lonelyboycrypto — COMMENTED** [review]
Yes this logo url is working now and is the proper link to use. The previous url didn't work resulting in no logo being displayed.

**Review by firstrank — COMMENTED** [review]
Looks good.

**Comment by Dh1988** [comment]
Conflicts I believe have been resolved please carry out the request to update the logo

**Review by firstrank — COMMENTED** [review]
This should update the logo to be correct.

**Review by Lonelyboycrypto — COMMENTED** [review]
Looks good please merge

**Comment by Jymfletzfur** [comment]
submission is incorrect, you attempt to alter a lot of items

**Pull request closed without merging**
