### PR TITLE
Earnstein

### PR DESCRIPTION
**Pull request by gcompteb**
# Validate [EARN](https://solscan.io/token/GhC2DRuknAcHeV9w9Zd2ASgJyGjTxa1tQnE6pBobZ8iw)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/earnstein_coin/status/1796450513531396322
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
token has no trading volume

**Comment by gcompteb** [comment]
We need to be listed to have trading volume

El ds., 1 de juny 2024, 1:30, Jymfletzfur ***@***.***> va
escriure:

**Comment by gcompte** [comment]
Because we are having problems with Raydium

**Comment by gcompteb** [comment]
Because we are having problems with Raydium

**Pull request closed without merging**
