### PR TITLE
Validate THOL

### PR DESCRIPTION
**Pull request by rodrigoyoshida**
# Validate [THOL](https://solscan.io/token/EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/tholanasol/status/1747093807303164036
- Coingecko URL: https://www.coingecko.com/pt/moedas/tholana

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by danyoshida — COMMENTED** [review]
Confirming the info below about the THOL token

> * [x]   Mint address: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q
> * [x]   Symbol: THOL
> * [x]   Token Decimals: 7
> * [x]   Token icon: https://i.imgur.com/BnZ8Eki.jpeg
> * [x]   On-chain metadata matches
> * [ ]   No duplication on Jupiter's strict list

**Comment by 2233f8** [comment]
Yes this is right. I attest to this update.

**Comment by TRINITYUNITAS** [comment]
i approve of this update

**Comment by blacktux88** [comment]
I approve of this update

**Comment by Mattttty89** [comment]
I approve of this update

**Comment by TurboDev0** [comment]
This update is correct.

**Comment by imadevbro** [comment]
Yes the update is correct thank you

**Comment by Jackharrower** [comment]
This update is correct!!!

**Comment by Transmess** [comment]
Acc this project

**Comment by Zesp77** [comment]
$THOL IS A LEGIT TOKEN, DEAR JUP DEVS, VALIDATE PLS 


- [x] Mint address: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q
- [x] Symbol: THOL
- [x] Token Decimals: 7
- [x] Token icon: https://gateway.irys.xyz/SeNZkL4N4x52OOUlydfcdvsCLk0D8q32PSUWvo5fgRA
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by Mikko-Luomaranta** [comment]
- [x] Mint address: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q
- [x] Symbol: THOL
- [x] Token Decimals: 7
- [x] Token icon: https://gateway.irys.xyz/SeNZkL4N4x52OOUlydfcdvsCLk0D8q32PSUWvo5fgRA
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by JABK007ONE** [comment]
$THOL is legit. I support the validation the CA is :EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q

**Comment by JABK007ONE** [comment]
$THOL is legit. I support the validation 
- [x] Mint address: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q
- [x] Symbol: THOL
- [x] Token Decimals: 7
- [x] Token icon: https://gateway.irys.xyz/SeNZkL4N4x52OOUlydfcdvsCLk0D8q32PSUWvo5fgRA
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by MikkoLuomaranta** [comment]
$THOL is legit token. All data given is correct. 

- [x] Mint address: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q
- [x] Symbol: THOL
- [x] Token Decimals: 7
- [x] Token icon: https://gateway.irys.xyz/SeNZkL4N4x52OOUlydfcdvsCLk0D8q32PSUWvo5fgRA
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by 2233f8** [comment]
$THOL legit, validate! CA: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q"

**Comment by jliving207** [comment]
$THOL is a legit token. Verified all data.

 Mint address: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q
 Symbol: THOL

**Comment by Mattttty89** [comment]
$THOL is legit. I support the validation

- [x] Mint address: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q
- [x] Symbol: THOL
- [x] Token Decimals: 7
- [x] Token icon: https://gateway.irys.xyz/SeNZkL4N4x52OOUlydfcdvsCLk0D8q32PSUWvo5fgRA
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by breestrassburg** [comment]
Validate! CA: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q

$THOL LEGIT, ALL DATA GIVEN IS 

- [x] Mint address: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q
- [x] Symbol: THOL
- [x] Token Decimals: 7
- [x] Token icon: https://gateway.irys.xyz/SeNZkL4N4x52OOUlydfcdvsCLk0D8q32PSUWvo5fgRA
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by blacktux88** [comment]
$THOL is legit token. All data given is correct.

 Mint address: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q
 Symbol: THOL
 Token Decimals: 7
 Token icon: https://gateway.irys.xyz/SeNZkL4N4x52OOUlydfcdvsCLk0D8q32PSUWvo5fgRA
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by juanmamahit** [comment]
Confirming this is $THOL

Mint address: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q
Symbol: THOL
Token Decimals: 7
Token icon: https://i.imgur.com/BnZ8Eki.jpeg
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by erans517** [comment]
Confirming this is $THOL

Mint address: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q
Symbol: THOL
Token Decimals: 7
Token icon: https://i.imgur.com/BnZ8Eki.jpeg
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Crypticwrl** [comment]
Good to go. It's legit THOL coin.

 Mint address: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q
 Symbol: THOL
 Token Decimals: 7
 Token icon: https://i.imgur.com/BnZ8Eki.jpeg
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by dgilperez** [comment]
This is good! $THOL token it is

Mint address: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q
Symbol: THOL
Token Decimals: 7
Token icon: https://i.imgur.com/BnZ8Eki.jpeg
On-chain metadata matches
No duplication on Jupiter's strict list

**Review by Zesp77 — COMMENTED** [review]
Legit

- [x] Mint address: EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q
- [x] Symbol: THOL
- [x] Token Decimals: 7
- [x] Token icon: https://gateway.irys.xyz/SeNZkL4N4x52OOUlydfcdvsCLk0D8q32PSUWvo5fgRA
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by rodrigoyoshida** [comment]
I have been keeping the PR up to date solving the conflicts, let me know if there is something more we can do to get approved

**Comment by rodrigoyoshida** [comment]
Hi! @siong1987 @9yoi @Timoon21 @robbestad 

Could you take a look at this PR? Just to make sure I'm not missing anything that can block Thol from being listed. Thanks!

**Comment by rodrigoyoshida** [comment]
Closing this PR so I can open a new one

**Pull request closed without merging**
