### PR TITLE
 Validate Polygone 

### PR DESCRIPTION
**Pull request by roninwar**
#  Validate Polygone (https://solscan.io/token/J9nsngni1Pavf4ijP4R9QBaD1yEzKzzUQ1vVgcDQT18J#metadata)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/PolygoneonSol/status/1735521099654586383?s=20 
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id} N/A

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by 9yoi** [comment]
Hey please include your token mint on your attestation tweet. It is so we have an official source of truth and prevent imposters from adding a fake mint

**Comment by 9yoi** [comment]
Screenshot 2023-12-21 at 5 48 46 PM
 
 ok i guess this will do

**Review by 9yoi — CHANGES_REQUESTED** [review]
See last comment

**Comment by roninwar** [comment]
ye will get that done now

**Pull request closed without merging**
