### PR TITLE
Validate Jon Wik

### PR DESCRIPTION
**Pull request by Csonuzun**
Added Jon Wik to the validated-tokens.csv

# Validate [WIK](https://solscan.io/token/wikkR42C9DC4KukAQXcZESnYcRcrQXPEYULk1qpcgeK)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: 
**Attestation Tweet from Jon Wik:** https://x.com/jonwikonsolana/status/1802761604481548553

**Interactions with projects:**

1. https://x.com/StepFinance_/status/1798437041975488949
2. https://x.com/assetdash/status/1800228902293639610
3. https://x.com/solflare_wallet/status/1798631619487801805?t=kjbE4dlyxT5_j43NHzKqEQ&s=08
4. https://x.com/solana/status/1793400183914688861?t=oLCRHcF2gL63nPMoozX9YA&s=08
5. https://x.com/Decaf_so/status/1801342298074091692?t=YJMf5iz8BGGlC96W2oMkoA&s=08
6. https://x.com/StepFinance_/status/1799725164755816663?t=fdcglJojxVZDfCloIIkc9A&s=08

- Coingecko/ CMC URL (If available): 

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by MESUT420** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [x]  Mint address: wikkR42C9DC4KukAQXcZESnYcRcrQXPEYULk1qpcgeK
- [x]  Symbol: WIK
- [x]  Token Decimals: 9
- [x]  Token icon: https://ipfs.io/ipfs/bafybeiflljnmin7wb34bb2z63cl74f5h5klzfvcde4sxbwd7p4ukff7rii
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by canergoksel** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [x]  Mint address: wikkR42C9DC4KukAQXcZESnYcRcrQXPEYULk1qpcgeK
- [x]  Symbol: WIK
- [x]  Token Decimals: 9
- [x]  Token icon: https://ipfs.io/ipfs/bafybeiflljnmin7wb34bb2z63cl74f5h5klzfvcde4sxbwd7p4ukff7rii
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by girgics** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [x]  Mint address: wikkR42C9DC4KukAQXcZESnYcRcrQXPEYULk1qpcgeK
- [x]  Symbol: WIK
- [x]  Token Decimals: 9
- [x]  Token icon: https://ipfs.io/ipfs/bafybeiflljnmin7wb34bb2z63cl74f5h5klzfvcde4sxbwd7p4ukff7rii
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by Iteralo** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [x]  Mint address: wikkR42C9DC4KukAQXcZESnYcRcrQXPEYULk1qpcgeK
- [x]  Symbol: WIK
- [x]  Token Decimals: 9
- [x]  Token icon: https://ipfs.io/ipfs/bafybeiflljnmin7wb34bb2z63cl74f5h5klzfvcde4sxbwd7p4ukff7rii
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by Conviously** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [x]  Mint address: wikkR42C9DC4KukAQXcZESnYcRcrQXPEYULk1qpcgeK
- [x]  Symbol: WIK
- [x]  Token Decimals: 9
- [x]  Token icon: https://ipfs.io/ipfs/bafybeiflljnmin7wb34bb2z63cl74f5h5klzfvcde4sxbwd7p4ukff7rii
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by bahadircan-bc** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [x]  Mint address: wikkR42C9DC4KukAQXcZESnYcRcrQXPEYULk1qpcgeK
- [x]  Symbol: WIK
- [x]  Token Decimals: 9
- [x]  Token icon: https://ipfs.io/ipfs/bafybeiflljnmin7wb34bb2z63cl74f5h5klzfvcde4sxbwd7p4ukff7rii
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by ardasevinc** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [x]  Mint address: wikkR42C9DC4KukAQXcZESnYcRcrQXPEYULk1qpcgeK
- [x]  Symbol: WIK
- [x]  Token Decimals: 9
- [x]  Token icon: https://ipfs.io/ipfs/bafybeiflljnmin7wb34bb2z63cl74f5h5klzfvcde4sxbwd7p4ukff7rii
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
