### PR TITLE
Validate ANUS

### PR DESCRIPTION
**Pull request by anus-engineer**
# Validate [ANUS](https://solscan.io/token/9hjZ8UTNrNWt3YUTHVpvzdQjNbp64NbKSDsbLqKR6BZc)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/anuscoinsol/status/1774792654259192210
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/uranus-sol
- https://coinmarketcap.com/currencies/uranus-sol/

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Ucfnationalchamps** [comment]
$ANUS

**Comment by jayzalowitz** [comment]
+1 in support @9yoi

**Comment by futjrnaut** [comment]
can't wait to pump more into UR$ANUS

**Comment by collector-man** [comment]
I am in support of $ANUS

**Comment by lukestokes** [comment]
Let the kids have their jokes, it’s all in good fun. Well distributed community token here.

**Comment by futjrnaut** [comment]
> Let the kids have their jokes, it’s all in good fun. Well distributed community token here.

og luke is og

**Review by Jymfletzfur — APPROVED** [review]

**Comment by jayzalowitz** [comment]
@9yoi what can we do to help?

**Comment by anus-engineer** [comment]
@9yoi  🐥

**Review by 9yoi — APPROVED** [review]

**Comment by futjrnaut** [comment]
great work here

**Pull request merged**
