### PR TITLE
Blizzard

### PR DESCRIPTION
**Pull request by 0xblizz**
# Validate [SBZ](https://solscan.io/token/HesnAGjtgM8dxeNyQiwK614omJqYE99nUCPYmDAmD5sb)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SolBliz/status/1741056558576939418
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by fortunatedrogba1** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [x] Mint address: HesnAGjtgM8dxeNyQiwK614omJqYE99nUCPYmDAmD5sb
- [x] Symbol: SBZ
- [x] Token Decimals: 6
- [x] Token icon: https://mizupad.xyz/sol/gizhQiPZOsRZXGXBJd_82PhVdlM_hACsT_q6wqwf5cSY7I/images/q6wqwf5cS.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by 0x3trady** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [x] Mint address: HesnAGjtgM8dxeNyQiwK614omJqYE99nUCPYmDAmD5sb
- [x] Symbol: SBZ
- [x] Token Decimals: 6
- [x] Token icon: https://mizupad.xyz/sol/gizhQiPZOsRZXGXBJd_82PhVdlM_hACsT_q6wqwf5cSY7I/images/q6wqwf5cS.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by olagunjuea1** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [x] Mint address: HesnAGjtgM8dxeNyQiwK614omJqYE99nUCPYmDAmD5sb
- [x] Symbol: SBZ
- [x] Token Decimals: 6
- [x] Token icon: https://mizupad.xyz/sol/gizhQiPZOsRZXGXBJd_82PhVdlM_hACsT_q6wqwf5cSY7I/images/q6wqwf5cS.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
