### PR TITLE
Validate BLZE

### PR DESCRIPTION
**Pull request by SolBlazeDev**
# Validate [BLZE](https://solscan.io/token/BLZEEuZUBVqFhj8adcCFPJvPVCiCyVmh3hkJMrU8KuJA)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/solblaze_org/status/1691690889956237484
- Coingecko/ CMC URL (If available): Not available yet

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by AC-devon** [comment]
* [x]  Mint address: BLZEEuZUBVqFhj8adcCFPJvPVCiCyVmh3hkJMrU8KuJA
 * [x]  Symbol: BLZE
 * [x]  Token Decimals: 9
 * [x]  Token icon: https://solblaze.org/assets/blze.png
 * [x]  On-chain metadata matches
 * [x]  No duplication on Jupiter's strict list
 
 **support this merge**

**Comment by ronnyhaase** [comment]
Hi! I happily confirm that the provided information are correct and I'm in full support of adding it to Jup's strict list.

 * [x]  Mint address: BLZEEuZUBVqFhj8adcCFPJvPVCiCyVmh3hkJMrU8KuJA
 * [x]  Symbol: BLZE
 * [x]  Token Decimals: 9
 * [x]  Token icon: https://solblaze.org/assets/blze.png
 * [x]  On-chain metadata matches
 * [x]  No duplication on Jupiter's strict list

**Comment by 0xCactus** [comment]
* [x]  Mint address: BLZEEuZUBVqFhj8adcCFPJvPVCiCyVmh3hkJMrU8KuJA
* [x]  Symbol: BLZE
* [x]  Token Decimals: 9
* [x]  Token icon: https://solblaze.org/assets/blze.png
* [x]  On-chain metadata matches
* [x]  No duplication on Jupiter's strict list

**Comment by billythedummy** [comment]
- [x] Mint address: BLZEEuZUBVqFhj8adcCFPJvPVCiCyVmh3hkJMrU8KuJA
- [x] Symbol: BLZE
- [x] Token Decimals: 9
- [x] Token icon: https://solblaze.org/assets/blze.png
- [x] On-chain metadata matches

Supporting this merge

**Comment by dansg1** [comment]
* [x]  Mint address: BLZEEuZUBVqFhj8adcCFPJvPVCiCyVmh3hkJMrU8KuJA
 * [x]  Symbol: BLZE
 * [x]  Token Decimals: 9
 * [x]  Token icon: https://solblaze.org/assets/blze.png
 * [x]  On-chain metadata matches
 * [x]  No duplication on Jupiter's strict list

**Comment by VikHubble** [comment]
* [x]  Mint address: BLZEEuZUBVqFhj8adcCFPJvPVCiCyVmh3hkJMrU8KuJA
 * [x]  Symbol: BLZE
 * [x]  Token Decimals: 9
 * [x]  Token icon: https://solblaze.org/assets/blze.png
 * [x]  On-chain metadata matches
 * [x]  No duplication on Jupiter's strict list

**Review by Timoon21 — COMMENTED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] Community validation
- [ ] Token is already live and trading on Jupiter

I will approve changes as soon as token will be tradable on jupiter

**Comment by Hemmykay** [comment]
* [x]  Mint address: BLZEEuZUBVqFhj8adcCFPJvPVCiCyVmh3hkJMrU8KuJA
 * [x]  Symbol: BLZE
 * [x]  Token Decimals: 9
 * [x]  Token icon: https://solblaze.org/assets/blze.png
 * [x]  On-chain metadata matches
 * [x]  No duplication on Jupiter's strict list

**Comment by dankelleher** [comment]
- [x ]  Mint address: BLZEEuZUBVqFhj8adcCFPJvPVCiCyVmh3hkJMrU8KuJA
- [x ]  Symbol: BLZE
- [ x]  Token Decimals: 9
- [ x]  Token icon: https://solblaze.org/assets/blze.png
- [x ]  On-chain metadata matches
- [ x]  No duplication on Jupiter's strict list

👍 to this PR

**Comment by s6thgehr** [comment]
* [x]  Mint address: BLZEEuZUBVqFhj8adcCFPJvPVCiCyVmh3hkJMrU8KuJA
 * [x]  Symbol: BLZE
 * [x]  Token Decimals: 9
 * [x]  Token icon: https://solblaze.org/assets/blze.png
 * [x]  On-chain metadata matches
 * [x]  No duplication on Jupiter's strict list

**Pull request merged**
