### PR TITLE
Adding SPX6900 (Wormhole) to the list

### PR DESCRIPTION
**Pull request by 1d34h4z4rd**
# Validate [SPX](https://solscan.io/token/J3NKxxXZcnNiMjKw9hYb2K4LUxgwB6t1FtPtQVsv3KFr)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: 

https://x.com/spx6900/status/1737720008095240464

- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/spx6900

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by 1d34h4z4rd** [comment]
Yo @9yoi - is there any additional steps I need to take to get a reviewer to take a look at this?

**Comment by 9yoi** [comment]
we pull wormhole tokens automatically.

are you here already? https://github.com/wormhole-foundation/wormhole-token-list

**Comment by 1d34h4z4rd** [comment]
> we pull wormhole tokens automatically.
> 
> are you here already? https://github.com/wormhole-foundation/wormhole-token-list

Hi yes we are here: https://github.com/wormhole-foundation/wormhole-token-list/blob/ff75fdfd59d4ff2aab206a674318d98e7e6a5b90/content/by_source.csv#L90

**Comment by 1d34h4z4rd** [comment]
Ideally we'd like to be added to the strict list as there are two scams posing as SPX on the all list 
image

**Comment by 9yoi** [comment]
> Ideally we'd like to be added to the strict list as there are two scams posing as SPX on the all list image

we automatically pulled the spx from the wormhole repo already

**Comment by spxfan** [comment]
hey @9yoi we noticed that SPX was removed from the strictlist? can we please be added back? all relevant links in thread

**Comment by 1d34h4z4rd** [comment]
Hey @9yoi @whereismeow @abhay @siong1987 @0xSoju2 @Jymfletzfur did you stop pulling from the Wormhole list? If so can we merge this?

**Pull request closed without merging**
