### PR TITLE
Validate ANSEM

### PR DESCRIPTION
**Pull request by 0xViva**
# Validate [ANSEM](https://solscan.io/token/3Lec18q7nPM62LQwqXG2ddiBTDrFCiNw1NEA1ehBZPgB)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: 

https://twitter.com/AnsemOnSOL/status/1742651080553513202

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers) : https://www.coingecko.com/en/coins/soylanamanletcaptainz 

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by mikeysolana** [comment]
pls approve ansem jup 

main character of solana = main coin of solana

**Comment by cudokub** [comment]
We support our captain

**Comment by Kriegermen** [comment]
Rock solid coin, dev is dedicated and been working on it since inception. Good community.

**Comment by StevenDefi** [comment]
Pls approve. We love &ANSEM

**Pull request closed without merging**
