### PR TITLE
Validate Doge

### PR DESCRIPTION
**Pull request by cryptoblinders**
# Validate [Doge](https://solscan.io/token/Hk82ay38uGpYgqjdXXCiATavVQwAMaBNyxsUWbapmKuL)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/doge_cto_sol/status/1798504883823534558
- Coingecko: https://www.coingecko.com/en/coins/doge-on-sol
- CMC: In progress

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Jymfletzfur — APPROVED** [review]

**Comment by cryptoblinders** [comment]
@9yoi whenever you're ready 🙏

**Comment by cryptoblinders** [comment]
Hi Mei, 

We understand your concerns about potential confusion and misrepresentation, we would like to provide some clarifications and points that we believe will address these issues effectively.

1. **Public Domain**: The Dogecoin brand is effectively public domain, with no active trademark enforcement because there is no trademark to begin with. The first use of this mark can't even be identified due to its widespread and ubiquitous public use. Additionally, Dogecoin's creators, Billy Markus and Jackson Palmer, abandoned their roles early on, leaving the brand to be shaped by the community. There was an attempt to trademark the Dogecoin logo, but it was abandoned. Enforcing such a trademark would be nearly impossible due to the decentralized and community-driven nature of Dogecoin.

2. **Unique Identity on Solana**: DOGE on Solana operates on a different blockchain than Dogechain, providing unique features such as faster transactions and lower fees. Our community is vast and growing, supporting its distinct identity:
   - **Homepage**: [dogeonsol.community](https://dogeonsol.community)
   - **Reddit**: [DogeOnSOL](https://www.reddit.com/r/DogeOnSOL/)
   - **TikTok**: [dogeonsol](https://www.tiktok.com/@dogeonsol?_t=8n8S4YzS3U1&_r=1)
   - **Telegram**: [doge_sol_cto](https://t.me/doge_sol_cto)
   - **Twitter**: [doge_cto_sol](https://x.com/doge_cto_sol)
   - **Daily Stories**: [DogeStories](https://x.com/DogeStories)
   - **Theme Song**: [Doge Theme Song](https://dogect.com/songs/doge.mp3)

3. **Utility**: We have several projects in the works that demonstrate our commitment to innovation and community engagement:
   - **NFT Collection**: A free (cost of mint or airdropped) NFT collection celebrating the spirit of DOGE.
   - **dogebridge.co**: A bridge project to facilitate cross-chain transactions. Strict list approval is holding back an API integration for this project.
   - **Whitepaper**: Final draft of the whitepaper is complete and is currently undergoing a review from our members before we publish.
   - **More Projects**: Additional projects ready to be revealed soon.

4. **Examples of Similar Migrations**: Several communities have successfully migrated to Solana and been approved on the Jupiter strict list despite potential trademark issues. These are direct migrations using the same ticker and logo:
   - **PEPE on SOL**: Successfully added to the Jupiter strict list, demonstrating a similar migration and approval process.
   - **Bonk**: Known for its significant community and active engagement after migrating to Solana.
   - **SHIB (Shiba Inu)**: Originally on Ethereum, now also active on Solana, showing cross-chain community support.
   - **GROK**: Migrated from X.com AI to ETH to Solana.
   - **AMC**: Transitioned from being a stock to ETH to Solana.
   - **GME (Gamestop)**: Moved from stock to ETH to Solana.

The strict list’s goal is to keep users safe and prevent impersonation. Regarding impersonation – there is precedent in point #4, but we would like to add that we are not, nor do we claim to be DOGECOIN. We are $DOGE on Solana, honoring the spirit of the original DOGECOIN. We are building a community that loves having fun, making memes, building relationships, tackling new projects, and more but want to do it on the Solana blockchain, not Dogechain. I think it would be reasonable to assume that it would not misleading people into assuming we are the original DOGECOIN. We believe we demonstrate that our goal aligns with your goal of keeping users safe with our community, dedication and commitment. By validating DOGE on Solana, we can provide users with a distinct option that benefits from the unique features and advantages of the Solana blockchain.

Thank you for considering our request.

From Our Community  
Aaron, CryptoBlinders, Toni, Nova, Fawl3r, Orange Trooper, WaterboyMatt, Peeps, Darius, BurntBeanz, AZ(Flexorcist)

**Comment by cryptoblinders** [comment]
Link to whitepaper: https://dogect.com/whitepaper

**Comment by 9yoi** [comment]
> Hi @9yoi,
> 
> We understand your concerns about potential confusion and misrepresentation, we would like to provide some clarifications and points that we believe will address these issues effectively.
> 
> 1. **Public Domain**: The Dogecoin brand is effectively public domain, with no active trademark enforcement because there is no trademark to begin with. The first use of this mark can't even be identified due to its widespread and ubiquitous public use. Additionally, Dogecoin's creators, Billy Markus and Jackson Palmer, abandoned their roles early on, leaving the brand to be shaped by the community. There was an attempt to trademark the Dogecoin logo, but it was abandoned. Enforcing such a trademark would be nearly impossible due to the decentralized and community-driven nature of Dogecoin.
> 2. **Unique Identity on Solana**: DOGE on Solana operates on a different blockchain than Dogechain, providing unique features such as faster transactions and lower fees. Our community is vast and growing, supporting its distinct identity:
>    
>    * **Homepage**: [dogeonsol.community](https://dogeonsol.community)
>    * **Reddit**: [DogeOnSOL](https://www.reddit.com/r/DogeOnSOL/)
>    * **TikTok**: [dogeonsol](https://www.tiktok.com/@dogeonsol?_t=8n8S4YzS3U1&_r=1)
>    * **Telegram**: [doge_sol_cto](https://t.me/doge_sol_cto)
>    * **Twitter**: [doge_cto_sol](https://x.com/doge_cto_sol)
>    * **Daily Stories**: [DogeStories](https://x.com/DogeStories)
>    * **Theme Song**: [Doge Theme Song](https://dogect.com/songs/doge.mp3)
> 3. **Utility**: We have several projects in the works that demonstrate our commitment to innovation and community engagement:
>    
>    * **NFT Collection**: A free (cost of mint or airdropped) NFT collection celebrating the spirit of DOGE.
>    * **dogebridge.co**: A bridge project to facilitate cross-chain transactions. Strict list approval is holding back an API integration for this project.
>    * **Whitepaper**: Final draft of the whitepaper is complete and is currently undergoing a review from our members before we publish.
>    * **More Projects**: Additional projects ready to be revealed soon.
> 4. **Examples of Similar Migrations**: Several communities have successfully migrated to Solana and been approved on the Jupiter strict list despite potential trademark issues. These are direct migrations using the same ticker and logo:
>    
>    * **PEPE on SOL**: Successfully added to the Jupiter strict list, demonstrating a similar migration and approval process.
>    * **Bonk**: Known for its significant community and active engagement after migrating to Solana.
>    * **SHIB (Shiba Inu)**: Originally on Ethereum, now also active on Solana, showing cross-chain community support.
>    * **GROK**: Migrated from X.com AI to ETH to Solana.
>    * **AMC**: Transitioned from being a stock to ETH to Solana.
>    * **GME (Gamestop)**: Moved from stock to ETH to Solana.
> 
> The strict list’s goal is to keep users safe and prevent impersonation. Regarding impersonation – there is precedent in point 4, but we would like to add that we are not, nor do we claim to be DOGECOIN. We are $DOGE on Solana, honoring the spirit of the original DOGECOIN. We are building a community that loves having fun, making memes, building relationships, tackling new projects, and more but want to do it on the Solana blockchain, not Dogechain. I think it would be reasonable to assume that it would not mislead people into assuming we are the original DOGECOIN. We believe we demonstrate that our goal aligns with your goal of keeping users safe with our community, dedication and commitment. By validating DOGE on Solana, we can provide users with a distinct option that benefits from the unique features and advantages of the Solana blockchain.
> 
> Thank you for considering our request.
> 

> From Our Community Aaron, CryptoBlinders, Toni, Nova, Fawl3r, Orange Trooper, WaterboyMatt, Peeps, Darius, BurntBeanz, AZ(Flexorcist)

Hi @cryptoblinders, sorry for the slow response, I was stuck on what to do next. I read your message and hear your side of the argument. At the same time, the original Dogechain is pretty well known for being on Dogechain, and your project's assertion of a migration to Solana can be misleading, since it's not a bridged or cloned coin. Also, If we go along the lines of the logic that there is no clear owner, then I would have to validate all of the other Doge coins in the screenshot below too with the same icon, and then we're back to square one.  

Screenshot 2024-06-23 at 6 22 24 PM

I am unable to help validate this right now

**Pull request closed without merging**
