### PR TITLE
Validate LEGEND

### PR DESCRIPTION
**Pull request by h4rkl**
# Validate [LEGEND](https://solscan.io/token/LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/Legends_of_SOL/status/1747456919894438305

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter. https://birdeye.so/token/LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx?chain=solana
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by h4rkl** [comment]
This is a second PR after I stupidly force pushed no changes to my branch to resolve conflicts here https://github.com/jup-ag/token-list/pull/1131

There are a huge amount of endorsements on my previous PR.

Sorry!

**Review by cdcruzdev — COMMENTED** [review]
Looks good!

✅Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
✅Symbol: LEGEND
✅Token Decimals: 9
✅Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8
✅On-chain metadata matches
✅No duplication on Jupiter's strict list

**Review by achrafyhy — COMMENTED** [review]
Everything looking cool so far no duplications.

✅Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
✅Symbol: LEGEND
✅Token Decimals: 9
✅Token icon: arweave.net/sCGvXDlbFn8p0s…
✅On-chain metadata matches
✅No duplication on Jupiter's strict list

**Comment by h4rkl** [comment]
> ✅Token icon: https://waq26xbzlmlh6koszuoh5k3ttw4op5fp3teymntjv5drqlkxlepq.arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9

This isn't correct ser

**Review by zfaizal2 — COMMENTED** [review]
this one is for the legends

✅Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
✅Symbol: LEGEND
✅Token Decimals: 9
✅Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8
✅On-chain metadata matches
✅No duplication on Jupiter's strict list

**Review by taxmansol — COMMENTED** [review]
Ship it 🫡

✅Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx 
✅Symbol: LEGEND 
✅Token Decimals: 9 
✅Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8 ✅On-chain metadata matches 
✅No duplication on Jupiter's strict list

**Review by taxmansol — COMMENTED** [review]
Ship it 🫡

✅Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx 
✅Symbol: LEGEND 
✅Token Decimals: 9 
✅Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8 
✅On-chain metadata matches 
✅No duplication on Jupiter's strict list

**Comment by h4rkl** [comment]
> this one is for the legends

Yo! Thank Zayyan ❤️

**Comment by h4rkl** [comment]
Any chance of an approval @9yoi or @benlvb?

**Comment by flamula** [comment]
can confirm, would validate again anytime!

✅Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
✅Symbol: LEGEND
✅Token Decimals: 9
✅Token icon: [https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8]
✅On-chain metadata matches
✅No duplication on Jupiter's strict list

**Comment by robbestad** [comment]
Confirmed

 ✅ Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
 ✅ Symbol: LEGEND 
 ✅ Token Decimals: 9 
 ✅ Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8 
 ✅ On-chain metadata matches 
 ✅ No duplication on Jupiter's strict list

**Comment by DrCryptonite** [comment]
Unsure why Jupiter is not reviewing this.

✅ Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
✅ Symbol: LEGEND
✅ Token Decimals: 9
✅ Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8
✅ On-chain metadata matches
✅ No duplication on Jupiter's strict list

**Comment by robbestad** [comment]
any chance of merging soon?

**Review by Jymfletzfur — APPROVED** [review]

**Review by 0xSoju2 — APPROVED** [review]

**Pull request merged**
