### PR TITLE
validate Cheese

### PR DESCRIPTION
**Pull request by artursapek**
# Validate [Cheese](https://solscan.io/token/AbrMJWfDVRZ2EWCQ1xSCpoVeVgZNpq1U2AoYG98oRXfn)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/dacheeseslice/status/1783272779183190410
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/cheese-2

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Chasewhip8** [comment]
Metadata provided is correct. I support the addition of Cheese.

**Comment by artursapek** [comment]
> Metadata provided is correct. I support the addition of Cheese.

thanks for looking at it! is there anything else you need from me to merge this?

**Comment by Chasewhip8** [comment]
> > Metadata provided is correct. I support the addition of Cheese.
> 
> thanks for looking at it! is there anything else you need from me to merge this?

I am not with the Jupiter team, bumped it in the channel though, but it should be good to go once Mei and Slorg review it.

**Review by Jymfletzfur — APPROVED** [review]

**Comment by artursapek** [comment]
thx @Jymfletzfur - looking for one more approve

**Review by 9yoi — APPROVED** [review]

**Comment by artursapek** [comment]
thanks guys

**Pull request merged**
