### PR TITLE
Validate Solana Meme (SOLMEME)

### PR DESCRIPTION
**Pull request by u4ma-hdd**
Validate Solana Meme (SOLMEME)

# Validate [SOLMEME](https://solscan.io/token/5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VE)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SOLMemeToken/status/1742444248237027709
- Coingecko/ CMC URL (If available):  N/A (work in progress)

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by u4ma-hdd** [comment]
Let me be the first to say that the SOLMEME project is community based. I can confirm that the provided token information is accurate. The token is valid.

Mint address: **5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB**
Symbol: **SOLMEME**
Token Decimals: **7**
Token icon: **https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png**
The On-chain metadata matches
There are no duplication on the current Jupiter's strict list

**Comment by Dorsypretty** [comment]
I attest the information is accurate.The token is Valid

**Comment by CryptoDory** [comment]
SOLMEME project is very community based!

I am sure the provided token information is accurate. The token is valid.

Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
The On-chain metadata matches
There are no duplication on the current Jupiter's strict list

**Comment by faithfulbassey2** [comment]
The SOLMEME project operates within a community-driven framework. I hereby verify the accuracy of the provided token information, confirming its validity.

- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token Icon: SOLMEME Logo
- On-chain metadata is consistent.
- No instances of duplication on Jupiter's stringent list.

**Comment by Fabulous88** [comment]
I want to emphatically attest that the below information is very accurate;

Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Toofooxx** [comment]
Hi, 
I can confirm that this token is a legit one, we are the community behind it


The community is active and we would like to make it simple for new comers, to grow more. 
Thanks 
Hereafter all needed info:
Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- The On-chain metadata matches
- There are no duplication on the current Jupiter's strict list

**Comment by mak-hue** [comment]
```- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- The On-chain metadata matches
- There are no duplication on the current Jupiter's strict list``

**Comment by Anna2784** [comment]
Solmeme is a community driven meme coin and I am one of its early members and investors. I can attest that the information provided is very accurate. 
Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB Symbol: SOLMEME Token Decimals: 7 Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png The On-chain metadata matches There are no duplication on the current Jupiter's strict list.

**Comment by marvyXCX** [comment]
I can attest to the fact that SOLMEME is a real project with a vibrant and active community.

Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
The On-chain metadata matches
There are no duplication on the current Jupiter's strict list

**Comment by Kind-leo** [comment]
> >

 LFG @everyone SOLMEME and address; 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB is a legit token is  and you can also take a look their twitter official handle; https://twitter.com/SOLMemeToken and
 website ;https://solme.me/
With real and active members
```- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- The On-chain metadata matches
- There are no duplication on the current Jupiter's strict list

**Comment by parishahrokh** [comment]
SOLMEME is a real project with an active and intimate community.

Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
The On-chain metadata matches
There are no duplication on the current Jupiter's strict list

**Comment by Vick112** [comment]
Have you checked <#1189558498770567298> , guys.

Let’s all help the project. Let’s all check and do the needful

**Comment by Ripple090** [comment]
Nice obe

**Comment by Vick112** [comment]
SOLMEME is a real project with an active and intimate community.

Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
The On-chain metadata matches
There are no duplication on the current Jupiter's strict list

**Comment by RaZoNsol** [comment]
I confirm the legitimacy of SOLMEME, they have a great and active community and I'm happy to be part of it.

Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
The On-chain metadata matches
There are no duplication on the current Jupiter's strict list

**Comment by Vick112** [comment]
I confirm the legitimacy of SOLMEME, they have a great and active community and I'm happy to be part of it.

Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
The On-chain metadata matches
There are no duplication on the current Jupiter's strict list

**Comment by Ochykes01** [comment]
SOlMeme is  a genuine project with an incredible community. I affirm the provided information is accurate . The token is valid.

**Comment by Ochykes01** [comment]
Solmeme is a genuine project with an incredible community. I affirm the provided information is accurate. The token is valid.
Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
The On-chain metadata matches
There are no duplication on the current Jupiter's strict list

**Comment by MissMaria97** [comment]
Solmeme is a solana Based project , it’s the next big thing, Looking promising , creative, SOLMEME IS HOME 🏡. The token is valid.

Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
The On-chain metadata matches
There are no duplication on the current Jupiter's strict list

**Comment by DEAN1799** [comment]
I unequivocally affirm the legitimacy of SOLMEME, a project marked by its robust and engaged community, of which I am proud to be a member. Their vibrant and active community exemplifies their credibility, and I am delighted to contribute to its growth and success.


Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
The On-chain metadata matches
There are no duplication on the current Jupiter's strict list

**Comment by GtarCrypto** [comment]
(SOLMEME) and address (5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB)

Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
The On-chain metadata matches
There are no duplication on the current Jupiter's strict list

**Comment by pardisbf** [comment]
Great team, Great project. "SOLMEME"

Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
The On-chain metadata matches
There are no duplication on the current Jupiter's strict list

**Comment by RichJames1** [comment]
I’m part of the SOLmeme great project having good potentials and road map, Servers best with more information and announcements from Discord 
Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
The On-chain metadata matches
There are no duplication on the current Jupiter's strict list

**Comment by MathiasSamuel** [comment]
> I confirm the legitimacy of SOLMEME, they have a great and active community and I'm happy to be part of it.
> 
> Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB Symbol: SOLMEME Token Decimals: 7 Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png The On-chain metadata matches There are no duplication on the current Jupiter's strict list



> I have been part of the amazing Discord Community for the past 2months . I attest the information is accurate.The token is Valid Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB Symbol: SOLMEME Token Decimals: 7 Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png The On-chain metadata matches There are no duplication on the current Jupiter's strict list

**Comment by MathiasSamuel** [comment]
I confirm the legitimacy of SOLMEME, they have a great and active community and I'm happy to be part of it.
> 
> Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB Symbol: SOLMEME Token Decimals: 7 Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png The On-chain metadata matches There are no duplication on the current Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
