### PR TITLE
Validate SolCard

### PR DESCRIPTION
**Pull request by TheSolanar**
# Validate [SOLC](https://solscan.io/token/DLUNTKRQt7CrpqSX1naHUYoBznJ9pvMP65uCeWQgYnRK)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SolCardCC/status/1768129386622992589
- Coingecko/ CMC URL (If available): 

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by 609NFT** [comment]
@TheSolanar I'm getting the same build error on my PR. Any idea how to fix?

**Comment by adityadees** [comment]
> @TheSolanar I'm getting the same build error on my PR. Any idea how to fix?

maybe because this 
 `Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)`

**Comment by TheSolanar** [comment]
> > @TheSolanar I'm getting the same build error on my PR. Any idea how to fix?
> 
> maybe because this `Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)`

possible, I contacted jupiter support already & will do a last try creating new PR.

**Comment by TheSolanar** [comment]
> @TheSolanar I'm getting the same build error on my PR. Any idea how to fix?

not really, contacted jupiter support & waiting for response.

**Pull request closed without merging**
