### PR TITLE
GMCOCK Request

### PR DESCRIPTION
**Pull request by dmconley**
# Validate [{GMCOCK}](https://solscan.io/token/{8CSTYs264XFrGym2WLy6QGgq6isxU8G4Und9q1gVbbbB})

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/GMCOCK_COIN/status/1740599742131061155?s=20
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by dmconley** [comment]
gm Jupitoooors thx for all your hard work.

**Comment by dmconley** [comment]
We dont have Coingecko but wasn't sure if I was meant to delete that or not

**Comment by dmconley** [comment]
I had a conflicting csv due to another token in the group 1068-1072 and have resolved it as per my understanding but can you guys please check that group when free?

**Comment by dmconley** [comment]
@0xSoju2 I spoke with you in discord a few days ago about this PR I just want to see that the issue I am bringing up in here is accurate and in 100% honestly am not trying to move my PR forward by tagging you. You mentioned that you would check it out when we spoke but just wanted to ping you to get eyes on the issue I brought up

**Comment by Jymfletzfur** [comment]
duplicate submission

**Pull request closed without merging**
