### PR TITLE
Add Spiral Safe

### PR DESCRIPTION
**Pull request by saberistic**
# Validate [{Spiral Safe}](https://solscan.io/token/XcjpebAGHtHsnkZjja8yFLUFdGyoWhF3GJLxj3isEUU)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SpiralSafe/status/1744888674259534151}
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [-] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)   (In Progress)

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by benlvb — APPROVED** [review]

**Comment by saberistic** [comment]
Thanks @benlvb for approving it. I resolved the conflict

**Comment by Jymfletzfur** [comment]
On chain name is Spiral Safe

On application its called SpiralSafe

**Comment by saberistic** [comment]
> On chain name is Spiral Safe
> 
> On application its called SpiralSafe

fixed it

**Comment by Jymfletzfur** [comment]
does not meet required metrics.

closing for now, please come into the Discord if you want to follow up

**Pull request closed without merging**
