### PR TITLE
Intergalactic ($IMSO)

### PR DESCRIPTION
**Pull request by johnwinsor**
# Validate [IMSO](https://solscan.io/token/imsoru6juztJ4pTJvPQaTnY766uEmCVc4AQJ8V1Yuvs)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/imsonft_chris/status/1806741580101071008
- Coingecko/ CMC URL (If available):

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by holyrood** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

* [x]   Mint address: imsoru6juztJ4pTJvPQaTnY766uEmCVc4AQJ8V1Yuvs
* [x]   Symbol: IMSO
* [x]   Token Decimals: 9
* [x]   Token icon: https://shdw-drive.genesysgo.net/BNhknYkm4djh4V7c5jYHrRWBYvsH3wngsjd5MM3q7Ho9/interImage.jpeg
* [x]   On-chain metadata matches
* [x]   No duplication on Jupiter's strict list

**Comment by johnwinsor** [comment]
I just wanted to add a comment - I realize that this token does not meet the requirement of being 3 weeks old. We are trying to expedite this as there are currently 3 copycat tokens discoverable on jup.ag that are using both our icon as well as our vanity address prefix. This is potentially confusing and dangerous for our community.

Thanks for considering us!

Screenshot 2024-06-28 at 2 23 54 PM

**Comment by danielmeyers34** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

* [x]   Mint address: imsoru6juztJ4pTJvPQaTnY766uEmCVc4AQJ8V1Yuvs
* [x]   Symbol: IMSO
* [x]   Token Decimals: 9
* [x]   Token icon: https://shdw-drive.genesysgo.net/BNhknYkm4djh4V7c5jYHrRWBYvsH3wngsjd5MM3q7Ho9/interImage.jpeg
* [x]   On-chain metadata matches
* [x]   No duplication on Jupiter's strict list

**Comment by scromie** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

* [x]   Mint address: imsoru6juztJ4pTJvPQaTnY766uEmCVc4AQJ8V1Yuvs
* [x]   Symbol: IMSO
* [x]   Token Decimals: 9
* [x]   Token icon: https://shdw-drive.genesysgo.net/BNhknYkm4djh4V7c5jYHrRWBYvsH3wngsjd5MM3q7Ho9/interImage.jpeg
* [x]   On-chain metadata matches
* [x]   No duplication on Jupiter's strict list

**Comment by numisman** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

* [x]   Mint address: imsoru6juztJ4pTJvPQaTnY766uEmCVc4AQJ8V1Yuvs
* [x]   Symbol: IMSO
* [x]   Token Decimals: 9
* [x]   Token icon: https://shdw-drive.genesysgo.net/BNhknYkm4djh4V7c5jYHrRWBYvsH3wngsjd5MM3q7Ho9/interImage.jpeg
* [x]   On-chain metadata matches
* [x]   No duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
