### PR TITLE
Validate  gigglechad

### PR DESCRIPTION
**Pull request by chedscott**
# Validate [CHED](https://solscan.io/token/12mcpYL84oMi8Hiinyjuv2Zq3F47tLLxjw1THLcAdKT2)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/giggleched/status/1783557995013484570?t=6UKc7Z16tqIWN77ZZeievw&s=19
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
please come into the discord

**Comment by chedscott** [comment]
Do you have the discord link for me?

**Comment by chedscott** [comment]
Tagged @slorg on dc with the validation number

**Comment by chedscott** [comment]
I am in the discord @scottg420



Op do 9 mei 2024 06:46 schreef Jymfletzfur ***@***.***>:

**Comment by Jymfletzfur** [comment]
Use this as the imagelink

https://bafybeidbzidjhf5wo2l2dljjgbcozxwafwdgsfjzzmt2zwcketodzzqdfa.ipfs.cf-ipfs.com/

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
