### PR TITLE
Corrected Wuffi token (WUF) URL (Update validated-tokens.csv)

### PR DESCRIPTION
**Pull request by wuffi-inu**
# Validate [WUF](https://solscan.io/token/73xsLcBnLnc9bh81cqVKqj8uEyiarXng5ZwJuTbnVebG)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/WUFFI_Inu/status/1800189728052121870
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/wuffi/ https://www.coingecko.com/en/coins/wuffi

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

Extra info: this PR corrects the previously incorrect logo URL provided in the original validation request

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
This is the image that appears in the metadata

https://ipfs.io/ipfs/QmPyfiqUWpeb2VpuKAoJph7mfoeJ3uoGVt6KgRZdUwoncA

**Comment by porkchop** [comment]
> This is the image that appears in the metadata
> 
> https://ipfs.io/ipfs/QmPyfiqUWpeb2VpuKAoJph7mfoeJ3uoGVt6KgRZdUwoncA

Thanks. I will correct it to that image

**Comment by wuffi-inu** [comment]
> This is the image that appears in the metadata
> 
> https://ipfs.io/ipfs/QmPyfiqUWpeb2VpuKAoJph7mfoeJ3uoGVt6KgRZdUwoncA

Oh right. Thank you. Give me one moment and we will correct that image path to the same as on chain...

**Comment by wuffi-inu** [comment]
I've corrected the icon path to the image URL on chain. Thanks for pointing that out.
Let me know if you'd like me to flatten the commits

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
