### PR TITLE
Validate $RKT

### PR DESCRIPTION
**Pull request by 0xBlackfish**
# Validate [$RKT](https://solscan.io/token/RKT69NZHN5uovcan3q5hRbZzfJuXiGEuPmGANoBJLLz)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/racket_wtf/status/1730974019321507915

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by sadik112769** [comment]
https://twitter.com/Taufiqu95020791/status/1730104329699578171?t=Vg8mBXe2eYhPs_QsAS4CpA&s=19

**Comment by Slamsol** [comment]
Happy to attest that the data in the PR matches the token in circulation for $RKT.  
$RKT is not found elsewhere on Solana.

**Comment by Slamsol** [comment]
https://x.com/anothercryptom1/status/1730140602254463152?s=46&t=4oRE-Lj7Cr08DjebiXhiIQ

**Comment by theBadThang** [comment]
I verified that on-chain metadata matches the PR, token address matches the tweet, no duplication on Jupiter's strict list, no duplication on CMC/CoinGecko, and that the token is already live and trading on Jupiter.

**Comment by opub** [comment]
- On-chain metadata matches the PR
- Token address matches the tweet
- No duplication on Jupiter's strict list
- No duplication on CMC/CoinGecko
- Community validation

**Comment by Timoon21** [comment]
Your PR in still in Draft.
On the commit you modify all the file.
Can you just add your token at the end of the file without apply change to all lines?
Check other token to compare "files changed" tab.

**Comment by 0xBlackfish** [comment]
All fixed @Timoon21 🙏🏼

**Review by benlvb — DISMISSED** [review]

**Review by Timoon21 — APPROVED** [review]

**Comment by 0xBlackfish** [comment]
@Timoon21 - where does it say "merge is blocked"?

**Review by benlvb — DISMISSED** [review]

**Pull request merged**
