### PR TITLE
Add Bonk of America ($BONKFA) to Strict List

### PR DESCRIPTION
**Pull request by oyoops**
I can hereby attest that the provided information are accurate, and the token is valid.

 Mint address: DoxsC4PpVHiUxCKYeKSkPXVVVSJYzidZZJxW4XCFF2t
 Symbol: BONKFA
 Token Decimals: 6
 Token icon: https://bafybeibh32qfakyjqnxl2p3zyndqmtubjcwkbiimk3qcb6v4wyzekmr5x4.ipfs.nftstorage.link/
 On-chain metadata matches
 No duplication on Jupiter's strict list

# [Validate BONKFA](https://solscan.io/token/DoxsC4PpVHiUxCKYeKSkPXVVVSJYzidZZJxW4XCFF2t)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/BonkOfA/status/1762518170420625763
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/dexscan/solana/GjJhMRANwZVDS1x7MzChEJDDyRp5qPRzARDkY2kEhBpx/

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Jymfletzfur — APPROVED** [review]

**Comment by randomshinichi** [comment]
```
Metadata does not match on-chain data: DoxsC4PpVHiUxCKYeKSkPXVVVSJYzidZZJxW4XCFF2t URI mismatch Expected: https://bonkfa.com/assets/images/bonkfa_logo.gif, Found Onchain: https://bafybeibh32qfakyjqnxl2p3zyndqmtubjcwkbiimk3qcb6v4wyzekmr5x4.ipfs.nftstorage.link/ (from JSON https://bafkreiaukfbgn3ockro3q2i5whpofk7ur4uagv2jbfvflitme73cz4ud4i.ipfs.nftstorage.link/)
```

Basically, just change your PR to point to https://bafybeibh32qfakyjqnxl2p3zyndqmtubjcwkbiimk3qcb6v4wyzekmr5x4.ipfs.nftstorage.link/

**Comment by oyoops** [comment]
@Jymfletzfur Token logo has been updated in PR!

**Review by oyoops — COMMENTED** [review]
Pointed BONKFA logo to on-chain

**Comment by nrsander** [comment]
### Re-Attestation:

**I can hereby attest that the provided information are accurate, and the token is valid.**

 **Mint address:** DoxsC4PpVHiUxCKYeKSkPXVVVSJYzidZZJxW4XCFF2t
 **Symbol:** BONKFA
 **Token Decimals:** 6
 **Token icon:** https://bafybeibh32qfakyjqnxl2p3zyndqmtubjcwkbiimk3qcb6v4wyzekmr5x4.ipfs.nftstorage.link
 **On-chain metadata** matches
 **No duplication** on Jupiter's strict list

**Comment by randomshinichi** [comment]
@9yoi I don't understand why the validator gives this error even though his commit just changes one line
```

Tokens already in the CSV should not be edited {
Name: 'Infinity',
Symbol: 'INF',
Mint: '5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm',
Decimals: '9',
LogoURI: 'https://cloudflare-ipfs.com/ipfs/bafkreiflz2xxkfn33qjch2wj55bvbn33q3s4mmb6bye5pt3mpgy4t2wg4e',
'Community Validated': false,
Line: 145
} {
Name: 'Socean staked SOL',
Symbol: 'scnSOL',
Mint: '5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm',
Decimals: '9',
LogoURI: 'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm/logo.png',
'Community Validated': false,
Line: 145
}
```

**Comment by oyoops** [comment]
> @9yoi I don't understand why the validator gives this error even though his commit just changes one line
> 
> ```
> 
> 
> 
> Tokens already in the CSV should not be edited {
> 
> Name: 'Infinity',
> 
> Symbol: 'INF',
> 
> Mint: '5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm',
> 
> Decimals: '9',
> 
> LogoURI: 'https://cloudflare-ipfs.com/ipfs/bafkreiflz2xxkfn33qjch2wj55bvbn33q3s4mmb6bye5pt3mpgy4t2wg4e',
> 
> 'Community Validated': false,
> 
> Line: 145
> 
> } {
> 
> Name: 'Socean staked SOL',
> 
> Symbol: 'scnSOL',
> 
> Mint: '5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm',
> 
> Decimals: '9',
> 
> LogoURI: 'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm/logo.png',
> 
> 'Community Validated': false,
> 
> Line: 145
> 
> }
> 
> ```

Is there anything I can do to help?

**Comment by oyoops** [comment]
> @9yoi I don't understand why the validator gives this error even though his commit just changes one line
> 
> ```
> 
> 
> 
> Tokens already in the CSV should not be edited {
> 
> Name: 'Infinity',
> 
> Symbol: 'INF',
> 
> Mint: '5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm',
> 
> Decimals: '9',
> 
> LogoURI: 'https://cloudflare-ipfs.com/ipfs/bafkreiflz2xxkfn33qjch2wj55bvbn33q3s4mmb6bye5pt3mpgy4t2wg4e',
> 
> 'Community Validated': false,
> 
> Line: 145
> 
> } {
> 
> Name: 'Socean staked SOL',
> 
> Symbol: 'scnSOL',
> 
> Mint: '5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm',
> 
> Decimals: '9',
> 
> LogoURI: 'https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm/logo.png',
> 
> 'Community Validated': false,
> 
> Line: 145
> 
> }
> 
> ```

Does it have something to do with how those two unrelated tokens share the same mint address?

Please don't forget about us!

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
