### PR TITLE
validate Twitter

### PR DESCRIPTION
**Pull request by twitteronsol**
# Validate [TWTR](https://solscan.io/token/FcScaNdN3TRPMwcgqHj1E5GuEh1rNesBGVN5WtZuad1z)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/TW1TTERonSOL/status/1764629935665336654?s=20}
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [ ] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by cpcryp** [comment]
WTR should really be on the strict list, the founder jpgphenom gives everything together with the team to get a successful project up and running. our community is growing every day. we don't want dumb and pump but a healthy and steady growth. we have created a really great community within a few days and would be really happy if you help us to take the project to the next level.

**Comment by CryptoSolvare** [comment]
$TWTR, great community, holding strong around the 100k - 200k mcap for a pretty long time. Honest dev, who’s working with a team behind the scenes on a website, marketing, listings, etc. Can’t forget the narrative, everyone loves the bird and it’ll always be called Twitter!

**Comment by samboateng23** [comment]
$TWTR: home of all the crypto alpha. Nostalgic and bringing back the infamous bird stock as we know it. Honest dev and fantastic community. The bird will fly! What better way to revive the $TWTR ticker than on the Solana ecosystem with a solid community.

**Comment by SB50000** [comment]
$TWTR: home of all the crypto alpha. Nostalgic and bringing back the infamous bird stock as we know it. Honest dev and fantastic community. The bird will fly! What better way to revive the $TWTR ticker than on the Solana ecosystem with a great community.

**Review by Jymfletzfur — APPROVED** [review]

**Comment by 9yoi** [comment]
Unsure about this one -- can we merge a Twitter TWTR that's not from the real twitter? seems like impersonation

**Comment by SB50000** [comment]
Hi 9yoi, in theory Twitter - TWTR no longer exists as it is now known as X.

**Comment by bachew** [comment]
Solsniffer score for this token is really bad:

https://solsniffer.com/scanner/FcScaNdN3TRPMwcgqHj1E5GuEh1rNesBGVN5WtZuad1z

**Comment by SB50000** [comment]
Hi Bachew,

What does this mean? This is a long term project so 11% has supply has been locked for 6 months and the other 11% for a year. Everything has been done by the book by our team.

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
