### PR TITLE
Validate DumbGayRetard

### PR DESCRIPTION
**Pull request by e-liminat**
# Validate [Blob](https://solscan.io/token/85vb4pd3gyVMxQ211ZBXXWQJwJ4xZPBC5AQXvnmb1HTi)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/blobfam1/status/1774970525603012880

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by mrchonky** [comment]
This is a very good coin loved by many. It is our favorite blob. Pls put on strict list so our loved ones do not get scammed pls bro

**Comment by blobfam1** [comment]
YO LFG $BLOB TO $1 BABY !!
I LOVE BLOB, CAN WE GET THIS ROLLING PLEASE !!!
12d5be50-79f9-462c-8e6a-371d10ed1ea8

**Comment by e-liminat** [comment]
Just checking in - is all of the criteria met for verification?

**Comment by e-liminat** [comment]
Hi, reaching out to see if there's anything that you need. In the past month since we've opened this PR, there have been 10 coins with the same name, and some have had their liquidity pulled. 

We'd like to ensure that we do everything we can to protect users, and want to know how we can reach you, in any capacity, to have this token reviewed and added to the safe list. 

We have a large community of frequent users on Twitter, we are an honest group of people, and we are taking our message through the appropriate channel. Is there anything you need us do to have the Jupiter team review our PR?

**Comment by Jymfletzfur** [comment]
Use this as your image link

https://bafkreifqv7y73fnk7vtpl2v5yocbxs4amwmw2r5ugg4ea3wt73zk6x2mb4.ipfs.nftstorage.link/

**Review by Jymfletzfur — APPROVED** [review]

**Comment by e-liminat** [comment]
Hi @Jymfletzfur,

when I opened this page a moment ago, I read the advice to update the link from

https://bafkreihnoonnyxbvgl3hmwncc5jf7ibduzcbo6wgts572peipa5vlhigmi.ipfs.nftstorage.link

to

https://bafkreifqv7y73fnk7vtpl2v5yocbxs4amwmw2r5ugg4ea3wt73zk6x2mb4.ipfs.nftstorage.link/

I'm reviewing the page now, and I see that you have reviewed and approved the token in it's current format. 
Would you still suggest that we make that update? I can perform it right now.

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
