### PR TITLE
Validate $IRAQ Iraq Lobster

### PR DESCRIPTION
**Pull request by JohnRM992**
# Validate [IRAQ](https://solscan.io/token/92ikAbse3AabxqKqNX4BnmTtES6umeyw5odqbpfb5unp)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/iraqlobstersol/status/1781438616310571135?s=46&t=NpeMi3ZksoVk-DW_G7Nc1Q
- Coingecko/ CMC URL (If available): Here is IRAQ auto-generated CMC from the on-chain information:
https://coinmarketcap.com/dexscan/solana/N89vPoJwSbymtUWjdDvNLB8sd81CY219Do4tTeUvKqW/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by JohnRM992 — COMMENTED** [review]
Moved from line 1418 to 1424 to resolve conflict

**Comment by JohnRM992** [comment]
Mint address: 92ikAbse3AabxqKqNX4BnmTtES6umeyw5odqbpfb5unp
Name: Iraq Lobster
 Symbol: IRAQ
 Token Decimals: 9
 Token icon: https://ibb.co/Z68gQSM
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by JohnRM992** [comment]
[x] Mint address: 92ikAbse3AabxqKqNX4BnmTtES6umeyw5odqbpfb5unp
[x] Name: Iraq Lobster
[x]  Symbol: IRAQ
[x]  Token Decimals: 9
[x]  Token icon: https://ibb.co/Z68gQSM
[x]  On-chain metadata matches
[x]  No duplication on Jupiter's strict list

**Comment by JohnRM992** [comment]
* [x]  Mint address: 92ikAbse3AabxqKqNX4BnmTtES6umeyw5odqbpfb5unp
 * [x]  Symbol: IRAQ
 * [x]  Name: Iraq Lobster
 * [x]  Token Decimals: 9
 * [x]  Token icon: https://ibb.co/Z68gQSM
 * [x]  On-chain metadata matches
 * [x]  No duplication on Jupiter's strict list

**Comment by CryptoExplorer92** [comment]
Official token from IraqLobsterSOL 
https://x.com/IraqLobsterSOL/status/1781438616310571135

**Comment by RaidsLunatic117** [comment]
* [x]  Mint address: 92ikAbse3AabxqKqNX4BnmTtES6umeyw5odqbpfb5unp
 * [x]  Symbol: IRAQ
 * [x]  Name: Iraq Lobster
 * [x]  Token Decimals: 9
 * [x]  Token icon: https://ibb.co/Z68gQSM
 * [x]  On-chain metadata matches
 * [x]  No duplication on Jupiter's strict list

**Comment by JonathanRM92** [comment]
* [x]  Mint address: 92ikAbse3AabxqKqNX4BnmTtES6umeyw5odqbpfb5unp
 * [x]  Symbol: IRAQ
 * [x]  Token Decimals: 9
 * [x]  Token icon: https://ibb.co/Z68gQSM
 * [x]  On-chain metadata matches
 * [x]  No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
