### PR TITLE
Validate PEPEMS

### PR DESCRIPTION
**Pull request by pepems**
# Validate [PEPEMS](https://solscan.io/token/6phcMedqo4MCKnVre46EngvnaXuk4mH8MXfsuNBvjz9b)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/Pepemanuscript/status/1784626820589011175
- Coingecko/ CMC URL (If available): COMING SOON

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by pepems** [comment]
[validate-PR](https://github.com/jup-ag/token-list/actions/workflows/validate-PR.yml)

**Review by pepems — COMMENTED** [review]
[validate-PR](https://github.com/jup-ag/token-list/actions/workflows/validate-PR.yml)

**Review by pepems — COMMENTED** [review]
ALL RIGHT

**Review by pepems — COMMENTED** [review]
Name: PEPE MANUSCRIPT V2
Symbol: PEPEMS
Mint Address: 6phcMedqo4MCKnVre46EngvnaXuk4mH8MXfsuNBvjz9b
Decimals: 6
LogoURI: https://bafybeif3ee4ifis2zficswa6334ia33gwebf3334x4pk7dysnve66akhyi.ipfs.nftstorage.link
Community Validated: true

**Review by devpepem — COMMENTED** [review]
all right

**Review by pepems — COMMENTED** [review]
all rights

**Comment by Jymfletzfur** [comment]
pr inappropriately attempts to alter several files unrelated to the csv

**Pull request closed without merging**
