### PR TITLE
Validate One Punch Man (SAITAMA)

### PR DESCRIPTION
**Pull request by tiparkki**
# Validate [SAITAMA](https://solscan.io/token/CVRwdbkwSube1ifeNLFDdZSTmVEnLcyDuKXTdaZX1ua5)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/saitama_sol_/status/1793024164804051000
- Coingecko/ CMC URL (If available): N/A

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by SmokedOut87 — COMMENTED** [review]
Approved.

**Review by SmokedOut87 — COMMENTED** [review]
approved

**Comment by SmokedOut87** [comment]
[x] Mint address: CVRwdbkwSube1ifeNLFDdZSTmVEnLcyDuKXTdaZX1ua5
[x] Symbol: SAITAMA
[x] Token Decimals: 9
[x] Token icon: https://static.wixstatic.com/media/eee02f_fc2caa69836949eca0e963201a863f77~mv2.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Comment by AndreiT1310** [comment]
Approving that the info below is correct

[x] Mint address: CVRwdbkwSube1ifeNLFDdZSTmVEnLcyDuKXTdaZX1ua5
[x] Symbol: SAITAMA
[x] Token Decimals: 9
[x] Token icon: https://static.wixstatic.com/media/eee02f_fc2caa69836949eca0e963201a863f77~mv2.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
