### PR TITLE
DILLY-DILLY

### PR DESCRIPTION
**Pull request by Dilly12**
# Validate [Dilly](https://solscan.io/token/61VtkXr9mRXtrFYe2T9arWYX52sbJnkAUQgfjGuCzox2)

## Attestations (Please provide links):
Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support:https://x.com/dillysol/status/1808181126126809131?s=46&t=26PDo8NOq_Xvc0vcLj90Qg
- Coingecko/ CMC URL (If available):https://www.coingecko.com/en/coins/dilly utm_source=screenshot&utm_medium=app

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x]Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Ayeedede — COMMENTED** [review]
I approve that all this information is correct

**Review by Ayeedede — COMMENTED** [review]
All information is correct and works fine

**Comment by ahmadiharja** [comment]
im pretty sure that all information is correct and works fine

**Comment by speedyatl** [comment]
I approve of this and can confirm all the information is correct

**Comment by Jymfletzfur** [comment]
your token has been selected to test our new application tool.

Nothing is needed to be done on your part, just sit tight.

I will be closing the PR.

**Comment by Dilly12** [comment]
Awesome, thanks!

**Pull request closed without merging**
