### PR TITLE
Validate $WOOPA

### PR DESCRIPTION
**Pull request by napoli800**
# Validate $WOOPA([https://solscan.io/token/{mint_address}](https://solscan.io/token/26vSyWdduSXwMRsA6MKbzAvuRUAuLSCKW9HRCLVgbxEm))

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/{your_account}/status/{your_tweet_id}
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by Dnvrsol** [comment]
I recognize and confirm the information provided is correct.

**Review by Dnvrsol — COMMENTED** [review]
I recognize and confirm that the information provided is correct.

**Comment by jqrqd888** [comment]
I recognize and confirm that the information provided is correct.

**Comment by SolSleeper** [comment]
I recognize and confirm that the information provided is correct.

**Comment by SolSleeper** [comment]
I recognize and confirm that the information provided is correct.

**Comment by Dadbunny34** [comment]
I recognize and confirm that the information provided is correct

**Comment by Januek** [comment]
I recognize and confirm that the information provided is correct

**Comment by hellotier2** [comment]
I recognize and confirm that the information provided is correct

**Comment by zekol98** [comment]
I recognize and confirm that the information provided is correct

**Comment by ronaldalways** [comment]
I recognize and confirm that the information provided is correct.

**Comment by meijiao** [comment]
Hey, please make the change only in the "validated-tokens" file. Also, I don't see an attestation tweet? You can reopen a new PR when you are ready

**Pull request closed without merging**
