### PR TITLE
[Example PR] Validate BIU

### PR DESCRIPTION
**Pull request by meijiao**
# Validate [BIU](https://solscan.io/token/4D7kEovLBEY3VQUzJUQjXyGR8fAZwQWSxEcsP5Y9nZ6S)

## Attestations:
Tweet with Mint address: https://twitter.com/BIUCOIN/status/1622950008684417027
Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/biu-coin

## Validation (Additonal material for reviewers):
 - [x] The metadata provided in the PR matches what is on-chain (Mandatory)
 - [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will take longer)
 - [x] Is Listed on Coingecko / CMC (Optional, but might be helpful for reviewers to check for duplicates)
 
 ## Acknowledgement
- [x] Acknowleged that I did not modify unrelated code.
- [x] Acknowledged that my change matches the format of other lines in the file (no spaces between fields).

### CODE REVIEW

**Review by Timoon21 — APPROVED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet / official website
- [x] No duplicate on CoinGecko
- [x] No duplicate on Jupiter's strict list

**Comment by LJQZZZ123** [comment]
- [ ] Mint address: 4D7kEovLBEY3VQUzJUQjXyGR8fAZwQWSxEcsP5Y9nZ6S

- [ ] Symbol: BIU

- [ ] Token Decimals: 9

- [ ] Token icon: https://biucoin.club/img/cat.png

- [ ] On-chain metadata matches

- [ ] No duplication on Jupiter's strict list

- [ ] Information matches on CoinGecko and no duplication

**Review by LJQZZZ123 — APPROVED** [review]

**Comment by andrira209** [comment]
Mint address: 6Z6v1vBzRs7J1HVHrW3xr2Zfmjzwc5dK2rcGnTErRGSQ

 Symbol: BERRY

 Token Decimals: 9

 Token icon: https://aw3piwag76xsjqpb5bpe5yen672htjtrqsay4syyo7acykjh5wnq.arweave.net/Bbb0WAb_ryTB4eheTuCN9_R5pnGEgY5LGHfALCkn7Zs

 On-chain metadata matches

 No duplication on Jupiter's strict list

 Information matches on CoinGecko and no duplication

**Comment by 1529998** [comment]
Name: Bobcat Miner 300
Symbol: Bobcat Min
Mint Address: [CFepMMsRuwV2TkcYAfgETXeq8esA7JQG8CjaRQ44xJ9N](https://solscan.io/address/CFepMMsRuwV2TkcYAfgETXeq8esA7JQG8CjaRQ44xJ9N)
Decimals: 4
LogoURI: https://bafkreibrxuno4c3bzxwwr3smgzhtveb2bewexusi2efn4gbgsvogdpg65m.ipfs.nftstorage.link/
Community Validated: true

**Pull request merged**
