### PR TITLE
Validate BULLZ

### PR DESCRIPTION
**Pull request by Guarmarketing**
# Validate [BULLZ](https://solscan.io/token/CdkXjsEokNWMabBn2HCrPcXNmSDE59QKtseLh1j9tEwd)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Motus_solana/status/1777719397294944267?t=JJdbuhvfHepvf669YHeWrQ&s=19
- Coingecko/ CMC URL (If available): Applied

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
the name and ticker in the metadata is BULLZ, please amend your pr to match

**Comment by Guarmarketing** [comment]
Changed the name and Ticker to BULLZ

**Comment by Guarmarketing** [comment]
> the name and ticker in the metadata is BULLZ, please amend your pr to match

Done the changes, thanks for the reply

**Comment by Guarmarketing** [comment]
> it has not been changed

Where exactly you want the change. As the pull request says VALIDATE BULLZ.

PLEASE if you could guide me

**Comment by Jymfletzfur** [comment]
image

in the actual submission your name and ticker do not match the metadata exactly

**Comment by Guarmarketing** [comment]
> image
> 
> in the actual submission your name and ticker do not match the metadata exactly



> image
> 
> in the actual submission your name and ticker do not match the metadata exactly

Thank you so much

**Comment by Guarmarketing** [comment]
Thanks a Ton.


i have done the changes, if not updated i will make a new Pull request.

**Review by Guarmarketing — COMMENTED** [review]
Changed name to match the PR

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
