### PR TITLE
Validate NOHAT

### PR DESCRIPTION
**Pull request by nohatsolana**
# Validate [NOHAT](https://solscan.io/token/5BKTP1cWao5dhr8tkKcfPW9mWkKtuheMEAU6nih2jSX)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/nohatsolana/status/1789972386848080055
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/dogwifnohat

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
metadata is not correct, please come into discord

**Comment by Jymfletzfur** [comment]
Use this as your image link

https://bafybeiev6osnezms577l2q3x2kafhpqlqnxswfga33tvgnohbviduawp6e.ipfs.cf-ipfs.com/

**Comment by nohatsolana** [comment]
> * [x]   Mint address: 5BKTP1cWao5dhr8tkKcfPW9mWkKtuheMEAU6nih2jSX
> * [x]   Symbol: NOHAT
> * [x]   Token Decimals: 6
> * [x]   Token icon: https://bafybeiev6osnezms577l2q3x2kafhpqlqnxswfga33tvgnohbviduawp6e.ipfs.cf-ipfs.com/
> * [x]   On-chain metadata matches
> * [x]   No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
Please come into discord.

**Pull request closed without merging**
