### PR TITLE
Validate El Salvador Coin

### PR DESCRIPTION
**Pull request by gabrielcustodio**
# Validate [SALVADOR](https://solscan.io/token/5hq7BFmjaX3wrH4MJMcr7s7XyvzvM6Hyeo8Cw5Hiw4kN)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SalvadorCto/status/1789361868391239973
- Coingecko/ CMC URL (If available): Not Available

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by gabrielcustodio** [comment]
Mint address: 5hq7BFmjaX3wrH4MJMcr7s7XyvzvM6Hyeo8Cw5Hiw4kN
 Symbol: SALVADOR
 Token Decimals: 9
 Token icon: https://imgur.com/a/puYcfiI
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by gabrielcustodio** [comment]
@Jymfletzfur Its okay now?

**Review by gabrielcustodio — COMMENTED** [review]
Upload URL image .png Validate El Salvador coin

**Comment by Jymfletzfur** [comment]
does not meet the required metrics and does not appear to meet any of the exemptions

**Comment by gabrielcustodio** [comment]
> does not meet the required metrics and does not appear to meet any of the exemptions

I understand that my changes do not meet the required metrics and do not seem to qualify for any exemptions. However, I am a bit unclear on what exactly is missing or needs adjustment. Could you please provide further guidance or clarify which specific metrics need to be met? I am committed to improving and would like to ensure that my contributions align with expectations. Thank you in advance for your assistance and guidance.

**Pull request closed without merging**
