### PR TITLE
Validate MARTY

### PR DESCRIPTION
**Pull request by MartyInuToken**
# Validate [MARTY](https://solscan.io/token/5KhJ3fvCoQ4ybq237jLSgshSWsy942CpQPiPfrDPz2NM)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/MartyInuToken/status/1750949981467386294
- Coingecko/ CMC URL (If available):  [https://www.coingecko.com/en/coins/marty-inu](https://www.coingecko.com/en/coins/marty-inu)

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by MartyInuToken** [comment]
Hi Team,

We've submitted PR #1287 ahead of time to prevent the emergence of fake tokens pre-launch. We followed all required guidelines and kindly ask for your review to ensure the authenticity and security of our token.

Please verify the accuracy of the last commit.

Thank you for your assistance in safeguarding the ecosystem.

cc @9yoi

**Comment by MartyInuToken** [comment]
We kind of appreciate if you help us to move forward with this PR as we are launching in a few hours. Wwww.martyinu.com

Thanks!

Cc:
@OxSoju2

**Comment by MartyInuToken** [comment]
Team,

Please help us to validate our token.

@Timoon21  @0xSoju2 

Thanks a lot.

**Comment by Jymfletzfur** [comment]
insufficient volume and mcap

**Comment by MartyInuToken** [comment]
@Jymfletzfur can you please guide me and show me where on the strict list requirements are those mentions.

**Comment by MartyInuToken** [comment]
Dear Team,

I am writing to express my concern and request clarification regarding the recent decision not to verify our token for the strict list.

I have reviewed the documentation carefully, specifically the section on requirements for strict list verification: https://station.jup.ag/docs/get-your-token-onto-jup. While the documentation outlines minimum liquidity and market cap requirements, I could not find any mention of @Jymfletzfur involvement in the verification process.

@9yoi to ensure my understanding, could you please confirm if the process has changed and now plays a role in strict list verification decisions? Additionally, if there are any criteria beyond the documented requirements that contributed to the decision, I would appreciate transparency and specific feedback.

We believe our token meets all the listed requirements outlined in the pull request. Given the lack of clarity surrounding the decision and the discrepancy between the documented criteria and the apparent process, we find it concerning that the decision seems to contradict publicly available information.

Thank you for your time and consideration. We appreciate your willingness to address our concerns and provide further clarification.

Sincerely,
Marty Inu Team

cc @Timoon21 @0xSoju2

**Pull request closed without merging**
