### PR TITLE
validate GNSH

### PR DESCRIPTION
**Pull request by JonaxelN**
# Validate [GNSH](https://solscan.io/token/7ezEsetNSF5sj6K1WE1oJxn14HN1k8yWD967pXoEq97G)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/GNSH_Coin/status/1775323731545518446
- Coingecko/ CMC URL (If available): 

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by alandalegend** [comment]
Hello, Alan from CDMX here 
image
, confirming the statement above:

- [x] Mint address: 7ezEsetNSF5sj6K1WE1oJxn14HN1k8yWD967pXoEq97G
- [x] Symbol: GNSH
- [x] Token Decimals: 9
- [x] Token icon: https://i.imgur.com/qnCnut5.png
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Review by chuycova — COMMENTED** [review]
Mint address: 7ezEsetNSF5sj6K1WE1oJxn14HN1k8yWD967pXoEq97G
 Symbol: GNSH
 Token Decimals: 9
 Token icon: https://i.imgur.com/qnCnut5.png
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Review by MGARCIA58 — COMMENTED** [review]
Confirming
Mint address: 7ezEsetNSF5sj6K1WE1oJxn14HN1k8yWD967pXoEq97G
Symbol: GNSH
Token Decimals: 9
Token icon: https://i.imgur.com/qnCnut5.png
On-chain metadata matches
No duplication on Jupiter´s strict list

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
