### PR TITLE
Main Costco Hot Dog

### PR DESCRIPTION
**Pull request by cashx101**
# Validate [COST](https://solscan.io/token/Av6qVigkb7USQyPXJkUvAEm4f599WTRvd75PUWBA9eNm)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/soyycash/status/1774692474931331425?s=46&t=nAgohDxmDs-LYrXIWWn25g
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by 21e8-miner — COMMENTED** [review]
Approved $COST

**Comment by thisisalexmcgregor** [comment]
The PR is correct but the X account is incorrect. [Here](https://x.com/costcodogsol/status/1774828080235794917?s=20) is the main account making the post tagging JupiterExchange.

**Comment by berrberr** [comment]
+1

**Review by Jymfletzfur — APPROVED** [review]

**Comment by johngroves** [comment]
LGTM

**Comment by callmepeco** [comment]
LGTM

**Comment by berrberr** [comment]
@9yoi could we grab your review on this one please? Thank you!! 😃

**Pull request merged**
