### PR TITLE
Validate FWOA

### PR DESCRIPTION
**Pull request by JunaidPeer**
# Validate [FWOA](https://solscan.io/token/62U5zYJadvquCqvtqxaWfZmpLU8iT59J8z3BEfVc3Q92)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/FWOAmemecoin/status/1763180736251633944?s=20
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by JunaidPeer** [comment]
- Mint address: 62U5zYJadvquCqvtqxaWfZmpLU8iT59J8z3BEfVc3Q92
- Symbol: FWOA
- Token Decimals: 6
- Token icon: https://bafkreia7yu6lx35627q766bl6uc7cvahqoreitgiqj67m4ihwf6fiqop3u.ipfs.nftstorage.link
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by Db0706** [comment]
- Mint address: 62U5zYJadvquCqvtqxaWfZmpLU8iT59J8z3BEfVc3Q92
- Symbol: FWOA
- Token Decimals: 6
- Token icon: https://bafkreia7yu6lx35627q766bl6uc7cvahqoreitgiqj67m4ihwf6fiqop3u.ipfs.nftstorage.link
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by jimmy6614** [comment]
- Mint address: 62U5zYJadvquCqvtqxaWfZmpLU8iT59J8z3BEfVc3Q92
- Symbol: FWOA
- Token Decimals: 6
- Token icon: https://bafkreia7yu6lx35627q766bl6uc7cvahqoreitgiqj67m4ihwf6fiqop3u.ipfs.nftstorage.link
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by HxnerNH** [comment]
Mint address: 62U5zYJadvquCqvtqxaWfZmpLU8iT59J8z3BEfVc3Q92
Symbol: FWOA
Token Decimals: 6
Token icon: https://bafkreia7yu6lx35627q766bl6uc7cvahqoreitgiqj67m4ihwf6fiqop3u.ipfs.nftstorage.link/
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
incorrect submission, do not attempt to alter the pull request template

**Comment by JunaidPeer** [comment]
> incorrect submission, do not attempt to alter the pull request template

can you please help us? or do I make a new pr?

**Pull request closed without merging**
