### PR TITLE
Validate BarkCoin

### PR DESCRIPTION
**Pull request by Colby653**
# Validate [BARK](https://solscan.io/token/APkM2bqzpwQaiv5BY2eA7vR7DEB1EX5MMf6JNcBCHYrC)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/thebarkcoin/status/1783270202571977033?s=46
- Still working on coingecko

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Coingecko https://www.coingecko.com/en/coins/barkcoin   

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter. Just not on strict
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
your name in the metadata is BarkCoin

**Comment by Colby653** [comment]
Correct name BarkCoin symb is BARK

**Comment by Jymfletzfur** [comment]
Please come into the Discord.

**Comment by Colby653** [comment]
What is wrong?

**Comment by Colby653** [comment]
Can we get it validated now?

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
