### PR TITLE
Validate SOL STREET BETS (SOLBET)

### PR DESCRIPTION
**Pull request by SOLSTREETBETS**
# Validate [SOL STREET BETS (SOLBET)](https://solscan.io/token/9nmkqy4wC5UqCjzUi9YHqE9aNiSgdq58GFxmwfeqzeBZ)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/bets_sol/status/1792928889523577042 + https://twitter.com/SOL_STREET_BETS/status/1790146472379342913
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/fr/currencies/sol-street-bets/

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by SOLSTREETBETS** [comment]
•	Name: SOL STREET BETS
•	Symbol: SOLBET
•	Mint Address: 9nmkqy4wC5UqCjzUi9YHqE9aNiSgdq58GFxmwfeqzeBZ
•	Decimals: 9
•	LogoURI: https://statics.solscan.io/cdn/imgs/s60?ref=68747470733a2f2f736f6c737472656574626574732e6f72672f5353542e706e67
•	Community Validated: true

**Comment by luizrosevelt** [comment]
I hereby attest that the provided information is accurate, and the token is valid :

• Name: SOL STREET BETS
• Symbol: SOLBET
• Mint Address: 9nmkqy4wC5UqCjzUi9YHqE9aNiSgdq58GFxmwfeqzeBZ
• Decimals: 9
• LogoURI: https://statics.solscan.io/cdn/imgs/s60?ref=68747470733a2f2f736f6c737472656574626574732e6f72672f5353542e706e67

No duplicate in strict list.

**Comment by LazerT1** [comment]
I hereby attest that the provided information is accurate, and the token is valid :

• Name: SOL STREET BETS
• Symbol: SOLBET
• Mint Address: 9nmkqy4wC5UqCjzUi9YHqE9aNiSgdq58GFxmwfeqzeBZ
• Decimals: 9
• LogoURI: https://statics.solscan.io/cdn/imgs/s60?ref=68747470733a2f2f736f6c737472656574626574732e6f72672f5353542e706e67

No duplicate in strict list.

Remain at your disposal for any further information.

**Comment by NVGONE** [comment]
I hereby attest that the provided information is accurate, and the token is valid :

• Name: SOL STREET BETS
• Symbol: SOLBET
• Mint Address: 9nmkqy4wC5UqCjzUi9YHqE9aNiSgdq58GFxmwfeqzeBZ
• Decimals: 9
• LogoURI: https://statics.solscan.io/cdn/imgs/s60?ref=68747470733a2f2f736f6c737472656574626574732e6f72672f5353542e706e67

No duplicate in strict list.

Remain at your disposal for any further information.

**Comment by SOLSTREETBETS** [comment]
To give you a bit of background, SOLBET is a community initiative, with supply being massively shared among its thousands of owners. We are not the developers of the project and have not heard from them since they left.

We are a team of a dozen very invested people (and hundreds of helpers) who are investing time and money in an ambitious project of public utility. Our website is already published but has not yet been made public (we can send you the link privately if necessary).

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
