### PR TITLE
BOLLY.DEV

### PR DESCRIPTION
**Pull request by loadev**
# Validate [BOLLY](https://solscan.io/token/CPxE3TB2fjoxf3ip2DkepUMje8eCAucHHavS17g3VER1)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/bollywoodonsol/status/1741159743807250835
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/bolly-dev

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Vira7777** [comment]
Hey men when $bolly?  @Timoon21  @benlvb 
Go go go. We all go to bollywood.

**Comment by AnthonyHapens** [comment]
@Timoon21 and @benlvb rocks 😎

**Comment by fr3ckl3d14dybug** [comment]
Hello @Timoon21  and  @benlvb JUP team! I want to make an appeal for you to put effort into validating the BOLLY project. 
We, enthusiasts of this project, have been awaiting for some time. We know that the BOLLY developers are doing their best to ensure that everything is impeccable for approval. JUP seems to be falling short here, and we're feeling a bit forgotten, unfairly. 
BOLLY is real, it's rock-solid, and ready to shine! 
We immensely appreciate your consideration for the work done so far by the BOLLY team! 🙏

**Comment by fr3ckl3d14dybug** [comment]
plz do your job here. We have everything so that we can be verified; we have a lot of work done! Can you confirm this? @9yoi @benlvb @Timoon21 @loufly1 @0xSoju2 @julesdamasta 
Thanks

**Comment by pi933** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.
 
* [x]   Mint address: CPxE3TB2fjoxf3ip2DkepUMje8eCAucHHavS17g3VER1
* [x]   Symbol: BOLLY.DEV (BOLLY)
* [x]   Token Decimals: 6
* [x]   Token icon: https://shdw-drive.genesysgo.net/9crU3xgj3MRbcGJiSWriLZmYtLJg3FbwLMNqxHxKhKXT/pajeet-token-logo.png
* [x]   On-chain metadata matches
* [x]   No duplication on Jupiter's strict list

**Pull request closed without merging**
