### PR TITLE
validate PRNT

### PR DESCRIPTION
**Pull request by drakdao**
# Validate [{Token Symbol}](https://solscan.io/token/{mint_address})

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/{your_account}/status/{your_tweet_id}
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by drakdao** [comment]
I am doing this for the project, but I am not part of the project. I am a holder, and wanted to help support them while they're busy working on other parts of this growing project.

I did find a PRNT, but not on Solana.  There is a Prime Numbers token on XDC, but that shouldn't matter I assume.

The project recently announced partnership with the Helio Pay team, and I've sent them this approval to publish on their Twitter feed (they were aware I'm submitting this, but the social media post might show up tomorrow due to the team going to bed (EU).

**Where the project will share the tweet with details**
https://twitter.com/printonsol

**Where I started with sharing it on mine**
https://twitter.com/drakDAO/status/1658252314770124802

**Comment by drakdao** [comment]
git force-push done to reset head and remove the dev doc update intended for a separate PR.  Apologies, haven't worked with forked PRs in a while apparently heh.

**Comment by scastradio** [comment]
Hi, I’m the projects lead developer. @Muhammadebrahim#1111 @storcaster on discord and twitter to confirm.

I testify and confirm. The information contained in the PR is correct.

**Comment by groozer84** [comment]
I confirm the information is valid.

https://twitter.com/TwitWithheld/status/1658443712827932672

**Review by Timoon21 — APPROVED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] No duplication on CMC/CoinGecko
- [x] Community validation

**Pull request merged**
