### PR TITLE
Eggdog

### PR DESCRIPTION
**Pull request by eggsolana**
# Validate [EGG](https://solscan.io/token/EXA537HSBVpsFijENbt6Muuy9AADUN8dUmYKD4oKbjJE)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/eggdogsolana/status/1739391311973929297
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/eggdog

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by fauzaanchan** [comment]
please validate eggdog

**Review by fauzaanchan — COMMENTED** [review]
validate the egg

**Comment by frqntr** [comment]
let the egg dogging, validate it

**Comment by richie0x** [comment]
validate eggdog, why hasnt it been added?

**Comment by imhere444222** [comment]
Validate the egg, it's wobbling.

**Comment by godgge** [comment]
let the egg dogging, validate it!!

**Comment by chaddiecrypt** [comment]
Please make sure to validate the egg, as the eggdog will be present everywhere

**Review by 0xSoju2 — APPROVED** [review]

**Pull request closed without merging**
