### PR TITLE
Validation for ASTRALIS

### PR DESCRIPTION
**Pull request by arkitoure**
# Validate [ASTRALIS](https://solscan.io/token/ASTRALvKjGK2xk2pamjMBU5dav5cEQa6zpKCP6FZ7BAJ)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: [https://twitter.com/PhysisVerse/status/1678049484641632258](https://twitter.com/PhysisVerse/status/1678049484641632258)
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by arkitoure** [comment]
@molotovbliss
@B1NKY
@Batman0383

**Comment by comrender** [comment]
- [x]   Mint address: ASTRALvKjGK2xk2pamjMBU5dav5cEQa6zpKCP6FZ7BAJ
- [x]   Symbol: ASTRALIS
- [x]   Token Decimals: 6
- [x]   Token icon: https://shdw-drive.genesysgo.net/AcG1tjtJ3vR1XzSCcVArheGLrwmMsphqExa6VodLymGF/astralis_1500x1500_8bit.png
- [x]   On-chain metadata matches
- [x]   No duplication on Jupiter's strict list

**Comment by SKY2SART** [comment]
- [x]   Mint address: ASTRALvKjGK2xk2pamjMBU5dav5cEQa6zpKCP6FZ7BAJ
- [x]   Symbol: ASTRALIS
- [x]   Token Decimals: 6
- [x]   Token icon: https://shdw-drive.genesysgo.net/AcG1tjtJ3vR1XzSCcVArheGLrwmMsphqExa6VodLymGF/astralis_1500x1500_8bit.png
- [x]   On-chain metadata matches
- [x]   No duplication on Jupiter's strict list

**Comment by B1NKY** [comment]
Validate **ASTRALIS**, gtg.

- [x]   Mint address: ASTRALvKjGK2xk2pamjMBU5dav5cEQa6zpKCP6FZ7BAJ
- [x]   Symbol: ASTRALIS
- [x]   Token Decimals: 6
- [x]   Token icon: https://shdw-drive.genesysgo.net/AcG1tjtJ3vR1XzSCcVArheGLrwmMsphqExa6VodLymGF/astralis_1500x1500_8bit.png
- [x]   On-chain metadata matches
- [x]   No duplication on Jupiter's strict list

**Comment by Batman0383** [comment]
> Validate **ASTRALIS**, gtg.
> 
> * [x]    Mint address: ASTRALvKjGK2xk2pamjMBU5dav5cEQa6zpKCP6FZ7BAJ
> * [x]    Symbol: ASTRALIS
> * [x]    Token Decimals: 6
> * [x]    Token icon: https://shdw-drive.genesysgo.net/AcG1tjtJ3vR1XzSCcVArheGLrwmMsphqExa6VodLymGF/astralis_1500x1500_8bit.png
> * [x]    On-chain metadata matches
> * [x]    No duplication on Jupiter's strict list

**Comment by Timoon21** [comment]
Your token must be already live on Jupiter to be added to the community strict list. I close the PR. You can reopen it when you're ready.

**Comment by arkitoure** [comment]
> Your token must be already live on Jupiter to be added to the community strict list. I close the PR. You can reopen it when you're ready.

Hi @Timoon21 Ok, was planning ahead before this took place. Will return, thx.

**Comment by arkitoure** [comment]
test

**Pull request closed without merging**
