### PR TITLE
validate MAGAIBA

### PR DESCRIPTION
**Pull request by magaibasogentle**
# Validate [MAGAIBA](https://solscan.io/token/A6rSPi9JmJgVkW6BatsA6MjFYLseizPM2Fnt92coFjf4)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/magaibasogentle/status/1770637385573007394?s=20
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/magaiba/

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Naweelon2** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

**Comment by Stdela** [comment]
The information given has been verified and is accurate.

**Comment by Ale-eth** [comment]
hey, Ale from Tandil. Just reviewed this pr, seems ok to me

**Comment by tl1987** [comment]
Hi there, this seems ok to me. 
On chain metadata matches
No duplication on Jupiter's strict list
The metadata provided in the PR matches what is on-chain - YES
Does not duplicate the symbol of another token on Jupiter's strict list - YES
I did not modify unrelated code. - TICK
My change matches the format in the file (no spaces between fields). - TICK
My token is already live and trading on Jupiter. - TICK

**Comment by fortizg** [comment]
The community behind magaiba is strong hands, gentle and so good. Thanks for taking the time for this review.

**Comment by Jymfletzfur** [comment]
on chain decimals says 8, you wrote 6

please amend

**Comment by giancarlobrusca** [comment]
> on chain decimals says 8, you wrote 6
> 
> please amend

Amended @Jymfletzfur

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
