### PR TITLE
SOLANA SUMMER - SWIFT

### PR DESCRIPTION
**Pull request by KrimitDeFrog**
# Validate [SWIFT](https://solscan.io/token/7ACrQshyNAULRWqZD7tQWpvUqV4pnpeRALoafXfsZVQa)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/solsummer_cto/status/1798172411587973142?s=46&t=MvvqedSY19CNbJS8RaR2MQ
- Coingecko/ CMC URL (If available): 

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by gavinlyla1303** [comment]
Love the $swift community!! Can't wait to be on Jupiter  list!! #solanasummer is for a long time! Not winter in session

**Comment by Crussty93** [comment]
I can confirm SWIFT is a legitimate coin!
We love Solana Summer, babyy!!

7ACrQshyNAULRWqZD7tQWpvUqV4pnpeRALoafXfsZVQa

**Comment by unoriginalcory** [comment]
I love the $SWIFT community as well. I’m learning so much! They helped me create my first GitHub account, excited to see what else I learn!!

**Comment by thedefidoll** [comment]
Love $SWIFT and $SWIFT team. Such a legit, based community... LFG Swifties!!! Solana Summer incoming and Swift on Solana is all year round... Love Jupiter Exchange and would love to be on main list as this is legit project with strong community support.

**Comment by domi3012** [comment]
the community of $SWIFT is building a strong fundament together and a next milestone would be the strict list of JUPITER. 
thank you

**Comment by Jymfletzfur** [comment]
please come into discord

**Comment by Jymfletzfur** [comment]
use this as your image

https://ipfs.io/ipfs/QmahJWZHWnPw2tB369HqsPi415DdEWw67ZWge7sz2iZSRu

**Pull request closed without merging**
