### PR TITLE
Validate $OPUS

### PR DESCRIPTION
**Pull request by DrCryptonite**
# Validate [OPUS](https://solscan.io/token/ChGwYVd94aTaB7HGLwaXSnYfqZzAh4PbksNeFEp3s1Mh)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/OpusCatSolana/status/1748759563870876132
- Coingecko/ CMC URL (If available): Application Pending

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by DrCryptonite** [comment]
@Timoon21 and @benlvb please see above

**Comment by DrCryptonite** [comment]
Doing a sanity check and my listing looks good.


Mint address: ChGwYVd94aTaB7HGLwaXSnYfqZzAh4PbksNeFEp3s1Mh
Symbol: OPUS
Token Decimals: 7
Token icon: https://3hz47nd2a2v3rs7mq3qlttwf6ubzn3v7jh5fn4b6mjxiumwwpdmq.arweave.net/2fPPtHoGq7jL7Ibguc7F9QOW7r9J-lbwPmJuijLWeNk
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by DrCryptonite** [comment]
Would appreciate some support on this when you guys are available. 

We have added $25K in liquidity across Meteora and Raydium.

**Comment by DrCryptonite** [comment]
@9yoi :)

**Comment by Jymfletzfur** [comment]
Insufficient volume, mcap, holders

**Pull request closed without merging**
