### PR TITLE
Validate BarrTremp

### PR DESCRIPTION
**Pull request by BarrTremp**
# Validate [BarrTremp](https://solscan.io/token/2CMxmFb2nsNdw351TfZoawpN1DnDuVrH4Wn6fxH2EJT6)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: 
- https://x.com/barrtremp_sol/status/1776230722350526896
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [.] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.
[validated-tokens.csv](https://github.com/jup-ag/token-list/files/14889593/validated-tokens.csv)

### CODE REVIEW

**Comment by iloveubro69** [comment]
Great Project with a powerful community. So much accomplished in only less than 5 days!

**Comment by TheGreatDurn007** [comment]
Barr Tremp is a great political meme with lots of volume being run by a tremendous community effort. The memes are some of the best I've ever seen and I can't wait for a Barr Tremp 2044 presidency

**Comment by TheGreatDurn007** [comment]
Barr Tremp is a great political meme with lots of volume being run by a tremendous community effort. The memes are some of the best I've ever seen and I cant wait for a Barr Tremp 2044 presidency

**Comment by BarrTremp** [comment]
This is a fantastic community run project showcasing the best in memes, resilience and also bringing awareness to the wider political ecosystem. $Barr to the moon!

**Pull request closed without merging**
