### PR TITLE
Validate $CORN

### PR DESCRIPTION
**Pull request by solanacorn**
# Validate $CORN 

(https://solscan.io/token/6DSqVXg9WLTWgz6LACqxN757QdHe1sCqkUfojWmxWtok)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/CornOnSolana/status/1728499118530510992
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/solanacorn

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by ErikThiart** [comment]
Please validate @jeffjagoe

**Comment by Timoon21** [comment]
gm @solanacorn 
You PR is not valid.
You must only add your token to the [validated-tokens.csv](https://github.com/jup-ag/token-list/blob/main/validated-tokens.csv) file. And dont add or modify other files.
Please apply changes.

**Comment by ErikThiart** [comment]
Hello @Timoon21 apologies about this, if I understand you correctly, I can fork the validated-tokens.csv file, add $corn there, and then submit a pull request.

**Comment by ErikThiart** [comment]
I hope this is correct?

https://github.com/jup-ag/token-list/pull/448

**Pull request closed without merging**
