### PR TITLE
Validate MAGA VP

### PR DESCRIPTION
**Pull request by TheSaltyLabs**
# Validate [MVP](https://solscan.io/token/55qMv1HtV8fqRjnFwDb9yDi9tBCeV8xwfgrPKgiJk5DN)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/magaVPcoin/status/1778616233845289214
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/maga-vp/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by SolnicSavage** [comment]
Great project.  Transparent leadership.  Outstanding community.

Telegram: https://t.me/MagaVP

**Comment by MAGAVP** [comment]
MAGA VP is headed to Dubai on the 16th Of April for the Global Blockchain Show. Goes to show how serious the team is trying to make waves in the PolitFi Space.

Website: https://www.magavpcoin.com/

**Comment by Texansmurf** [comment]
MAGA VP IS AWESOME! Let’s go! This project is awesome

**Comment by Undercoverwhal3** [comment]
First To market narrative + hard working team and community right here. MAGA VP is going places!

$MVP

**Comment by CryptoCesar503** [comment]
The only reason you haven't looked into $MVP is because you haven't met the right people. When you surround yourself with individuals that want to be successful and show love to their team and community, you begin to feel a sense of belonging. When you look into MAGAVP, it is more than just a political meme token. It is a movement of like minded people that know what it takes to deliver and conquer. We are never going to be successful on our own. We have to prove we are worthy. We meet friends along the way and build an unbreakable foundation. Join the tg and let me know you have joined. If you read this much, you belong with us. Say whatsup. WE ARE $MVP. 

¡¡¡VIVA MVP CABRONES!!!

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
