### PR TITLE
Validate Solchan.org

### PR DESCRIPTION
**Pull request by Kuroshades**
# Validate [Solchan.org](https://solscan.io/token/ChanM2vka4gJ3ob1SejJXnxoNuoAXGGJxDMJRSLD7nzW)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Solchan_org/status/1788555648697049090

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by chongkan — COMMENTED** [review]
Seems Legit! :-p

**Review by Jymfletzfur — APPROVED** [review]

**Comment by mysticpimp222** [comment]
[x] Mint address: ChanM2vka4gJ3ob1SejJXnxoNuoAXGGJxDMJRSLD7nzW
[x] Symbol: SOLCHAN
[x] Token Decimals: 9
[x] Token icon: https://raw.githubusercontent.com/Kuroshades/solchan-data/master/logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by ddog221** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: ChanM2vka4gJ3ob1SejJXnxoNuoAXGGJxDMJRSLD7nzW
[x] Symbol: SOLCHAN
[x] Token Decimals: 9
[x] Token icon: https://raw.githubusercontent.com/Kuroshades/solchan-data/master/logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by lunkenl** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: ChanM2vka4gJ3ob1SejJXnxoNuoAXGGJxDMJRSLD7nzW
[x] Symbol: SOLCHAN
[x] Token Decimals: 9
[x] Token icon: https://raw.githubusercontent.com/Kuroshades/solchan-data/master/logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by ChadHil** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: ChanM2vka4gJ3ob1SejJXnxoNuoAXGGJxDMJRSLD7nzW
[x] Symbol: SOLCHAN
[x] Token Decimals: 9
[x] Token icon: https://raw.githubusercontent.com/Kuroshades/solchan-data/master/logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by Dagsor** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: ChanM2vka4gJ3ob1SejJXnxoNuoAXGGJxDMJRSLD7nzW
[x] Symbol: SOLCHAN
[x] Token Decimals: 9
[x] Token icon: https://raw.githubusercontent.com/Kuroshades/solchan-data/master/logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by weibeu** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: ChanM2vka4gJ3ob1SejJXnxoNuoAXGGJxDMJRSLD7nzW
[x] Symbol: SOLCHAN
[x] Token Decimals: 9
[x] Token icon: https://raw.githubusercontent.com/Kuroshades/solchan-data/master/logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by weibeu** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: ChanM2vka4gJ3ob1SejJXnxoNuoAXGGJxDMJRSLD7nzW
[x] Symbol: SOLCHAN
[x] Token Decimals: 9
[x] Token icon: https://raw.githubusercontent.com/Kuroshades/solchan-data/master/logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
