### PR TITLE
Validate CatSolHat (SOLCAT)

### PR DESCRIPTION
**Pull request by catsolhat**
# Validate [SOLCAT](https://solscan.io/token/E99fN4tCRb1tQphXK1DU7prXji6hMzxETyPNJro19Fwz)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/catsolhat/status/1793157620750266738 The quoted tweet provides significant evidence of community support.
- Coingecko URL: https://www.coingecko.com/en/coins/catsolhat | CoinMarketCap URL: https://coinmarketcap.com/currencies/catsolhat/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by catsolhat** [comment]
CatSolHat $SOLCAT

- CoinGecko listing: done
- Coinmarketcap listing: in process
- Jupiter strict list: pending

We have a vibrant community waiting for being listed on Jupiter strict-list. Please review it soon. Thank you.

**Comment by catsolhat** [comment]
$SOLCAT (CatSolHat) just landed on CoinMarketCap: https://coinmarketcap.com/currencies/catsolhat/

**Comment by Jymfletzfur** [comment]
Please come into discord

**Comment by Jymfletzfur** [comment]
the image link in the metadata:

https://imgur.com/cointool-nft-6dJWbbL

**Comment by catsolhat** [comment]
Both options work for us, but if it's mandatory, please help us change the image link to the one in the metadata.

The reason for submitting another link: we created the token using cointool.app, and there might have been a bug when we uploaded a .png file that ended up as a .jpeg file. This resulted in a white background, which is really annoying when viewed in full size (not rounded) of the logo.

**Comment by catsolhat** [comment]
Do we need to create a new pull request? Please guide me the next step to fix this issue

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
