### PR TITLE
Validate LEGEND

### PR DESCRIPTION
**Pull request by h4rkl**
# Validate [LEGEND](https://solscan.io/token/LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/Legends_of_SOL/status/1747456919894438305

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter. https://birdeye.so/token/LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx?chain=solana
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by AmritpalChera — COMMENTED** [review]
Looks good to me

**Comment by cdcruzdev** [comment]
Everything looks in order

Need the devs to go and validate our JUP PR

Add a comment with:

- Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
- Symbol: LEGEND
- Token Decimals: 9
- Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by cdcruzdev** [comment]
Everything looks in order

Need the devs to go and validate our JUP PR

-Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
-Symbol: LEGEND
-Token Decimals: 9
-Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8
-On-chain metadata matches
-No duplication on Jupiter's strict list

**Comment by taxmansol** [comment]
Ship it

[x] Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
[x] Symbol: LEGEND
[x] Token Decimals: 9
[x] Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by crypt0miester** [comment]
pls. mi familia. kek

**Review by taxmansol — COMMENTED** [review]
git-redact

**Comment by h4rkl** [comment]
> Ship it. Solscan is flat ether now. Solana FM ftw. taxman.sol @taxmansol
> 
> * [x]  Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
> * [x]  Symbol: LEGEND
> * [x]  Token Decimals: 9
> * [x]  Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8
> * [x]  On-chain metadata matches
> * [x]  No duplication on Jupiter's strict list

I see your Solana.fm and raise you [Helius XRAY ](https://xray.helius.xyz/) ❤️

**Review by taxmansol — COMMENTED** [review]
Ship it. Solscan is flat ether now.  ̶S̶o̶l̶a̶n̶a̶ ̶F̶M̶  [Helius XRAY](https://xray.helius.xyz/) ftw. taxman.sol [@taxmansol](https://twitter.com/taxmansol)

* [x] Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
* [x] Symbol: LEGEND
* [x] Token Decimals: 9
* [x] Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8
* [x] On-chain metadata matches
* [x] No duplication on Jupiter's strict list

**Comment by R-K-H** [comment]
Everything looks good. Confirmed https://shdw-drive.genesysgo.net/NZkFUhCfuhhDKnQnPjqVcanddkkaf51rVwYYhryxiZo/kE94cDcRWswNMTYamnxqx.json matches and the explorer links are confirmed.

**Comment by AngryPacifist** [comment]
- [x] Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
- [x]  Symbol: LEGEND
- [x] Token Decimals: 9
- [x] Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by flamula** [comment]
ahhhh I'm validatiiiing! (can confirm)

[x] Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
[x]  Symbol: LEGEND
[x] Token Decimals: 9
[x] Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Review by MWest2020 — COMMENTED** [review]
For verification:

x] Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
[x] Symbol: LEGEND
[x] Token Decimals: 9
[x] Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by LeonAlvarez** [comment]
LGTM

[x] Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
[x] Symbol: LEGEND
[x] Token Decimals: 9
[x] Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by frigaate** [comment]
Tick all the green boxes

✅️Mint address: LGNDeXXXaDDeRerwwHfUtPBNz5s6vrn1NMSt9hdaCwx
✅️Symbol: LEGEND
✅️Token Decimals: 9
✅️Token icon: https://arweave.net/sCGvXDlbFn8p0s0cfqtznbjn9K_cyYY2aa9HGC1XWR8
✅️On-chain metadata matches
✅️No duplication on Jupiter's strict list

**Pull request closed without merging**
