### PR TITLE
validate ShivX

### PR DESCRIPTION
**Pull request by ShivXPrivacy**
# Validate [SHIVX](https://solscan.io/token/Gqiou284yNmVtTGVVM8guof4DaQtbrEDC4kgjNHZbbo4)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/ShivXprivacy/status/1738275769749811677?t=3EumA6tlK1JH3hKeN9WVrA&s=19
- Coingecko/ CMC URL (If available): https://www.geckoterminal.com/solana/pools/12e58eh6SNkpACeLcrpo8UPshDuCvNF7MYMKwAxDtCMJ

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [  ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by parthd575** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: Gqiou284yNmVtTGVVM8guof4DaQtbrEDC4kgjNHZbbo4
[x] Symbol: SHIVX
[x] Token Decimals: 4
[x] Token icon: https://raw.githubusercontent.com/ShivXPrivacy/token-list/48e89eaa1a5b4577fc4f3066e5661933612bdec9/assets/mainnet/Gqiou284yNmVtTGVVM8guof4DaQtbrEDC4kgjNHZbbo4/Logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by shivamjoshi789** [comment]
I can attest that the provided information is accurate, and the token is valid.

- [x] Mint address: Gqiou284yNmVtTGVVM8guof4DaQtbrEDC4kgjNHZbbo4
- [x] Symbol: SHIVX
- [x] Token Decimals: 4
- [x] Token icon: https://raw.githubusercontent.com/ShivXPrivacy/token-list/48e89eaa1a5b4577fc4f3066e5661933612bdec9/assets/mainnet/Gqiou284yNmVtTGVVM8guof4DaQtbrEDC4kgjNHZbbo4/Logo.png
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by amd-99** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: Gqiou284yNmVtTGVVM8guof4DaQtbrEDC4kgjNHZbbo4
[x] Symbol: SHIVX
[x] Token Decimals: 4
[x] Token icon: https://raw.githubusercontent.com/ShivXPrivacy/token-list/48e89eaa1a5b4577fc4f3066e5661933612bdec9/assets/mainnet/Gqiou284yNmVtTGVVM8guof4DaQtbrEDC4kgjNHZbbo4/Logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
