### PR TITLE
Validate $SBF

### PR DESCRIPTION
**Pull request by ErikThiart**
# Validate [SBF](https://solscan.io/token/FkbWN4dcFQym2PgCELfThghQqLuA2e2jThMJyhZjfG4M)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/sambankmeme/status/1748291913164439707
- Coingecko/ CMC URL (If available): Application pending - CL1801240054
- Geckoterminal URL: (https://www.geckoterminal.com/solana/pools/7eEq58YoaHEnsF4PBtG18X5TuBQYGE2ogkuaByUFjAKn)

## Additional References:

- Website: (https://www.sambankmeme.com)

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by ErikThiart** [comment]
@benlvb just sending a ping - surpassed 1M marketcap, read Jupiter changed how strict listing work, just want to ask if doing these PRs are still the way.

If so. Would appreciate your time on this.

**Comment by DrCryptonite** [comment]
@Saadiqui these guys are grinding

**Comment by DrCryptonite** [comment]
[x] Mint address: FkbWN4dcFQym2PgCELfThghQqLuA2e2jThMJyhZjfG4M
[x] Symbol: SBF
[x] Token Decimals: 6
[x] Token icon: https://bafkreifhqihaiwyo4g2aogdu4qyfqftkxy3aq4xxbhoxdkbkufrobsnjwm.ipfs.nftstorage.link
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by DrCryptonite** [comment]
Adding a ping to @benlvb I know they have their hands full with the Jupiter launches, but maybe he gets free time today.

**Comment by DrCryptonite** [comment]
https://twitter.com/Poloniex/status/1750028478953746654

Listed on Poloniex, still no strict listing. 

@Timoon21 @whereismeow @benchow -- is this still the correct way to add tokens?

Waiting on so many validations, hurting projects a little bit now.

**Comment by Jymfletzfur** [comment]
name does not match what is on chain

**Comment by ErikThiart** [comment]
What do you mean the name does not match?

**Pull request closed without merging**
