### PR TITLE
Validate GIKO

### PR DESCRIPTION
**Pull request by bigdenergy**
# Validate [GIKO](https://solscan.io/token/3WPep4ufaToK1aS5s8BL9inzeUrt4DYaQCiic6ZkkC1U)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/gikocoinsol/status/1783579595133870192
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by bigdenergy** [comment]
LFG

**Comment by Jymfletzfur** [comment]
pls use the image link in your metadata

also its Giko Cat in the metadata, not Giko cat

**Comment by bigdenergy** [comment]
> pls use the image link in your metadata
> 
> also its Giko Cat in the metadata, not Giko cat

updated in the last commit
thanks!

**Comment by bigdenergy** [comment]
Yooo, can someone validate GIKO pls? :)

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Comment by 9yoi** [comment]
Moved here and merged https://github.com/jup-ag/token-list/pull/3409

**Pull request closed without merging**
