### PR TITLE
validate Ww3

### PR DESCRIPTION
**Pull request by joshkeldam**
# Validate [Ww3](https://solscan.io/token/7m2TUkpPZCScBhPJnGjWjbh75KkDNnwAdd7i74m8awad)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/ww3solanacoin/status/1779534834794455184?s=46&t=VZFQc656fqGSsonaU33fzg
- Coingecko/ CMC URL (If available): Have submitted and waiting approval

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Jymfletzfur — APPROVED** [review]

**Comment by joshkeldam** [comment]
@9yoi Can we get some eyes on this for a second approval please? 🙏

**Comment by joshkeldam** [comment]
@ZhengYuTay can i get a second approval on this please?

**Comment by joshkeldam** [comment]
@wkitsin Can we get another approval please so this can get merged?

**Review by 9yoi — APPROVED** [review]

**Comment by joshkeldam** [comment]
Thank you

**Pull request merged**
