### PR TITLE
Validate RHO

### PR DESCRIPTION
**Pull request by emberist**
# Validate [RHO](https://solscan.io/token/Trhor7npQLca4DFiUWR9vJCAw1je2zghSbwh37nW81i)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/rhospl20/status/1773844914071060968?s=20
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/rho

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by cicoph** [comment]
I have checked that the provided info are ok, and the coin respect the liquidity criteria also.

- [x] Name: RHO
- [x] Symbol: RHO
- [x] Mint Address: Trhor7npQLca4DFiUWR9vJCAw1je2zghSbwh37nW81i
- [x] Decimals: 6
- [x] Token Image: https://bafkreif5ri7om5uezpbiqyx7xo74mxwoth5lsc2l4h6yki3aqlcmhsxkwe.ipfs.nftstorage.link/
- [x] No duplication on Jupiter's strict list 
- [x] Robust Discord, X and Telegram Community Validated: true
- [x] On-chain metadata matches
- [x] Use Token2022 Program

**Comment by Willozzo** [comment]
I have checked that the provided infos are ok, and the coin respects the liquidity criteria also.

- [x] Name: RHO
- [x] Symbol: RHO
- [x] Mint Address: Trhor7npQLca4DFiUWR9vJCAw1je2zghSbwh37nW81i
- [x] Decimals: 6
- [x] Token Image: https://bafkreif5ri7om5uezpbiqyx7xo74mxwoth5lsc2l4h6yki3aqlcmhsxkwe.ipfs.nftstorage.link/
- [x] No duplication on Jupiter's strict list 
- [x] Robust Discord, X and Telegram Community Validated: true
- [x] On-chain metadata matches
- [x] Use Token2022 Program

**Comment by matyuu21** [comment]
I have checked that the provided infos are ok, and the coin respects the liquidity criteria also.

- [x] Name: RHO
- [x] Symbol: RHO
- [x] Mint Address: Trhor7npQLca4DFiUWR9vJCAw1je2zghSbwh37nW81i
- [x] Decimals: 6
- [x] Token Image: https://bafkreif5ri7om5uezpbiqyx7xo74mxwoth5lsc2l4h6yki3aqlcmhsxkwe.ipfs.nftstorage.link/
- [x] No duplication on Jupiter's strict list 
- [x] Robust Discord, X and Telegram Community Validated: true
- [x] On-chain metadata matches
- [x] Use Token2022 Program

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Comment by 9yoi** [comment]
moved here: https://github.com/jup-ag/token-list/pull/2375

**Pull request closed without merging**
