### PR TITLE
GIGS Validate

### PR DESCRIPTION
**Pull request by Belacosaur**
# Validate [GIGS](https://solscan.io/token/9U8Bn6zAf6Wyp1YHdXtLyfbN7yMvdvW1qQY475iZ5ftZ)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/GigaDAOio/status/1723558083346268369
- Coingecko coming soon. CoinGecko: https://www.coingecko.com/en/coins/gigadao - CMC: https://coinmarketcap.com/dexscan/solana/HWPeHd2SsjTUnjrQ1PBTcff2gNRsQXhqHhcEmkMsrm6v/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC 

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by Timoon21** [comment]
You should only PR validated-tokens.csv file by adding your token at the end of the list.

**Comment by Belacosaur** [comment]
@Timoon21 

That's exactly what I am doing.

I open the file in excel, I add the token to the bottom of the list, I git push and create a PR.

Should I be opening the file in a different way that is not being said?

**Comment by Belacosaur** [comment]
Can you please explain which formatter exactly?

Do you want me to only have a repo with validated-tokens.csv and nothing else?

**Comment by Timoon21** [comment]
> Can you please explain which formatter exactly?
> 
> Do you want me to only have a repo with validated-tokens.csv and nothing else?

No. Apply change like you do but not with excel. This breaks GitHub' logic.

Try editing file with GitHub.
https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files

**Comment by Belacosaur** [comment]
Thanks I'll try that now

**Comment by Belacosaur** [comment]
New PR created on https://github.com/jup-ag/token-list/pull/417

**Pull request closed without merging**
