### PR TITLE
Validate dainSOL

### PR DESCRIPTION
**Pull request by cleon30**
# Validate [dainSOL](https://solscan.io/token/2LuXDpkn7ZWMqufwgUv7ZisggGkSE5FpeHCHBsRgLg3m)

## Attestations (Please provide links):
- Santum LST Tweet: https://x.com/sanctumso/status/1798726459051430238
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/0xCleon/status/1798763830996242856 . We are in stealth for now until official announcement.

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by cleon30** [comment]
Hey there!! I am cleon(https://x.com/0xCleon) and today was released our dainSOL. Right now we haven't created the announcement but we are live on Sanctum already.  Please let me know any more info required! Thanks

**Comment by Jymfletzfur** [comment]
can you or sanctum tweet the token address out from the project account pls

**Comment by cleon30** [comment]
Yes, in their official website is public. You can search dainSOL in their trade and will appear(https://app.sanctum.so/trade):
image

**Comment by Jymfletzfur** [comment]
ok it looks to be the same coin to me

can you use this exact link for your image please

https://tca2vwit4gdsuwo3evencavzatf6sdit6e3xpiw374fmid45q55q.arweave.net/mIGq2RPhhypZ2yVI0QK5BMvpDRPxN3ei2_8KxA-dh3s

**Comment by cleon30** [comment]
Perfect, just modified to the final link 👍

**Review by Jymfletzfur — APPROVED** [review]

**Comment by cleon30** [comment]
@9yoi gm! following up to request review! 👀

**Review by 9yoi — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
