### PR TITLE
LANDLORD RONALD - $LANDLORD

### PR DESCRIPTION
**Pull request by Alon-5254**
# Validate [$LANDLORD](https://solscan.io/token/43uhykFm8Y9gLvHrWs7r7w1HCKu6vikDi7j394FaSfNz)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/LandlordRonald/status/1808934832753553515
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/landlord-roland

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by mrcryptic-com** [comment]
- [x] Mint address: 43uhykFm8Y9gLvHrWs7r7w1HCKu6vikDi7j394FaSfNz
- [x] Symbol: $LANDLORD
- [x] Token Decimals: 9
- [x] Token icon: https://cdn.dexscreener.com/cms/images/PAJgR-ETkWCGaJVl
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list
- [x] Project has a large number of holders 3300 at the time of this writing
- [x] Marketcap around 3M-4M
- [x] Telegram users: 3567

Obviously the project has a great community adoption and should be verified by the Jupiter team.
Please expedite this!

**Review by king4130 — COMMENTED** [review]
Expidite

**Comment by BertyBoi520** [comment]
This looks good. Please expedite

**Comment by Jymfletzfur** [comment]
We are using your token to test the new application portal with.

Your token will be added, but I will be closing the PR.

Nothing needed on your part.

**Pull request closed without merging**
