### PR TITLE
Validate TAOlie

### PR DESCRIPTION
**Pull request by TAOlie-Coin**
# Validate [TAOLIE](https://solscan.io/token/2zE5rJ2ctXMz9hVbk1AvJa78X7mh3kuR728SNzGXTEeu)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/TAOlie_SOL/status/1780292250380927016
- Coingecko/ CMC (PENDING)
- Image: https://ibb.co/cwcJzNF 
## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (PENDING)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by TAOlie-Coin** [comment]
Hello confirming the statement above:

 CA: 2zE5rJ2ctXMz9hVbk1AvJa78X7mh3kuR728SNzGXTEeu
 Symbol: TAOLIE
 Token Decimals: 9
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by therealbeliever** [comment]
Hello, confirming the statement above.

**Comment by JOSEMORALES11** [comment]
Hello confirming the statement above:

CA: 2zE5rJ2ctXMz9hVbk1AvJa78X7mh3kuR728SNzGXTEeu
Symbol: TAOLIE
Token Decimals: 9
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by GLACrypyo** [comment]
Hello confirming the statement above:

 CA: 2zE5rJ2ctXMz9hVbk1AvJa78X7mh3kuR728SNzGXTEeu
 Symbol: TAOLIE
 Token Decimals: 9
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Pull request closed without merging**
