### PR TITLE
Validate $MERTD

### PR DESCRIPTION
**Pull request by edgarpavlovsky**
# Validate [MERTD](https://solscan.io/token/DDRmuJ77t7d6pkBDXE47ZALjSZm3udVGJMgZjZBk41LH)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/MertdSOL/status/1766285804018831530
- ~Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE~ Not on coingecko yet, but working on it
- Website: https://www.merted.xyz/
- Telegram: https://t.me/Mertd_On_SOL

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by JunaidPeer** [comment]
- Mint address: DDRmuJ77t7d6pkBDXE47ZALjSZm3udVGJMgZjZBk41LH
- Symbol: MERTD
- Token Decimals: 9
- Token icon: https://bafybeibpf5nm257i63j2ttxrnzsirmmavwn5fj5y24olh5a55ydlugekpe.ipfs.nftstorage.link
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Review by 9yoi — CHANGES_REQUESTED** [review]
On chain name does not match name here

**Comment by metasal1** [comment]
Hi @9yoi 
please see this one 
https://github.com/jup-ag/token-list/pull/1844

**Comment by Jymfletzfur** [comment]
Using the other PR because it has the correct name

**Pull request closed without merging**
