### PR TITLE
Validate WGC (migration to new token address)

### PR DESCRIPTION
**Pull request by jameswgc**
# Validate [WGC](https://solscan.io/token/4Eb7ReeT936hX25KMBfYtyP1RWDdd9iixEwGJroACeLC)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/wildgoatcoin/status/1790343096594497795
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/wild-goat-coin-2

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by jameswgc** [comment]
Hello guys,
Please can you validate new WGC token as part of token address migration.
We aim to launch the new token next week.
Coingecko page currently still lists old token address, but this will be changed imminently.
Thanks

**Comment by jameswgc** [comment]
Coingecko link for the new WGC token: https://www.coingecko.com/en/coins/wild-goat-coin-2

**Review by 9yoi — APPROVED** [review]

**Comment by 9yoi** [comment]
It seems like the address of the new coin is 4Eb7ReeT936hX25KMBfYtyP1RWDdd9iixEwGJroACeLC? That's different from the one in your PR

**Review by Jymfletzfur — APPROVED** [review]

**Comment by jameswgc** [comment]
Hi @9yoi sorry, not sure what happened, seems there was a typo.
It should be 4Eb7ReeT936hX25KMBfYtyP1RWDdd9iixEwGJroACeLC.
Thanks

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
