### PR TITLE
Validate Guufy

### PR DESCRIPTION
**Pull request by guufymeme**
# Validate [GUUFY](https://solscan.io/token/inLbkByUvP9WGsLfMy1w9QX5pvaab5mkvLcz48DbkmF)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/GuufyMeme/status/1774903119903658385?t=mIuVvzdeZ6p3URLIJGGUgw&s=19

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by heroesbattlearena** [comment]
I can confirm this is a legit project

**Comment by OnlyRaydek** [comment]
All Data and info provided is correct! Project is legit

**Comment by MidasSolutions** [comment]
All Data and info provided is correct! Project is legit

**Comment by jekmen** [comment]
I can confirm that the project is absolutely legit.

**Comment by MidasSolutions** [comment]
Data provided, everything transparent, I think project is good 👍🏼

**Comment by guufymeme** [comment]
Please validate $GUUFY

**Review by heroesbattlearena — COMMENTED** [review]
Legit

**Review by jekmen — COMMENTED** [review]
The information here is accurate, the project is real.

**Comment by guufymeme** [comment]
Token is live and ready to trade on Jupiter.

**Comment by guufymeme** [comment]
Token listed on CMC: https://coinmarketcap.com/currencies/guufy/

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — CHANGES_REQUESTED** [review]
your name does not match onchain, please fix

**Comment by guufymeme** [comment]
> your name does not match onchain, please fix

Sorry, I didnt get what to fix, can you please clarify this point? appreciate it

**Comment by Jymfletzfur** [comment]
The name in the actual metadata is GUUFY, but you use Guufy in your application

**Comment by guufymeme** [comment]
> The name in the actual metadata is GUUFY, but you use Guufy in your application

@Jymfletzfur and @9yoi sorry! Name in file was fixed. Please confirm

**Pull request merged**
