### PR TITLE
Validate 99CENTS

### PR DESCRIPTION
**Pull request by thinksymply1**
# Validate [99CENTS](https://solscan.io/token/3VTXWW93L1WRfQ7QDPjvfBQgzFRVqDgHPnc8vwQmEpUi)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/99CENTS__/status/1791525416164901164
- [Coingecko/ CMC URL (If available): (https://www.coingecko.com/en/coins/arizona-iced-tea)

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
Please come into discord

**Comment by thinksymply1** [comment]
Roger!

**Comment by Jymfletzfur** [comment]
Use this image link in your PR

https://ipfs.io/ipfs/Qmc5YUcDU8aYBMoXHSjXwLKb65Mw6KSUHPufftVCyzE5fM

**Comment by thinksymply1** [comment]
Task completed, please let me know if anything else is need from my end.

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
