### PR TITLE
Validate CatWifHat ($CIF)

### PR DESCRIPTION
**Pull request by catwifhat**
# Validate [$CIF](https://solscan.io/token/G3vWvAaXPHCnncnyAbq6yBRXqfRtEV3h7vExzasZeT6g})

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/CatwifHatcoin/status/1734544375924076774
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/catwifhat

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by catwifhat** [comment]
@9yoi Just fixed the twitter link from the other PR, there was a closing bracket added in the link that was embedded. Sorry for the trouble

**Comment by catwifhat** [comment]
We got added to Coingecko : https://www.coingecko.com/en/coins/catwifhat

Updated the PR message with link

**Comment by catwifhat** [comment]
@9yoi We also made another tweet to Jupiter (on top of the former one in the PR)  https://twitter.com/CatwifHatcoin/status/1737446558604444021

**Comment by law6662** [comment]
Please don't merge. That was from a dev that left the project. The real one is PR #667

**Comment by law6662** [comment]
We have no control over this PR. Sry for the inconveniences. I hope we can sort this quickly. Sadly that guy just left and doesn't write back.

**Comment by catwifhat** [comment]
> Please don't merge. That was from a dev that left the project. The real one is PR #667

What do you mean by "real one" ? There is only one $CIF and it's the one I submitted for here in this PR. The PR that you mentioned has been created by another party, I checked their commit and the token is the same anyway so whatever you decide to merge between these 2 PR's will result in the listing of the right token.

Could you please clarify this ?

**Comment by law6662** [comment]
Hit an admin up in the telegram chat. Also you have a wrong number of decimals in the commit. It's 6. Also the header says validate "wif". Do us all a favor and delete this and let's sort out in #667 .

**Comment by catwifhat** [comment]
> Hit an admin up in the telegram chat. Also you have a wrong number of decimals in the commit. It's 6. Also the header says validate "wif". Do us all a favor and delete this and let's sort out in #667 .

We want the same thing, hopefully they treat one of both.

**Comment by 9yoi** [comment]
There are still 3 Cats with Hats trying to validate 

https://github.com/jup-ag/token-list/pull/565
https://github.com/jup-ag/token-list/pull/559
https://github.com/jup-ag/token-list/pull/634

**Comment by Aventurine365** [comment]
> There are still 3 Cats with Hats trying to validate
> 
> #565 #559 #634

Hello what is the situation regarding this request? Looks like somebody has submitted multiple requests to create confusion.

Please refer to the Coingecko and CMC links provided to make it easier and clear the confusion:

https://www.coingecko.com/en/coins/catwifhat
https://coinmarketcap.com/currencies/catwifhat/#About

Both should match the token address: G3vWvAaXPHCnncnyAbq6yBRXqfRtEV3h7vExzasZeT6g

Thank You!

**Review by Aventurine365 — COMMENTED** [review]
Links to the token address and photograph for CatWifHat, CIF are accurate.

**Comment by 9yoi** [comment]
Closing in lieu of https://github.com/jup-ag/token-list/pull/667

**Pull request closed without merging**
