### PR TITLE
validate Casper

### PR DESCRIPTION
**Pull request by goodmemecoin**
# Validate [CSPR](https://solscan.io/token/Gpq4ZdpcSzsJndXu3HiWP5ie744unt1VVg4uUMqHpS9i)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/caspersolcoin/status/1789924220027465962
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by goodmemecoin** [comment]
Just to summarize:
1. accidently sent 2 commits, one is incomplete, the latter one is complete.
2. The Twitter post is there https://x.com/caspersolcoin/status/1789924220027465962, but there is no listing on Coingecko or CMC therefore no link provided
3. The answer to the question "My Token is already live and trading on Jupiter"... it is live and its traded on Raydium. It can be traded on Jupiter but only if you uncheck the strict list, hence I did not check this option. But it is tradeable.

**Comment by goodmemecoin** [comment]
Validation by COINGECKO is underway, Nr: CL1305240145

**Comment by Jymfletzfur** [comment]
insufficient volume

**Comment by goodmemecoin** [comment]
> insufficient volume

We need lists to get the volume up, 
Not giving up on the project or holders.
Just like other coins here that have no volume (0 transactions literally) and are getting positive reviews of the pull request.
I can post an example here if necessary.

**Pull request closed without merging**
