### PR TITLE
VALIDATE KEANU

### PR DESCRIPTION
**Pull request by KeanuCoin**
# Validate [KEANU](https://solscan.io/token/AdTqNaPieJhNzNWNf1bTi7ffbmFty71TX7zeFxxvrFgg)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/Keanu_Bull/status/1776637025350750296
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by SolanaFan — COMMENTED** [review]
Looks good. No spaces, all information valid. Approved.

**Review by MemecoinSol — COMMENTED** [review]
Changes as required. No errors. Will pass.

**Comment by MemecoinSol** [comment]
Original Wif Founder Bateman received an allocation and is supporting. Original Wif dev Arashii is the coder.

**Comment by Jymfletzfur** [comment]
insufficient volume

**Comment by KeanuCoin** [comment]
This is a catch-22. It is obvious once a token is whitelisted more volume will come. Reopen the merge request.

**Pull request closed without merging**
