### PR TITLE
Validate WHC

### PR DESCRIPTION
**Pull request by svrebelo-afv**
# Validate [WHC](https://solscan.io/token/9VLtWhS7Zope97RAJ1KBk2n8FHcNDu5QxqXWv1A3WMko)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/whcsol/status/1794476486943965224
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/whales-club

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
Please come into discord

**Comment by svrebelo-afv** [comment]
> Please come into discord

What's the Discord?

**Comment by svrebelo-afv** [comment]
> Please come into discord

I've sent a message in token-list channel

**Comment by Jymfletzfur** [comment]
Change name to Whales Club

Change image to https://bafybeigielouskhwv5a7f324ngysg7oyitvhea4gntznaami7g6fwpc2wy.ipfs.nftstorage.link/

**Comment by svrebelo-afv** [comment]
> Change name to Whales Club
> 
> Change image to https://bafybeigielouskhwv5a7f324ngysg7oyitvhea4gntznaami7g6fwpc2wy.ipfs.nftstorage.link/

Done! New Commit added

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
