### PR TITLE
Adding ANKHA to the Strict List

### PR DESCRIPTION
**Pull request by Texaglo**
Added ANKHA to the token list

# Validate ANKHA (https://solscan.io/token/A2Qb7iwxvUT6JEPyZH6eLAWSLBZ5H2x1KWPfHES3pump)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/ANKHAsolana/status/1802387753897709571
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jiminitro** [comment]
Looks good

**Comment by Jiminitro** [comment]
Token address is good 👍

**Review by Jiminitro — COMMENTED** [review]
Token is good, address is correct

**Comment by Jymfletzfur** [comment]
token is too new, please come back in 10 days

**Comment by Texaglo** [comment]
Can you give a better reason than that it is too new? There was a token yesterday that got listed that is only a few days old. please make that make sense. this token is over a week old and is doing all the work. @Jymfletzfur

**Pull request closed without merging**
