### PR TITLE
Validate CIGGS

### PR DESCRIPTION
**Pull request by darkmode-ff**
# Validate [CIGGS](https://solscan.io/token/7p6RjGNZ7HLHpfTo6nh21XYw4CZgxXLQPzKXG72pNd2y)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/chunghwa_solana/status/1781489600118288401
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/dexscan/solana/5cjaHtaDjJZqy4fKP5CQFBnQLE7R9XUtneztnDUK4mmz/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers) - Pending

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by ctpancake — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: 7p6RjGNZ7HLHpfTo6nh21XYw4CZgxXLQPzKXG72pNd2y
[x] Symbol: CIGGS
[x] Token Decimals: 9
[x] Token icon: https://bafkreieagcborzxb4mkn37uvxjq7wzrxuuix76crpyym7by2bkkrik4jn4.ipfs.nftstorage.link
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by chunghwalover** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: 7p6RjGNZ7HLHpfTo6nh21XYw4CZgxXLQPzKXG72pNd2y
[x] Symbol: CIGGS
[x] Token Decimals: 9
[x] Token icon: https://bafkreieagcborzxb4mkn37uvxjq7wzrxuuix76crpyym7by2bkkrik4jn4.ipfs.nftstorage.link/
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Review by chunghwalover — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: 7p6RjGNZ7HLHpfTo6nh21XYw4CZgxXLQPzKXG72pNd2y
[x] Symbol: CIGGS
[x] Token Decimals: 9
[x] Token icon: https://bafkreieagcborzxb4mkn37uvxjq7wzrxuuix76crpyym7by2bkkrik4jn4.ipfs.nftstorage.link/
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by Aeon-Chris** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: 7p6RjGNZ7HLHpfTo6nh21XYw4CZgxXLQPzKXG72pNd2y
[x] Symbol: CIGGS
[x] Token Decimals: 9
[x] Token icon: https://bafkreieagcborzxb4mkn37uvxjq7wzrxuuix76crpyym7by2bkkrik4jn4.ipfs.nftstorage.link/
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
