### PR TITLE
Validate CHAT

### PR DESCRIPTION
**Pull request by solchatapp**
# Validate [CHAT](https://solscan.io/token/947tEoG318GUmyjVYhraNRvWpMX7fpBTDQFBoJvSkSG3)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SolChatCoin/status/1768642829956309329
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/solchat/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by wayzeek — COMMENTED** [review]
adding $chat

**Comment by gabrielcustodio** [comment]
This will be of great value.

**Comment by Zoturi** [comment]
Let's add CHAT. Should be a no brainer, as this project is going places.

**Review by Jymfletzfur — APPROVED** [review]

**Comment by picoc** [comment]
Best project solana 2024

**Comment by Fredrick1285** [comment]
Solchat is technology

**Comment by BlueV6** [comment]
This project is a game changing

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
