### PR TITLE
Validate Dolan Duck ($DOLAN)

### PR DESCRIPTION
**Pull request by ProjectDolanDuck**
# Validate [DOLAN](https://solscan.io/token/4YK1njyeCkBuXG6phNtidJWKCbBhB659iwGkUJx98P5Z)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/DolanDuckSol69/status/1774228501119304181
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/dolan-duck

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by CryptoXfiles** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.
 
 * [x]   Mint address: 4YK1njyeCkBuXG6phNtidJWKCbBhB659iwGkUJx98P5Z
 * [x]   Symbol: DOLAN
 * [x]   Token Decimals: 6
 * [x]   Token icon: https://imgur.com/vsLVmwv
 * [x]   On-chain metadata matches
 * [x]   No duplication on Jupiter's strict list

**Comment by Mushy0** [comment]
Mushy0 confirms that the information provided below is accurate.

 Mint address: 4YK1njyeCkBuXG6phNtidJWKCbBhB659iwGkUJx98P5Z
 Symbol: DOLAN
 Token Decimals: 6
 Token icon: https://imgur.com/vsLVmwv
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Review by 9yoi — CHANGES_REQUESTED** [review]
Please use the image url in your onchain metadata. Imgur is down

**Comment by ProjectDolanDuck** [comment]
@9yoi updated the image in the PR, using the one present on solscan metadata.

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
