### PR TITLE
$PAP3R

### PR DESCRIPTION
**Pull request by Xaymaca**
# Validate [$PAP3R](https://solscan.io/token/8o47HJsvFAaUpAFTcJfDnbinjaRWRsWpphCXNpphVias)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/pap3ronsolana/status/1751351214271291695?s=46&t=R0kzHnkroARu7Fb7RaTbZQ
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by fandbcoach — COMMENTED** [review]
Everything looks great. Well done. Nothing to change

**Comment by fandbcoach** [comment]
Amazing and strong community for $PAP3R. This definitely needs to get this approved as there's so many influencers starting to get involved and OG communities

**Comment by MargeRed** [comment]
I have acknowledged all the information, it looks great, good work!

**Comment by lollythedogey** [comment]
This all looks great and valid. Congrats

**Comment by Jymfletzfur** [comment]
Insufficient volume, holder number, mcap and age

**Pull request closed without merging**
