### PR TITLE
Validate SCP

### PR DESCRIPTION
**Pull request by solidGad**
# Validate [SCP](https://solscan.io/token/5sMyPtYRcrEVt27DW3xhGVVha3zCXLv4caVt88PXjBgV) 

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/ScPrimeCloud/status/1795897537645203491
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/scprime

## Validation (Please check off boxes):
- [x ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x ] My change matches the format in the file (no spaces between fields).
- [x ] My token is already live and trading on Jupiter.
- [x ] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x ] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by r3nat** [comment]
[x] Mint address: 5sMyPtYRcrEVt27DW3xhGVVha3zCXLv4caVt88PXjBgV
[x] Symbol: SCP
[x] Token Decimals: 9
[x] Token icon: https://scpri.me/files/scp/logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by solidGad** [comment]
ScPrime (SCP) launced in 2018 and is a decentralized storage project with an AWS S3 drop in replacement product called [XNS/D2](https://xns.tech/). 50% of the SCP supply is on a PoW blockchain, while 50% is in the process of being moved to Solana, which is why we are now applying to have SCP on the strict list. The coin has been in circulation for 5+ years.

**Comment by Jymfletzfur** [comment]
Please come into discord

**Comment by Jymfletzfur** [comment]
Change name to SCP to reflect the metadata

**Comment by solidGad** [comment]
> Change name to SCP to reflect the metadata

Hello. I assume you meant the title of the PR? If so, I changed to SCP. Thanks!

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
