### PR TITLE
Validate VOTE

### PR DESCRIPTION
**Pull request by VOTE-UnitedDogedom**
# Validate [VOTE](https://solscan.io/token/7Cy8QKRGDx42idnRELTVBtYo83PUPWQJ8qnWENUSGuzR)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: 
- https://x.com/Dogedom_VOTE/status/1771654275896119373?s=20
- Coingecko terminal https://www.geckoterminal.com/?q=7Cy8QKRGDx42idnRELTVBtYo83PUPWQJ8qnWENUSGuzR

Token is trading
https://dexscreener.com/solana/8xogx8b4xzchr7syptgykzzpgxwvarhitauuaqixdcge
https://birdeye.so/token/7Cy8QKRGDx42idnRELTVBtYo83PUPWQJ8qnWENUSGuzR?chain=solana

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by pantsjj** [comment]
Just bought this token on DEX, works a treat.
Token now also has links to socials and website👌

**Comment by VOTE-UnitedDogedom** [comment]
Thanks. Dex trading has been always available @pantsjj, merely link to Socials got updated in the last week.
Glad to see community starting to pick up.
Need to get Token validated on Jup-Ag first, to deal with that exclamation mark 👍

**Comment by Jymfletzfur** [comment]
token does not appear to exist on birdeye or solscan

**Comment by VOTE-UnitedDogedom** [comment]
Clicking these same links takes you directly to the working DEX,

Which links are you looking at @Jymfletzfur ?

image

image

image

**Comment by VOTE-UnitedDogedom** [comment]
image

Solscan an showing the same 

@Jymfletzfur could you explain why this ticket is getting closed without validation?

**Pull request closed without merging**
