### PR TITLE
Validate JUPY

### PR DESCRIPTION
**Pull request by jupycoin**
# Validate [$JUPY](https://solscan.io/token/D2tUTtv1rgFL7s9kp5VixQGSFabGe52eBDwUEAoJFAM5)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/jupycoin/status/1730618180991582384
- Coingecko/ CMC URL (If available): In Progress

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by lakshay35** [comment]
Can confirm, community support

**Review by Timoon21 — APPROVED** [review]

**Comment by 9yoi** [comment]
Not sure if we can validate this to the strict list so soon-- it has very similar name to JUP and used our logo in the tweet, which is not endorsed by us. In the meantime, your token is still tradeable on the 'All' list

**Comment by jupycoin** [comment]
Jupylab (https://jupycoin.com) is a 100% community-driven toolkit for launching new projects on Solana with
1- Token Generation Suite
2- Launchpad
3- Listing and Trading GUI 

We are fully supported by the Solana community and have no inherent relation to Jupiter Exchange except our dog's name Jupy the dog going to Jupiter, the planet. We are launching our website JupyLab.com soon and looking forward to your support. For the Twitter post, we tag you for strict list approval and other than that tweet we never share your logo without permission. Our name Jupy resembles to JUP token of Jupiter Exchange, which is only a similarity that we often see in crypto space, but completely different names. One common example could be Avalanche (Avax) layer one, we see Avalaunch (Xava) as the launchpad for Avax layer one.

We are building toolkits that will be useful for the whole Solana ecosystem and are also looking forward to your support.

**Comment by jupycoin** [comment]
Hey Jup team! We're kindly following up on the listing request, our community is passionately waiting.

**Comment by Jymfletzfur** [comment]
Insufficient volume

**Pull request closed without merging**
