### PR TITLE
Validate GME

### PR DESCRIPTION
**Pull request by solanardev**
# Validate [GME](https://solscan.io/token/8wXtPeU6557ETkp9WHFY1n1EcU6NxDvbAggHGsMYiHsB)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: 
https://twitter.com/gmecoinsol/status/1753922069241139337?s=46&t=ak2Ixxkd-wibwYC15m06jw
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/gme, https://coinmarketcap.com/currencies/gme/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by daniloruslan** [comment]
- [x] Mint address: 8wXtPeU6557ETkp9WHFY1n1EcU6NxDvbAggHGsMYiHsB
- [x] Symbol: GME
- [x] Token Decimals: 9
- [x] Token icon: https://img.fotofolio.xyz/?url=https%3A%2F%2Fnftstorage.link%2Fipfs%2Fbafybeiddrzeyne4n2hi7qkhyhqorc4jbs4565pset7fc3ifwvhvxfdrt7q%2Fgamestop-logo.jpeg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by robbestad** [comment]
token image link is wrong. use direct link

**Comment by daniloruslan** [comment]
> token image link is wrong. use direct link

 @robbestad, thanks. Updated the link

**Comment by robbestad** [comment]
> > token image link is wrong. use direct link
> 
> @robbestad, thanks. Updated the link

Did you push it? I still see
https://img.fotofolio.xyz/?url=https%3A%2F%2Fnftstorage.link%2Fipfs%2Fbafybeiddrzeyne4n2hi7qkhyhqorc4jbs4565pset7fc3ifwvhvxfdrt7q%2Fgamestop-logo.jpeg,true

While it should be https://nftstorage.link/ipfs/bafybeiddrzeyne4n2hi7qkhyhqorc4jbs4565pset7fc3ifwvhvxfdrt7q/gamestop-logo.jpeg

I see that fotofolio is a resize and cache service, but it's not really necessary to use such as service here.

**Comment by solanardev** [comment]
> > > token image link is wrong. use direct link
> > 
> > 
> > @robbestad, thanks. Updated the link
> 
> Did you push it? I still see https://img.fotofolio.xyz/?url=https%3A%2F%2Fnftstorage.link%2Fipfs%2Fbafybeiddrzeyne4n2hi7qkhyhqorc4jbs4565pset7fc3ifwvhvxfdrt7q%2Fgamestop-logo.jpeg,true
> 
> While it should be https://nftstorage.link/ipfs/bafybeiddrzeyne4n2hi7qkhyhqorc4jbs4565pset7fc3ifwvhvxfdrt7q/gamestop-logo.jpeg
> 
> I see that fotofolio is a resize and cache service, but it's not really necessary to use such as service here.

**Comment by solanardev** [comment]
Hey @robbestad, I changed the link to the right one.

**Comment by robbestad** [comment]
Happy to review again when you re-open it :)

**Pull request closed without merging**
