### PR TITLE
Validate GME

### PR DESCRIPTION
**Pull request by daniloruslan**
# Validate [GME](https://solscan.io/token/8wXtPeU6557ETkp9WHFY1n1EcU6NxDvbAggHGsMYiHsB)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support:
https://twitter.com/gmecoinsol/status/1753922069241139337
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/gme, https://coinmarketcap.com/currencies/gme/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by daniloruslan** [comment]
@robbestad, would you please take a look at this PR? This is a corrected version of https://github.com/jup-ag/token-list/pull/1418

Thanks in advance!

**Comment by Jymfletzfur** [comment]
On chain name is Gamestop, but in the submission the name is GME

**Comment by daniloruslan** [comment]
@9yoi, would you please take a look as well? Much appreciated.

**Comment by Jymfletzfur** [comment]
Closing because redundant submission. 

Other submission will be handled.

**Pull request closed without merging**
