### PR TITLE
Validate HONK

### PR DESCRIPTION
**Pull request by MONKEycHIMP**
# Validate [HONK](https://solscan.io/token/3ag1Mj9AKz9FAkCQ6gAEhpLSX8B2pUbPdkb9iBsDLZNB)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/honk_sol/status/1749441346148995542?t=8i-v5AG79bX5DknVBqvAsw&s=19
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/honk / https://coinmarketcap.com/currencies/honk

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by MYRAwifeofMYRO** [comment]
Looks good!

✅Mint address: 3ag1Mj9AKz9FAkCQ6gAEhpLSX8B2pUbPdkb9iBsDLZNB
✅Symbol: HONK
✅Token Decimals: 9
✅Token icon: https://bafkreia5nmyxbrxshpiebsakviidhkfuoevpcyzonwov7bmaovce5ekzym.ipfs.nftstorage.link/
✅On-chain metadata matches
✅No duplication on Jupiter's strict list

**Comment by MONKEycHIMP** [comment]
@0xSoju2 please validate and merge $HONK to Strict LIst

**Review by MONKEycHIMP — COMMENTED** [review]
@0xSoju2 kindly tagging please merge $HONK to main [validated-tokens.csv](https://github.com/jup-ag/token-list/blob/main/validated-tokens.csv) thanks

**Comment by MONKEycHIMP** [comment]
$HONK Officially Listed on CMC : https://coinmarketcap.com/currencies/honk/

**Comment by MONKEycHIMP** [comment]
Screenshot 2024-01-26 113841
Daily 24hours volume on Jupiter . :  https://solscan.io/token/3ag1Mj9AKz9FAkCQ6gAEhpLSX8B2pUbPdkb9iBsDLZNB#markets
Also we list on Poloniex : https://poloniex.com/trade/HONK_USDT/?type=spot

@0xSoju2 Kindly requesting and Tagging for updating on Strict list ([validated-tokens.csv](https://github.com/jup-ag/token-list/blob/main/validated-tokens.csv)) on Jupiter Exchange .

**Review by 0xSoju2 — APPROVED** [review]

**Pull request merged**
