### PR TITLE
SIMP validation

### PR DESCRIPTION
**Pull request by SIMPonSOL33**
# Validate [SIMP](https://solscan.io/token/3pzH2ZU4HF2SHMKRrpm1eh3wBs3EXj7nu3pxihxrXMSt)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/SIMPonSOL33/status/1780357625718468674
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x ] My change matches the format in the file (no spaces between fields).
- [x ] My token is already live and trading on Jupiter.
- [x ] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x ] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by SIMPsimpSIMP** [comment]
just pinging here to see if theres anything else i need to do

**Comment by Jymfletzfur** [comment]
insufficient volume

**Comment by bobboyle33** [comment]
Hey @Jymfletzfur we can’t really maintain sufficient volume without order routing through Jupiter as the only liquidity is in form of EGIRL. There’s 47k in liquidity most of which is burned, is there an alternative method of approval? Can you understand why this is a confusing situation that might require a bit more consideration.

**Comment by bobboyle33** [comment]
Maybe reopen request please, would be a real shame to potentially kill a project cause of an arbitrary rule that’s not even stated in your guidelines.

**Comment by Jymfletzfur** [comment]
I can reopen you

Feel free to pop into the discord for any further inquiries.

**Comment by Jymfletzfur** [comment]
closing due to insufficient volume, feel free to pop into the discord to discuss.

**Pull request closed without merging**
