### PR TITLE
Validate KATCHU

### PR DESCRIPTION
**Pull request by KATCHUCoin**
# Validate [KATCHU](https://solscan.io/token/CKiW2P4zngHa6fiPhMJGGhgDZm638dWotxkzgi8PsDxf)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Level100Coin/status/1789035758671552640
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/katchu-coin/

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
token is too new and does not appear to meet any exemptions, come back in a couple of weeks

**Comment by KATCHUCoin** [comment]
Hey there,

Can you elaborate on what exemptions it doesn't meet exactly?

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by KATCHUCoin** [comment]
Can you respond to my previous question?

**Comment by Jymfletzfur** [comment]
Name is Katchu Coin

Image link is

https://node1.irys.xyz/5Wfa6AyqS0xT0i5n4UmHTdacOSv55pZIlamhixfuFeE

**Comment by KATCHUCoin** [comment]
Name is KATCHU. Thank you

Sent with [Proton Mail](https://proton.me/) secure email.

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
