### PR TITLE
Validate shork

### PR DESCRIPTION
**Pull request by JustAChad124**
# Validate [shork](https://solscan.io/token/BJB5tHWAHboMAwti5AHbCNX17F3jL8ehkh4zuTUx99Zn)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/shork_coin/status/1779317725707300970
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/shork/
## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by csanchez812** [comment]
- [x] Mint Address: BJB5tHWAHboMAwti5AHbCNX17F3jL8ehkh4zuTUx99Zn

- [x] Symbol: SHORK

- [x]  Token Decimals: 6

- [x]  Token icon: https://postimg.cc/FfNCmcvQ

- [x] On-chain metadata matches

- [x] No duplication on Jupiter's strict list

**Comment by Buythefxndip** [comment]
- [x] Mint Address: BJB5tHWAHboMAwti5AHbCNX17F3jL8ehkh4zuTUx99Zn

- [x] Symbol: SHORK

- [x]  Token Decimals: 6

- [x] Token icon: https://ibb.co/CKyHVPW

- [x] On-chain metadata matches

- [x] No duplication on Jupiter's strict list

**Comment by JustAChad124** [comment]
Please validate many imposters Trying to copy our token. Would be very helpful for our community. Thank you so much.

**Comment by Jymfletzfur** [comment]
application does not match the on chain metadata, please amend

**Review by JustAChad124 — COMMENTED** [review]
Fixed Believe that is what you wanted. is that correct sir ?

**Comment by Jymfletzfur** [comment]
the name and ticker in the metadata is lowercase shork

please amend application to match

**Comment by JustAChad124** [comment]
Done sir.

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
