### PR TITLE
Update validated-tokens.csv for BullishCoinSol

### PR DESCRIPTION
**Pull request by kir-hakeem**
validate BullishCoinSol

# Validate [BULLCS](https://solscan.io/token/FjcNEkD1WysjgYXizPsCa5hHKnAZKLdQLFHTJBgDFJna)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/BullishCoinSol/status/1768360481998409863?s=20
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by kir-hakeem** [comment]
this commit is to verify  BullishCoinSol

**Review by kir-hakeem — COMMENTED** [review]
BullishCoinSol symbol BULLCS is updated to Bullish and BULL. Validate

**Review by kirmanh — COMMENTED** [review]
this is good to go.. Validate

**Review by kirmanh — COMMENTED** [review]
good to go. Validate

**Comment by RoksJones** [comment]
This token is listed on Dexscreener https://dexscreener.com/solana/apvnovgnwvfveqquos6ebtvwkpa2fpatbwynz3hvfajq

**Review by kir-hakeem — COMMENTED** [review]
I want Bullish BULL to be verify ASAP

**Pull request closed without merging**
