### PR TITLE
Validate $Croco

### PR DESCRIPTION
**Pull request by SolanaCroco**
# Validate [$CROCO](https://solscan.io/token/G8cEYL7MhmWAUiozQbtwrZA7N224QBXu2nDN22xfMhFA)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/CrocoSolana/status/1756056734014075034
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/croco
https://coinmarketcap.com/currencies/croco

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by VaiBozuh** [comment]
Would love to see $CROCO on JUP

**Comment by deadstream215** [comment]
$CROCO on JUP!

**Comment by Jammmmin** [comment]
$CROCO in Jup would be legendary!!

**Comment by Emmaximum-Dexter** [comment]
I would love to see $Coco on Jupiter Great community and Dev and would bring lots of attraction to the solana space.

**Comment by vishalsinghji** [comment]
Hi can anyone validate this PR @Timoon21  @9yoi ? 
We have provided all the required links.
[CMC ](https://coinmarketcap.com/currencies/croco)
[Coingecko](https://www.coingecko.com/en/coins/croco)
[Twitter](https://twitter.com/CrocoSolana/status/1756056734014075034)
[Solscan](https://solscan.io/token/G8cEYL7MhmWAUiozQbtwrZA7N224QBXu2nDN22xfMhFA)

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
