### PR TITLE
MEALS TOKEN

### PR DESCRIPTION
**Pull request by MEALS-TOKEN**
# Validate [MEALS](https://solscan.io/token/BLimDFGYnr6SNNWEGiXbe2FYSKgyHhjbVKMt47h5GezV)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/MealsToken/status/1765982804113043518
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by MEALS-TOKEN — COMMENTED** [review]
Thanks! Can't wait to become part of Jupiter's strict list.

**Comment by Misterglut** [comment]
MEALS TOKEN (MEALS) *VALIDATE 👍
- [x] Mint address: BLimDFGYnr6SNNWEGiXbe2FYSKgyHhjbVKMt47h5GezV
- [x] Symbol: MEALS
- [x] Token Decimals: 5
- [x] Token icon: https://bafkreihz34bzin2seyxgx5z336kpun5kkdn6huxy3hro264zddjayjnzzu.ipfs.nftstorage.link
- [x] On-chain metadata matches
- [×] No duplication on Jupiter's strict list

**Comment by Mogzix85** [comment]
Good luck! great token!

**Comment by Jymfletzfur** [comment]
token fails to meet several criteria including mcap, volume, holder count

**Pull request closed without merging**
