### PR TITLE
Validate $Badger 

### PR DESCRIPTION
**Pull request by Cribsterbozo**
# Validate [badger](https://solscan.io/token/9V4x6ikFm9XKsnh3TiYJWPwQfFkJZDjifu7VSUqg3es1)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/badgerspl22/status/1765346795570307135
- Coingecko/ CMC URL (If available): Working on listing

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Cribsterbozo** [comment]
**Community support of badger is huge! Thank you brodgers**🦡https://twitter.com/badgerspl22/status/1765346795570307135

**Comment by Cribsterbozo** [comment]
Good morning @9yoi @randomshinichi,

I hope you're both doing well. I wanted to check in regarding the $badger PR I opened 3 days ago. Could you please confirm if everything is in order with the submission? Your feedback or any further steps needed from my side would be greatly appreciated. Thank you for your time and assistance.

Best regards. 
Badger Cribster

**Comment by Cribsterbozo** [comment]
@randomshinichi How can I fix that error “exit code 4”?

IMG_4099

**Comment by randomshinichi** [comment]
Hi, thanks for being proactive. As you might have noticed, the exit code is nonzero when   there's a list problem like duplicate name/symbol or bad characters in the symbol etc.. I just wish GitHub showed the script's output...

**Comment by Cribsterbozo** [comment]
> Hi, thanks for being proactive. As you might have noticed, the exit code is nonzero when there's a list problem like duplicate name/symbol or bad characters in the symbol etc.. I just wish GitHub showed the script's output...

Yes. I have quickly runned through that and noticed. I hope now is everything in order.

**Comment by Cribsterbozo** [comment]
@9yoi @randomshinichi Can we try to merge it once again?

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
