### PR TITLE
Adding 777FuckIlluminatiWorldwide

### PR DESCRIPTION
**Pull request by aliyukamilu**
# Validate [FIW](https://solscan.io/token/FeKmTunVrXDKEoDJbuTwZi8vfFFw3MHzpPB79JD8ARYU)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/YOUR_ACCOUNT_NAME_HERE/status/YOUR_TWEET_ID_HERE
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by abubakarhb** [comment]
> * [x]   Mint address: FeKmTunVrXDKEoDJbuTwZi8vfFFw3MHzpPB79JD8ARYU
> * [x]   Symbol: FIW
> * [x]   Token Decimals: 6
> * [x]   Token icon: https://node1.irys.xyz/L6E7LMN7Trvj-Iv4EzvkDqL205JVxGOHoY67LUr8Ytg
> * [x]   On-chain metadata matches
> * [x]   No duplication on Jupiter's strict list

**Comment by anasyakubu** [comment]
> * [x]   Mint address: FeKmTunVrXDKEoDJbuTwZi8vfFFw3MHzpPB79JD8ARYU
> * [x]   Symbol: FIW
> * [x]   Token Decimals: 6
> * [x]   Token icon: https://node1.irys.xyz/L6E7LMN7Trvj-Iv4EzvkDqL205JVxGOHoY67LUr8Ytg
> * [x]   On-chain metadata matches
> * [x]   No duplication on Jupiter's strict list

**Comment by abbasyakubu** [comment]
> * [x]   Mint address: FeKmTunVrXDKEoDJbuTwZi8vfFFw3MHzpPB79JD8ARYU
> * [x]   Symbol: FIW
> * [x]   Token Decimals: 6
> * [x]   Token icon: https://node1.irys.xyz/L6E7LMN7Trvj-Iv4EzvkDqL205JVxGOHoY67LUr8Ytg
> * [x]   On-chain metadata matches
> * [x]   No duplication on Jupiter's strict list

**Comment by amajostech** [comment]
> * [x]   Mint address: FeKmTunVrXDKEoDJbuTwZi8vfFFw3MHzpPB79JD8ARYU
> * [x]   Symbol: FIW
> * [x]   Token Decimals: 6
> * [x]   Token icon: https://node1.irys.xyz/L6E7LMN7Trvj-Iv4EzvkDqL205JVxGOHoY67LUr8Ytg
> * [x]   On-chain metadata matches
> * [x]   No duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
