### PR TITLE
validate DONALD

### PR DESCRIPTION
**Pull request by donald-on-sol**
# Validate [{DONALD}](https://solscan.io/token/4Yz5zByTwnVe46AXD6hsrccbq4TKLyih2xRqPyLBDT1P)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/realDonaldonSol/status/1761485518628360584

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x]  Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by jordan7272** [comment]
* Mint address: 4Yz5zByTwnVe46AXD6hsrccbq4TKLyih2xRqPyLBDT1P
* Symbol: DONALD
* Token Decimals: 6
* Token icon: https://gateway.irys.xyz/LQ9YCmIWoXtDUAxNQhPjpbGbTgLjkgnLFVQJfRn73o0
* On-chain metadata matches
* No duplication on Jupiter's strict list

**Comment by prestonrosemont** [comment]
* Mint address: 4Yz5zByTwnVe46AXD6hsrccbq4TKLyih2xRqPyLBDT1P
* Symbol: DONALD
* Token Decimals: 6
* Token icon: https://gateway.irys.xyz/LQ9YCmIWoXtDUAxNQhPjpbGbTgLjkgnLFVQJfRn73o0
* On-chain metadata matches
* No duplication on Jupiter's strict list

**Comment by shimondama** [comment]
* Mint address: 4Yz5zByTwnVe46AXD6hsrccbq4TKLyih2xRqPyLBDT1P
* Symbol: DONALD
* Token Decimals: 6
* Token icon: https://gateway.irys.xyz/LQ9YCmIWoXtDUAxNQhPjpbGbTgLjkgnLFVQJfRn73o0
* On-chain metadata matches
* No duplication on Jupiter's strict list

**Review by Anularsheers — COMMENTED** [review]
ok

* Mint address: 4Yz5zByTwnVe46AXD6hsrccbq4TKLyih2xRqPyLBDT1P
* Symbol: DONALD
* Token Decimals: 6
* Token icon: https://gateway.irys.xyz/LQ9YCmIWoXtDUAxNQhPjpbGbTgLjkgnLFVQJfRn73o0
* On-chain metadata matches
* No duplication on Jupiter's strict list

**Comment by kcl228** [comment]
* Mint address: 4Yz5zByTwnVe46AXD6hsrccbq4TKLyih2xRqPyLBDT1P
* Symbol: DONALD
* Token Decimals: 6
* Token icon: https://gateway.irys.xyz/LQ9YCmIWoXtDUAxNQhPjpbGbTgLjkgnLFVQJfRn73o0
* On-chain metadata matches
* No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
metrics look good

Only one thing

On chain name is DONALD

Submission calls it Donald

Needs to match

**Comment by donald-on-sol** [comment]
> metrics look good
> 
> Only one thing
> 
> On chain name is DONALD
> 
> Submission calls it Donald
> 
> Needs to match

This has been resolved.

**Pull request closed without merging**
