### PR TITLE
Validated QB

### PR DESCRIPTION
**Pull request by ArashiSol**
# Validate [QB](https://solscan.io/token/4iGtA8VSTFNFjXdQZiSkMkM2sS4x21tC9y5DAU9WxoQd)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/quantitybuild/status/1695518297582874870
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by Quantity1** [comment]
Letsgo

**Comment by wrstnghtmre** [comment]
Validate $qb

**Comment by purpolsol** [comment]
Validate $QB

**Comment by ArashiSol** [comment]
Lets verify @Timoon21 @meijiao

**Review by Timoon21 — APPROVED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] Community validation

**Pull request merged**
