### PR TITLE
DOGE

### PR DESCRIPTION
**Pull request by DogeOnSol**
# Validate [TOKEN_SYMBOL_HERE](https://solscan.io/token/43DCU6q6YQr9R8ymqoKvuAfGQdn83BcmJooiHoBzrg4B)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/dogesoltakeover/status/1791267020438220926?s=46
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by DogeOnSol** [comment]
Hey, anything on our end that we have to fix thank you

**Comment by DogeOnSol** [comment]
We’re the only active dogecoin on solana and highest market cap by any
others. there are daily scams with the same name and we seem to be fallen
under that category. The ethereum doge not only is spelled as “Dogecoin” vs
us being “DogeCoin” to add, considering we’re the highest market cap doge
on solana and the only chart that’s actually available on platforms like
dexscreener, etc, is because majority of other tokens are just phishing
baits for those who want to trade the real Solana deriv being us. Please
reconsider so we can continue to make a place for doge on solana 🫶🏼

**Comment by AlpDeluxe20** [comment]
How is this an exact copy if we are on the Solana Blockchain? If it is the ticker $Doge what you meant this shouldn't be the problem Dogecoin is the most known Memecoin and the people won't buy by mistake our Doge on Solana. We are working hard for this project and we as the Doge team. Would be very appreciated to get your confirmation.

Best regards
Alperen Pacacioglu
Dogecoin on Solana Team member

**Comment by AlpDeluxe20** [comment]
Can we please get a reply @9yoi?

Thanks

**Comment by AlpDeluxe20** [comment]
@9yoi can you please review our reply please. We wait for weeks now.

**Comment by AlpDeluxe20** [comment]
?? Can we have any reply please? This is getting serious now.

**Pull request closed without merging**
