### PR TITLE
Validate CROC

### PR DESCRIPTION
**Pull request by husscroccer**
# Validate [CROC](https://solscan.io/token/5V9qpFo8NMFyhYHbrqY2c1TJrvzZSnRJAdj4ryPVB18n)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/croccat69/status/1760115343224451367?s=46
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/croc-cat
- telegram link for community: https://t.me/+HCI0OCFtJ2Q4YWMx

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by andy7284** [comment]
I can hereby attest that the provided information is accurate, and the token is valid. Mint address: 5V9qpFo8NMFyhYHbrqY2c1TJrvzZSnRJAdj4ryPVB18n Symbol: CROC Token Decimals: 9 Token icon:https://imgur.com/a/6PC6XK6 On-chain metadata matches No duplication on Jupiter's strict list

**Comment by ItzMrA** [comment]
I affirm the accuracy of the supplied details, confirming the legitimacy of the token. Minting address: 5V9qpFo8NMFyhYHbrqY2c1TJrvzZSnRJAdj4ryPVB18n Symbol: CROC Token Decimals: 9 Token icon: https://imgur.com/a/6PC6XK6 The on-chain metadata aligns, and there is no replication on Jupiter's stringent registry.

**Comment by MrNikaa** [comment]
all of the details are accurate.  the token is legit and valid. Minting address: 5V9qpFo8NMFyhYHbrqY2c1TJrvzZSnRJAdj4ryPVB18n Symbol: CROC Token Decimals: 9 Token icon: https://imgur.com/a/6PC6XK6 The on-chain metadata is matching, and has no replication on the Jupiters stringent registry

**Comment by olaccrocer** [comment]
I am confirming that the token is legit. Minting address: 5V9qpFo8NMFyhYHbrqY2c1TJrvzZSnRJAdj4ryPVB18n Symbol: CROC Token Decimals: 9 Token icon: https://imgur.com/a/6PC6XK6 The on-chain metadata aligns, and there is no replication on Jupiter's stringent registry.

**Comment by atomprime786** [comment]
I confirm the accuracy of the following data and ask for approval. 
Croccat is a nice cat and legit meme from 2018
However community could be more respectful of different opinions.

Minting address: 5V9qpFo8NMFyhYHbrqY2c1TJrvzZSnRJAdj4ryPVB18n Symbol: CROC Token Decimals: 9 Token icon: https://imgur.com/a/6PC6XK6 The on-chain metadata aligns, and there is no replication on Jupiter's stringent registry.

**Comment by Euii36** [comment]
I can confirm that Croccat is 100% real and community is really healthy.
Mint address: 5V9qpFo8NMFyhYHbrqY2c1TJrvzZSnRJAdj4ryPVB18n
 Symbol: CROC
 Token Decimals: 9
 Token icon:https://imgur.com/a/6PC6XK6
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Pull request closed without merging**
