### PR TITLE
Wojak change of logo URL

### PR DESCRIPTION
**Pull request by Dh1988**
# Validate [Wojak][https://solscan.io/token/4MPA8WbyYtKiufXDSdckEoMPdN5XK1Xw9S9LSLMjK5Y4]

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: 
- [https://x.com/Wojak_Coin_Sol/status/1772305659607855351?s=20]- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Lonelyboycrypto — COMMENTED** [review]
Yes this is the right way to replace logo. Looks good, maintainer please merge

**Review by firstrank — COMMENTED** [review]
This will update the logo image on Jupiter.  Please proceed.

**Comment by Dh1988** [comment]
please merge

**Review by firstrank — COMMENTED** [review]
Please proceed with merge

**Review by Lonelyboycrypto — COMMENTED** [review]
Looks good now

**Review by Lonelyboycrypto — COMMENTED** [review]
Plz update logo

**Comment by Dh1988** [comment]
can we please have the merge completed

**Comment by Dh1988** [comment]
Hi, we can’t see the contact on Jupiter exchange this morning is this due to the update?

**Review by firstrank — COMMENTED** [review]
Please complete this merge

**Review by Jymfletzfur — APPROVED** [review]

**Review by firstrank — COMMENTED** [review]
Please merge this.

**Comment by Dh1988** [comment]
I believe we need one more approval if we can get this done. Thank you

**Review by 9yoi — CHANGES_REQUESTED** [review]
Unable to approve. does not match onchain image: https://bafybeidzhrlmyjgx52t56ribawbm6jvn5rdr2aly5mxabxjsciqmrczq4i.ipfs.nftstorage.link

**Comment by Dh1988** [comment]
This image is from the previous Dev before a community take over. Please check this link on Dex screener, it is the image we are trying to use 

https://dexscreener.com/solana/6ckfpq5wme37paydyk8igmcaeuw1nhya2h4naxknxugs

their is also not of the community takeover on here.

Also Birdeye… 

https://birdeye.so/token/4MPA8WbyYtKiufXDSdckEoMPdN5XK1Xw9S9LSLMjK5Y4?chain=solana

please consider the merge on this basis the solscan info is incorrect and scam dev set this before the community takeover which has been awarded and was paid for.

**Comment by Jymfletzfur** [comment]
feel free to come into discord to discuss

**Comment by Dh1988** [comment]
the logo on solscan has now been updated, please merge so this can be updated on the strict list also

thanks

**Pull request closed without merging**
