### PR TITLE
Validate boden

### PR DESCRIPTION
**Pull request by thisisalexmcgregor**
# Validate [boden](https://solscan.io/token/3psH1Mj1f7yUfaD5gh6Zj7epE8hhrMkMETgv5TshQA4o)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: 
- [Tweet from Official Account](https://x.com/boden4pres/status/1770633194024395056?s=46&t=NHmkLu-SpO2S2CLwsSlDcw)

- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/jeo-boden

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by CreggTheEgg** [comment]
Hello, I can validate that this is correct. 

[Here is a twitter post with hundreds of engagements asking for boden as well.](https://twitter.com/EggNamedCregg/status/1770257565756080547)

There are other fake boden coins which are allowing users to be potentially scammed. Boden is currently sitting at 20m 24 hour volume with ~20k holders and it would help keep many users safe to have it on the approved list.

**Review by Jymfletzfur — APPROVED** [review]

**Comment by EvanJRichard** [comment]
+1, jupiter user/boden holder here, PR LGTM and I think it'd help cut down on scams.

**Comment by bulutbuyru** [comment]
lgtm

**Comment by bigchickendefi** [comment]
Vouch

**Comment by 0x6d656d6573** [comment]
PR looks good, ship it

**Comment by thisisalexmcgregor** [comment]
@9yoi LMK if I need to resign that commit. Otherwise I think PR is good to go.

**Comment by jamesdabr** [comment]
PR looks good

**Comment by CryptoLemmingtestnet** [comment]
PR looks good, let's go

**Review by 0xSoju2 — APPROVED** [review]

**Pull request merged**
