### PR TITLE
VALIDATE SHIB

### PR DESCRIPTION
**Pull request by clrhc**
# Validate [SHIB](https://solscan.io/token/F6qoefQq4iCBLoNZ34RjEqHjHkD8vtmoRSdw9Nd55J1k)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/shibwifcoin/status/1776682938706301229?s=46
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/shibwifhatcoin https://coinmarketcap.com/currencies/shibwifhat/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Jymfletzfur — APPROVED** [review]

**Comment by Jamesolmars** [comment]
@9yoi Please approve it ASAP
The project listed on CMC and CG and listed on Exchanges and followed by TrustWallet and many big names.
#Shibwifhat ATH hit +20M mc
Thank you so much!

**Comment by therealbeliever** [comment]
This project is real and legit confirmed

**Comment by BigRZ90** [comment]
Project is real.

**Comment by ddoniwailer** [comment]
I believe JUPITER will approve Shibwifhat strict list resquest ASAP 😎

**Comment by Jamesolmars** [comment]
@9yoi The community is eagerly awaiting approval

**Comment by Jamesolmars** [comment]
Why shibwifhat not added yet to strict list?  @Jymfletzfur @9yoi

**Comment by hashTor** [comment]
Hi @9yoi  or any reviewer and approvers, please review and approved this request. This is Shibwifhat in Solana and been there for a while now.  I saw new projects with less than 700 holders in been in strict list but this one hasn’t. Additionally, this was also listed in Bitmart (with ticker SHIBWIF)  , listed in Trustwallet , and had community (holders and influencers) support. Thank you.

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
