### PR TITLE
Add Meow ($MEOW) to Validated Tokens

### PR DESCRIPTION
**Pull request by BlueSkyN7**
# Validate [Meow](https://solscan.io/token/{AQvXeBUfK5chiuTxeuAecEWJcMGgoRtaRsk3fUiGtZdu})

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: 
- https://x.com/Meowsolanacoin/status/1751385113504489612?s=20 The quoted tweet shows significant evidence of community support.
- Coingecko/ CMC URL (If available): We have applied for CoinGecko listing

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by ADASTRAAMC** [comment]
[x] Mint address: AQvXeBUfK5chiuTxeuAecEWJcMGgoRtaRsk3fUiGtZdu
    [x] Symbol: MEOW
    [x] Token Decimals: 9
    [x] Token icon: https://i.imgur.com/V3Mw6NI.png
    [x] On-chain metadata matches
    [x] No duplication on Jupiter's strict list

**Comment by fermand** [comment]
"[x] Mint address:    AQvXeBUfK5chiuTxeuAecEWJcMGgoRtaRsk3fUiGtZdu
    [x] Symbol: MEOW
    [x] Token Decimals: 9
    [x] Token icon: https://i.imgur.com/V3Mw6NI.png
    [x] On-chain metadata matches
    [x] No duplication on Jupiter's strict list"

**Comment by Mssael** [comment]
"[x] Mint address:    AQvXeBUfK5chiuTxeuAecEWJcMGgoRtaRsk3fUiGtZdu
    [x] Symbol: MEOW
    [x] Token Decimals: 9
    [x] Token icon: https://i.imgur.com/V3Mw6NI.png
    [x] On-chain metadata matches
    [x] No duplication on Jupiter's strict list"

**Comment by solanerdegen** [comment]
"[x] Mint address:    AQvXeBUfK5chiuTxeuAecEWJcMGgoRtaRsk3fUiGtZdu
    [x] Symbol: MEOW
    [x] Token Decimals: 9
    [x] Token icon: https://i.imgur.com/V3Mw6NI.png
    [x] On-chain metadata matches
    [x] No duplication on Jupiter's strict list"

**Comment by asterixlemonarque** [comment]
[x] Mint address:    AQvXeBUfK5chiuTxeuAecEWJcMGgoRtaRsk3fUiGtZdu
    [x] Symbol: MEOW
    [x] Token Decimals: 9
    [x] Token icon: https://i.imgur.com/V3Mw6NI.png
    [x] On-chain metadata matches
    [x] No duplication on Jupiter's strict list

**Comment by Arez97** [comment]
"[x] Mint address:    AQvXeBUfK5chiuTxeuAecEWJcMGgoRtaRsk3fUiGtZdu
    [x] Symbol: MEOW
    [x] Token Decimals: 9
    [x] Token icon: https://i.imgur.com/V3Mw6NI.png
    [x] On-chain metadata matches
    [x] No duplication on Jupiter's strict list"

**Comment by Kraedar** [comment]
"[x] Mint address:    AQvXeBUfK5chiuTxeuAecEWJcMGgoRtaRsk3fUiGtZdu
    [x] Symbol: MEOW
    [x] Token Decimals: 9
    [x] Token icon: https://i.imgur.com/V3Mw6NI.png
    [x] On-chain metadata matches
    [x] No duplication on Jupiter's strict list"

**Comment by co242424** [comment]
[x] Mint address:    AQvXeBUfK5chiuTxeuAecEWJcMGgoRtaRsk3fUiGtZdu
    [x] Symbol: MEOW
    [x] Token Decimals: 9
    [x] Token icon: https://i.imgur.com/V3Mw6NI.png
    [x] On-chain metadata matches
    [x] No duplication on Jupiter's strict list

**Comment by co242424** [comment]
[x] Mint address: AQvXeBUfK5chiuTxeuAecEWJcMGgoRtaRsk3fUiGtZdu
[x] Symbol: MEOW
[x] Token Decimals: 9
[x] Token icon: https://i.imgur.com/V3Mw6NI.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by infinite404** [comment]
[x] Mint address: AQvXeBUfK5chiuTxeuAecEWJcMGgoRtaRsk3fUiGtZdu
[x] Symbol: MEOW
[x] Token Decimals: 9
[x] Token icon: https://i.imgur.com/V3Mw6NI.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by etuck2080** [comment]
"[x] Mint address:    AQvXeBUfK5chiuTxeuAecEWJcMGgoRtaRsk3fUiGtZdu
  [x] Symbol: MEOW
  [x] Token Decimals: 9
  [x] Token icon: https://i.imgur.com/V3Mw6NI.png
  [x] On-chain metadata matches
  [x] No duplication on Jupiter's strict list"

**Comment by Jymfletzfur** [comment]
Insufficient volume, mcap

**Pull request closed without merging**
