### PR TITLE
validate DRAGGIN

### PR DESCRIPTION
**Pull request by Meciah**
# Validate [DRAGGIN](https://solscan.io/token/3EmPaYSeWEMjKikcKgxAJKJC3VdMfPWESZTUQnHvunSP)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/dragginballzsol/status/1755595298486043087?s=20
- Coingecko/ CMC URL (If available): Not yet listed. Applied for both.

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Ptbnk** [comment]
I am part of the $DRAGGIN community and can confirm the following is accurate:

- [x] Mint address: 3EmPaYSeWEMjKikcKgxAJKJC3VdMfPWESZTUQnHvunSP
- [x] Symbol: DRAGGIN
- [x] Token Decimals: 6
- [x] Token icon: https://bafkreidmnwyoflryznli3nowccbj5b67ninam7s2eqh5sj2gk27qtgnshq.ipfs.nftstorage.link
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by NFTsloth** [comment]
I am part of the $DRAGGIN community and can confirm the following is accurate:

 Mint address: 3EmPaYSeWEMjKikcKgxAJKJC3VdMfPWESZTUQnHvunSP
 Symbol: DRAGGIN
 Token Decimals: 6
 Token icon: https://bafkreidmnwyoflryznli3nowccbj5b67ninam7s2eqh5sj2gk27qtgnshq.ipfs.nftstorage.link/
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Review by NFTsloth — COMMENTED** [review]
I am part of the $DRAGGIN community and can confirm the following is accurate:

 Mint address: 3EmPaYSeWEMjKikcKgxAJKJC3VdMfPWESZTUQnHvunSP
 Symbol: DRAGGIN
 Token Decimals: 6
 Token icon: https://bafkreidmnwyoflryznli3nowccbj5b67ninam7s2eqh5sj2gk27qtgnshq.ipfs.nftstorage.link/
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Review by NFTolkien — COMMENTED** [review]
I am part of the $DRAGGIN community and can confirm the following is accurate:

[x] Mint address: 3EmPaYSeWEMjKikcKgxAJKJC3VdMfPWESZTUQnHvunSP
[x] Symbol: DRAGGIN
[x] Token Decimals: 6
[x] Token icon: https://bafkreidmnwyoflryznli3nowccbj5b67ninam7s2eqh5sj2gk27qtgnshq.ipfs.nftstorage.link/
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Review by FeelingLuckySOL — COMMENTED** [review]
I am part of the $DRAGGIN community and can confirm the following is accurate:

[x] Mint address: 3EmPaYSeWEMjKikcKgxAJKJC3VdMfPWESZTUQnHvunSP
[x] Symbol: DRAGGIN
[x] Token Decimals: 6
[x] Token icon: https://bafkreidmnwyoflryznli3nowccbj5b67ninam7s2eqh5sj2gk27qtgnshq.ipfs.nftstorage.link/
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by Perseus-T** [comment]
I am part of the $DRAGGIN community and can confirm the following is accurate:

- [x] Mint address: 3EmPaYSeWEMjKikcKgxAJKJC3VdMfPWESZTUQnHvunSP
- [x] Symbol: DRAGGIN
- [x] Token Decimals: 6
- [x] Token icon: https://bafkreidmnwyoflryznli3nowccbj5b67ninam7s2eqh5sj2gk27qtgnshq.ipfs.nftstorage.link/
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by gugunaga** [comment]
I am part of the $DRAGGIN community and can confirm the following is accurate:

I am currently in $DRAGGIN community telegram and holding considerable amount og tokens. They are legit. 

 Mint address: 3EmPaYSeWEMjKikcKgxAJKJC3VdMfPWESZTUQnHvunSP
 Symbol: DRAGGIN
 Token Decimals: 6
 Token icon: https://bafkreidmnwyoflryznli3nowccbj5b67ninam7s2eqh5sj2gk27qtgnshq.ipfs.nftstorage.link/
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Review by gugunaga — COMMENTED** [review]
All data provided is correct and valid. This is a community token, active on twitter, telegram and tradable.

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
