### PR TITLE
VALIDATE EEPYCOIN ($EEPY)

### PR DESCRIPTION
**Pull request by EEPYCOIN**
# Validate EEPY (https://solscan.io/token/6U3cXmG7rzDVNt61z5yJZL7sp8nfDeeKAVZLM1rtPNKy)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/eepy_coin/status/1778808872993509787
- Coingecko/ CMC URL: Unavailable yet (work in progress)

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Pekky-xyz** [comment]
ADD $EEPY TO STRICT LIST YOU WONT REGRET IT
                 🥺
              👉👈

**Comment by Kenche8** [comment]
ADD $EEPY TO STRICT LIST!! It’s an up and coming crypto!! You won’t be sorry!!

**Comment by Web3Entusiast** [comment]
Add $EEPY to Strict list 
It's a great project with amazing Devs and a lively community

**Comment by Febrian00** [comment]
Please add and list $EEPY 🙂

**Comment by dodakdodak778** [comment]
Give us $EPPY GOOD LUCK

**Comment by Lildonut7** [comment]
Add $EEPY to strict list, this cat is tired of waiting 😿

**Comment by corneringboy** [comment]
Add $EEPY to strict  list

**Comment by EEPYhodler** [comment]
Hey Jup exchange!! 

Please add EEPYCOIN to safe list!

their LP is Locked in a locker, ecofarm created, 6k on Twitter, discord, telegram!

this team is truly taking all the steps in the right direction to be a coin that people want to buy

**Comment by Dexill** [comment]
ADD $EEPY TO STRICT LIST  let's go ✊🏻✊🏻✊🏻

**Comment by Techno11111** [comment]
Add $EEPY to strict list

**Comment by Thesuper23** [comment]
Add $Eepy, Eepycoin to strict list

**Comment by Skeletonsoup** [comment]
ADD $EEPY TO THE STRICT LIST GANG

**Comment by Comerciante369** [comment]
Gogo $EEPY

**Comment by LSUtigershark** [comment]
Add $EEPY to the strict list.

Thank you

**Comment by Godreaper7** [comment]
ADD $EEPY TO STRICT LIST PLEASE

**Comment by johnarohloff1** [comment]
ADD $EEPY TO STRICT LIST PLZ!

**Comment by deliveryboyasif** [comment]
Add $EEPY TO STRICT list it's a people's choice plz 🙏

**Comment by XXunn** [comment]
ADD $EEPY TO STRICT LIST !!! Let's do this!

**Comment by YaYunnick** [comment]
ADD $EEPY TO STRICT LIST! LET'S GOOO!

**Comment by CryptoBoarder** [comment]
Cryptoboarder says you need to add $EEPY to the strict list!

**Comment by zhaogougou0721** [comment]
Please add and list $EEPY 🙂

**Comment by noey210** [comment]
ADD $EEPY TO STRICT LIST YOU WONT REGRET IT
🥺

**Comment by noey210** [comment]
ADD $EEPY TO STRICT LIST

**Comment by Danchik134** [comment]
ДОБАВЬТЕ $EEPY В СТРОГО СПИСОК, ВЫ НЕ ПОЖАЛЕЕТЕ
🥺
👉👈

**Comment by Seiverrx** [comment]
Let's go 🔥
Add $EEPY to stritch list 🚀🚀

**Comment by itskeyfrm26O** [comment]
Add $EEPY TO STRICT list it's a people's choice plz 🙏

**Comment by easycashflow69** [comment]
Come on add $EPPY to the strict list we waiting patiently

**Comment by Jymfletzfur** [comment]
insufficient volume

**Comment by corneringboy** [comment]
Add $EPPY TO strict list and wont regret later

**Pull request closed without merging**
