### PR TITLE
Validate LPFi, xLPFi, zSOL

### PR DESCRIPTION
**Pull request by aperire**
# Validate [LPFi](https://solscan.io/token/LPFiNAybMobY5oHfYVdy9jPozFBGKpPiEGoobK2xCe3), [xLPFi](https://solscan.io/token/xLPFiPmWve5rUnAYcHZSZWjwgyqEdcV6dDzoBJRtNw9), [zSOL](https://solscan.io/token/So111DzVTTNpDq81EbeyKZMi4SkhU9yekqB8xmMpqzA)

## Attestations:
- Tweet from your Twitter Account attesting the Mint address: https://twitter.com/LPFinance_/status/1626016173027368960?s=20
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/lp-finance
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/xlp-finance
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/zsol

## Validation (Additonal material for reviewers):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will take longer)
- [x] Is Listed on Coingecko / CMC (Optional, but is helpful for reviewers to check for duplicates)  

## Acknowledgement
- [x] Acknowleged that I did not modify unrelated code.
- [x] Acknowledged that my change matches the format of other lines in the file (no spaces between fields).

### CODE REVIEW

**Comment by LJQZZZ123** [comment]
LPFi
- [ ] Token decimals is missing in the PR
- [ ] Token address matches the tweet
- [ ] Can be searched on CoinGecko/CMC and no duplication
- [ ] No duplication on Jupiter's strict list

xLPFi
- [ ] Token decimals is missing in the PR
- [ ] Token address matches the tweet
- [ ] Can be searched on CoinGecko and no duplication
- [ ] No duplication on Jupiter's strict list

zSOL
- [ ] Token decimals is missing in the PR
- [ ] Token address matches the tweet
- [ ] Can be searched on CoinGecko and no duplication
- [ ] The same token symbol can be searched on CMC but seems unrelated
- [ ] No duplication on Jupiter's strict list

> https://coinmarketcap.com/dexscan/bsc/0x89793b4ae1451ea690e76ff75bb2c8f5fc7526e6

**Comment by aperire** [comment]
@LJQZZZ123 added decimals for LPFi, xLPFi, zSOL!

**Review by LJQZZZ123 — DISMISSED** [review]

**Review by Timoon21 — CHANGES_REQUESTED** [review]
- [ ] On-chain metadata matches the PR
LPFi on-chain metadata img : https://raw.githubusercontent.com/LP-Finance-Inc/token-image/main/LPFiToken.png

- [x] Token address matches the official website
- [x] Not on CoinGecko, no duplication
- [x] No duplication on the Jupiter's strict list

- [ ] Change dont matches the format of other lines in the file (spaces between fields).

**Review by Timoon21 — APPROVED** [review]

**Comment by meijiao** [comment]
Could not resolve the merge conflicts and didn't have permission to update the PR in your repo. Please open a new PR and copy your changes in. Thanks!

**Pull request closed without merging**
