### PR TITLE
Validate OPN Ticketing Ecosystem Token (formerly GET Protocol)

### PR DESCRIPTION
**Pull request by kasper-keunen**
# [Validate OPN Ticketing Ecosystem Token](https://solscan.io/token/J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address:  [Tweet to Jupiter](https://twitter.com/onopenxyz/status/1772980190987067644)
- Coingecko/CMC URL (If available): The migration to OPN will take place on the 29th of March so at the moment the OPN token is not yet traded. 

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter’s strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  -> token will be listed on cmc and gecko after launch on 29th of march.

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter. (liquidity will be added on the 28th)
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says “Main”, or “Validate”, it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

Note: On 29 of march at 9:30 UTC [GET 0x8a854288a5976036A725879164Ca3e91d30c6A1B](https://etherscan.io/address/0x8a854288a5976036A725879164Ca3e91d30c6A1B) will be migrating to OPN (Open Ticketing Ecosystem Token).  The address of OPN on Ethereum is: [OPN 0xc28eb2250d1AE32c7E74CFb6d6b86afC9BEb6509](https://etherscan.io/address/0xc28eb2250d1AE32c7E74CFb6d6b86afC9BEb6509)

Note: I also added validation for wormhole and solana fm, not sure if that is something that is allowed. I did notice other PRs also doing that hence i took the liberty to do that as well. I would be glad to revert these changes if that is preferred.

Logo of OPN in SVG: [Arweave link](https://y45xyr7v6dybwrveq4eo4eyhaefnndqyuexxdwmls2uvk2tc54ta.arweave.net/xzt8R_Xw8BtGpIcI7hMHAQrWjhihL3HZi5apVWpi7yY)

Logo of OPN in PNG: [Arweave link](https://4lp2twpwieongl7p75tmd4lag5lfntnryyaujxjatl37pworbica.arweave.net/4t-p2fZBHNMv7_9mwfFgN1ZWzbHGAUTdIJr399nRCgQ)

For verification of token addresses refer to: https://onopen.xyz/token-migration and for GET refer to: https://www.get-protocol.io/token-migration

As for listing criteria:
- OPN is the migrated token of GET Protocol [coingecko](https://www.coingecko.com/en/coins/get-protocol) with 70 million market cap and a lot of volume
- GET was deployed in 2017: [etherscan](https://etherscan.io/address/0x8a854288a5976036a725879164ca3e91d30c6a1b)  and has more than 10k holders on Ethereum
- On the 29th of march GET will migrate to OPN and it will also in this move start on-chain ticketing on Solana (GET has issued more than 5 million NFT tickets to date on Polygon, this will for a large part move to SOL).

### CODE REVIEW

**Comment by kasper-keunen** [comment]
I took the liberty to all add the info for wormhole and solana fm - as i noticed that in some cases this was also allowed/done by other devs. Happy to remove that of course. 

This is the community tweet: [https://twitter.com/onopenxyz/status/1772980190987067644](tweet of OPN to Jupiter)

**Comment by Khrafts** [comment]
Hello, Uyoyou from Open Ticketing Ecosystem (fka GET Protocol) here, confirming the statement above:


- [x] Mint address: J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv

- [x] Symbol: OPN

- [x] Token Decimals: 8

- [x]  Token icon: https://arweave.net/4t-p2fZBHNMv7_9mwfFgN1ZWzbHGAUTdIJr399nRCgQ

- [x] On-chain metadata matches

- [x] No duplication on Jupiter's strict list

**Comment by FransTwisk** [comment]
- [x] Mint address: `J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv`
- [x] Symbol: `OPN`
- [x] Token Decimals: `8`
- [x]  Token icon: https://arweave.net/4t-p2fZBHNMv7_9mwfFgN1ZWzbHGAUTdIJr399nRCgQ
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by ameyarao98** [comment]
- Mint address: J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv
-  Symbol: OPN
- Token Decimals: 8
- Token icon: https://arweave.net/4t-p2fZBHNMv7_9mwfFgN1ZWzbHGAUTdIJr399nRCgQ
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by kasper-keunen** [comment]
As for listing criteria:
- OPN is the migrated token of GET Protocolhttps://www.coingecko.com/en/coins/get-protocol with 70 million market cap and a lot of volume daily
- GET was deployed in 2017: https://etherscan.io/address/0x8a854288a5976036a725879164ca3e91d30c6a1b  and has more than 10k holders on Ethereum
- On the 29th of march GET will migrate to OPN and it will also in this move start on-chain ticketing on Solana (GET has issued more than 5 million NFT tickets to date on Polygon, this will for a large part move to SOL).

Therefor it is my belief that OPN would deserve to be on the Jupiter strict list as it has a lot of volume, holders and has proven to be legit. Let me know if there are any questions or concerns.

**Comment by rooie1971** [comment]
Would be appreciated if the pr could be approved before march 29th

**Comment by rooie1971** [comment]
Hello, XXX would be great to add OPN to the strict list before the migration on the 29th (where it will be migrating from GET with a 50M market cap to OPN).


- [x] Mint address: J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv

- [x] Symbol: OPN

- [x] Token Decimals: 8

- [x]  Token icon: https://arweave.net/4t-p2fZBHNMv7_9mwfFgN1ZWzbHGAUTdIJr399nRCgQ

- [x] On-chain metadata matches

- [x] No duplication on Jupiter's strict list

**Comment by bakman2** [comment]
Project is valid, solid and sound. 
 
- [x] Mint address: J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv
- [x] Symbol: OPN
- [x] Token Decimals: 8
- [x]  Token icon: https://arweave.net/4t-p2fZBHNMv7_9mwfFgN1ZWzbHGAUTdIJr399nRCgQ
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by SanderKo** [comment]
Please add OPN to the strict list before launch on march 29th. OPN is a solid and OG project which will be migrating from GET on the 29th.

-Mint address: J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv
Symbol: OPN
Token Decimals: 8
Token icon: https://arweave.net/4t-p2fZBHNMv7_9mwfFgN1ZWzbHGAUTdIJr399nRCgQ
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by eyaluth** [comment]
Project is valid!

 Mint address: J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv
 Symbol: OPN
 Token Decimals: 8
 Token icon: https://arweave.net/4t-p2fZBHNMv7_9mwfFgN1ZWzbHGAUTdIJr399nRCgQ
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by bromdigital** [comment]
It would be great to add OPN to the strict list before the migration on the 29th (where it will be migrating from GET with a 50M market cap to OPN).

- [x] Mint address: J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv

- [x] Symbol: OPN

- [x] Token Decimals: 8

- [x]  Token icon: https://arweave.net/4t-p2fZBHNMv7_9mwfFgN1ZWzbHGAUTdIJr399nRCgQ

- [x] On-chain metadata matches

- [x] No duplication on Jupiter's strict list

**Comment by bromdigital** [comment]
It would be great to add OPN to the strict list before the migration on the 29th (where it will be migrating from GET with a 50M market cap to OPN).

- Mint address: J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv
- Symbol: OPN
- Token Decimals: 8
- Token icon: https://arweave.net/4t-p2fZBHNMv7_9mwfFgN1ZWzbHGAUTdIJr399nRCgQ
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by markjongkind** [comment]
Please merge, this is great and valid project.

- Mint address: J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv
- Symbol: OPN
- Token Decimals: 8
- Token icon: https://arweave.net/4t-p2fZBHNMv7_9mwfFgN1ZWzbHGAUTdIJr399nRCgQ
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by Bender441** [comment]
please add OPN to the strict list before the migration on the 29th March. the project has sold millions of tickets and registered onchain, releasnig financing for events on chain and also serving large event organisers in netherlands and internationally

Mint address: J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv
Symbol: OPN
Token Decimals: 8
Token icon: https://arweave.net/4t-p2fZBHNMv7_9mwfFgN1ZWzbHGAUTdIJr399nRCgQ
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by malfidev** [comment]
Please review and approve this PR as this is a valid project.

    Mint address: J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv
    Symbol: OPN
    Token Decimals: 8
    Token icon: https://arweave.net/4t-p2fZBHNMv7_9mwfFgN1ZWzbHGAUTdIJr399nRCgQ
    On-chain metadata matches
    No duplication on Jupiter's strict list

**Comment by Deofex** [comment]
This wonderful project has been in existence since 2017 under a different ticker (GET) and is now gearing up to launch on Solana. While bellow message looks like a botarmy (everyone is posting the same) I understood this format is a mandatory requirement. Nevertheless, it's essential to underscore the importance of listing OPN. By adding this token to your exchange, you not only bolster its value but also cater to the burgeoning demand from users eager to trade it on your platform in the foreseeable future.

* [x]  Mint address: J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv
* [x]  Symbol: OPN
* [x]  Token Decimals: 8
* [x]   Token icon: https://arweave.net/4t-p2fZBHNMv7_9mwfFgN1ZWzbHGAUTdIJr399nRCgQ
* [x]  On-chain metadata matches
* [x]  No duplication on Jupiter's strict list

**Comment by Vercoutere** [comment]
Happy to vouch for this one. They have a flawless track record.

- Mint address: J1YnyKzmxBwFkPftvZexnHTm4Am7JnmWydhxtXdwEmMv
- Symbol: OPN
- Token Decimals: 8
- Token icon: https://arweave.net/4t-p2fZBHNMv7_9mwfFgN1ZWzbHGAUTdIJr399nRCgQ
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by benlvb** [comment]
Apologies for the delay, the name seems to be different on the block explorer, and there might be some issue with your token logo metadata. 

Screenshot 2024-03-29 at 02 32 02

**Comment by kasper-keunen** [comment]
> Apologies for the delay, the name seems to be different on the block explorer, and there might be some issue with your token logo metadata.
> 
> Screenshot 2024-03-29 at 02 32 02

You are right, this is also sort of the reason why this issue is a bit more pressing.

We are migrating from Ethereum (so currently our token is GET on eth: 0x8a854288a5976036A725879164Ca3e91d30c6A1B). The plan is that current holders (more than 10k+) will burn GET, mint OPN and then use the wormhole to get into Solana. 

Due to this the token is issued by the wormhole bridge. We cannot set the metadata at all (including the logo/bame). We have escalated this with wormhole but they do not provide a solution.

Due to this the token shows up 'poorly' in Solana DAPP frontends.  It was the understanding that addition to the list would mitigate the issue partly. It is expected that in time wormhole will improve this. Tokens as bridged in USDC via the wormhole do show a logo while their origin is the same.

**Review by Jymfletzfur — APPROVED** [review]

**Review by benlvb — APPROVED** [review]

**Pull request merged**
