### PR TITLE
Validate Bowti

### PR DESCRIPTION
**Pull request by BriceKensy**
# Validate [BOWTI](https://solscan.io/token/21exqQkiHsATKfEcGXt3Z4FhtJP6Lf36Cpk75ZSPrPBx)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/bowticoin/status/1785703407497396520
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by BriceKensy — COMMENTED** [review]
[x] Mint address: 21exqQkiHsATKfEcGXt3Z4FhtJP6Lf36Cpk75ZSPrPBx
[x] Symbol: BOWTI
[x] Token Decimals: 6
[x] Token icon: https://bafybeia7rvthzkgonzyrczp3umgnwealy3igjgtmsspnnl2d2wqyjehspy.ipfs.nftstorage.link
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by BriceKensy** [comment]
- [ ] Mint address: 21exqQkiHsATKfEcGXt3Z4FhtJP6Lf36Cpk75ZSPrPBx
- [ ] Symbol: BOWTI
- [ ] Token Decimals: 6
- [ ] Token icon: https://bafybeia7rvthzkgonzyrczp3umgnwealy3igjgtmsspnnl2d2wqyjehspy.ipfs.nftstorage.link
- [ ] On-chain metadata matches
- [ ] No duplication on Jupiter's strict list

**Comment by bowticoin** [comment]
- [x] Mint address: 21exqQkiHsATKfEcGXt3Z4FhtJP6Lf36Cpk75ZSPrPBx
- [x] Symbol: BOWTI
- [x] Token Decimals: 6
- [x] Token icon: https://bafybeia7rvthzkgonzyrczp3umgnwealy3igjgtmsspnnl2d2wqyjehspy.ipfs.nftstorage.link
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by Ritch-001** [comment]
- [x] Mint address: 21exqQkiHsATKfEcGXt3Z4FhtJP6Lf36Cpk75ZSPrPBx
- [x] Symbol: BOWTI
- [x] Token Decimals: 6
- [x] Token icon: https://bafybeia7rvthzkgonzyrczp3umgnwealy3igjgtmsspnnl2d2wqyjehspy.ipfs.nftstorage.link
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by ddony99** [comment]
- [x] Mint address: 21exqQkiHsATKfEcGXt3Z4FhtJP6Lf36Cpk75ZSPrPBx
- [x] Symbol: BOWTI
- [x] Token Decimals: 6
- [x] Token icon: https://bafybeia7rvthzkgonzyrczp3umgnwealy3igjgtmsspnnl2d2wqyjehspy.ipfs.nftstorage.link
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
