### PR TITLE
Validate VALKYRIE

### PR DESCRIPTION
**Pull request by SolanaValkyrie**
Mint address: 84KY3exPaKV3b49YowaW2E71DrVjYVLog9vdFXZYfokA Symbol: VALK
Token Decimals: 9
Token icon: https://arweave.net/qXcUvMYTFqiJEWosnydID47TRyAhiYpii-Y0n_FEtts On-chain metadata matches
No duplication on Jupiter's strict list

# Validate [{Token Symbol}](https://solscan.io/token/{mint_address})

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/{your_account}/status/{your_tweet_id}
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [ ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [ ] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [ ] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by Timoon21** [comment]
You need to add your token at the end of validated-tokens.csv file. And update Solscan & Twitter links.

Check other PR as example. Dont make changes on other files or dont create new file.
Please update your PR (or close it and open another one).

**Comment by SolanaValkyrie** [comment]
> You need to add your token at the end of validated-tokens.csv file. And update Solscan & Twitter links.
> 
> Check other PR as example. Dont make changes on other files or dont create new file. Please update your PR (or close it and open another one).

I've already made a change. is it true?

**Comment by dotonsol** [comment]
We confirms that the information provided is accurate.
- [ ] Mint address: 84KY3exPaKV3b49YowaW2E71DrVjYVLog9vdFXZYfokA
- [ ] Symbol: VALK
- [ ] Token Decimals: 9
- [ ] Token icon: https://arweave.net/qXcUvMYTFqiJEWosnydID47TRyAhiYpii-Y0n_FEtts
- [ ] On-chain metadata matches
- [ ] No duplication on Jupiter's strict list

**Comment by Timoon21** [comment]
duplicate #373

**Pull request closed without merging**
