### PR TITLE
DOGER

### PR DESCRIPTION
**Pull request by JohnGrubba**
# Validate [DOGER](https://solscan.io/token/HjzdHqdVKwNnvEA16BVRk5cNL6SUNMrXqGP1BGh8m7Hm)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/DogeRocketCoin/status/1773477823514104096
- Coingecko/ CMC URL (If available): Still working to get coin gecko set up for DOGER

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Woernycoin** [comment]
Woernycoin confirms that the information provided is accurate.

Mint address: HjzdHqdVKwNnvEA16BVRk5cNL6SUNMrXqGP1BGh8m7Hm
Symbol: DOGER
Token Decimals: 9
Token icon: https://raw.githubusercontent.com/JohnGrubba/JohnGrubba/main/DogeRocket.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by LeitnerLukas** [comment]
As an investor I can confirm that this information is correct:

* [x]   Mint address: HjzdHqdVKwNnvEA16BVRk5cNL6SUNMrXqGP1BGh8m7Hm
* [x]   Symbol: DOGER
* [x]   Token Decimals: 9
* [x]   Token icon: https://raw.githubusercontent.com/JohnGrubba/JohnGrubba/main/DogeRocket.png
* [x]   On-chain metadata matches
* [x]   No duplication on Jupiter's strict list

**Comment by SchlexanderOlz** [comment]
As a DOGER investor I confirm that the following information is correct:
* [x]   Mint address: HjzdHqdVKwNnvEA16BVRk5cNL6SUNMrXqGP1BGh8m7Hm
* [x]   Symbol: DOGER
* [x]   Token Decimals: 9
* [x]   Token icon: https://raw.githubusercontent.com/JohnGrubba/JohnGrubba/main/DogeRocket.png
* [x]   On-chain metadata matches
* [x]   No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
