### PR TITLE
Validate CHINGON

### PR DESCRIPTION
**Pull request by dpeim2029**
# Validate [CHINGON](https://solscan.io/token/BpFmEt9efz3ekb7g35DuWiywX3o9nfsRANX76D1g6fNk)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Mexico_chingon/status/1787199701420519846
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/mexico-chingon/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by dpeim2029** [comment]
Hola amigos de Jupiter 👋
We are a Mexican community learning crypto/blockchain by educating and doing, hence we funded publicly on a Fairsale CHINGON.
There has been tokens trying to impersonate $CHINGON putting our community at risk.
Would you be so kind to validate us?

**Comment by dpeim2029** [comment]
Just got listed on CMC if that helps: https://coinmarketcap.com/currencies/mexico-chingon/

**Comment by Jymfletzfur** [comment]
please come into discord

**Comment by Jymfletzfur** [comment]
can you use the image in your metadata

https://photos.pinksale.finance/file/pinksale-logo-upload/1713555096483-cdead6d4759893fd0452f1938b40f44f.png

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
