### PR TITLE
Validate HXD

### PR DESCRIPTION
**Pull request by honeylanddev**
# Validate [HXD](https://solscan.io/token/3dgCCb15HMQSA4Pn3Tfii5vRk7aRqTH95LJjxzsG2Mug)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/PlayHoneyland/status/1724846833019576712
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/honeyland/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by Timoon21** [comment]
Hey, This is a community validation. Try to get support, here on Github, twitter or on the Jupiter discord (#community-address-validation channel). Thx.

**Comment by meijiao** [comment]
Closing --- please reopen when you have some community support on the tweets. You can try Jupiter discord, or other communities that you are in.

**Comment by honeylanddev** [comment]
Hey, we posted another tweet that shows community support. Is it possible to reopen this pull request?
Thanks

**Comment by Timoon21** [comment]
> Hey, we posted another tweet that shows community support. Is it possible to reopen this pull request? Thanks

Hey, got it. We will review again. Reopened.

**Review by Timoon21 — APPROVED** [review]

**Review by Timoon21 — APPROVED** [review]

**Pull request merged**
