### PR TITLE
MISHOCAT GO TO MOON - MGTM

### PR DESCRIPTION
**Pull request by MISHOCAT**
# Validate [MGTM](https://solscan.io/token/2TxJVRaFWV1DdBxLZrqBGR6VBP8WBE3sExAhCfU7NhrC)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/CatGoToMoon/status/1804287671470297306
- Coingecko/ CMC URL (If available): https://www.geckoterminal.com/solana/pools/5fCf1SMv2QU3taNrEgFJ757nVygjLAxrH3owNwmU6Em4

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by behroozrahmani** [comment]
I like this project and I know they are building a good community, they will bring quality of new people to Crypto market and they are really professional! Finger crossed!!

**Review by hoomanity — COMMENTED** [review]
I recently came across this meme coin project and I am thoroughly impressed by the quality and dedication shown by the development team. The codebase is well-structured and clean, demonstrating the use of best practices and clear documentation, which makes it easy to understand and contribute to. The team has maintained a high level of transparency by regularly updating the community through commits and discussions, building trust and showing their commitment to the project’s success. Additionally, the developers are highly active in the issues and pull requests sections, providing timely responses and solutions, which indicates their value for community input and collaboration. The project introduces some innovative features that set it apart from other meme coins, making it an exciting project to follow. Given the current progress and roadmap, I believe this project has significant potential and can achieve great success in the meme coin space. Overall, I am highly optimistic about this project and look forward to its future developments. Keep up the great work!

**Review by BIJAXI — COMMENTED** [review]
I know this new Cryptocurrency and Im confident that this Project will be one of the top notch projects on Solana Blockchain and In crypto market. 
This is truly an innovative and positive project and the developers are amazingly working on all transparencies that they can offer to the community.
Their team are working on the pull request and community needs and wants to stay sustainable in this industry and develop the best practices to be able to deliver the milestones of the project. 
Ive been witnessing that the Developers have been working hard day by day to deliver their promises and Since their launch , the number of holders and community are growing organically and reasonably.
The project is based in Australia which gives the owners and developers the power to utilise the latest technologies and leverage the assistance of the huge population of crypto enthusiasts in Australia and all over the world.
Welcome to the land of Crypto Mishocat and good luck of the best lucks! 
 **$MGTM GOT TO GO TO THE MOON SOON** 
Im a big fan 🚀LETs Go
Regards 
Bijax

**Comment by Jymfletzfur** [comment]
insufficient volume

**Comment by behroozrahmani** [comment]
Hi there! 
How can they get volume with the warning sign?? They have 3 pairs and volume spread in 3 different pool! It seems you didn’t check it properly! 
Sent from Yahoo Mail for iPhone


On Sunday, June 23, 2024, 8:07 AM, Jymfletzfur ***@***.***> wrote:




Closed #4644.

**Pull request closed without merging**
