### PR TITLE
VALIDATE DVINCI

### PR DESCRIPTION
**Pull request by TraderGucc**
# Validate [DVINCI](https://solscan.io/token/5jFJCvNgg8ytGWBygoquaUC6bMZyr7C5jmGHECBzrxR5)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/DvinciCTO/status/1797007979629162828
- Coingecko/ CMC URL (If available): CG applied

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Httoco — COMMENTED** [review]
X] Mint address: 5jFJCvNgg8ytGWBygoquaUC6bMZyr7C5jmGHECBzrxR5
[X] Symbol: DVINCI
[X] Token Decimals: 6
[X] Token icon: https://bafkreihbx7trnvsdgd5gi7gzldasjcimedtnmuqpnhgen2c6vkxw44u7ky.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by eli2xf — COMMENTED** [review]
X] Mint address: 5jFJCvNgg8ytGWBygoquaUC6bMZyr7C5jmGHECBzrxR5
[X] Symbol: DVINCI
[X] Token Decimals: 6
[X] Token icon: https://bafkreihbx7trnvsdgd5gi7gzldasjcimedtnmuqpnhgen2c6vkxw44u7ky.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by Lafi41912 — COMMENTED** [review]
X] Mint address: 5jFJCvNgg8ytGWBygoquaUC6bMZyr7C5jmGHECBzrxR5
[X] Symbol: DVINCI
[X] Token Decimals: 6
[X] Token icon: https://bafkreihbx7trnvsdgd5gi7gzldasjcimedtnmuqpnhgen2c6vkxw44u7ky.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Comment by ARAGOVS** [comment]
X] Mint address: 5jFJCvNgg8ytGWBygoquaUC6bMZyr7C5jmGHECBzrxR5
[X] Symbol: DVINCI
[X] Token Decimals: 6
[X] Token icon: https://bafkreihbx7trnvsdgd5gi7gzldasjcimedtnmuqpnhgen2c6vkxw44u7ky.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Comment by Hassan1278** [comment]
X] Mint address: 5jFJCvNgg8ytGWBygoquaUC6bMZyr7C5jmGHECBzrxR5
[X] Symbol: DVINCI
[X] Token Decimals: 6
[X] Token icon: https://bafkreihbx7trnvsdgd5gi7gzldasjcimedtnmuqpnhgen2c6vkxw44u7ky.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Comment by JCJCJC92** [comment]
X] Mint address: 5jFJCvNgg8ytGWBygoquaUC6bMZyr7C5jmGHECBzrxR5
[X] Symbol: DVINCI
[X] Token Decimals: 6
[X] Token icon: https://bafkreihbx7trnvsdgd5gi7gzldasjcimedtnmuqpnhgen2c6vkxw44u7ky.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by JCJCJC92 — COMMENTED** [review]
X] Mint address: 5jFJCvNgg8ytGWBygoquaUC6bMZyr7C5jmGHECBzrxR5
[X] Symbol: DVINCI
[X] Token Decimals: 6
[X] Token icon: https://bafkreihbx7trnvsdgd5gi7gzldasjcimedtnmuqpnhgen2c6vkxw44u7ky.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by JCJCJC92 — COMMENTED** [review]
X] Mint address: 5jFJCvNgg8ytGWBygoquaUC6bMZyr7C5jmGHECBzrxR5
[X] Symbol: DVINCI
[X] Token Decimals: 6
[X] Token icon: https://bafkreihbx7trnvsdgd5gi7gzldasjcimedtnmuqpnhgen2c6vkxw44u7ky.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Comment by Cryptomate9** [comment]
X] Mint address: 5jFJCvNgg8ytGWBygoquaUC6bMZyr7C5jmGHECBzrxR5
[X] Symbol: DVINCI
[X] Token Decimals: 6
[X] Token icon: https://bafkreihbx7trnvsdgd5gi7gzldasjcimedtnmuqpnhgen2c6vkxw44u7ky.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Comment by Shaggybtc** [comment]
X] Mint address: 5jFJCvNgg8ytGWBygoquaUC6bMZyr7C5jmGHECBzrxR5
[X] Symbol: DVINCI
[X] Token Decimals: 6
[X] Token icon: https://bafkreihbx7trnvsdgd5gi7gzldasjcimedtnmuqpnhgen2c6vkxw44u7ky.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by yash02500 — COMMENTED** [review]
X] Mint address: 5jFJCvNgg8ytGWBygoquaUC6bMZyr7C5jmGHECBzrxR5
[X] Symbol: DVINCI
[X] Token Decimals: 6
[X] Token icon: https://bafkreihbx7trnvsdgd5gi7gzldasjcimedtnmuqpnhgen2c6vkxw44u7ky.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Comment by 9yoi** [comment]
Merged here: https://github.com/jup-ag/token-list/pull/4163

**Pull request closed without merging**
