### PR TITLE
ADD Tyson't Tiger (TTIGER) to Strict List

### PR DESCRIPTION
**Pull request by TysonsTiger**
I tried doing this in the Strict List page but it kept failing saying I am not a collaborator. Please help if this is again not right

# Validate [TTIGER](https://solscan.io/token/H1C5T6BnmbkBacLCaYoczxFQ7qB5Ggx85hJFAL2HHNBj)

## Attestations (Please provide links):
https://x.com/tysonstiger69/status/1780038194995572966
https://twitter.com/tysonstiger69/with_replies
@tysontiger69 (main)
@coachbarry18 (Dev/Founder)

Telegram https://t.me/TTIGERMikeTyson

CG Application in and approval pending
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [ X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X ] My change matches the format in the file (no spaces between fields).
- [X ] My token is already live and trading on Jupiter.
- [ ] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

Screenshot 2024-04-15 225126
support1

### CODE REVIEW

**Comment by TysonsTiger** [comment]
I am doing this to add our token to the Jupiter Strict List - Our token was listed through Raydium yesterday and was trading on Jupiter as well, but it would help people find it better and add credibility if we could get it on the strict list. I added Telegram invite link and Tweet and tweeter profiles as well. There is also a website at https://miketysonstiger.ca but it may be down for maintenance if you check. It is working now but a team member is tweaking it tonight.

**Comment by PandaBlobs** [comment]
Can't wait for this to list! 🚀

**Comment by Slade0579** [comment]
$TTIGER ready for takeoff!!

**Comment by Jymfletzfur** [comment]
this does not submit an entry to the csv

It just posts the template again

**Comment by TysonsTiger** [comment]
How exactly do I merge this onto the correct main list so I didn't do all of this for nothing. Newb here.

**Pull request closed without merging**
