### PR TITLE
Nansee Peloonsi $INSIDER

### PR DESCRIPTION
**Pull request by shep4**
# Validate [INSIDER](https://solscan.io/token/G9rDx2ZGuKZGGiYkShNBJsEXcsxmRsEtKyHxrqdLxPKn)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/nanseepeloonsi/status/1770924293230104980?s=20
- Coingecko/ CMC URL (If available):
- https://www.geckoterminal.com/solana/pools/FnzCdgwkCxZXoHjSqP5VGNBJT9rjqcSGPiduaScV1mE8?utm_source=coingecko&utm_medium=referral&utm_campaign=searchresults

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by NanseePeloonsi — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

**Review by Jpark23 — COMMENTED** [review]
Everything looks good!

**Review by Jpark23 — COMMENTED** [review]
Looks good!

**Review by NanseePeloonsi — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

**Review by Jpark23 — COMMENTED** [review]
Looks good!

**Review by NanseePeloonsi — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

**Review by NanseePeloonsi — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

**Review by NanseePeloonsi — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

**Review by Jpark23 — COMMENTED** [review]
Great

**Comment by onidus02** [comment]
Can validate that CA is: G9rDx2ZGuKZGGiYkShNBJsEXcsxmRsEtKyHxrqdLxPKn

Can validate tweet from Official Nansee Twitter @ Jupiter Exchange: https://x.com/nanseepeloonsi/status/1770924293230104980?s=20

Everything looks good

**Review by onidus02 — COMMENTED** [review]
As stated above, this looks good.

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
