### PR TITLE
Validate GIGA

### PR DESCRIPTION
**Pull request by lakshay35**
# Validate [GIGA](https://solscan.io/token/63LfDmNb3MQ8mw9MtZ2To9bEA2M71kZUUGq5tiJxcqj9)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/LakshaySharm/status/1750016728443084958?s=20 and https://x.com/GIGACHAD_meme/status/1750020111157608703?s=20
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/gigachad-2

## Validation (Please check off boxes):
- [&check;] The metadata provided in the PR matches what is on-chain (Mandatory)
- [&check;] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [&check;] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [&check;] My change matches the format in the file (no spaces between fields).
- [&check;] My token is already live and trading on Jupiter.
- [&check;] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [&check;] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by lakshay35** [comment]
@9yoi we'd love to get your attention on this :)

**Comment by lakshay35** [comment]
@robbestad  can you approved this one?

**Comment by lakshay35** [comment]
> > @robbestad can you review this one?
> 
> Yep, confirmed!
> 
> All boxes ticked off.
> 
> ✅ The metadata provided in the PR matches what is on-chain https://xray.helius.xyz/token/63LfDmNb3MQ8mw9MtZ2To9bEA2M71kZUUGq5tiJxcqj9?network=mainnet ✅ Symbol: GIGA. Does not duplicate the symbol of another token on Jupiter's strict list ✅ Is Listed on Coingecko ✅ Token is already live and trading on Jupiter. ✅ Community support ✅ Token Decimals: 5
> 
> _FYI @lakshay35 the solscan link in the subject includes a space so it's invalid_
Fixed. When can we merge this pr @robbestad?

**Comment by lakshay35** [comment]
@Timoon21 can you review this pr ser?

**Comment by robbestad** [comment]
> Fixed the title @robbestad. When can we merge this?
> 
> > > @robbestad can you review this one?
> > 
> > 
> > Yep, confirmed!
> > All boxes ticked off.
> > ✅ The metadata provided in the PR matches what is on-chain https://xray.helius.xyz/token/63LfDmNb3MQ8mw9MtZ2To9bEA2M71kZUUGq5tiJxcqj9?network=mainnet ✅ Symbol: GIGA. Does not duplicate the symbol of another token on Jupiter's strict list ✅ Is Listed on Coingecko ✅ Token is already live and trading on Jupiter. ✅ Community support ✅ Token Decimals: 5
> > _FYI @lakshay35 the solscan link in the subject includes a space so it's invalid_
> > Fixed. When can we merge this pr @robbestad?

I don't have this power :) I just review now and then

**Comment by lakshay35** [comment]
Hey @siong1987 @9yoi @Timoon21 I'm kindly following up on this PR. I made sure of everything. @robbestad validated it as well. Would appreciate if we could get this reviewed and merged

**Comment by m1kobu** [comment]
LFG! Giga deserves to be validated! Can we get this done for the Chads?

**Comment by lakshay35** [comment]
@benlvb can we get an approval?

**Comment by m1kobu** [comment]
Hey @robbestad! I know it’s probably a “giga busy” time for you guys at JUP, but if possible, could we please expedite the validation process so we can utilize other ecosystem tools that rely on this being processed?

if there is anything we as a community can do to speed up the decision making process, do let us know so we can take charge. Assuming most community members do not, or don’t know how to use github, it’s hard to push them to come comment however if you look at the twitter, or even hop in the telegram, you will realize how active the community is.

Thank you! 

Cheers!

**Comment by m1kobu** [comment]
> > Fixed the title @robbestad. When can we merge this?
> > > > @robbestad can you review this one?
> > > 
> > > 
> > > Yep, confirmed!
> > > All boxes ticked off.
> > > ✅ The metadata provided in the PR matches what is on-chain https://xray.helius.xyz/token/63LfDmNb3MQ8mw9MtZ2To9bEA2M71kZUUGq5tiJxcqj9?network=mainnet ✅ Symbol: GIGA. Does not duplicate the symbol of another token on Jupiter's strict list ✅ Is Listed on Coingecko ✅ Token is already live and trading on Jupiter. ✅ Community support ✅ Token Decimals: 5
> > > _FYI @lakshay35 the solscan link in the subject includes a space so it's invalid_
> > > Fixed. When can we merge this pr @robbestad?
> 
> I don't have this power :) I just review now and then

There were 2 x Dynamic LPs added to Meteora for GIGA/USDC and GIGA/SOL.

Read in instructions this helps with validation. Each pool is a 500$ pair.

https://app.meteora.ag/pools/Gmhwvg6xvfbDxjqXhZJobT8zavNZwV8Fw1hrn6zjrHnS

https://app.meteora.ag/pools/DRL2jTqrBH7F4aAzFWpuv21jYRt9i3LnSGo4nm1h9DN

Hope this helps.

**Pull request closed without merging**
