### PR TITLE
VALIDATE HUNTBODEN

### PR DESCRIPTION
**Pull request by Aybryan5**
# Validate [HuntBoden](https://solscan.io/token/22513u2QwiY6xaJn7nVFWGKy3aBdw6WfZsRPW2RRtCKj/)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support:  https://x.com/h0ynu/status/1782484658728419516?s=46&t=-UvgBbacBpJFr3fCtB1Spg

Community highly support HuntBoden

- Coingecko/ CMC URL (If available): 
 Here is our coingecko url : 
https://www.coingecko.com/en/coins/hunter-boden

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Jymfletzfur — APPROVED** [review]

**Comment by Jymfletzfur** [comment]
is that your on chain image in the metadata that you submitted?

**Comment by Aybryan5** [comment]
> is that your on chain image in the metadata that you submitted?

Yeah it’s just that the image have no background so it depends on the website

**Comment by Jymfletzfur** [comment]
can you submit it with the image link in your metadata pls

**Comment by Aybryan5** [comment]
> can you submit it with the image link in your metadata pls

Did it

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
