### PR TITLE
Add Olympic Games Token (OGT) to strict list

### PR DESCRIPTION
**Pull request by Olympic-CM**
# Validate [OGT](https://solscan.io/token/DHbCBJVWGTHpiV4WNZ9AajvNkEWKRdu2mmJXYjQj847t)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Olympics_Solana/status/1784518550343897574
- Coingecko/ CMC URL (If available): Still working to get coin gecko set up for OGT

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by vitrola410** [comment]
* [x]    Mint address: DHbCBJVWGTHpiV4WNZ9AajvNkEWKRdu2mmJXYjQj847t
* [x]    Symbol: OGT
* [x]    Token Decimals: 9
* [x]    On-chain metadata matches
* [x]    No duplication on Jupiter's strict list

**Comment by Gimba4u** [comment]
> # Validate [OGT](https://solscan.io/token/DHbCBJVWGTHpiV4WNZ9AajvNkEWKRdu2mmJXYjQj847t)
> ## Attestations (Please provide links):
> * Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Olympics_Solana/status/1784518550343897574
> * Coingecko/ CMC URL (If available): Still working to get coin gecko set up for OGT
> 
> ## Validation (Please check off boxes):
> * [x]  The metadata provided in the PR matches what is on-chain (Mandatory)
> * [x]  Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
> * [ ]  Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)
> 
> ## Acknowledgement (Please check off boxes)
> * [x]  My change matches the format in the file (no spaces between fields).
> * [x]  My token is already live and trading on Jupiter.
> * [x]  !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
> * [x]  Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

OGT is one of the best Solana meme coins community I have ever come across in the crypto space. These guys are simply amazing

**Comment by Gimba4u** [comment]
> # Validate [OGT](https://solscan.io/token/DHbCBJVWGTHpiV4WNZ9AajvNkEWKRdu2mmJXYjQj847t)
> ## Attestations (Please provide links):
> * Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Olympics_Solana/status/1784518550343897574
> * Coingecko/ CMC URL (If available): Still working to get coin gecko set up for OGT
> 
> ## Validation (Please check off boxes):
> * [x]  The metadata provided in the PR matches what is on-chain (Mandatory)
> * [x]  Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
> * [ ]  Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)
> 
> ## Acknowledgement (Please check off boxes)
> * [x]  My change matches the format in the file (no spaces between fields).
> * [x]  My token is already live and trading on Jupiter.
> * [x]  !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
> * [x]  Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

* [x]    Mint address: DHbCBJVWGTHpiV4WNZ9AajvNkEWKRdu2mmJXYjQj847t
* [x]    Symbol: OGT
* [x]    Token Decimals: 9
* [x]    On-chain metadata matches
* [x]    No duplication on Jupiter's strict list

**Comment by Gimba4u** [comment]
* [x]    Mint address: DHbCBJVWGTHpiV4WNZ9AajvNkEWKRdu2mmJXYjQj847t
* [x]    Symbol: OGT
* [x]    Token Decimals: 9
* [x]    On-chain metadata matches
* [x]    No duplication on Jupiter's strict list

**Comment by Bmwm3gt1** [comment]
I have been with OGT almost from the start and they have ever only shown commitment and dedication to this project, I have been in countless crypto projects and feel that this one is genuine and unique.

**Comment by Gimba4u** [comment]
> # Validate [OGT](https://solscan.io/token/DHbCBJVWGTHpiV4WNZ9AajvNkEWKRdu2mmJXYjQj847t)
> ## Attestations (Please provide links):
> * Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Olympics_Solana/status/1784518550343897574
> * Coingecko/ CMC URL (If available): Still working to get coin gecko set up for OGT
> 
> ## Validation (Please check off boxes):
> * [x]  The metadata provided in the PR matches what is on-chain (Mandatory)
> * [x]  Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
> * [ ]  Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)
> 
> ## Acknowledgement (Please check off boxes)
> * [x]  My change matches the format in the file (no spaces between fields).
> * [x]  My token is already live and trading on Jupiter.
> * [x]  !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
> * [x]  Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

* [x]    Mint address: DHbCBJVWGTHpiV4WNZ9AajvNkEWKRdu2mmJXYjQj847t
* [x]    Symbol: OGT
* [x]    Token Decimals: 9
* [x]    On-chain metadata matches
* [x]    No duplication on Jupiter's strict list

**Comment by Gimba4u** [comment]
* [x]    Mint address: DHbCBJVWGTHpiV4WNZ9AajvNkEWKRdu2mmJXYjQj847t
* [x]    Symbol: OGT
* [x]    Token Decimals: 9
* [x]    On-chain metadata matches
* [x]    No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
PR inappropriately attempts to alter files other than the CSV

**Comment by Olympic-CM** [comment]
> PR inappropriately attempts to alter files other than the CSV
Hello, please can you explain me what does that exactly mean ? What do we have to change concretely  @Jymfletzfur

**Pull request closed without merging**
