### PR TITLE
Validate $COSHI

### PR DESCRIPTION
**Pull request by gorganrares**
# Validate Coshi (https://solscan.io/token/FMG9mNVazePvGtAY1WESUmY9j3LvhVzmkQsaucwRy8EB)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: (https://twitter.com/CattoshiToken/status/1630909498754834433)
- Coingecko/ CMC URL (If available): not available

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will de delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] I did not modify unrelated code.
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and will get community support on Twitter.

### CODE REVIEW

**Comment by Timoon21** [comment]
Please get community support on Discord/Twitter, or I'll close the PR.

**Comment by gorganrares** [comment]
Can you explain more please?

**Comment by Timoon21** [comment]
Check out: https://github.com/jup-ag/token-list#community-driven-validation-into-strict-list

You need community support for your PR

**Comment by gorganrares** [comment]
Hi, You can also share about your project in our [token-validation discord channel](https://discord.gg/SJmyW8TG). This discord invite link is invalid. Can you give a new one?

**Comment by gorganrares** [comment]
We make a post now

https://twitter.com/CattoshiToken/status/1630909498754834433

**Comment by Timoon21** [comment]
> Hi, You can also share about your project in our [token-validation discord channel](https://discord.gg/SJmyW8TG). This discord invite link is invalid. Can you give me a new one?

We will update the link later. Thx for reporting.
You can use this one : https://discord.gg/jup #community-validation channel.

**Comment by gorganrares** [comment]
Hi, how's going?

**Comment by gorganrares** [comment]
https://twitter.com/devanwonders/status/1631760061273104391

**Comment by LJQZZZ123** [comment]
Image address doesn't match on-chain metadata, which should be:
https://arweave.net/k5GPPYbAhUhJBc36Cjk_iVqhQfA63Kn01A3TMv65P04

**Comment by gorganrares** [comment]
Hi, I just updated the image url

**Comment by Timoon21** [comment]
> Hi, I just updated the image url

Please edit again. When you have merge, the old url was restored.

**Comment by gorganrares** [comment]
Done

**Review by meijiao — APPROVED** [review]

**Pull request merged**
