### PR TITLE
Validate Gummy

### PR DESCRIPTION
**Pull request by ADHDBanter**
# Validate [GUMMY](https://solscan.io/token/H7bTHGb5Cvo5fGe5jBDNDPUv8KykQnzyZA3qZ8sH7yxw)

## Attestations (Please provide links):
- https://x.com/gummyonsolana/status/1782070655082487928 - Gummy account tags @jupiterexchange to confirm CA 
- https://x.com/gummyonsolana/status/1781774599769702532 - Gummy account asserts CA on launch
- https://x.com/cryptomanran/status/1781775582847529425 - Public figure and project advisor attest official gummy account and CA
- https://x.com/frankherrerar/status/1782056244800278530 - Community Support
- https://x.com/mrgibenny/status/1781984553747251659 - More Community support
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/gummy

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
onchain name is GUMMY not Gummy

**Comment by ADHDBanter** [comment]
@Jymfletzfur true, must I create a new pull request or can I edit and force push?

**Comment by Jymfletzfur** [comment]
No, you can amend it

**Comment by Gespot666** [comment]
I am a community member and I attest the project is legit:

[x] Mint Address: H7bTHGb5Cvo5fGe5jBDNDPUv8KykQnzyZA3qZ8sH7yxw
[x]Symbol: GUMMY
[x]Token Decimals: 9 
[x]Token icon: https://arweave.net/KETOQzT7wT0Mzq4ObkXceUV_6Rq4Jxpp7-RpodA1BgE 
[x]On-chain Metadata Matches
[x]No duplication on Jupiter’s Strict List

**Comment by AJMourot** [comment]
I am a community member and I can attest to this post and projects legitimacy.

[x] Mint Address: H7bTHGb5Cvo5fGe5jBDNDPUv8KykQnzyZA3qZ8sH7yxw
[x]Symbol: GUMMY
[x]Token Decimals: 9 
[x]Token icon: https://arweave.net/KETOQzT7wT0Mzq4ObkXceUV_6Rq4Jxpp7-RpodA1BgE 
[x]On-chain Metadata Matches
[x]No duplication on Jupiter’s Strict List

**Comment by Jymfletzfur** [comment]
this submission is now unnecessary, token is on the list

**Pull request closed without merging**
