### PR TITLE
Validate APU

### PR DESCRIPTION
**Pull request by pg686**
# Validate [APU](https://solscan.io/token/ECutGg12PNhqhkvnH1s1FcuXgCDzKDNhSf5aLtANioR7)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/ApuSolFrens/status/1792999966660554948
- Coingecko/ CMC URL (If available): N/A

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by mewh0** [comment]
Approving that the info below is correct

 [x] Mint address: ECutGg12PNhqhkvnH1s1FcuXgCDzKDNhSf5aLtANioR7
 [x] Symbol: APU
 [x] Token Decimals: 6
 [x] Token icon: https://raw.githubusercontent.com/mewh0/apu_logo/main/apu%20pic%20400x400.jpg
 [x] On-chain metadata matches
 [x] No duplication on Jupiter's strict list

**Comment by SatoshiWagmito** [comment]
wfm 🫶 
 
 [x] Mint address: ECutGg12PNhqhkvnH1s1FcuXgCDzKDNhSf5aLtANioR7
 [x] Symbol: APU
 [x] Token Decimals: 6
 [x] Token icon: https://raw.githubusercontent.com/mewh0/apu_logo/main/apu%20pic%20400x400.jpg
 [x] On-chain metadata matches
 [x] No duplication on Jupiter's strict list

**Comment by boyanq** [comment]
supporting this is the right one

[x] Mint address: ECutGg12PNhqhkvnH1s1FcuXgCDzKDNhSf5aLtANioR7
[x] Symbol: APU
[x] Token Decimals: 6
[x] Token icon: https://raw.githubusercontent.com/mewh0/apu_logo/main/apu%20pic%20400x400.jpg
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
please come into discord

**Comment by Jymfletzfur** [comment]
can you use this as your image file

https://soldeployer.mypinata.cloud/ipfs/QmVb8aYRjzvr7hRkKLD3L3mTfDo41dECpPMpa1pzcqhD2L

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
