### PR TITLE
WOJAK

### PR DESCRIPTION
**Pull request by Dh1988**
# Validate [WOJAK](https://solscan.io/token/MINT_ADDRES_HERE)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](http://x.com/Wojak_Community/status1761141188361375746?s=20) and showing community support: https://twitter.com/Wojak_Community/status/1761141188361375746?s=20
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [ x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [ x] My change matches the format in the file (no spaces between fields).
- [ x] My token is already live and trading on Jupiter.
- [ x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x ] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Dh1988** [comment]
Changes are fine. Please go ahead with the pull request.

**Review by Lonelyboycrypto — COMMENTED** [review]
Might need to update top change

**Review by Dh1988 — COMMENTED** [review]
Edited

**Review by Lonelyboycrypto — COMMENTED** [review]
Changes look good now

**Comment by firstrank** [comment]
I support the pull request

**Review by firstrank — COMMENTED** [review]
I support this.

**Comment by Jymfletzfur** [comment]
On chain name and ticker is Wojak

Submission is WOJAK

please amend

**Review by Lonelyboycrypto — COMMENTED** [review]
The ticker capitalization has been amended as per Jupiter's request.

**Review by firstrank — COMMENTED** [review]
Ticker has been updated to be lower case.  Please merge request.

**Comment by Dh1988** [comment]
Hi I believe all conflicts are resolved the markers are all removed (deleted)

**Review by firstrank — COMMENTED** [review]
Looks good.

**Review by 9yoi — APPROVED** [review]

**Review by Jymfletzfur — APPROVED** [review]

**Comment by Dh1988** [comment]
Seems to be an issue with the link supplied for the logo image is it possible to send link and update or need to do a new pull request? 

Thank you for the assistance also

**Comment by Dh1988** [comment]
https://raw.githubusercontent.com/Lonelyboycrypto/Wojak/main/wojak-logo.png

this is the link I would like to use the other seems to have an issue with it

**Pull request merged**
