### PR TITLE
Add Bozo Coin - Update validated-tokens.csv

### PR DESCRIPTION
**Pull request by bozocode**
# Validate [BOZO](https://solscan.io/token/{EJPtJEDogxzDbvM8qvAsqYbLmPj5n1vQeqoAzj9Yfv3q})

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/BozoSPL20/status/1743273574356377888
- Coingecko - https://www.coingecko.com/en/coins/bozo-hybrid
- GeckoTerminal - https://www.geckoterminal.com/solana/pools/5zGFqaUYYtm7GMz9sD5kBhc294SRLA4hXfzwaHdM3kXo

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by bozocode** [comment]
Hi @Timoon21, 

I hope you are having a great weekend. When you have time can you kindly take a look at this PR. Links for social proof below. Any concerns and more information required, please comment and I will try to add/source it. Thank you 

Social proof - Tweet by a known account - https://twitter.com/PARABOLIT/status/1743939102641135993?s=20
Magic Eden listing and organic growth - https://magiceden.io/marketplace/bozo_
BirdEye trading  - https://birdeye.so/token/EJPtJEDogxzDbvM8qvAsqYbLmPj5n1vQeqoAzj9Yfv3q?chain=solana

**Comment by NotoriousPyro** [comment]
Scam

**Comment by bozocode** [comment]
Hi @Timoon21.

PS: Coingecko listing link added

**Comment by Jymfletzfur** [comment]
already added

**Pull request closed without merging**
