### PR TITLE
validate Phauntem

### PR DESCRIPTION
**Pull request by sebamatusr**
# Validate [PHAUNTEM](https://solscan.io/token/5veVHPNDsmSxDW4Abpb368wLHpo32LP3fqhfJHnkSSwo)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/phaunteum69/status/1766829826143297960
- Coingecko/ CMC URL (If available): [CMC](https://coinmarketcap.com/currencies/phauntem) - [Coingecko](https://www.coingecko.com/en/coins/phauntem)

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by err0r403 — COMMENTED** [review]
I certify that the data is correct.
- [x]  Mint address: 5veVHPNDsmSxDW4Abpb368wLHpo32LP3fqhfJHnkSSwo
- [x]  Symbol: PHAUNTEM
- [x]  Token Decimals: 9
- [x]  Token icon: https://cdn.discordapp.com/attachments/1205497765749067807/1211620777426690128/Phauntem_3.png?ex=65eedcc8&is=65dc67c8&hm=e95bce28bc2d45c0f2bab47b250b7fab4d8abe3e04737c4aefe0ad1071fc98dc&
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by gmunozc** [comment]
I certify that the data is correct.

**Comment by braininteractive** [comment]
I certify that the data is correct.

 Mint address: 5veVHPNDsmSxDW4Abpb368wLHpo32LP3fqhfJHnkSSwo
 Symbol: PHAUNTEM
 Token Decimals: 9
 Token icon: https://cdn.discordapp.com/attachments/1205497765749067807/1211620777426690128/Phauntem_3.png?ex=65eedcc8&is=65dc67c8&hm=e95bce28bc2d45c0f2bab47b250b7fab4d8abe3e04737c4aefe0ad1071fc98dc&
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Comment by 9yoi** [comment]
Unable to load the token image -- please use an image host

**Review by 9yoi — DISMISSED** [review]
Unable to load token image -- please use an image host. it should also match what's in your onchain metadata

**Comment by sebamatusr** [comment]
> Unable to load token image -- please use an image host. it should also match what's in your onchain metadata

Its a community takeover, dev is not around anymore so we cant change the project metadata, the url in this PR matches the one in the metadata

**Comment by sebamatusr** [comment]
> Unable to load token image -- please use an image host. it should also match what's in your onchain metadata

is there a way we can fix it without dev? He renounced the project, I guess he still has authority to change token metadata, but its a long shot, we as a community took over the project and are trying to build on top of it.

**Comment by 9yoi** [comment]
> > Unable to load token image -- please use an image host. it should also match what's in your onchain metadata
> 
> is there a way we can fix it without dev? He renounced the project, I guess he still has authority to change token metadata, but its a long shot, we as a community took over the project and are trying to build on top of it.

Ideally your icon should match what's in your onchain metadata.
If not, just host the icon somewhere else and give us the link in your PR. Right now this link does not load https://cdn.discordapp.com/attachments/1205497765749067807/1211620777426690128/Phauntem_3.png?ex=65eedcc8&is=65dc67c8&hm=e95bce28bc2d45c0f2bab47b250b7fab4d8abe3e04737c4aefe0ad1071fc98dc&

**Comment by sebamatusr** [comment]
> > > Unable to load token image -- please use an image host. it should also match what's in your onchain metadata
> > 
> > 
> > is there a way we can fix it without dev? He renounced the project, I guess he still has authority to change token metadata, but its a long shot, we as a community took over the project and are trying to build on top of it.
> 
> Ideally your icon should match what's in your onchain metadata. If not, just host the icon somewhere else and give us the link in your PR. Right now this link does not load https://cdn.discordapp.com/attachments/1205497765749067807/1211620777426690128/Phauntem_3.png?ex=65eedcc8&is=65dc67c8&hm=e95bce28bc2d45c0f2bab47b250b7fab4d8abe3e04737c4aefe0ad1071fc98dc&

I got in touch with the original dev, he said he didn't have the deployer keys anymore so he couldn't update the metadata. 
I changed the PR image link to a new one, I used ipfs as a host:

https://d391b93f5f62d9c15f67142e43841acc.ipfscdn.io/ipfs/bafybeih6j3sy74rfxeoh3aywsuda4bkzrp5ihz4jz6x23cd26uwonermku/phauntem.jpg

**Review by Jymfletzfur — APPROVED** [review]

**Review by 0xSoju2 — APPROVED** [review]

**Pull request merged**
