### PR TITLE
Validate Wolf on Solana

### PR DESCRIPTION
**Pull request by Wolfonsolana**
# Validate [$WOLF](https://solscan.io/token/3EagcZ66c8z2hZdFSd5412yEW9U48AAb9P6d1yhjuGmY)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/WolfOnSolana/status/172998624838986155a1?t=PweP7xK_Ft1vYwGI8WsQfw
- Coingecko/ CMC URL (If available): 

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by Wolfonsolana** [comment]
Please note that [#282](https://github.com/jup-ag/token-list/pull/282) is "WOLF SOLANA" and the token in this PR is "Wolf on Solana". 
The ticker name WOLF was earlier declined ([previous PR](https://github.com/jup-ag/token-list/pull/450) ) on the basis that users might find it difficult to differentiate both tokens.  The team has decided to proceed with $WOLF.


We also believe the distinctively different token images (clear difference in colour themes) would make it easy to differentiate both tokens. 
- [WOLF SOLANA picture](https://x2tutvgpw4mlutrk4mfgjnonnxp2q5gc6mnllxmblcwpgbeew7rq.arweave.net/vqdJ1M-3GLpOKuMKZLXNbd-odMLzGrXdgVis8wSEt-M) <== The token currently on the strict list
- [Wolf on Solana picture](https://i.ibb.co/CQPd6FL/20231123-211619.png) <= Wolf on Solana

**Comment by Timoon21** [comment]
Hey @Wolfonsolana 
Thanks for the updated metadata.

"Hmm...this page doesn’t exist. Try searching for something else." said the twitter link.
Can you update the link?

**Comment by Timoon21** [comment]
Btw, on chain it's still "WOLF" not "$WOLF". Please update the PR or the on-chain metadata.
Symbol on both should matches.

**Comment by Jymfletzfur** [comment]
Insufficient Volume

**Pull request closed without merging**
