### PR TITLE
Validate GrowSol

### PR DESCRIPTION
**Pull request by GrowSolOfficial**
# Validate [$GRW](https://solscan.io/token/FPymkKgpg1sLFbVao4JMk4ip8xb8C8uKqfMdARMobHaw)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/GrowSolOfficial/status/1766195155445448927
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by 4leaf88** [comment]
I can hereby attest that the provided information are accurate, and the token is valid. 
 
 Mint address: FPymkKgpg1sLFbVao4JMk4ip8xb8C8uKqfMdARMobHaw
 Symbol: $GRW
 Token Decimals: 9
 Token icon: https://bafybeiaf23s4jadgatgzrmad3u3ahic4wdpsgcubl4ka2a2mleuq7j4eya.ipfs.nftstorage.link/
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by WhaleWalllas** [comment]
I can hereby attest that the provided information are accurate, and the token is valid. 
 
 Mint address: FPymkKgpg1sLFbVao4JMk4ip8xb8C8uKqfMdARMobHaw
 Symbol: $GRW
 Token Decimals: 9
 Token icon: https://bafybeiaf23s4jadgatgzrmad3u3ahic4wdpsgcubl4ka2a2mleuq7j4eya.ipfs.nftstorage.link/
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by FakeJaw** [comment]
I can hereby attest that the provided information are accurate, and the token is valid. 
 
 Mint address: FPymkKgpg1sLFbVao4JMk4ip8xb8C8uKqfMdARMobHaw
 Symbol: $GRW
 Token Decimals: 9
 Token icon: https://bafybeiaf23s4jadgatgzrmad3u3ahic4wdpsgcubl4ka2a2mleuq7j4eya.ipfs.nftstorage.link/
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by Japarion** [comment]
I can hereby attest that the provided information are accurate, and the token is valid. 
 
 Mint address: FPymkKgpg1sLFbVao4JMk4ip8xb8C8uKqfMdARMobHaw
 Symbol: $GRW
 Token Decimals: 9
 Token icon: https://bafybeiaf23s4jadgatgzrmad3u3ahic4wdpsgcubl4ka2a2mleuq7j4eya.ipfs.nftstorage.link/
 On-chain metadata matches
 No duplication on Jupiter's strict list, thank you

**Comment by archman098** [comment]
I can hereby attest that the provided information are accurate, and the token is valid. 
 
 Mint address: FPymkKgpg1sLFbVao4JMk4ip8xb8C8uKqfMdARMobHaw
 Symbol: $GRW
 Token Decimals: 9
 Token icon: https://bafybeiaf23s4jadgatgzrmad3u3ahic4wdpsgcubl4ka2a2mleuq7j4eya.ipfs.nftstorage.link/
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by Kryptomayk** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: FPymkKgpg1sLFbVao4JMk4ip8xb8C8uKqfMdARMobHaw
Symbol: $GRW
Token Decimals: 9
Token icon: https://bafybeiaf23s4jadgatgzrmad3u3ahic4wdpsgcubl4ka2a2mleuq7j4eya.ipfs.nftstorage.link/
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by BisyoCrypto** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

**Comment by arra3nidad** [comment]
I can hereby attest that the provided information are accurate, and the token is valid. 
 
 Mint address: FPymkKgpg1sLFbVao4JMk4ip8xb8C8uKqfMdARMobHaw
 Symbol: $GRW
 Token Decimals: 9
 Token icon: https://bafybeiaf23s4jadgatgzrmad3u3ahic4wdpsgcubl4ka2a2mleuq7j4eya.ipfs.nftstorage.link/
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
you add a random new line to your application, could you amend without it

**Comment by GrowSolOfficial** [comment]
> you add a random new line to your application, could you amend without it

Sorry I don't understand what you mean by that. What I currently see is this:

image

**Comment by GrowSolOfficial** [comment]
> you add a random new line to your application, could you amend without it

We solved the issue in the branch. Let us know, thanks.

**Comment by Jymfletzfur** [comment]
Please come into the main discord into the token channel.

**Pull request closed without merging**
