### PR TITLE
Validate Token - Swirl

### PR DESCRIPTION
**Pull request by swirlonsolana**
# Validate [SWIRL] (https://solscan.io/token/FpJatkyuic8b8VNQufLc3MYgeqfyU3FkUvgs5w1DWJxq)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/swirlsocialapp/status/1771813400123003138?s=46&t=cm09mv06gt4EvgWUH8DHaQ 
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by salmandayal** [comment]
- [x] Mint address: FpJatkyuic8b8VNQufLc3MYgeqfyU3FkUvgs5w1DWJxq
- [x] Symbol: SWIRL
- [x] Token Decimals: 9
- [x] Token icon: https://v2.akord.com/public/vaults/active/NTGbcis497cJt3cajiPCwyLvgg_7rnG_8yvVqXMQFhc/gallery#6e85e0dc-61ce-4977-8c67-931e07dafc69
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by adnanmayo** [comment]
My Name is Adnan and I confirm the information below.

- [x] Mint address: FpJatkyuic8b8VNQufLc3MYgeqfyU3FkUvgs5w1DWJxq
- [x] Symbol: SWIRL
- [x] Token Decimals: 9
- [x] Token icon: https://v2.akord.com/public/vaults/active/NTGbcis497cJt3cajiPCwyLvgg_7rnG_8yvVqXMQFhc/gallery#6e85e0dc-61ce-4977-8c67-931e07dafc69
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by faisal-rehman19** [comment]
- [x] Mint address: FpJatkyuic8b8VNQufLc3MYgeqfyU3FkUvgs5w1DWJxq
- [x] Symbol: SWIRL
- [x] Token Decimals: 9
- [x] Token icon: https://v2.akord.com/public/vaults/active/NTGbcis497cJt3cajiPCwyLvgg_7rnG_8yvVqXMQFhc/gallery#6e85e0dc-61ce-4977-8c67-931e07dafc69
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by usamadilshad11** [comment]
Mint address: FpJatkyuic8b8VNQufLc3MYgeqfyU3FkUvgs5w1DWJxq
 Symbol: SWIRL
 Token Decimals: 9
Token icon: https://v2.akord.com/public/vaults/active/NTGbcis497cJt3cajiPCwyLvgg_7rnG_8yvVqXMQFhc/gallery#6e85e0dc-61ce-4977-8c67-931e07dafc69
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by amna142** [comment]
My Name is Amna and I confirm that the information provided below is accurate.

- [ ] - Mint address: FpJatkyuic8b8VNQufLc3MYgeqfyU3FkUvgs5w1DWJxq
- [ ] - Symbol: SWIRL
- [ ] - Token Decimals: 9
- [ ] - Token icon: https://v2.akord.com/public/vaults/active/NTGbcis497cJt3cajiPCwyLvgg_7rnG_8yvVqXMQFhc/gallery#6e85e0dc-61ce-4977-8c67-931e07dafc69
- [ ] - On-chain metadata matches
- [ ] - No duplication on Jupiter's strict list

**Comment by MuhammadIrfanCodeupscale** [comment]
My Name is Muhammad Irfan and I confirm that the information provided below is accurate.

- [x] Mint address: FpJatkyuic8b8VNQufLc3MYgeqfyU3FkUvgs5w1DWJxq
- [x] Symbol: SWIRL
- [x] Token Decimals: 9
- [x] Token icon: https://v2.akord.com/public/vaults/active/NTGbcis497cJt3cajiPCwyLvgg_7rnG_8yvVqXMQFhc/gallery#6e85e0dc-61ce-4977-8c67-931e07dafc69
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by UmerMaalik12** [comment]
My Name is Umer Maalik and I confirm that the information provided below is accurate.

 -[x]Mint address: FpJatkyuic8b8VNQufLc3MYgeqfyU3FkUvgs5w1DWJxq
-[x] Symbol: SWIRL
 -[x]Token Decimals: 9
 -[x]Token icon: https://v2.akord.com/public/vaults/active/NTGbcis497cJt3cajiPCwyLvgg_7rnG_8yvVqXMQFhc/gallery#6e85e0dc--[x]61ce-4977-8c67-931e07dafc69
 -[x]On-chain metadata matches
 -[x]No duplication on Jupiter's strict list

**Comment by abdur00** [comment]
My Name is Abdur Rehman and I confirm that the information provided below is accurate.

- [x] Mint address: FpJatkyuic8b8VNQufLc3MYgeqfyU3FkUvgs5w1DWJxq
- [x] Symbol: SWIRL
- [x] Token Decimals: 9
- [x] Token icon: https://v2.akord.com/public/vaults/active/NTGbcis497cJt3cajiPCwyLvgg_7rnG_8yvVqXMQFhc/gallery#6e85e0dc-61ce-4977-8c67-931e07dafc69
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
insufficient volume

**Comment by salmandayal** [comment]
What is the minimum threshold for volume?

**Pull request closed without merging**
