### PR TITLE
Validate SolSpend

### PR DESCRIPTION
**Pull request by WizzyDev**
# Validate [SPEND](https://solscan.io/token/3mp1MN5v7zdGXTvvcC9zUMoszMrh9pNdaCDkAQKc7Fec)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SolSpend/status/1786103772147601773
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/solspend, https://coinmarketcap.com/currencies/solspend/

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by WizzyDev** [comment]
This request supersedes the request made on March 28th (PR #2290) which was closed due to improper formatting.

**Comment by Dr0wned92** [comment]
Spend is legit. Utility is amazing.

**Comment by cryptomanmachine** [comment]
This is a very important project for the Solana blockchain, providing an offramp for users of the telegram bot. I think there are several imposter tokens already. It is key that this be approved as soon as possible to protect buyers and users of the Telegram bot.

**Comment by CryptoRoaster** [comment]
Legit project

**Comment by Jody-Newman** [comment]
Let’s get this approved! 👍🏽

**Comment by dileth** [comment]
I confirm that the information provided is accurate, and the token is valid.

Mint Address: 3mp1MN5v7zdGXTvvcC9zUMoszMrh9pNdaCDkAQKc7Fec
Symbol: SPEND
Token Decimals: 5
Token Icon: [Link to Icon](https://bafkreic4r56jg7fvkthkfzmmfy2z6ypfltqgowjvs44ghf32nh2nz77tva.ipfs.nftstorage.link/)
On-chain Metadata: Matches
Duplication Status: No duplication found on Jupiter's strict list

**Comment by Droopytan** [comment]
This is indeed one of thw best projects on solana out there. Who doesn't like to offramp their crypto earnings irl with having to worry about stupid texes? Literally no body right :D $spend gonna keep spending 💰

**Comment by Waldot123** [comment]
I have been following this project since it launched a couple of months ago, great project and great team.

I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: 3mp1MN5v7zdGXTvvcC9zUMoszMrh9pNdaCDkAQKc7Fec
Symbol: SPEND
Token Decimals: 5
Token icon: https://bafkreic4r56jg7fvkthkfzmmfy2z6ypfltqgowjvs44ghf32nh2nz77tva.ipfs.nftstorage.link/
On-chain metadata matches
No duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
