### PR TITLE
MoonMarket, MOON

### PR DESCRIPTION
**Pull request by MoonSolana**
# Validate [MOON](https://solscan.io/token/CcPYxgVbSmP9VgNRLdT7KkznZJQ7DyFJ2ZvSPwgdN62e)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/MoonMarketSol/status/1794425845425025386

## Validation (Please check off boxes):
- [x ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [ x] My change matches the format in the file (no spaces between fields).
- [ x] My token is already live and trading on Jupiter.
- [ x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [ x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by MoonSolana** [comment]
Hi! What is the estimated time to review and be granted a decision?
Let me know if you need any additional information 
Thanks!

**Comment by Jymfletzfur** [comment]
Please come into discord

**Comment by MoonSolana** [comment]
Where is the discord?

**Comment by MoonSolana** [comment]
I joined the discord - not sure what to do next.

**Comment by Jymfletzfur** [comment]
Use this as your image file

https://bafybeigiguuw3qpptpdxyt6fxxql6z3wsh3dwemvpw7sydo25ffoqqghha.ipfs.cf-ipfs.com/

**Comment by MoonSolana** [comment]
Where am I using that image?

**Comment by MoonSolana** [comment]
i changed my profile picture to that image but am unsure if there is somewhere else I need to do that

**Comment by MoonSolana** [comment]
Should be fixed now

**Comment by MoonSolana** [comment]
Used that link in the code for new image

**Comment by MoonSolana** [comment]
I need help, not sure what I'm doing wrong. I copy and pasted that URL for the image you provided

**Comment by MoonSolana** [comment]
i've tried to delet

**Comment by MoonSolana** [comment]
Screen Shot 2024-05-27 at 7 55 01 PM
I've tried to delete this request and open another one and when I do that i get this message.
I need assistance

**Comment by MoonSolana** [comment]
If it is easier and will fix this issue can you just delete this request so I can make a new one. I'm not sure how

**Comment by MoonSolana** [comment]
I think I amended this pull request can you check?

**Comment by MoonSolana** [comment]
Screen Shot 2024-05-28 at 1 44 11 PM

I've tried a couple different things - even when i press resolve conflicts on this and change the image URL to the one provided there isn't a way to save it from what I've seen. Any direction or assistance would be appreciated

**Pull request closed without merging**
