### PR TITLE
ROBOTCITY

### PR DESCRIPTION
**Pull request by web3aidevelloper**
# Validate [ROBOTCITY](https://solscan.io/token/P1wqqNbaefFW96Pj2jeq93XBREq6bj7QB9mxGeamd6s)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/robotcitysol/status/1753508297611596078?s=20
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [ ] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by piupiutoken** [comment]
hi i like this NFTs

**Comment by piupiutoken** [comment]
I can confirm that all the provided information are accurate, and the token is valid

**Comment by Anouszerrou** [comment]
I can confirm that all the provided information are accurate, and the token is valid

**Comment by robbestad** [comment]
Use a decentralized storage network for the token image (arweave or ipfs)

**Comment by Jymfletzfur** [comment]
does not meet volume criteria

**Pull request closed without merging**
