### PR TITLE
ICEDOUT

### PR DESCRIPTION
**Pull request by icedoutbulls**
# Validate [ICEDOUT](https://solscan.io/token/26bedy893CHqi5bcuUFhMgD6uTLw9V9iLWKAQjjDjpEA)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/IcedOutBulls/status/1750907969095532634 - See the quoted Tweet for community support
- Coingecko/ CMC URL (If available): Still trying to get this set up

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by lopjf** [comment]
I attest that the provided information are accurate, and the token is valid.

- [x] Mint address: 26bedy893CHqi5bcuUFhMgD6uTLw9V9iLWKAQjjDjpEA
- [x] Symbol: ICEDOUT
- [x] Token Decimals: 9
- [x] Token icon: https://icedoutbulls.github.io/icedoutbulls/io_logo.png
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by mina-adw** [comment]
I attest that the following information is accurate and the token is valid:

 Mint address: 26bedy893CHqi5bcuUFhMgD6uTLw9V9iLWKAQjjDjpEA
 Symbol: ICEDOUT
 Token Decimals: 9
 Token icon: https://icedoutbulls.github.io/icedoutbulls/io_logo.png
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by Buster0x** [comment]
I attest that the following information is accurate and the token is valid:

[x] Mint address: 26bedy893CHqi5bcuUFhMgD6uTLw9V9iLWKAQjjDjpEA
[x] Symbol: ICEDOUT
[x] Token Decimals: 9
[x] Token icon: https://icedoutbulls.github.io/icedoutbulls/io_logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by HalfaWadlow** [comment]
I attest that the provided information are accurate, and the token is valid.

 Mint address: 26bedy893CHqi5bcuUFhMgD6uTLw9V9iLWKAQjjDjpEA
 Symbol: ICEDOUT
 Token Decimals: 9
 Token icon: https://icedoutbulls.github.io/icedoutbulls/io_logo.png
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by DoooX** [comment]
I attest that the following information is accurate and the token is valid:

[x] Mint address: 26bedy893CHqi5bcuUFhMgD6uTLw9V9iLWKAQjjDjpEA
[x] Symbol: ICEDOUT
[x] Token Decimals: 9
[x] Token icon: https://icedoutbulls.github.io/icedoutbulls/io_logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by Arashk-A** [comment]
I can confirm that this information is true and accurate:

[x] Mint address: 26bedy893CHqi5bcuUFhMgD6uTLw9V9iLWKAQjjDjpEA
[x] Symbol: ICEDOUT
[x] Token Decimals: 9
[x] Token icon: https://icedoutbulls.github.io/icedoutbulls/io_logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by Arashk-A** [comment]
I can confirm that this information is true and accurate:

[x] Mint address: 26bedy893CHqi5bcuUFhMgD6uTLw9V9iLWKAQjjDjpEA
[x] Symbol: ICEDOUT
[x] Token Decimals: 9
[x] Token icon: https://icedoutbulls.github.io/icedoutbulls/io_logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by ParisShillton** [comment]
[x] Mint address: 26bedy893CHqi5bcuUFhMgD6uTLw9V9iLWKAQjjDjpEA
[x] Symbol: ICEDOUT
[x] Token Decimals: 9
[x] Token icon: https://icedoutbulls.github.io/icedoutbulls/io_logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by AndreMoonUK** [comment]
I attest that the following information is accurate and the token is valid:

 Mint address: 26bedy893CHqi5bcuUFhMgD6uTLw9V9iLWKAQjjDjpEA
 Symbol: ICEDOUT
 Token Decimals: 9
 Token icon: https://icedoutbulls.github.io/icedoutbulls/io_logo.png
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by BulbulatorIO** [comment]
all is here:
[x] Mint address: 26bedy893CHqi5bcuUFhMgD6uTLw9V9iLWKAQjjDjpEA
[x] Symbol: ICEDOUT
[x] Token Decimals: 9
[x] Token icon: https://icedoutbulls.github.io/icedoutbulls/io_logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
Insufficient volume, mcap, age

**Pull request closed without merging**
