### PR TITLE
Validate $DRUNK

### PR DESCRIPTION
**Pull request by kissenry**
# Validate [$DRUNK](https://solscan.io/token/EaRMzBwWRwvSgus8rfdZGfdzX3ZKRKoCL7U36G7xfvcb)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/drunk_solana/status/1773476610185863228
- Coingecko/ CMC URL : [here](https://coingecko.com/en/coins/drunk)

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Drieskee** [comment]
I confirm all provided data is valid and true

**Comment by MvpFlorin** [comment]
I confirm all provided data is valid and true

**Comment by beehave9** [comment]
I confirm all provided data is valid and true

**Comment by Rab1984** [comment]
I confirm that all provided data is valid and true

**Comment by Mills388** [comment]
I confirm all provided data is valid and true

**Comment by Rafamn1999** [comment]
I confirm all provided data is valid and true

**Comment by lalitksharma90** [comment]
GX9m8dHRacReBpV6rK7szJAFHLF468A1hk6bBZk78kcK

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
