### PR TITLE
Validate THOL

### PR DESCRIPTION
**Pull request by rodrigoyoshida**
# Validate [THOL](https://solscan.io/token/EKCW975DWdt1roK1NVQDf4QGfaGTcQPU5tFD1DMcMe9Q)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/tholanasol/status/1747093807303164036
- Coingecko URL: https://www.coingecko.com/pt/moedas/tholana

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by rodrigoyoshida** [comment]
Created this new PR, here is the original: https://github.com/jup-ag/token-list/pull/1117

**Comment by Foozie3Moons** [comment]
The information contained here looks correct to me. Token name is Tholana, Ticker name is THOL, address is correct, decimals 7, image is correct, and has active twitter and telegram community.

**Comment by JABK007ONE** [comment]
All the information is correct

**Comment by rodrigoyoshida** [comment]
Just fixed the conflict with the KIWI listing

**Comment by robbestad** [comment]
Use a decentralized storage network for the token image (arweave or ipfs)

**Comment by rodrigoyoshida** [comment]
> Use a decentralized storage network for the token image (arweave or ipfs)

@robbestad thanks for pointing out that! Already updated the PR with the image on Arweave and also resolved the conflicts with today's approvals

**Review by Jymfletzfur — APPROVED** [review]

**Review by 0xSoju2 — APPROVED** [review]

**Pull request merged**
