### PR TITLE
Validate BHST - Bit Harvest Studio Token

### PR DESCRIPTION
**Pull request by source-code-sa**
# Validate [BHST](https://solscan.io/token/BHSTv1nsz57fsXZzcsYWXhEygyqAaQu63DUJd3Rcp5Jo)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/BHS_Studio/status/1751225494605861259

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by source-code-sa** [comment]
https://discord.gg/EBPEefp8Yk
Bit Harvest Studio Discord Community

**Comment by Ay0hCrypto** [comment]
All community members and token Holders have been notified of the Token Address change: 
OLD  - 94eKLx2MnfnVpbwqGvBwQCAyjdYUqs4B9MG19GS1mJ5i
NEW- BHSTv1nsz57fsXZzcsYWXhEygyqAaQu63DUJd3Rcp5Jo
Discord link in above comment, twitter link: https://twitter.com/Bitharvest_Luna/status/1751678550564827617

**Comment by Ay0hCrypto** [comment]
original pr #672

**Comment by source-code-sa** [comment]
Any updates on this validation team...

**Review by Ay0hCrypto — COMMENTED** [review]
All data is correct.
Please let us know when this is merged so we a PR a ban on the old token contract.

**Comment by Jymfletzfur** [comment]
Insufficient volume, holders, mcap

**Comment by source-code-sa** [comment]
https://twitter.com/BHS_Studio/status/1751225494605861259

**Pull request closed without merging**
