### PR TITLE
Validate BER

### PR DESCRIPTION
**Pull request by Ber2024**
# Validate [BER](https://solscan.io/token/4gb2DyZBApzz18bDGFc6gfQWQQcJn3fK6CCKrjqf4heA)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/BougieBer/status/1750352989045313592
- Coingecko/ CMC URL (If available): Still working to get on CoinGecko/CMC

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by E-MW88** [comment]
Confirming the provided information is accurate and the token is valid.

- [X] Mint address: 4gb2DyZBApzz18bDGFc6gfQWQQcJn3fK6CCKrjqf4heA
 - [X] Symbol: BRR
 - [X] Token Decimals: 9
 - [X] Token icon: https://bafybeigh5mzgn5ybg6lnoncm6dulqe7c4jxbeg76mo2o2oh4cvyqsk5g2u.ipfs.nftstorage.link
 - [X] On-chain metadata matches
 - [X] No duplication on Jupiter's strict list

**Comment by CryptoDad7** [comment]
CryptoDad7 confirming that the information provided for BER (Bougie Ber) is correct.

- [X] Mint address: 4gb2DyZBApzz18bDGFc6gfQWQQcJn3fK6CCKrjqf4heA
 - [X] Symbol: BRR
 - [X] Token Decimals: 9
 - [X] Token icon: https://bafybeigh5mzgn5ybg6lnoncm6dulqe7c4jxbeg76mo2o2oh4cvyqsk5g2u.ipfs.nftstorage.link
 - [X] On-chain metadata matches
 - [X] No duplication on Jupiter's strict list

**Comment by Abdoulmerlic** [comment]
Ber is great with good potentials

**Comment by CrypticTrip** [comment]
- [X] BER Bougie Ber is a valid token
----------------------------------------------------
- [X] Mint address: 4gb2DyZBApzz18bDGFc6gfQWQQcJn3fK6CCKrjqf4heA
- [X] Symbol: BRR
- [X] Token Decimals: 9
- [X] Token icon: https://bafybeigh5mzgn5ybg6lnoncm6dulqe7c4jxbeg76mo2o2oh4cvyqsk5g2u.ipfs.nftstorage.link/
- [X] On-chain metadata matches
- [X] No duplication on Jupiter's strict list
------------------------------------------------------
- [X] Website https://www.bougieber.com Verified
- [X] Twitter X https://twitter.com/BougieBer Verified
- [X] Telegram https://t.me/bougieber Verified
- [X] https://dexscreener.com/solana/gstck5zmqi41lwvoej811nkqxqpwhedcmwb9ajkgwmtf Verified
- [X] https://www.geckoterminal.com/solana/pools/GStCK5ZMqi41LWVoEj811nKQXQPWhedcMwB9AjkgwmTF Verified
-------------------------------------------------------

**Comment by CryptoDad7** [comment]
@Ber2024 Any news with the how the request is going?

**Comment by Jymfletzfur** [comment]
Ber token does not meet the criteria

**Pull request closed without merging**
