### PR TITLE
validate CIRCLE

### PR DESCRIPTION
**Pull request by CircleGameSol**
# Validate [CIRCLE](https://solscan.io/token/EkHr62PC6Y1axrLS7cR8YC4BZeW19mtHxQLCLMrf9vnq)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/circlegamesol/status/1749226986289988036
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/you-looked

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by mugoosse** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

* [x]   Mint address: EkHr62PC6Y1axrLS7cR8YC4BZeW19mtHxQLCLMrf9vnq
* [x]   Symbol: CIRCLE
* [x]   Token Decimals: 9
* [x]   Token icon: https://i.imgur.com/fEFVS51.png
* [x]   On-chain metadata matches
* [x]   No duplication on Jupiter's strict list

**Comment by dansku** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

 Mint address: EkHr62PC6Y1axrLS7cR8YC4BZeW19mtHxQLCLMrf9vnq
 Symbol: CIRCLE
 Token Decimals: 3
 Token icon: https://i.imgur.com/fEFVS51.png
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by 1thiagao** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [ ]  Mint address: EkHr62PC6Y1axrLS7cR8YC4BZeW19mtHxQLCLMrf9vnq
- [ ]  Symbol: CIRCLE
- [ ]  Token Decimals: 3
- [ ]  Token icon: https://i.imgur.com/fEFVS51.png
- [ ]  On-chain metadata matches
- [ ]  No duplication on Jupiter's strict list

**Comment by rohenaz** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

- [x] Mint address: EkHr62PC6YY1axrL57cR8YC4BZeW19mtHxQLCLMr9vnq
- [x] Symbol: CIRCLE
- [x] Token Decimals: 3
- [x] Token icon: CIRCLE
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by danielzabotti** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [ ]  Mint address: EkHr62PC6Y1axrLS7cR8YC4BZeW19mtHxQLCLMrf9vnq
- [ ]  Symbol: CIRCLE
- [ ]  Token Decimals: 3
- [ ]  Token icon: https://i.imgur.com/fEFVS51.png
- [ ]  On-chain metadata matches
- [ ]  No duplication on Jupiter's strict list

**Comment by bobrobaggins** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

**Pull request merged**
