### PR TITLE
Validate BHST

### PR DESCRIPTION
**Pull request by source-code-sa**
# Validate [BHST](https://solscan.io/token/94eKLx2MnfnVpbwqGvBwQCAyjdYUqs4B9MG19GS1mJ5i)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Bitharvest_Luna/status/1734406769877692751

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by source-code-sa** [comment]
https://github.com/jup-ag/token-list/pull/607

**Comment by Ay0hCrypto** [comment]
Referencing PR #520 . TY for your time.
94eKLx2MnfnVpbwqGvBwQCAyjdYUqs4B9MG19GS1mJ5i

**Comment by source-code-sa** [comment]
https://github.com/jup-ag/token-list/pull/520

**Review by Ay0hCrypto — COMMENTED** [review]
**BHST** all details perfect.

**Comment by Ay0hCrypto** [comment]
@9yoi @whereismeow  Can we get this pushed before Jan 1 ?

**Comment by Timoon21** [comment]
Hey, I dont see a lot of community support, or volume on-chain.

**Comment by Ay0hCrypto** [comment]
> Hey, I dont see a lot of community support, or volume on-chain.

Yeah, our community isnt twitter HEAVY. https://discord.gg/mhw9NDWU feel free to check out our discord community, where we're active. And no after a month of multi K a day in volume but no listing, trading is obviously lower.

**Pull request merged**
