### PR TITLE
validate BROKIE

### PR DESCRIPTION
**Pull request by BrokieDev**
# Validate [BROKIE](https://solscan.io/token/4neSyzJmcSWQF58DKHdo7FNzJDDKSgaaQqrzuSXS5U6g)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: 
https://twitter.com/BrokieInu/status/1776260686269551010
- Coingecko/ CMC URL (If available): still working to get coin gecko set up for BROKIE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by sushrutranade** [comment]
[x] Mint address: 4neSyzJmcSWQF58DKHdo7FNzJDDKSgaaQqrzuSXS5U6g
[x] Symbol: BROKIE
[x] Token Decimals: 6
[x] Token icon:https://bafybeihdzznprzu25kp2psnn455m5qyp25tw46istuuvovdijigjnzgde4.ipfs.dweb.link/ 
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by mohammedkhatri** [comment]
- [x] Mint address: 4neSyzJmcSWQF58DKHdo7FNzJDDKSgaaQqrzuSXS5U6g
- [x] Symbol: BROKIE
- [x] Token Decimals: 6
- [x] Token icon:<https://bafybeihdzznprzu25kp2psnn455m5qyp25tw46istuuvovdijigjnzgde4.ipfs.dweb.link/>
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by harmanshal** [comment]
```
- [x] Mint address: 4neSyzJmcSWQF58DKHdo7FNzJDDKSgaaQqrzuSXS5U6g
- [x] Symbol: BROKIE
- [x] Token Decimals: 6
- [x] Token icon:<https://bafybeihdzznprzu25kp2psnn455m5qyp25tw46istuuvovdijigjnzgde4.ipfs.dweb.link/>
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list
```

**Comment by parag** [comment]
- [x] Mint address: 4neSyzJmcSWQF58DKHdo7FNzJDDKSgaaQqrzuSXS5U6g
- [x] Symbol: BROKIE
- [x] Token Decimals: 6
- [x] Token icon:<https://bafybeihdzznprzu25kp2psnn455m5qyp25tw46istuuvovdijigjnzgde4.ipfs.dweb.link/>
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by sujithps** [comment]
•⁠  ⁠[x] Mint address: 4neSyzJmcSWQF58DKHdo7FNzJDDKSgaaQqrzuSXS5U6g
•⁠  ⁠[x] Symbol: BROKIE
•⁠  ⁠[x] Token Decimals: 6
•⁠  ⁠[x] Token icon:<https://bafybeihdzznprzu25kp2psnn455m5qyp25tw46istuuvovdijigjnzgde4.ipfs.dweb.link/>
•⁠  ⁠[x] On-chain metadata matches
•⁠  ⁠[x] No duplication on Jupiter's strict list

**Comment by sujithps** [comment]
- ⁠[x] Mint address: 4neSyzJmcSWQF58DKHdo7FNzJDDKSgaaQqrzuSXS5U6g
- [x] Symbol: BROKIE
- ⁠[x] Token Decimals: 6
- ⁠[x] Token icon:<https://bafybeihdzznprzu25kp2psnn455m5qyp25tw46istuuvovdijigjnzgde4.ipfs.dweb.link/>
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by prasad-kadu** [comment]
[x] Mint address: 4neSyzJmcSWQF58DKHdo7FNzJDDKSgaaQqrzuSXS5U6g
[x] Symbol: BROKIE
[x] Token Decimals: 6
[x] Token icon:<https://bafybeihdzznprzu25kp2psnn455m5qyp25tw46istuuvovdijigjnzgde4.ipfs.dweb.link/>
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by officialYogesh** [comment]
- [x] Mint address: 4neSyzJmcSWQF58DKHdo7FNzJDDKSgaaQqrzuSXS5U6g
- [x] Symbol: BROKIE
- [x] Token Decimals: 6
- [x] Token icon:<https://bafybeihdzznprzu25kp2psnn455m5qyp25tw46istuuvovdijigjnzgde4.ipfs.dweb.link/>
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
