### PR TITLE
validate CHEEPEPE

### PR DESCRIPTION
**Pull request by cheepepe**
# Validate [CHEEPEPE](https://solscan.io/token/FwBixtdcmxawRFzBNeUmzhQzaFuvv6czs5wCQuLgWWsg)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/cheepepe_sol/status/1784062333511516552
- Coingecko/ CMC URL (If available): [https://www.coingecko.com/en/coins/cheepepe](https://www.coingecko.com/en/coins/cheepepe)

## Validation (Please check off boxes):
* [x] The metadata provided in the PR matches what is on-chain (Mandatory)
* [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
 * [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
* [x] My change matches the format in the file (no spaces between fields).
* [x] My token is already live and trading on Jupiter.
* [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
* [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by qqpmew** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- Mint address: FwBixtdcmxawRFzBNeUmzhQzaFuvv6czs5wCQuLgWWsg
- Symbol: CHEEPEPE
- Token Decimals: 6
- Token icon: https://bafybeichlgwyhbuo4c7v5cxlhqwwd7hy2xoirpsfukli4fc3ym5qlb4g4q.ipfs.nftstorage.link/
- On-chain metadata matches: https://solscan.io/token/FwBixtdcmxawRFzBNeUmzhQzaFuvv6czs5wCQuLgWWsg
- No duplication on Jupiter's strict list

**Comment by cheepepe** [comment]
@Jymfletzfur I have updated the token icon. Please check again for us. Thank you very much

**Review by BlockchainSavingsNonprofitBank — COMMENTED** [review]
checked, all good

**Comment by cheepepe** [comment]
> checked, all good

What do we need to do next to merge the pull request?

**Comment by cheepepe** [comment]
> checked, all good

Thank you so much

**Comment by cheepepe** [comment]
> @Jymfletzfur I have updated the token icon. Please check again for us. Thank you very much

@Jymfletzfur  Any update for us, sir. Please, help us!

**Comment by cheepepe** [comment]
> checked, all good

@BlockchainSavingsNonprofitBank  Can you approve the pull request to help me again? Sorry for bothering you. Please help us

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
