### PR TITLE
Validate SOLMEME

### PR DESCRIPTION
**Pull request by solmemetoken**
# Validate [SOLMEME](https://solscan.io/token/5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: [https://twitter.com/SOLMemeToken/status/1742444248237027709](https://twitter.com/SOLMemeToken/status/1742444248237027709)
- Coingecko/ CMC URL (If available): N/A (work in progress)

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by u4ma-hdd** [comment]
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Review by u4ma-hdd — COMMENTED** [review]
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by BigBlackCrypto053** [comment]
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by Sanyashii-here** [comment]
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by Ochykes01** [comment]
<@&1189564230882558022>, please take a look at the giveaway I’m about to announce…. I would like for everyone on the team to first do this, so that the community sees an example. I have done it myself…

@everyone:

Here’s our Giveaway for today 🎉:

We all want to see SOLMEME go to the moon 🚀. You would have noticed that:

- the Token is hard to find in Phantom (if you don’t previously hold it), 
- it shows as an *Unverified Token* in Solflare. 
- it’s not part of the validated list of tokens in Jupiter. 

Let’s help change all this today! Please go vote 👍 for SOLMEME to be added to validate tokens in Jupiter. That will really help 🙏. 

Share proof to doing this and your wallet address, and <@898012344901320757>  will airdrop **50,000 SOLMEME** to you! 💰

**How to assist with this?**

- Just go to https://github.com/jup-ag/token-list/pull/954, login with your GitHub account, or create a new free account; then add the following comment:

``` 
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list 
```

**Comment by BigJC21** [comment]
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by Ochykes01** [comment]
Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
On-chain metadata matches
No duplication on Jupiter's

**Comment by CryptoRizz** [comment]
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by Beatzby** [comment]
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by Dorsypretty** [comment]
Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by JOHNee001** [comment]
``` 
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list 
```

**Comment by JOHNee001** [comment]
``` 
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list 
```

**Comment by Prodia25** [comment]
``` 
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list 
```

**Comment by marvyXCX** [comment]
SOLMEME is a valid token driven by a community of Solana enthusiasts.  The following info is accurate:
 
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by Breadloss** [comment]
``` 
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list 
```


Everyone works as intended

**Comment by billpan21** [comment]
This is a community project with a group of Solana enthusiasts that needs to be validated.
The following is true
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by theRoadster** [comment]
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by Dean516** [comment]
This is a community driven project and its going places  the following information here is true 
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list 
```

**Comment by theRoadster** [comment]
The SOLMEME project is community based. I can confirm that the provided token information is accurate. The token is valid.

Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Toofooxx** [comment]
Hi,
I am not a dev, but I'm part of the SolMeme community.
This token is a valid one. The community is active, and we are ready to be listed in CMC and coin gecko.

- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by Vick112** [comment]
The SOLMEME project is community based. I can confirm that the provided token information is accurate. The token is valid.

Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by cathlesis** [comment]
The SOLMEME project is community based. I can confirm that the provided token information is accurate. The token is valid.

Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by AlbertJaku** [comment]
The SOLMEME project is community based. I can confirm that the provided token information is accurate. The token is valid.

- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by amazon4479** [comment]
SOLMEME is really absolute project 
- Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
- Symbol: SOLMEME
- Token Decimals: 7
- Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
- On-chain metadata matches
- No duplication on Jupiter's strict list 
```

**Comment by Starebug** [comment]
I can attest that SOLMEME is really a community based  project. I confirm that the provided token information is accurate and valid.
Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Joshuachibuike** [comment]
I can attest that that the solmeme coin is a credible community I can always trust

**Comment by ivovaladares** [comment]
I can attest the provided information is accurate and the token is valid.
Mint address: 5MRMqvLZyRQhrMn2a8vSL3Kv9vfjNhjRKRPHtTBz1VEB
Symbol: SOLMEME
Token Decimals: 7
Token icon: https://raw.githubusercontent.com/solmemetoken/solememe/main/logo.png
On-chain metadata matches
No duplication on Jupiter's

**Pull request closed without merging**
