### PR TITLE
Validate GATI Please

### PR DESCRIPTION
**Pull request by indiotc**
# Validate [GATI](https://solscan.io/token/BYXW9eyDUMKu7Y6UeXSHxhYMZJMTNiA5tewpvGjGf7MT)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://x.com/gaticoinsol/status/1784654972715409727) and showing community support: https://x.com/gaticoinsol/status/1782450838775980385
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Goldenlight77 — COMMENTED** [review]
It looks a solid project and ownership is strong with the dedicated team.

**Comment by MasterKen05** [comment]
Gati to the Moon.

**Comment by MasterKen05** [comment]
This is really a project with great potentials.

**Comment by Johnson07068524021** [comment]
GATI is one of the best project GATI to moon 🌙🌙🌙 buy more and hold 
- Collaborative
- Ambitious
- Creative
- Impactful

**Comment by Sylvadirect** [comment]
$GATI is an awesome project with good and transparent intentions and concepts 
Good community background. 
Good supporters.
Dedicated team.
Project has lots of potentials.

**Comment by Obasi5754** [comment]
Good project 
Bullish with GATI

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
