### PR TITLE
Validate WHO

### PR DESCRIPTION
**Pull request by WormSol**
# Validate [{WHO}]({https://solscan.io/token/A8eYjpNQF6QYEE7DnM4F514MErFzV1pxVT69d7mdSsMk})

## Attestations (Please provide links): https://solscan.io/token/A8eYjpNQF6QYEE7DnM4F514MErFzV1pxVT69d7mdSsMk
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/tickerwho/status/1729131282129727562?s=46&t=Rkn52fTv5CjYZqcBAJxQdg}
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [✔️] The metadata provided in the PR matches what is on-chain (Mandatory)
- [✔️]Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [✔️] My change matches the format in the file (no spaces between fields).
- [✔️] My token is already live and trading on Jupiter.
- [✔️] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by 9yoi** [comment]
I don't think we can validate a token that's called wormhole

**Comment by WormSol** [comment]
> I don't think we can validate a token that's called wormhole

Can you verify that? We can still update metadata and change the name if it’s 100% necessary. I don’t see how the crypto company wormhole would have a bearing over the name of something so ambiguous

**Comment by WormSol** [comment]
> I don't think we can validate a token that's called wormhole

Hello, no response to my last question so we will take the hint and adjust our name/re-submit the request. Thank you

**Comment by Timoon21** [comment]
duplicate: https://github.com/jup-ag/token-list/pull/500

**Pull request closed without merging**
