### PR TITLE
Validate babs

### PR DESCRIPTION
**Pull request by gorganrares**
# Validate [Token Symbol](https://solscan.io/token/{mint_address})

## Attestations:
- Tweet from your Twitter Account attesting the Mint address: https://twitter.com/babsuniverse/status/1626301759407652871?s=20
- Coingecko/ CMC URL (If available): not available

## Validation (Additonal material for reviewers):

Name: BABS
Symbol: BABS
Mint Address: Ceqwd4CSGBZnW8PHEexBQCAV2NDPkBoSqheiKR7gzELV
Decimals: 5
LogoURI: https://iili.io/HaOytTu.png
Community Validated: false

- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will take longer)
- [ ] Is Listed on Coingecko / CMC (Optional, but is helpful for reviewers to check for duplicates)  

## Acknowledgement
- [x] Acknowleged that I did not modify unrelated code.
- [x] Acknowledged that my change matches the format of other lines in the file (no spaces between fields).

### CODE REVIEW

**Review by Timoon21 — COMMENTED** [review]
You need PR validated-tokens.csv not the template

**Review by Timoon21 — CHANGES_REQUESTED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the official website
- [x] Not on CoinGecko, no duplication
- [x] No duplication on the Jupiter's strict list

- [ ] Change dont matches the format of other lines in the file (spaces between fields).
- [ ] Set last field to true, not false

**Comment by gorganrares** [comment]
is ok now?

**Review by Timoon21 — APPROVED** [review]
Change matches the format of other lines in the file

**Comment by gorganrares** [comment]
Can you tell me exactly how to write? I don't understand what's wrong, thank you

**Comment by Timoon21** [comment]
> Can you tell me exactly how to write? I don't understand what's wrong, thank you

It's ok now

**Comment by gorganrares** [comment]
Perfect, so now, is ready for merge?
we will have the token verified right?

**Comment by Timoon21** [comment]
> Perfect, so now, is ready for merge? we will have the token verified right?

At least 3 approving reviews are required by reviewers with write access.

**Comment by gorganrares** [comment]
so we just have to wait now right?

**Review by LJQZZZ123 — APPROVED** [review]

**Comment by meijiao** [comment]
Please remove change to the .md file, that should not be amended. Open a new PR when you're ready and reference this PR in your new one. Thanks!

**Pull request closed without merging**
