### PR TITLE
Validate Puri

### PR DESCRIPTION
**Pull request by Purionsolana**
# Validate [Puri](https://solscan.io/token/CzLWmvjtj5bp9YEWkzzBnuWovVtogeuchFu5GeFh68hB)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: [Tweet 1 ](https://twitter.com/PuriOnSolana/status/1743235463820026158)
[Tweet 2](https://twitter.com/PuriOnSolana/status/1766245993937326291)
[Tweet 3](https://twitter.com/PuriOnSolana/status/1741762392625991778)
- Coingecko/ CMC URL (If available): Submissions under review.

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by CGS-cc — COMMENTED** [review]
Looks good.

**Comment by CGS-cc** [comment]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x]  No duplication on Jupiter's strict list
- [x] Community validation

**Review by neofox2000 — COMMENTED** [review]
Looks good :)

* [x]  On-chain metadata matches the PR
* [x]  Token address matches the tweet
* [x]   No duplication on Jupiter's strict list
* [x]  Community validation

**Review by acsaifz88 — COMMENTED** [review]
Looks good.
- [x] On-chain metadata matches the PR
- [x] Token is active and tradeable
- [x] Community validation
- [x] No duplication on Jupiter's strict list 
- [x] Token account on tweets are correct.

**Comment by Jymfletzfur** [comment]
your PR edits the submission template, please amend

**Comment by Purionsolana** [comment]
> your PR edits the submission template, please amend

I deleted the file from the commit.  Will that suffice?  I am not sure how to remove the commit with the submission template altogether.

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
