### PR TITLE
Validate BHST - Bit Harvest Studio Token

### PR DESCRIPTION
**Pull request by source-code-sa**
Validate BHST - Bit Harvest Community Token

Validate [BHST](https://solscan.io/token/94eKLx2MnfnVpbwqGvBwQCAyjdYUqs4B9MG19GS1mJ5i)
https://solscan.io/token/94eKLx2MnfnVpbwqGvBwQCAyjdYUqs4B9MG19GS1mJ5i
Token Address: 94eKLx2MnfnVpbwqGvBwQCAyjdYUqs4B9MG19GS1mJ5i

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Bitharvest_Luna/status/1734406769877692751

## Validation (Please check off boxes):
- [*] The metadata provided in the PR matches what is on-chain (Mandatory)
- [*] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [*] My change matches the format in the file (no spaces between fields).
- [*] My token is already live and trading on Jupiter.
- [*] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by source-code-sa** [comment]
https://discord.gg/EBPEefp8Yk

**Comment by Ay0hCrypto** [comment]
94eKLx2MnfnVpbwqGvBwQCAyjdYUqs4B9MG19GS1mJ5i - Token Address
9EMgJLDDcG4bLaxLBRAWE1Vtm5rZsuHQ7B8n3msELALW - OWNER Wallet is Realms Community Governance Wallet See Link:
https://app.realms.today/dao/5GMb1LM6TSwjLLHE1xfmPxq4Vjji6bveCzHdFKrZaARW/treasury/v2
BHST Twitter - @Bitharvest_Luna
My verification - I am:
Ay0h Bitharvest.Studio - Discord. @Ay0h_Sol - Twitter. @ay0h_sol - Telegram.
@benchow @whereismeow  are both in our Telegram group if you have any other questions. 
over 20k TVL - Fully community and developer funded. 5 active pools on Meteoria.

**Review by Ay0hCrypto — COMMENTED** [review]
looks great!

**Comment by 9yoi** [comment]
hey your PR should change the validated tokens csv, not the markdown file. Can you look at the example PR in the README? Please open a new PR when you're ready and reference this one, I'll pick it up asap

**Comment by Ay0hCrypto** [comment]
Validate BHST #607

**Pull request closed without merging**
