### PR TITLE
validate Cashmo.

### PR DESCRIPTION
**Pull request by Hodlerforlife**
# Validate [CASHMO](https://solscan.io/token/Ds1UMLfwWcn5cBgGg2eLdyR3hCtDxo9Bimqnp6eHfbhC)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/CASHMOTOKEN/status/1775492015163085174?s=20
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by RoyaltyCompany** [comment]
The idea to promote this token is very smart, they first want to get validated before they start with huge marketing about an influencer. Validate it please, my bags are ready!

**Comment by bullishcoinspotter** [comment]
So bullish!!! Let's hit that 50M marketcap. $CASHMO!!!

**Comment by cashcraze** [comment]
Cash me on the moon howbowdah 😂

**Comment by Televators7** [comment]
Lfgoooooo 🔥

**Comment by Jymfletzfur** [comment]
submission is highly inappropriate and attempts to alter 22 unrelated files.

**Pull request closed without merging**
