### PR TITLE
Validate AMC

### PR DESCRIPTION
**Pull request by AMCONSOL**
# Validate [AMC](https://solscan.io/token/9jaZhJM6nMHTo4hY9DGabQ1HNuUWhJtm7js1fmKMVpkN)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/amconsolbtfd/status/1789995155912634471?s=46
- Coingecko/ CMC URL (If available): https://www.geckoterminal.com/solana/pools/HZZofxusqKaA9JqaeXW8PtUALRXUwSLLwnt4eBFiyEdC?utm_source=coingecko&utm_medium=referral&utm_campaign=searchresults
## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
Image link isn't correct, please come into discord.

**Comment by AMCONSOL** [comment]
> Image link isn't correct, please come into discord
sorry about that, what is the discord link? @Jymfletzfur

**Comment by AMCONSOL** [comment]
> Image link isn't correct, please come into discord.

amconsol_53702 joined the discord @Jymfletzfur

**Comment by Jymfletzfur** [comment]
Swap the image link with this:

https://bafkreic5kaqbao44hmgvcpa2ssah2rrmw7a4kwu7cnihbidoiqi6juiiai.ipfs.nftstorage.link/

**Pull request closed without merging**
