### PR TITLE
EverSol

### PR DESCRIPTION
**Pull request by EverSolOfficial**
# Validate [$EVER](https://solscan.io/token/4UbbkzFuYub2Q7sFZ3dqQiVer2Wg5K5aA4BStZPcNYJA)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/OfficialEverSol/status/1754959556923507014
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by shhitzelectric** [comment]
edit your title from just "Main" or they Will close your request for Validation

**Comment by EverSolOfficial** [comment]
> edit your title from just "Main" or they Will close your request for Validation

We still did not get verified. Any idea why?

**Comment by shhitzelectric** [comment]
No, I think they’re doing this to a lot of people. I think it’s a little
more complex then they lead on. I just know that was the first reason why
ours wasn’t “” validated, I do wish I could help a little more, But really,
that’s not my field of expertise. I just read the fine print a little bit
more on the pull request example and try to understand as best you can. And
don’t let it eat up. I kind of just let it go.

**Comment by shhitzelectric** [comment]
If you look on there to see how many actually get validated is very
peculiar, and how often they are doing validation I asked them why mine
wasn’t validated and the simple response, and only response was gatekeeper,

**Comment by robbestad** [comment]
First step is to use a decentralized network for your token image (arweave or ipfs)

**Comment by shhitzelectric** [comment]
Thanks for the tip! I really think this will help I appreciate the advice
thanks for connecting with us on this!!! !!! !!!

**Comment by shhitzelectric** [comment]
Do you know how I would do that??? ??? ???

**Comment by robbestad** [comment]
The person with the token authority can change it easily with one of the many online tools and it will automatically be uploaded to Arweave or IPFS. One that is good is fluxbeam's token editor.

**Comment by shhitzelectric** [comment]
I have edited the conflict and committed to merge using soul scan, does it
look good??? ??? ???

**Comment by shhitzelectric** [comment]
Check #1359

**Comment by EverSolOfficial** [comment]
> The person with the token authority can change it easily with one of the many online tools and it will automatically be uploaded to Arweave or IPFS. One that is good is fluxbeam's token editor.

We fixed our link for the logo.

**Comment by shhitzelectric** [comment]
Great! So did #1359 please validate

**Review by EverSolOfficial — COMMENTED** [review]
Updated the link for the logo.

**Comment by EverSolOfficial** [comment]
Asking for updates in regards to the strict list. Thanks

**Pull request closed without merging**
