### PR TITLE
Validate ISKT

### PR DESCRIPTION
**Pull request by birkir**
# Validate [ISKT](https://solscan.io/token/isktkk27QaTpoRUhwwS5n9YUoYf8ydCuoTz5R2tFEKu)

## Attestations:
- Tweet from your Twitter Account attesting the Mint address: https://twitter.com/Mintum_is/status/1626509056226492417
- OpenSerum: https://openserum.io/7fcy5Mi4eQ8jxT1uThkpcYjC5FjjTojK9xSyKXQmHa1S

## Validation (Additonal material for reviewers):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will take longer)
- Is Listed on Coingecko / CMC: in progress

## Acknowledgement
- [x] Acknowleged that I did not modify unrelated code.
- [x] Acknowledged that my change matches the format of other lines in the file (no spaces between fields).

### CODE REVIEW

**Comment by Gsuz** [comment]
I'm on the ISKT team with Birkir, wanted to confirm and add some additional Info.  

Further info: 

ISKT metadata (as entered in metaplex) : https://github.com/rafmyntasjodur/iskt-metadata

Our github: https://github.com/rafmyntasjodur

Our website: https://mintum.is

Our company "Rafmyntasjóður Íslands" is a registered crypto service provider with the Icelandic national bank. Proof: 
https://www.sedlabanki.is/utgefid-efni/frettir-og-tilkynningar/frettasafn/frett/2022/07/08/Rafmyntasjodur-Islands-ehf.-skrad-sem-thjonustuveitandi-syndareigna/ 

Article in Icelandic newspaper on the founders: https://www.vb.is/frettir/gefa-ut-islenska-rafkronu/

**Comment by LJQZZZ123** [comment]
- [ ] On-chain metadata matches the PR
- [ ] Token address matches the tweet
- [ ] No duplication on CoinGecko/ CMC
- [ ] No duplication on Jupiter's strict list

**Review by LJQZZZ123 — DISMISSED** [review]

**Review by Timoon21 — DISMISSED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on CoinGecko/ CMC
- [x] No duplication on Jupiter's strict list

**Comment by Timoon21** [comment]
> I'm on the ISKT team with Birkir, wanted to confirm and add some additional Info.
> 
> Further info:
> 
> ISKT metadata (as entered in metaplex) : https://github.com/rafmyntasjodur/iskt-metadata
> 
> Our github: https://github.com/rafmyntasjodur
> 
> Our website: https://mintum.is
> 
> Our company "Rafmyntasjóður Íslands" is a registered crypto service provider with the Icelandic national bank. Proof: https://www.sedlabanki.is/utgefid-efni/frettir-og-tilkynningar/frettasafn/frett/2022/07/08/Rafmyntasjodur-Islands-ehf.-skrad-sem-thjonustuveitandi-syndareigna/
> 
> Article in Icelandic newspaper on the founders: https://www.vb.is/frettir/gefa-ut-islenska-rafkronu/

Feel free to come and pitch your project here.
https://discord.gg/jup   #token-discussion channel

**Pull request merged**
