### PR TITLE
Validate LST

### PR DESCRIPTION
**Pull request by edgarpavlovsky**
# Validate [LST](https://solscan.io/token/LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/marginfi/status/1706378726622060649
- Coingecko/ CMC URL (If available): Still working to get coingecko set up for LST

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter. (update: this is coming momentarily, will update here)
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by 0xmustapha** [comment]
[x] Mint address: LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp
[x] Symbol: LST
[x] Token Decimals: 9
[x] Token icon: https://storage.googleapis.com/static-marginfi/lst.png
[x] On-chain metadata matches

**Comment by sumptuosol** [comment]
we implore Jupiter aggregator team to help validate $LST. we believe this is the right thing to do in driving the ecosystem and adoption forward. $LST is a new liquid staking token powered by jito-solana client to maximize MEV rewards. mrgn labs is very committed to this new product. Thanks for your usual cooperation.

**Comment by sumptuosol** [comment]
[x] Mint address: LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp
[x] Symbol: LST
[x] Token Decimals: 9
[x] Token icon: https://storage.googleapis.com/static-marginfi/lst.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by jkbpvsc** [comment]
[x] Mint address: LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp
[x] Symbol: LST
[x] Token Decimals: 9
[x] Token icon: https://storage.googleapis.com/static-marginfi/lst.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by SOELTH** [comment]
[x] Mint address: LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp
[x] Symbol: LST
[x] Token Decimals: 9
[x] Token icon: https://storage.googleapis.com/static-marginfi/lst.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by buddhanft** [comment]
[x] Mint address: LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp
[x] Symbol: LST
[x] Token Decimals: 9
[x] Token icon: https://storage.googleapis.com/static-marginfi/lst.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Pull request merged**
