### PR TITLE
Add GUARD OF DECENT (GODEX) to validated-tokens.csv

### PR DESCRIPTION
**Pull request by guardianofdecentralization**
# Validate [GODEX](https://solscan.io/token/GoDCaGctsLDnkV8T6jBAfTeMj8DesxT71CkZekV5ZXcf)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/guardofdecent/status/1799696694558544051
- Coingecko URL: https://www.coingecko.com/en/coins/guard-of-decent
- CMC URL: https://coinmarketcap.com/dexscan/de/solana/HKzoW96kaweMKvxQNUr3f6vJ37K8aQWqmLEYHx8Akzp8/

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by guardianofdecentralization** [comment]
Dear GitHut Team,

I would like to bring to your attention an issue regarding a token on Jupiter. The token works perfectly on Birdeye and Raydium, but its name has not been updated on Jupiter. Despite the correct information being listed in the "all list" file on your server, the platform still displays the old name.

Token: GoDCaGctsLDnkV8T6jBAfTeMj8DesxT71CkZekV5ZXcf

Old Name: Guardian of Decentralization (GoD)
New Name: GUARD OF DECENT (GODEX)

The reason for this change was to ensure the TICKER is unique. GODEX stands for Guardian of Decentralization Exchange.

I would appreciate it if you could look into this issue briefly. Thank you in advance for your prompt and professional handling of this matter. There's no ticker issue on Birdeye and Raydium.


Best regards from Switzerland,
Genesis

References:
1of4 birdeye (good)
4of5 jupiter (wrong)
2of4 raydium (good)
3of4 jup all list (good)

**Comment by guardianofdecentralization** [comment]
We are checking with solana.fm the issue with the old entry now, however we are not able to join into your discord channel. The account is fresh, no interaction had before, have a look please, we get error:
"Einladung kann nicht angenommen werden" (invitation can not be assumed) 

Thanks very much in advance.

no discord
jup issue

**Comment by guardianofdecentralization** [comment]
We are now on Coingecko:
https://www.coingecko.com/en/coins/guard-of-decent

**Comment by guardianofdecentralization** [comment]
In the meanwhile coinmarketcap (CMC) listed us automatically too:
https://coinmarketcap.com/dexscan/de/solana/HKzoW96kaweMKvxQNUr3f6vJ37K8aQWqmLEYHx8Akzp8/

**Comment by 9yoi** [comment]
This token has been submitted to our new site at https://catdetlist.jup.ag/pending and will be handled there

If you have questions, please stop by our token-list channel in discord

**Pull request closed without merging**
