### PR TITLE
Validate $TRUMP (Make Solana Great Again)

### PR DESCRIPTION
**Pull request by Make-Solana-Great-Again**
# Validate $TRUMP https://solscan.io/token/A1gAnCfwfKpoqFoAAxDLuwxSGQZfNo1eSRi8TfyrbV28
## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/MSGAcoin/status/1751019130017534064
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/make-solana-great-again
## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Make-Solana-Great-Again** [comment]
- [X] Mint address: A1gAnCfwfKpoqFoAAxDLuwxSGQZfNo1eSRi8TfyrbV28
- [X]  Symbol: $TRUMP
- [X] Token Decimals: 7
- [X]  Token icon: https://bafkreiaxrodehtevurgmj4574zqlzwgs6e4gou3zusjugvjnrjaxfw3zjq.ipfs.nftstorage.link
- [X] On-chain metadata matches
- [X] No duplication on Jupiter's strict list

**Comment by Gleggans** [comment]
- [X] Mint address: A1gAnCfwfKpoqFoAAxDLuwxSGQZfNo1eSRi8TfyrbV28
- [X]  Symbol: $TRUMP
- [X] Token Decimals: 7
- [X]  Token icon: https://bafkreiaxrodehtevurgmj4574zqlzwgs6e4gou3zusjugvjnrjaxfw3zjq.ipfs.nftstorage.link
- [X] On-chain metadata matches
- [X] No duplication on Jupiter's strict list

**Comment by kuyajoy** [comment]
- [X] Mint address: A1gAnCfwfKpoqFoAAxDLuwxSGQZfNo1eSRi8TfyrbV28
- [X]  Symbol: $TRUMP
- [X] Token Decimals: 7
- [X]  Token icon: https://bafkreiaxrodehtevurgmj4574zqlzwgs6e4gou3zusjugvjnrjaxfw3zjq.ipfs.nftstorage.link
- [X] On-chain metadata matches
- [X] No duplication on Jupiter's strict list

**Review by Gleggans — COMMENTED** [review]
- [X] Mint address: A1gAnCfwfKpoqFoAAxDLuwxSGQZfNo1eSRi8TfyrbV28
- [X]  Symbol: $TRUMP
- [X] Token Decimals: 7
- [X]  Token icon: https://bafkreiaxrodehtevurgmj4574zqlzwgs6e4gou3zusjugvjnrjaxfw3zjq.ipfs.nftstorage.link
- [X] On-chain metadata matches
- [X] No duplication on Jupiter's strict list

**Comment by kuyajoy** [comment]
- [X] Mint address: A1gAnCfwfKpoqFoAAxDLuwxSGQZfNo1eSRi8TfyrbV28
- [X]  Symbol: $TRUMP
- [X] Token Decimals: 7
- [X]  Token icon: https://bafkreiaxrodehtevurgmj4574zqlzwgs6e4gou3zusjugvjnrjaxfw3zjq.ipfs.nftstorage.link
- [X] On-chain metadata matches
- [X] No duplication on Jupiter's strict list

**Comment by tnbosshogg** [comment]
Mint address: A1gAnCfwfKpoqFoAAxDLuwxSGQZfNo1eSRi8TfyrbV28
 Symbol: $TRUMP
 Token Decimals: 7
 Token icon: https://bafkreiaxrodehtevurgmj4574zqlzwgs6e4gou3zusjugvjnrjaxfw3zjq.ipfs.nftstorage.link/
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by DeezyEllis** [comment]
- [X] Mint address: A1gAnCfwfKpoqFoAAxDLuwxSGQZfNo1eSRi8TfyrbV28
- [X]  Symbol: $TRUMP
- [X] Token Decimals: 7
- [X]  Token icon: https://bafkreiaxrodehtevurgmj4574zqlzwgs6e4gou3zusjugvjnrjaxfw3zjq.ipfs.nftstorage.link
- [X] On-chain metadata matches
- [X] No duplication on Jupiter's strict list

**Review by DeezyEllis — COMMENTED** [review]
- [X] Mint address: A1gAnCfwfKpoqFoAAxDLuwxSGQZfNo1eSRi8TfyrbV28
- [X]  Symbol: $TRUMP
- [X] Token Decimals: 7
- [X]  Token icon: https://bafkreiaxrodehtevurgmj4574zqlzwgs6e4gou3zusjugvjnrjaxfw3zjq.ipfs.nftstorage.link
- [X] On-chain metadata matches
- [X] No duplication on Jupiter's strict list

**Comment by CryptoHermit** [comment]
- [X] Mint address: A1gAnCfwfKpoqFoAAxDLuwxSGQZfNo1eSRi8TfyrbV28
- [X]  Symbol: [$TRUMP](https://twitter.com/search?q=%24TRUMP&src=cashtag_click)
- [X] Token Decimals: 7
- [X]  Token icon: https://bafkreiaxrodehtevurgmj4574zqlzwgs6e4gou3zusjugvjnrjaxfw3zjq.ipfs.nftstorage.link
- [X] On-chain metadata matches
- [X] No duplication on Jupiter's strict list

**Comment by Kar-muh** [comment]
- [X] Mint address: A1gAnCfwfKpoqFoAAxDLuwxSGQZfNo1eSRi8TfyrbV28
- [X]  Symbol: [$TRUMP](https://twitter.com/search?q=%24TRUMP&src=cashtag_click)
- [X] Token Decimals: 7
- [X]  Token icon: https://bafkreiaxrodehtevurgmj4574zqlzwgs6e4gou3zusjugvjnrjaxfw3zjq.ipfs.nftstorage.link
- [X] On-chain metadata matches
- [X] No duplication on Jupiter's strict list

**Comment by wealthedge** [comment]
- [X] Mint address: A1gAnCfwfKpoqFoAAxDLuwxSGQZfNo1eSRi8TfyrbV28
- [X]  Symbol: $TRUMP
- [X] Token Decimals: 7
- [X]  Token icon: https://bafkreiaxrodehtevurgmj4574zqlzwgs6e4gou3zusjugvjnrjaxfw3zjq.ipfs.nftstorage.link
- [X] On-chain metadata matches
- [X] No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
Insufficient volume

**Pull request closed without merging**
