### PR TITLE
Validate HARAMBE

### PR DESCRIPTION
**Pull request by tactokal**
# Validate [HARAMBE](https://solscan.io/token/Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/harambeonsolana/status/1751759710330515542?s=20
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/harambe-on-solana

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by tactokal** [comment]
@maintainers please let me know if I should have the dollar sign in front of the token name or not - I saw $WIF used it, but some other projects didn't

**Comment by 200horsemeat** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by etrmx** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by jap-source** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by harambefan** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by dracon1000** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by MERK001** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by amosburto** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by JBizzy69** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by Wastedgetech** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by jefe1** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by Chumhynft** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by Harambe1** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by KillerGasy** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by isarisariver** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by Serloudegen** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by SEANGMN8** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by solarnius** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Comment by LONGLIVEHARAMBE** [comment]
I can hereby attest that the provided information are accurate, and the token is valid

[x] Mint address: Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP
[x] Symbol: HARAMBE
[x] Token Decimals: 9
[x] Token icon: https://turquoise-worried-llama-208.mypinata.cloud/ipfs/QmSsf1AHHx56hyR66DrfvohdQ9mwNrXcZc3WYZb3xi9Tfs?pinataGatewayToken=IjmxGjT2wDVCW9f1Vtqqu4mFAuFmeTtF2KuGOPOUmuNDv0IzHYWPG90almZJn1qp
[x] On-chain metadata matches
[x] no duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
