### PR TITLE
Add Race Raiders Rewards(RRR)

### PR DESCRIPTION
**Pull request by team-race**
# Validate [RRR](https://solscan.io/token/3zE4Qmh9hrC4inHynT3aSRzHcWhnxPCHLeN9WWqvoRVz)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange)  and showing community support:   https://twitter.com/RaceGameTeam/status/1640773574582517760
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/dexscan/solana/5GpMNPFcsLd48N4oEaf1c9BrXHbV2n5Sz8oDr22qHToL/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by DogLooksGood** [comment]
Tianshu from RACE Protocol. I confirm that the information is correct.

[ ] Mint address: 3zE4Qmh9hrC4inHynT3aSRzHcWhnxPCHLeN9WWqvoRVz
[ ] Symbol: RRR
[ ] Token Decimals: 9
[ ] Token icon: https://arweave.net/SH106hrChudKjQ_c6e6yd0tsGUbFIScv2LL6Dp-LDiI
[ ] On-chain metadata matches
[ ] No duplication on Jupiter's strict list

**Comment by Linerre** [comment]
Linerre from RACE Protocol and I confirm that the information is correct.

[ ] Mint address: 3zE4Qmh9hrC4inHynT3aSRzHcWhnxPCHLeN9WWqvoRVz
[ ] Symbol: RRR
[ ] Token Decimals: 9
[ ] Token icon: https://arweave.net/SH106hrChudKjQ_c6e6yd0tsGUbFIScv2LL6Dp-LDiI
[ ] On-chain metadata matches
[ ] No duplication on Jupiter's strict list

**Comment by 2907a** [comment]
Was watching cat memes, came across this thread. Here is my 2 pennies

- [x] Mint address: 3zE4Qmh9hrC4inHynT3aSRzHcWhnxPCHLeN9WWqvoRVz
- [x] Symbol: RRR
- [x] Token Decimals: 9
- [x] Token icon: https://arweave.net/SH106hrChudKjQ_c6e6yd0tsGUbFIScv2LL6Dp-LDiI
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by team-race** [comment]
The commit of GM introduced a conflict, just have it fixed. Please review again, thanks!

**Review by Timoon21 — DISMISSED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] No duplication on CMC/CoinGecko
- [x] Community validation

**Pull request merged**
