### PR TITLE
Validate BOOMER

### PR DESCRIPTION
**Pull request by bivsk**
# Validate [BOOMER](https://solscan.io/token/7jmaTFBooHkaSrBJDftu3LcK85KPtqWTCaFZCDxQV7ZW)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Boomer_onsolana/status/1785166528864039138
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/boomers-on-sol

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
your image link is:

https://bafybeicyv3sn4btptwdgptm3cx47xv4nrr7mpnq6kikxwfi5qrvbo4qiiy.ipfs.nftstorage.link

**Comment by bivsk** [comment]
> your image link is:
> 
> https://bafybeicyv3sn4btptwdgptm3cx47xv4nrr7mpnq6kikxwfi5qrvbo4qiiy.ipfs.nftstorage.link

Oh jeez. Thanks, fixing now.

Thought I had copy-pasted from solscan, but not sure what went wrong..

**Comment by 0x6d656d6573** [comment]
CA, twitter, links everything lgtm

**Comment by bivsk** [comment]
Should be all fixed now. Thanks for letting me know.

**Comment by CreggTheEgg** [comment]
the Image URL in the commit now resolves correctly for me. I think this should be all set to review and pass unless Im also missing something.

**Comment by awitherow** [comment]
everything LGTM.

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
