### PR TITLE
Validate DEGEN

### PR DESCRIPTION
**Pull request by soldegen**
# Validate [DEGEN](https://solscan.io/token/5SuHxgTNE8cbCoK4gfQ7LxpiKgrkENVEQmq78FoAr6La)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/soldegen_com/status/1736370179729142023?s=20

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers) - https://coinmarketcap.com/currencies/degen-sol/

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by queiroz** [comment]
- [x] Mint address: 5SuHxgTNE8cbCoK4gfQ7LxpiKgrkENVEQmq78FoAr6La
- [x] Symbol: DEGEN
- [x] Token Decimals: 9
- [x] Token icon: https://raw.githubusercontent.com/soldegen/token/main/assets/token_logo.png
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by blockseekerio** [comment]
- [x] Mint address: 5SuHxgTNE8cbCoK4gfQ7LxpiKgrkENVEQmq78FoAr6La
- [x] Symbol: DEGEN
- [x] Token Decimals: 9
- [x] Token icon: https://raw.githubusercontent.com/soldegen/token/main/assets/token_logo.png
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by nmehta001** [comment]
- [x]  Mint address: 5SuHxgTNE8cbCoK4gfQ7LxpiKgrkENVEQmq78FoAr6La
- [x]  Symbol: DEGEN
- [x]  Token Decimals: 9
- [x]  Token icon: [https://raw.githubusercontent.com/soldegen/token/main/assets/token_logo.png](https://raw.githubusercontent.com/soldegen/token/main/assets/token_logo.png)
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by soldegen** [comment]
Updated PR to include CoinMarketCap listing.

**Review by Timoon21 — APPROVED** [review]

**Comment by soldegen** [comment]
Update: We have been listed on [xt.com/DEGEN_USDT](https://www.xt.com/en/trade/degen_usdt) and CoinGecko submitted.

**Comment by Jymfletzfur** [comment]
insufficient holders and mcap

**Comment by soldegen** [comment]
@Jymfletzfur can you elaborate on holders and mcap? The doc does not specify a minimum what would suffice? 

Perhaps the docs could be updated to detail what is required as looking through the list I see many projects who's gone through with much less

**Pull request closed without merging**
