### PR TITLE
validate MXM

### PR DESCRIPTION
**Pull request by sky-wang**
# Validate [TOKEN_SYMBOL_HERE](https://solscan.io/token/MINT_ADDRES_HERE)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/MixMobOrigin/status/1762187177490883028
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/mixmob

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by semeon** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

- The token address matches the tweet: H53UGEyBrB9easo9ego8yYk7o4Zq1G5cCtkxD3E3hZav
- On-chain metadata matches
- Symbol: MXM
- Token Decimals: 6
- Token icon: https://assets.mixmob.io/images/MXM_Token.png
- Community validation - YES
- No duplication on Jupiter's strict list
- Listed on coingecko

**Comment by vofan** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

- The token address matches the tweet: H53UGEyBrB9easo9ego8yYk7o4Zq1G5cCtkxD3E3hZav
- On-chain metadata matches
- Symbol: MXM
- Token Decimals: 6
- Token icon: https://assets.mixmob.io/images/MXM_Token.png
- Community validation - YES
- No duplication on Jupiter's strict list
- Listed on coingecko

**Comment by julian-mixmob** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.
The token address matches the tweet: H53UGEyBrB9easo9ego8yYk7o4Zq1G5cCtkxD3E3hZav
On-chain metadata matches
Symbol: MXM
Token Decimals: 6
Token icon: https://assets.mixmob.io/images/MXM_Token.png
Community validation - YES
No duplication on Jupiter's strict list
Listed on coingecko

**Review by Jymfletzfur — APPROVED** [review]

**Comment by 9yoi** [comment]
not sure why i couldn't resolve conflicts on this PR so i moved it here: https://github.com/jup-ag/token-list/pull/1812

**Pull request closed without merging**
