### PR TITLE
Validate COMFY

### PR DESCRIPTION
**Pull request by Socomfy**
# Validate [COMFY](https://solscan.io/token/FbJpd8yhrGGkWVL1Ujf7qFvTw4uD4675k8CYk82LEKvZ)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/SoComfyToken/status/1766153175138968062?s=20
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/socomfy

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by entre2o** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.  
  
[x] Mint address: FbJpd8yhrGGkWVL1Ujf7qFvTw4uD4675k8CYk82LEKvZ  
[x] Symbol: COMFY  
[x] Token Decimals: 8  
[x] Token icon: https://assets.coingecko.com/coins/images/34322/standard/comfy_round_logo.png?1704646404 
[x] On-chain metadata matches  
[x] No duplication on Jupiter's strict list

**Comment by SoccaBlyat** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.  
  
[x] Mint address: FbJpd8yhrGGkWVL1Ujf7qFvTw4uD4675k8CYk82LEKvZ  
[x] Symbol: COMFY  
[x] Token Decimals: 8  
[x] Token icon: https://assets.coingecko.com/coins/images/34322/standard/comfy_round_logo.png?1704646404 
[x] On-chain metadata matches  
[x] No duplication on Jupiter's strict list

**Comment by SoccaBlyat** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.  
  
[x] Mint address: FbJpd8yhrGGkWVL1Ujf7qFvTw4uD4675k8CYk82LEKvZ  
[x] Symbol: COMFY  
[x] Token Decimals: 8  
[x] Token icon: https://assets.coingecko.com/coins/images/34322/standard/comfy_round_logo.png?1704646404 
[x] On-chain metadata matches  
[x] No duplication on Jupiter's strict list

**Review by Hydralynx — COMMENTED** [review]
I can confirm that the provided information are correct, and the token is valid. 
 
[x] Mint address: FbJpd8yhrGGkWVL1Ujf7qFvTw4uD4675k8CYk82LEKvZ 
[x] Symbol: COMFY 
[x] Token Decimals: 8 
[x] Token icon: https://assets.coingecko.com/coins/images/34322/standard/comfy_round_logo.png?1704646404
[x] On-chain metadata matches 
[x] No duplication on Jupiter's strict list

**Comment by sakurdi** [comment]
Token has been going strong for two months and recently gained a lot of attention, I think it would benefit everybody if it made it to the strict list. I totally vouch for it

✅ Mint address: FbJpd8yhrGGkWVL1Ujf7qFvTw4uD4675k8CYk82LEKvZ
✅ Symbol: COMFY
✅ Token Decimals: 8
✅ Token icon: https://assets.coingecko.com/coins/images/34322/standard/comfy_round_logo.png?1704646404
✅ On-chain metadata matches
✅ No duplication on Jupiter's strict list

**Comment by samratsakthi** [comment]
Here's the Mint Address link @9yoi 
https://solscan.io/token/FbJpd8yhrGGkWVL1Ujf7qFvTw4uD4675k8CYk82LEKvZ

**Review by Jymfletzfur — APPROVED** [review]

**Comment by samratsakthi** [comment]
@9yoi Can you help us to get into the STRICT list since there are few scammers who are duplicating COMFY. We don't want people to fall for them.

**Comment by samratsakthi** [comment]
@9yoi We need 1 more approval from you to be part of STRICT list. Can you save people from getting scammed.

**Comment by samratsakthi** [comment]
@9yoi Can you help us to get into strict list? We need 1 more approval.

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
