### PR TITLE
Validate CA

### PR DESCRIPTION
**Pull request by vijaypondini**
# Validate [CA](https://solscan.io/token/AfkUkcoJ5Yt7eU9BwnF1RjRqt4fQG5zYV1eS1ytDk7FE)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/contractaddress/status/1743022532599439773
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/contract-address-meme

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by vijaypondini** [comment]
I can validate that this information is accurate

[x] Mint address: AFkUkcoJ5Yt7eU9BwnF1RjRqt4fQG5zYV1eS1ytDk7FE
[x] Symbol: CA
[x] Token Decimals: 9
[x] Token icon: https://imgur.com/a/1A480Gw
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by majimanjii** [comment]
Taking a look over things, the below information should all be correct to the best of my knowledge

- [x] Mint address: AFkUkcoJ5Yt7eU9BwnF1RjRqt4fQG5zYV1eS1ytDk7FE
- [x] Symbol: CA
- [x] Token Decimals: 9
- [x] Token icon: https://imgur.com/a/1A480Gw
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by 0xwastemon** [comment]
Reviewed the information below and everything is correct and accurate.

- [x] Mint address: AFkUkcoJ5Yt7eU9BwnF1RjRqt4fQG5zYV1eS1ytDk7FE
- [x] Symbol: CA
- [x] Token Decimals: 9
- [x] Token icon: https://imgur.com/a/1A480Gw
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Review by ArenaLegends — COMMENTED** [review]
Everything here is correct:

- [x] Mint address: AFkUkcoJ5Yt7eU9BwnF1RjRqt4fQG5zYV1eS1ytDk7FE
- [x] Symbol: CA
- [x] Token Decimals: 9
- [x] Token icon: https://imgur.com/a/1A480Gw
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by maeve2222** [comment]
I double checked and the below information is the right one

- [x] Mint address: AFkUkcoJ5Yt7eU9BwnF1RjRqt4fQG5zYV1eS1ytDk7FE
- [x] Symbol: CA
- [x] Token Decimals: 9
- [x] Token icon: https://imgur.com/a/1A480Gw
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Review by Kognitif — COMMENTED** [review]
I double checked and the below information is the right one

- [x]  Mint address: AFkUkcoJ5Yt7eU9BwnF1RjRqt4fQG5zYV1eS1ytDk7FE
- [x]  Symbol: CA
- [x]  Token Decimals: 9
- [x]  Token icon: https://imgur.com/a/1A480Gw
- [x]  On-chain metadata matches
- [ ]  No duplication on Jupiter's strict list

**Comment by vijaypondini** [comment]
@0xSoju2 would be great if approved! ^^

**Comment by PoloXBT** [comment]
I can validate that this information is accurate

- [x] Mint address: AFkUkcoJ5Yt7eU9BwnF1RjRqt4fQG5zYV1eS1ytDk7FE
- [x] Symbol: CA
- [x] Token Decimals: 9
- [x] Token icon: https://imgur.com/a/1A480Gw
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by vijaypondini** [comment]
@Kognitif @ArenaLegends please review and approve!

**Comment by JoshH265** [comment]
After looking into it. I can validate that this information is accurate

- [x] Mint address: AFkUkcoJ5Yt7eU9BwnF1RjRqt4fQG5zYV1eS1ytDk7FE
- [x] Symbol: CA
- [x] Token Decimals: 9
- [x] Token icon: https://imgur.com/a/1A480Gw
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by KuwaTakushi** [comment]
I can validate that this information is accurate

- [x] Mint address: AFkUkcoJ5Yt7eU9BwnF1RjRqt4fQG5zYV1eS1ytDk7FE
- [x] Symbol: CA
- [x] Token Decimals: 9
- [x] Token icon: https://imgur.com/a/1A480Gw
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Review by Kognitif — COMMENTED** [review]
I double checked and the below information is the right one

- [x]  Mint address: AFkUkcoJ5Yt7eU9BwnF1RjRqt4fQG5zYV1eS1ytDk7FE
- [x]  Symbol: CA
- [x]  Token Decimals: 9
- [x]  Token icon: https://imgur.com/a/1A480Gw
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by vijaypondini** [comment]
@ArenaLegends Waiting on your approval for merge.

**Review by 0xSoju2 — DISMISSED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request closed without merging**
