### PR TITLE
Validate $NINJA

### PR DESCRIPTION
**Pull request by ArashiSol**
# Validate [NINJA](https://solscan.io/token/DFrJxDoLMYt6bNYeNe8Wrjzj2UPUSLZLEMMYBLuTKcTk)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/NINJA_TSS/status/1684994478849892355
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by ArashiSol** [comment]
@Timoon21

**Comment by ArashiSol** [comment]
@meijiao

**Comment by ArashiSol** [comment]
@benlvb

**Comment by nate669** [comment]
Bazaart_20230714_040354_646

**Comment by Nafiusegun** [comment]
Ninja 💚

**Comment by nate669** [comment]
https://www.geckoterminal.com/solana/pools/Q8W6oLSEDiKdyWbSDPpoYUeunC6zowWzg985it5GsUi

**Comment by han1818** [comment]
To the moon NINJA. Verification soon 🚀🥷🐢

**Comment by ednito** [comment]
Solid community,  clear tokenomics and the nfts are cool

**Comment by MJ-ElectricLion1** [comment]
Great community and builders who are Working for the community not for self!

**Comment by lolipeter01** [comment]
Lfg I love Ninja community

**Comment by enf-mankind** [comment]
Great Project

**Comment by Senzify** [comment]
Awesome project! LFNINJA!! 🫡🥷

**Comment by Cann0n666** [comment]
Let's go Ninjas! Strong community and future!

**Comment by lawiyke** [comment]
I am bullish on $NINJA

**Comment by lawiyke** [comment]
Bullish on NINJA

**Comment by Syfgj** [comment]
> # Validate [NINJA](https://solscan.io/token/DFrJxDoLMYt6bNYeNe8Wrjzj2UPUSLZLEMMYBLuTKcTk)
> ## Attestations (Please provide links):
> * Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/NINJA_TSS/status/1684994478849892355
> * Coingecko/ CMC URL (If available): [https://www.coingecko.com/en/coins/{id}](https://www.coingecko.com/en/coins/%7Bid%7D)
> 
> ## Validation (Please check off boxes):
> * [x]  The metadata provided in the PR matches what is on-chain (Mandatory)
> * [x]  Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
> * [ ]  Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)
> 
> ## Acknowledgement (Please check off boxes)
> * [x]  My change matches the format in the file (no spaces between fields).
> * [x]  My token is already live and trading on Jupiter.
> * [x]  !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

Amazing project 👏

**Comment by ArashiSol** [comment]
@Timoon21 LFG ♥️

**Comment by ArashiSol** [comment]
@meijiao

**Review by Timoon21 — DISMISSED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [ ] Symbol duplication on Jupiter's strict list, but different name, different logo
- [x] Community validation

**Comment by ArashiSol** [comment]
@meijiao

**Pull request merged**
