### PR TITLE
added GRAPHITE

### PR DESCRIPTION
**Pull request by razvanwaz**
# Validate [GP](https://solscan.io/token/31k88G5Mq7ptbRDf3AM13HAq6wRQHXHikR8hik7wPygk)

## Attestations:
- Tweet from your Twitter Account attesting the Mint address:https://twitter.com/GraphiteProto/status/1625207656783745025?s=20
- Coingecko/ CMC URL (If available): -

## Validation (Additonal material for reviewers):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will de delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement
- [x] I did not modify unrelated code.
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! This PR will not be reviewed until your project is known by our community. Please drop the PR link in our #token-validation discord channel, introduce your project and get their help to validate you.

### CODE REVIEW

**Comment by LJQZZZ123** [comment]
- [ ] On-chain metadata matches the PR
- [ ] Token address matches the tweet
- [ ] The same token symbol can be searched on CMC/ CoinGecko but seems unrelated
- [ ] No duplication on Jupiter's strict list
- [ ] Known by the community

> https://www.coingecko.com/en/coins/nexus-asa
> https://www.coingecko.com/en/coins/genesis-particle
> https://www.coingecko.com/en/coins/wizards-and-dragons

**Review by LJQZZZ123 — APPROVED** [review]

**Review by Timoon21 — CHANGES_REQUESTED** [review]
Hey, Can you update your PR to match the logo address to the on-chain metadata logo address?
on-chain logo address: https://arweave.net/ALLzymnuIihFPhoNUJpPxQzbGI8LodXKhNzXzbRMPbA

**Comment by razvanwaz** [comment]
> Hey, Can you update your PR to match the logo address to the on-chain metadata logo address? on-chain logo address: https://arweave.net/ALLzymnuIihFPhoNUJpPxQzbGI8LodXKhNzXzbRMPbA

Hi! I've updated the link

**Review by Timoon21 — DISMISSED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the official twitter account
- [x] Duplicated token on CoinGecko but unrelated
- [x] No duplication on the Jupiter's strict list

**Pull request merged**
