### PR TITLE
Validate Sharbi

### PR DESCRIPTION
**Pull request by sharbiarb23**
# Validate [SHARBI](https://solscan.io/token/8D1nUMJQam54o34Kj2knFhSTaWoehEr4mBc7LfiDdCqq)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SharbiToken/status/1783644693781176448
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/sharbi

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by CryptoHero22** [comment]
Excited to see Sharbi on Jupiter!

**Comment by crisnewton** [comment]
Would love to see this on jupiter finance.

**Review by CryptoHero22 — COMMENTED** [review]
Looks good

**Review by sharbiarb23 — COMMENTED** [review]
++

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
