### PR TITLE
Validate Pepe

### PR DESCRIPTION
**Pull request by PepeSPL**
# Validate [Pepe](https://solscan.io/token/B5WTLaRwaUQpKk7ir1wniNB6m5o8GgMrimhKMYan2R6B)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/pepesolanacomm/status/1795522759294063061
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/dexscan/solana/FCEnSxyJfRSKsz6tASUENCsfGwKgkH6YuRn1AMmyHhZn/ https://www.coingecko.com/en/coins/pepe-sol

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by shponglecoinsol** [comment]
Add CoinGecko link. We are already listed there. It helps with review.

**Comment by shponglecoinsol** [comment]
And remove "Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)". It is already added one.

**Comment by shponglecoinsol** [comment]
Remove this mark: "Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)"

Check list. It's already there one with same name if I don't mistake

**Comment by timmaycastags** [comment]
[x] On-chain metadata matches the PR
[x] Token address matches the tweet :  B5WTLaRwaUQpKk7ir1wniNB6m5o8GgMrimhKMYan2R6B
[x] Community validation: I attest
[x] CoinGecko link: https://www.coingecko.com/en/coins/pepe-sol
[x] Symbol: Pepe
[x] Token Decimals: 6

**Review by timmaycastags — COMMENTED** [review]
[x] On-chain metadata matches the PR
[x] Token address matches the tweet : B5WTLaRwaUQpKk7ir1wniNB6m5o8GgMrimhKMYan2R6B
[x] Community validation: I attest
[x] CoinGecko link: https://www.coingecko.com/en/coins/pepe-sol
[x] Symbol: Pepe
[x] Token Decimals: 6

**Review by OctonautBoi — COMMENTED** [review]
[x] On-chain metadata matches the PR
[x] Token address matches the tweet : B5WTLaRwaUQpKk7ir1wniNB6m5o8GgMrimhKMYan2R6B
[x] Community validation: I attest
[x] CoinGecko link: https://www.coingecko.com/en/coins/pepe-sol
[x] Symbol: Pepe
[x] Token Decimals: 6

**Comment by PepeSPL** [comment]
Added Coingecko link and revised conflicts. Thanks!

**Review by PepeSPL — COMMENTED** [review]
Revised the conflicts! Thank you so much!

**Comment by PepeSPL** [comment]
> Add CoinGecko link. We are already listed there. It helps with review.

We appreciate your help. Updated.

**Review by Vladimir110386 — COMMENTED** [review]
[x] On-chain metadata matches the PR
[x] Token address matches the tweet : B5WTLaRwaUQpKk7ir1wniNB6m5o8GgMrimhKMYan2R6B
[x] Community validation: I attest
[x] CoinGecko link: https://www.coingecko.com/en/coins/pepe-sol
[x] Symbol: Pepe
[x] Token Decimals: 6

**Comment by Jymfletzfur** [comment]
PR appears to add multiple tokens at once, please resubmit

**Pull request closed without merging**
