### PR TITLE
add jucySOL

### PR DESCRIPTION
**Pull request by DataKnox**
# Validate [jucySOL](https://solscan.io/token/jucy5XJ76pHVvtPZb5TKRcGQExkwit2P5s4vY8UzmpC#metadata)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: [Tweet](https://x.com/knox_trades/status/1754487374971609121?s=20)
- Coingecko/ CMC URL (If available): Working on Gecko

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by robbestad** [comment]
Don't use shadow drive as image src as it will be broken for users blocked by them

**Comment by DataKnox** [comment]
> Don't use shadow drive as image src as it will be broken for users blocked by them

Shadow Drive blocks users? These arent privately hosted images. I've hosted images for NFT metadata on SDrive without ever having an issue

**Comment by robbestad** [comment]
It's a recent development. I can assure you all shdw drive links you have are broken with my IP range. Further evidence, look at stube.io. It's also in their TOS.

**Comment by DataKnox** [comment]
> It's a recent development. I can assure you all shdw drive links you have are broken with my IP range. Further evidence, look at stube.io. It's also in their TOS.

I see, TIL.

**Pull request closed without merging**
