### PR TITLE
Validate HC

### PR DESCRIPTION
**Pull request by HypercoinHC**
# Validate [HC](https://solscan.io/token/6eQ5a1qhn1v7Q8h7zYHZrfgeAKrVgN7RJgty3ttth6R7)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Hypercoin_sol/status/1643317073874137089
- Coingecko/ CMC URL (If available): On the process in listing HC on coingecko

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by Absidy2134** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: 6eQ5a1qhn1v7Q8h7zYHZrfgeAKrVgN7RJgty3ttth6R7
Symbol: HC
Token Decimals: 4
Token icon: https://bafkreigwterpxjrdsavfxduhffbkgshm6r4z2d76kpj6vti5m76qzl7xxq.ipfs.dweb.link/
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by zionneyui** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: 6eQ5a1qhn1v7Q8h7zYHZrfgeAKrVgN7RJgty3ttth6R7
Symbol: HC
Token Decimals: 4
Token icon: https://bafkreigwterpxjrdsavfxduhffbkgshm6r4z2d76kpj6vti5m76qzl7xxq.ipfs.dweb.link
On-chain metadata matches
No duplication on Jupiter's strict list

**Review by Timoon21 — APPROVED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] No duplication on CMC/CoinGecko
- [x] Community validation

**Comment by LJQZZZ123** [comment]
- [ ] On-chain metadata matches the PR
- [ ] Token address matches the tweet
- [ ] The same token symbol can be searched on CMC but seems unrelated
- [ ] No duplication on Jupiter's strict list
- [ ] Known by the community

**Review by LJQZZZ123 — DISMISSED** [review]

**Comment by HypercoinHC** [comment]
Hi is there someone who can approve on the workflow? And how would this merge?

**Comment by HypercoinHC** [comment]
Hello, any update on this PR? Thank you!

**Comment by meijiao** [comment]
Hi there, your token is already tradable on the All list. For the strict list, we require some degree of community discussion and support, which I don't see yet on your tweets.

**Comment by HypercoinHC** [comment]
> Hi there, your token is already tradable on the All list. For the strict list, we require some degree of community discussion and support, which I don't see yet on your tweets.

Hi, I'm not sure what happened but we we're removed in the all list on Jupiter. We're so pre occupied in applying on coingecko and our NFT minting. Can you re evaluate this? And look into the twitter posts to see the community support. Thank you!

**Comment by meijiao** [comment]
> > Hi there, your token is already tradable on the All list. For the strict list, we require some degree of community discussion and support, which I don't see yet on your tweets.
> 
> Hi, I'm not sure what happened but we were removed in the all list on Jupiter. We're so pre occupied in applying on coingecko and our NFT minting. Can you re-evaluate this? And look into the twitter posts to see the community support. Thank you!

Presence on the all list is automated and your token will appear as long as it meets the liquidity requirements
https://docs.jup.ag/notes/getting-your-token-on-jupiter

**Pull request closed without merging**
