### PR TITLE
Validate of $ANON Token

### PR DESCRIPTION
**Pull request by Pandybary**
# Validate [ANON](https://solscan.io/token/4PEMPJXiYd4THpNuaFTf2zB8jKYJJPoEN86vdvKnjv9R)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/AnonCoinSol/status/1657374688304046082?t=RD9IoBr2DejHFpFam10WTg&s=19
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [✔️] The metadata provided in the PR matches what is on-chain (Mandatory)
- [✔️] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [✔️] My change matches the format in the file (no spaces between fields).
- [✔️] My token is already live and trading on Jupiter.
- [✔️] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by Pandybary** [comment]
Thank you in advance ANON! For the Culture!

**Comment by pythdream** [comment]
$ANON as shown the power of greatness amongst other projects , despite the market volatility and bearish $ANON already proof to the ecosystem that community is the power/core stir to every successful project ..

**Comment by Seedorffits** [comment]
The best community so far is $ANON

**Comment by kikokikokikokikokiko** [comment]
$ANON is for the people

Best community ever

**Comment by Timoon21** [comment]
You should only PR _validated-tokens.csv_ by adding your token at the end of the file.
Not other files. 
I close the PR.
You can recreate the PR with only _validated-tokens.csv_

**Review by Pandybary — COMMENTED** [review]
{"name":"ANON","symbol":"$ANON","image":"https://arweave.net/hSyqZL4l_8wpk291raYcTZlBs0hNzHncklBQWALOB8E","description":"Hi everyone, I'm Anon, I launched my own token today on SOL","creator":{"name":"DEXLAB MINTING LAB","site":"https://www.dexlab.space"}}

**Pull request closed without merging**
