### PR TITLE
Validate DINO

### PR DESCRIPTION
**Pull request by CasperCrypto**
# Validate [{DINO}](https://solscan.io/token/33eWALS9GkzSMS3EsKSdYCsrUiMdQDgX2QzGx4vA9wE8)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/DinoLFG/status/1734310823491949041
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/dinolfg https://coinmarketcap.com/currencies/dinolfg/

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by CasperCrypto** [comment]
Hey, I hope it will be helpful: 

- [X] Mint address: 33eWALS9GkzSMS3EsKSdYCsrUiMdQDgX2QzGx4vA9wE8
- [X] Symbol: DINO
- [X] Token Decimals: 8
- [X] Token icon: https://i.ibb.co/QkXyK80/Dino-Sol-Logo.png
- [X] On-chain metadata matches
- [ ] No duplication on Jupiter's strict list - Different coin with different lofo and name

**Comment by CasperCrypto** [comment]
Hey, @9yoi 

We would appreciate if we can add DinoLFG to Jupiter 🦖💚

Our Community:
https:/t.me/officialDinoLFG
https:/x com/DinoLFG

**Comment by Timoon21** [comment]
Hey @CasperCrypto 
You should make changes and PR only validated-tokens.csv by adding your token at the end of the file.
Dont makes changes on other files.
I close the PR.
You can recreate the PR with validated-tokens.csv changes. You can check other PR as example.

**Comment by CasperCrypto** [comment]
Hey @Timoon21 thanks for help! Opened new PR:
https://github.com/jup-ag/token-list/pull/601

**Pull request closed without merging**
