### PR TITLE
Validate FURBY

### PR DESCRIPTION
**Pull request by bjameson72**
# Validate [FURBY](https://solscan.io/token/34pxeud2ajwJaq7XZrYdvUUGHKJP2dFrAg6k8zvSsigt)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/furbycoinsol/status/1775220116155924861?t=mCv20GqKmfRHVzBlf2PN0w&s=19
- Coingecko/ CMC URL (If available): still working to get coin gecko setup for FURBY

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by jlogank — COMMENTED** [review]
I attest this is the correct address. 
https://x.com/jlogank/status/1775230728110051721?s=20

**Comment by Serv010** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [x] Mint address: 34pxeud2ajwJaq7XZrYdvUUGHKJP2dFrAg6k8zvSsigt
- [x]  Symbol: FURBY
- [x]  Token Decimals: 9
- [x]  Token icon: https://dd.dexscreener.com/ds-data/tokens/solana/34pxeud2ajwJaq7XZrYdvUUGHKJP2dFrAg6k8zvSsigt.png?size=lg&key=108564
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by AkhyarAlham** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

 Mint address: 34pxeud2ajwJaq7XZrYdvUUGHKJP2dFrAg6k8zvSsigt
  Symbol: FURBY
  Token Decimals: 9
  Token icon: https://dd.dexscreener.com/ds-data/tokens/solana/34pxeud2ajwJaq7XZrYdvUUGHKJP2dFrAg6k8zvSsigt.png?size=lg&key=108564
  On-chain metadata matches
  No duplication on Jupiter's strict list

**Comment by prismshadow** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [x] Mint address: 34pxeud2ajwJaq7XZrYdvUUGHKJP2dFrAg6k8zvSsigt
- [x]  Symbol: FURBY
- [x]  Token Decimals: 9
- [x]  Token icon: https://dd.dexscreener.com/ds-data/tokens/solana/34pxeud2ajwJaq7XZrYdvUUGHKJP2dFrAg6k8zvSsigt.png?size=lg&key=108564
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
