### PR TITLE
Validate DinoLFG (DINO)

### PR DESCRIPTION
**Pull request by CasperCrypto**
Added DinoLFG (DINO)

# Validate [DINO](https://solscan.io/token/33eWALS9GkzSMS3EsKSdYCsrUiMdQDgX2QzGx4vA9wE8)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/DinoLFG/status/1734310823491949041
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/dinolfg / https://coinmarketcap.com/currencies/dinolfg

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by CasperCrypto** [comment]
Hey Jup Team, this time should be correct lol. Thanks

@9yoi  @Timoon21

**Comment by CasperCrypto** [comment]
@Timoon21 @9yoi I would appreciate that If we can finalize it! 🦖

$DINO is already 1+ year old
Screenshot_2023-12-27-15-42-46-994_com twitter android-edit

**Comment by CasperCrypto** [comment]
@0xBlackfish @Timoon21 @9yoi

**Comment by CasperCrypto** [comment]
@9yoi @Timoon21 @0xSoju2

**Comment by 0xSoju2** [comment]
It duplicates another existing token.

**Comment by CasperCrypto** [comment]
> It duplicates the symbol of another existing token.

Yeah just ticker. Different contract, different logo, different name (DinoLFG). Biggest dinosaur memecoin. Just bridged to Solana from eth.

I don't see conflict xd

**Pull request closed without merging**
