### PR TITLE
Validate Doraemon - Dorae

### PR DESCRIPTION
**Pull request by TheoDestroyer**
# Validate [DORAE] (https://solscan.io/token/F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/Doraemoncto/status/1807909521886699865
- Coingecko/ CMC URL (If available): Still working to get on CoinGecko and CMC.

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Review by ArdiaX — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: Dorae
Token Decimals: 6
LogoURI: blob: https://imgur.com/bf6f9462-650c-4295-9896-45deb9750229
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Ponzinaire** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: Dorae
Token Decimals: 6
LogoURI: blob: https://imgur.com/bf6f9462-650c-4295-9896-45deb9750229
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by CryptoCat22** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: Dorae
Token Decimals: 6
LogoURI: blob: https://imgur.com/bf6f9462-650c-4295-9896-45deb9750229
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by lorijlh** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: Dorae
Token Decimals: 6
LogoURI: blob: https://i.imgur.com/kIzaxSb.jpeg
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Ponzinaire** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: DORAE
Token Decimals: 6
LogoURI: blob: https://i.imgur.com/kIzaxSb.jpeg
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by ziaul69** [comment]
lol all fake comments

**Comment by J-K100** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: Dorae
Token Decimals: 6
LogoURI: blob: https://i.imgur.com/kIzaxSb.jpeg
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by blockchainjunkie99** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: Dorae
Token Decimals: 6
LogoURI: blob: https://i.imgur.com/kIzaxSb.jpeg
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by blockchainjunkie99** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: Dorae
Token Decimals: 6
LogoURI: blob: https://i.imgur.com/kIzaxSb.jpeg
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Review by blockchainjunkie99 — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: Dorae
Token Decimals: 6
LogoURI: blob: https://i.imgur.com/kIzaxSb.jpeg
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by bezie0** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: Dorae
Token Decimals: 6
LogoURI: blob: https://i.imgur.com/kIzaxSb.jpeg
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by BusyMan1109** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: Dorae
Token Decimals: 6
LogoURI: blob: https://i.imgur.com/kIzaxSb.jpeg
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Teemly** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: Dorae
Token Decimals: 6
LogoURI: blob: https://i.imgur.com/kIzaxSb.jpeg
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by mrmicroeconomy** [comment]
I attest that the provided information is accurate, and the token is valid.
Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: Dorae
Token Decimals: 6
LogoURI: blob: https://i.imgur.com/GnCgs92.jpeg
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by mrmicroeconomy** [comment]
I attest that the provided information is accurate, and the token is valid.
Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: Dorae
Token Decimals: 6
LogoURI: blob: https://i.imgur.com/GnCgs92.jpeg
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by ridvann** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: Dorae
Token Decimals: 6
LogoURI: blob: https://imgur.com/bf6f9462-650c-4295-9896-45deb9750229
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
please come into discord

**Comment by Ponzinaire** [comment]
I attest that the provided information is accurate, and the token is valid.
Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: DORAE
Token Decimals: 6
LogoURI: blob: https://i.imgur.com/GnCgs92.jpeg
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by unidogsolana** [comment]
I attest that the provided information is accurate, and the token is valid.
Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: DORAE
Token Decimals: 6
LogoURI: blob: https://i.imgur.com/GnCgs92.jpeg
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by unidogsolana** [comment]
I attest that the provided information is accurate, and the token is valid.
Mint Address: F6s6hxSW6yWF4h5YBbW28JHLFEGXKYbEmungaTPtpump
Symbol: DORAE
Token Decimals: 6
LogoURI: blob: https://i.imgur.com/GnCgs92.jpeg
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by 9yoi** [comment]
This token has been submitted to our new site at https://catdetlist.jup.ag/pending and will be handled there

If you have questions, please stop by our token-list channel in discord

**Pull request closed without merging**
