### PR TITLE
Validate LIRIK

### PR DESCRIPTION
**Pull request by TraderGucc**
# Validate [LIRIK](https://solscan.io/token/Cc8dDzbxsbVmLx6o5yun9kMGB71MtA8KmkhRNWpv5q6V)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Lirikcoinsol/status/1779973874572046363
- Coingecko/ CMC URL (If available): CG and CMC submitted

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Sucalakafufu — COMMENTED** [review]
[X] Mint address: Cc8dDzbxsbVmLx6o5yun9kMGB71MtA8KmkhRNWpv5q6V
[X] Symbol: LIRIK
[X] Token Decimals: 6
[X] Token icon: https://dd.dexscreener.com/ds-data/tokens/solana/Cc8dDzbxsbVmLx6o5yun9kMGB71MtA8KmkhRNWpv5q6V.png
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by hnisgis — COMMENTED** [review]
Good

**Review by wigger3hunna — COMMENTED** [review]
[X] Mint address: Cc8dDzbxsbVmLx6o5yun9kMGB71MtA8KmkhRNWpv5q6V
[X] Symbol: LIRIK
[X] Token Decimals: 6
[X] Token icon: https://dd.dexscreener.com/ds-data/tokens/solana/Cc8dDzbxsbVmLx6o5yun9kMGB71MtA8KmkhRNWpv5q6V.png
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by hnisgis — COMMENTED** [review]
Good

**Review by Hectolacy — COMMENTED** [review]
[X] Mint address: Cc8dDzbxsbVmLx6o5yun9kMGB71MtA8KmkhRNWpv5q6V
[X] Symbol: LIRIK
[X] Token Decimals: 6
[X] Token icon: https://dd.dexscreener.com/ds-data/tokens/solana/Cc8dDzbxsbVmLx6o5yun9kMGB71MtA8KmkhRNWpv5q6V.png
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by Hectolacy — COMMENTED** [review]
[X] Mint address: Cc8dDzbxsbVmLx6o5yun9kMGB71MtA8KmkhRNWpv5q6V
[X] Symbol: LIRIK
[X] Token Decimals: 6
[X] Token icon: https://dd.dexscreener.com/ds-data/tokens/solana/Cc8dDzbxsbVmLx6o5yun9kMGB71MtA8KmkhRNWpv5q6V.png
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
