### PR TITLE
validate ZOOMER

### PR DESCRIPTION
**Pull request by rhlsthrm**
# Validate [ZOOMER](https://solscan.io/token/nBZEcHSG771mRbi4y2sSgKjfDUH8jsM2Eo5fNcASLeU)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/ZoomerCoin/status/1753041956836385204
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/zoomer

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by robbestad** [comment]
Use a decentralized storage network for the token image (arweave or ipfs)

**Comment by rhlsthrm** [comment]
The token image is not set in metadata, it's a Wormhole token so it's set with that @robbestad

**Comment by robbestad** [comment]
Well, ok, I always think it's better to have it on something like ipfs or arweave, but regardless, everything looks good otherwise

✅ Change matches the format in the file
✅ Decimals match (8)
✅ Token address matches (nBZEcHSG771mRbi4y2sSgKjfDUH8jsM2Eo5fNcASLeU)
✅ Is tradeable on Jupiter 
✅ On-chain metadata matches
✅ No duplication on Jupiter's strict list

**Comment by rhlsthrm** [comment]
I'd love to but unfortunately we have no control over the metadata. I've brought this up with Wormhole as well.

**Comment by Jymfletzfur** [comment]
insufficient volume, mcap

**Comment by rhlsthrm** [comment]
@Jymfletzfur this is a cross-chain token with mcap and volume spread across 6 chains! Can it be reconsidered?

**Comment by scara89** [comment]
An other fake ZOOMER is rugging on solana, just because the real ZOOMER it’s not being updated and displayed properly 🙏 
IMG_9738

**Comment by rhlsthrm** [comment]
Correct, @Jymfletzfur we see other scam ZOOMER tokens pop up and they display data correctly.

**Comment by Jymfletzfur** [comment]
Come into the Discord

**Pull request merged**
