### PR TITLE
Adding $LC Lion Cat

### PR DESCRIPTION
**Pull request by chiefblackf00t**
# Validate [LC](https://solscan.io/token/5HJ3fCrCXUEEraLJUBLvhbNwSYS2RNzjuuS33FLH7UjP)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/LionCatOnSolana/status/1775201302147908048?s=20
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/dexscan/solana/HAA8cxfs9Hies47YiWa7ksF3fmyuRfdsxdBC8U9rNF5R/

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by chiefblackf00t** [comment]
Can we get this approved please

**Comment by chiefblackf00t** [comment]
Hello, may we please get this approved?

**Review by Jymfletzfur — APPROVED** [review]

**Comment by chiefblackf00t** [comment]
Hello, is there an issue? I do not see any relevant output in the build job that failed...

**Review by 9yoi — APPROVED** [review]

**Review by 9yoi — CHANGES_REQUESTED** [review]
Please change your token url -- it should match your onchain metadata image

**Comment by chiefblackf00t** [comment]
This is updated now @9yoi

**Comment by chiefblackf00t** [comment]
> Please change your token url -- it should match your onchain metadata image

This is complete

**Comment by chiefblackf00t** [comment]
Can we get this approved and merged?

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
