### PR TITLE
Update CZOL - Image,Name

### PR DESCRIPTION
**Pull request by Usama-Abbasi**
# Validate [CZOL](https://solscan.io/token/AUwugnCh1tFc5scRHLNqnHjfcRbHRsq7yrKFUe7Ysmgs)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support:https://x.com/czol_wtf/status/1793189239183561132
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/czolana

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by shakkaist — COMMENTED** [review]
CZOLANA name and symbol both are CZOL. However, in PR it is different. check please

**Comment by Usama-Abbasi** [comment]
Name updated

**Review by shakkaist — COMMENTED** [review]
looks good to me

**Comment by shakkaist** [comment]
Looks good to me

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
