### PR TITLE
Validate PEEP

### PR DESCRIPTION
**Pull request by Peepo2023**
# Validate [{PEEP}](https://solscan.io/token/n54ZwXEcLnc3o7zK48nhrLV4KTU5wWD4iq7Gvdt5tik)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/PeepoCoinOnSOL/status/1721590109915521204
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by Timoon21** [comment]
I dont see enough community support on tweeter for now. Can you try to get more support?

**Comment by Peepo2023** [comment]
We are currently sending out airdrops and it should gain traction here soon.

**Comment by Peepo2023** [comment]
Hey @Timoon21 wondering if you can take another look at this please.

**Comment by Peepo2023** [comment]
https://www.coingecko.com/en/coins/peepo-sol

**Review by Timoon21 — APPROVED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] Community validation

**Pull request merged**
