### PR TITLE
BRETT Token Validation

### PR DESCRIPTION
**Pull request by defiantmouse**
# Validate [BRETT](https://solscan.io/token/DxtssVdyYe4wWE5f5zEgx2NqtDFbVL3ABGY62WCycHWg)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: [Tweet URL](https://twitter.com/Brett_Solana/status/1743790946431447454?s=20)

- Coingecko URL: https://www.coingecko.com/en/coins/brett 
- CMC URL: https://coinmarketcap.com/dexscan/solana/AyjpwPZVkEqN6r4R9MyzkqcdzW1LwsBppuV8Ns55Mqvb
- Telegram URL: https://t.me/BrettSolana
- Other links available here (Should anymore validation be needed): https://linktr.ee/brettsolana OR https://brett.fyi

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by defy93** [comment]
Hey guys, I am not a contributor but can confirm that all of the details above are correct. 

`Mint address: DxtssVdyYe4wWE5f5zEgx2NqtDFbVL3ABGY62WCycHWg`

**Comment by Quad-zy** [comment]
I attest the above information is correct.

Ticker : $BRETT
Contract address: DxtssVdyYe4wWE5f5zEgx2NqtDFbVL3ABGY62WCycHWg

https://www.coingecko.com/en/coins/brett

**Review by satoshi-testaccount — COMMENTED** [review]
This is correct for BRETT on SOLANA

**Comment by eip-4844** [comment]
the information for Brett is correct

Ticker: $Brett

CA: DxtssVdyYe4wWE5f5zEgx2NqtDFbVL3ABGY62WCycHWg

X:
https://x.com/brett_solana?s=21&t=qCR3PY_1RUb3HYJamJsiYw

CMC:
https://coinmarketcap.com/currencies/brett-token/

CoinGecko:
https://www.coingecko.com/de/munze/brett

www:
brett.fyi

linktree:
linktr.ee/brettsolana

**Review by 0xSoju2 — APPROVED** [review]

**Pull request merged**
