### PR TITLE
Validate PUP

### PR DESCRIPTION
**Pull request by puppymeme**
# Validate [PUP](https://solscan.io/token/8PsMC8QfL4XQksjvhB3rwPUA5c78pDNY3VBzusdABt7w)

Name: Puppy Meme
Symbol: PUP
Mint Address: 8PsMC8QfL4XQksjvhB3rwPUA5c78pDNY3VBzusdABt7w
Decimals: 2
Logo URL: https://raw.githubusercontent.com/puppymeme/Puppy-Meme/main/Puppy%20Meme_Logo%202_Trans_500x500.png
Tweet: https://twitter.com/puppymemetoken/status/1751176733225799721
Community Validated:true

Attestations (Please provide links):
Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: (https://twitter.com/puppymemetoken/status/1751176733225799721)
Coingecko/ CMC URL (If available): Request sent
Validation (Please check off boxes):
[v] The metadata provided in the PR matches what is on-chain (Mandatory)
[v] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
[ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)
Acknowledgement (Please check off boxes)
[v] My change matches the format in the file (no spaces between fields).
[v] My token is already live and trading on Jupiter.
[v] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
[v] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by jaymorgan90** [comment]
Change the name and it's a good win for me

**Comment by saolatoken** [comment]
Good to see on listed

**Comment by teumemecoin** [comment]
Hope you love KIT together

**Comment by kittymeme** [comment]
Hello PUP my best friend

**Comment by Jymfletzfur** [comment]
Has 2 holders, no volume.

**Pull request closed without merging**
