### PR TITLE
Tzu Token

### PR DESCRIPTION
**Pull request by TzuToken**
# Validate [TZUTO](https://solscan.io/token/Q4V3rb1jxJwBZfpGCWeujZEo4ZTe4XmhP2p1LNgg6Y1)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/TzuToken/status/1742696465754173485?s=20
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by TzuToken** [comment]
Hello! Thank you for your consideration! In case of questions or remarks, please let us know here or other option: Telegram @TzuTokenAdmin. Have a great day!

**Comment by TzuToken** [comment]
Let me know how I can support to remove obstacles before token can be validated please?

**Comment by TzuToken** [comment]
@benchow @benlvb Hi, could you let us know how our project (https://tzutoken.dog) can get reviewed for approval/token validation? Thank you so much!

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
