### PR TITLE
Digital pound coin

### PR DESCRIPTION
**Pull request by Digitalpoundcoin**
# Validate [DPC](https://solscan.io/token/AG5UpqUR7zhfK7wYK6jsAwYQqwsnCSFSgeubw4HjbBSX )

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange] https://twitter.com/digitalpoundc/status/1757543518157918691?t=lp6iqkjVDNeRRnlOFSd4UQ&s=19  and showing community support: https://twitter.com/digitalpoundc/status/1753952106321518606?t=iu8F6gUZ-kvWakr_d4Q5LQ&s=19

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ x ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [ x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [ x ] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by JustShabs** [comment]
Everything on the file looks a match and it’s a good project

**Review by JustShabs — COMMENTED** [review]
Approved

**Comment by mhmd2123** [comment]
The project is done nicely, and everything in the file is perfect.

**Comment by mhmd2123** [comment]
Approved

**Comment by jadmer** [comment]
Everything looks fine and good... Its a very good project 🤠

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
