### PR TITLE
Fix simbawifhat image ipfs url

### PR DESCRIPTION
**Pull request by simbawifhat**
Update simbawifhat image link to use the correct image link.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
please come into the discord

**Comment by simbawifhat** [comment]
> please come into the discord

Please share the discord link if you are referring to a specific group.

**Comment by simbawifhat** [comment]
> please come into the discord

@Jymfletzfur - We have posted it in the discussion form and there's not reply yet. Can you share the discord link that you want us to join?

**Comment by Jymfletzfur** [comment]
This is the actual image in metadata:

https://ipfs.io/ipfs/QmTUg6JjcSzRjeZyDgguqVi484dcPk7r6DVbqwxWA4dufa

**Comment by simbawifhat** [comment]
> https://ipfs.io/ipfs/QmTUg6JjcSzRjeZyDgguqVi484dcPk7r6DVbqwxWA4dufa

I can open a new PR with the above link if that's what the preference is.. Let me know. Thanks

**Pull request closed without merging**
