### PR TITLE
NEKO 

### PR DESCRIPTION
**Pull request by ChakaCrypto**
# Validate [NEKO](https://solscan.io/token/6wdbFQAxDVwUdJrZEnnzgPzsZ1NruvLhf9qCvmSD5DLX)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/NekoTotheMoon/status/1795857517899096321
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/neko-coin/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
please use this image link:

https://ipfs.io/ipfs/QmWPQHhRAgsztGEME1TCauuGeyeo7ZhAHY1ShJTx5no9NF

**Comment by ChakaCrypto** [comment]
@Jymfletzfur Thank you for reviewing my PR. I have updated the URL to https://ipfs.io/ipfs/QmWPQHhRAgsztGEME1TCauuGeyeo7ZhAHY1ShJTx5no9NF.

**Review by Leuviah1337x2 — COMMENTED** [review]
Reviewed by team member

**Review by ChakaCrypto — COMMENTED** [review]
Reviewed

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
