### PR TITLE
Validate brainrot

### PR DESCRIPTION
**Pull request by ubokim**
# Validate [rot](https://solscan.io/token/APoM2sXUzdRHTkUjXSsdUheX1wPPdP4HFLotmtRNMU8P)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/brainrot_sol/status/1793397196185907227
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/brainrot

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by ubokim** [comment]
GONtPiSWIAAr0qS

**Comment by BruceBanner0** [comment]
plz validate token sers plz my family ser plz

**Comment by enjinir000** [comment]
had to break my mewing streak to drop this comment , I think it was worth it

**Comment by Acesigma** [comment]
Ser validate rot I want to continue my mewing streak can't stop won't stop.

**Comment by RuffyTaroo** [comment]
image

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
