### PR TITLE
Validate monkeyhaircut

### PR DESCRIPTION
**Pull request by saori-eth**
# Validate [{monk}](https://solscan.io/token/FYa25XnBsXQXAdTnsyKBKd5gZ1VZhChBRF57CqfRxJZX})

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/monkhairsol/status/1736221876169416902

## Validation (Please check off boxes):
- [✔️] ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [✔️] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [✔️ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [ ✔️]] My change matches the format in the file (no spaces between fields).
- [✔️ ] My token is already live and trading on Jupiter.
- [ ✔️] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by testdev1-1** [comment]
Can we get this merged?

**Comment by saori-eth** [comment]
@9yoi Hello, wanted to bump this to at least make sure that the format is correct. Seeing more recent PRs get attention.

**Comment by testdev1-1** [comment]
@9yoi  Would be good to get this looked at, been sitting for a moment

**Comment by virppa** [comment]
Approval or any review comments would be very much appreciated.

**Comment by mikeysolana** [comment]
This really should be added to the strict list.

**Comment by Jymfletzfur** [comment]
already on list

**Pull request closed without merging**
