### PR TITLE
Haribo

### PR DESCRIPTION
**Pull request by Josh00077**
# Validate [TOKEN_SYMBOL_HERE](https://solscan.io/token/CYobWQ73DYiyERWcvgLkYMSzkXn5Vy18JKxidjeqM6oy)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/HariboonSolana/status/1795084452365791445
- Coingecko/ CMC URL (If available): https://www.geckoterminal.com/solana/pools/FZpf3tPf9nqN7VQQDAvakjT11kZHEwFBN1Vd4h9xvrKg

## Validation (Please check off boxes):
- [X ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X ] My change matches the format in the file (no spaces between fields).
- [X ] My token is already live and trading on Jupiter.
- [ X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [ X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
Please come into discord

**Comment by Jymfletzfur** [comment]
Name is Haribo not HARIBO

change image link to this

https://bafkreige4xbv3mefdb4zvjzays47jpz3kqei7pciulislnxb6sqhdx7taq.ipfs.nftstorage.link/

**Comment by Josh00077** [comment]
Hey changes have been made

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Comment by Josh00077** [comment]
Hi when will this show in the strict list ?

**Pull request merged**
