### PR TITLE
Update validated-tokens.csv

### PR DESCRIPTION
**Pull request by nonconforme**
# Validate [NSA](https://solscan.io/token/4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/NsaToken/status/1646313366162481152
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by meijiao** [comment]
PRs will not be reviewed until there is some community engagement and demand on your tweet / discord posts. Please refer to the README, talk to us in discord, and reopen the PR when you're ready. Your token will still be tradable even without being on the strict list.

**Comment by nonolerobotlunaire** [comment]
I confirm the data below of the Nebula Stars Anthill token is valid.

Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
 Symbol: NSA
 Token Decimals: 9
 Token icon: https://cdn.jsdelivr.net/gh/nonconforme/nebula_stars_anthill/nebula_logo.png
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by DavidMicheal007** [comment]
This project is the best you can invest, efforts have been made. This is valid

Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by samirokc** [comment]
nonolerobotlunaire.   
Confirmation  of valid address  of NEBULA STARS ANTHILL  Token  

Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by NSAMoon** [comment]
the token is valid and will be the new revelation on the solana network !! 🚀🚀🚀

Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png

**Comment by hk750315** [comment]
I firmly believe this is a real and great project!

Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by hk750315** [comment]
I firmly believe this is a real and great project! I confirm the data below of the Nebula Stars Anthill token is valid.

Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Mechatron00** [comment]
I have been mining NSA coins in this project since one and half year.I can say this is the beat project and you only have to invest is you time.
Also the support team is best they put their efforts to solve your issue. I am confirming the following data is true and valid.Lets makes it successful. 





Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Haadisco1** [comment]
I can confirm NSA is a valid token 
Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Chirokix** [comment]
Confirmation of valid address of NEBULA STARS ANTHILL Token.
Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Review by Beebzil1 — COMMENTED** [review]
nonolerobotlunaire

**Comment by sherifokee** [comment]
I confirm that Nebula Anthill project is a valid one. It's icon is not copied and has the following valid details:-

Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png
on-chain metadata matches

**Comment by krlmon** [comment]
I confirm that Nebula Anthill project is a valid one. It's icon is not copied and has the following valid details:-

Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png
on-chain metadata matches

**Comment by rhapy01** [comment]
I believe in the integrity of the team and the success of this project.
And I also confirmed that the data of Nebula Star Anthill Token listed below is valid. 

Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Ben-Gz** [comment]
Great project 

Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by amngs46** [comment]
Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Chat1234** [comment]
I am associated with this project for more than 2 years and I am certain that the team behind this is dedicated and talented. My best regards for the future!

Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by Colunk** [comment]
I love NSA token. Is one the best. I am lucky to have participate in this project

**Comment by Colunk** [comment]
Great work... I am a participant with this project. It really meets all the required informations for a good project. The data below is legit.

Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Comment by BoomTwice2510** [comment]
I followed this project from very early, and i confirmed that the project is very legit with a  genuine team behind it.

Mint address: 4CuBdvKbwy1wo8o9sDs7mUQZTL1weKitpBA6X2D5a1nX
Symbol: NSA
Token Decimals: 9
Token icon: https://shdw-drive.genesysgo.net/9UBK6E223iCeBnF5crU4BjydzSNxgzVJsdUhHybjTbxk/nebula_logo.png
On-chain metadata matches
No duplication on Jupiter's strict list

**Pull request closed without merging**
