### PR TITLE
Validate StarShip🚀

### PR DESCRIPTION
**Pull request by StarShipSol**
# Validate [STSHIP](https://solscan.io/token/GHtLF7drbYXGTHX73uSxqPKkJUzDqcBNe2M9fzjJzr3j)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/StarShip_Sol/status/1739105842652164403
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/starship-4

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by StarShipSol** [comment]
The merge conflict has been successfully resolved.

**Comment by StarShipSol** [comment]
@9yoi  Please Validate our pull request. We have done everything correctly. We are seeing other tokens getting validated after our pull request.

**Comment by cmartinezone** [comment]
Please validate the last commit

**Comment by StarShipSol** [comment]
Please validate the last commit

**Comment by StarShipSol** [comment]
@Timoon21 Could you please help us Validate our token?

**Pull request closed without merging**
