### PR TITLE
Validate $BAGS

### PR DESCRIPTION
**Pull request by Lypheal**
# Validate [$BAGS](https://solscan.io/token/{8wbKU77rWVmpfejfXxGVo5H47fyRQHkpWxZnqUT1Vjd3})

## Attestations:
- Tweet Mint Address: https://twitter.com/bags_inu/status/1628495575074185218?s=20
- Coingecko/ CMC URL (If available): https://www.geckoterminal.com/solana/pools/C5EaC2BxgbCU1JUHqc23uqULbsmjFnoSrCZvw5sHdCiu?utm_source=coingecko&utm_medium=referral&utm_campaign=searchresults

## Validation:
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will de delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement
- [x] I did not modify unrelated code.
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and will introduce my project to the community in discord.

### CODE REVIEW

**Comment by LJQZZZ123** [comment]
Token name and image address doesn't matches on-chain metadata.
Token name: $BAGS
On-chain address: https://shdw-drive.genesysgo.net/DzX4XevSiYbmXH9GDQZPVKdEMXiDprvMYBt7LbZ31XhH/image.png

**Comment by Lypheal** [comment]
> 

Commit with update

**Review by Timoon21 — APPROVED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on CoinGecko/ CMC
- [x] No duplication on Jupiter's strict list

**Review by LJQZZZ123 — APPROVED** [review]

**Comment by meijiao** [comment]
Closing this PR because there's no community support shown on the tweet and discord. Please reopen when activity picks up.

**Pull request closed without merging**
