### PR TITLE
Validate CUFF

### PR DESCRIPTION
**Pull request by cuffsol**
# Validate [CUFF](https://solscan.io/token/2VYVwrwSNM8WxbFdPU4KQpZUB9FWCenFFoDqvpHQ7rZE)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/cuffsol/status/1792270503450644683
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/jail-cat-cuff/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by cuffsol** [comment]
Hi Jymfletzfur, This is my first time doing this. Can you please explain why the PR was closed? Thanks

**Comment by cuffsol** [comment]
Hi, Can you please advise if something was done incorrectly?

Thanks,
cuffsol

**Comment by cuffsol** [comment]
I guess It was because title was "main" ... Now been updated

**Comment by cuffsol** [comment]
It's becoming a security risk for people as there are other imitation tokens in the "all" list. We have MC over $2m with 3.55k Holders. We also have Gold checkmark on Twitter. Our volume past 24h is over $1.5m and liquidity around $350k. 

Please advise. 

Thank you

**Comment by Jymfletzfur** [comment]
Use this as your image file:

https://ipfs.io/ipfs/QmPt7Jdh3JMVVdehGq2cnLN8mEqNnByThcuSadmuoYcSzt

**Review by cuffsol — COMMENTED** [review]
URL for image has been updated as per request

**Review by cuffsol — COMMENTED** [review]
I have tried to merge as requested

**Comment by cuffsol** [comment]
@9yoi Hey, anything else I need to do?

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
