### PR TITLE
Please Validate (My Neighbor) Totoro

### PR DESCRIPTION
**Pull request by 4E614EBread**
# Validate Totoro [Totoro](https://solscan.io/token/E1bcNNEiyiTGYuxbNWMsd54tom5WhWXPA6Z1G1QfsQ8d)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/the_ghibli/status/1778111558146728009?s=19
- Coingecko URL: https://www.geckoterminal.com/solana/pools/9yx5tmSrMuNezRHt5hKKXN5e7JnC9gDjUyn7cce9W7tF?utm_source=coingecko&utm_medium=referral&utm_campaign=searchresults
- CMC URL: https://coinmarketcap.com/dexscan/solana/9yx5tmSrMuNezRHt5hKKXN5e7JnC9gDjUyn7cce9W7tF/
- DexScreener URL: https://dexscreener.com/solana/9yx5tmsrmunezrht5hkkxn5e7jnc9gdjuyn7cce9w7tf
- DexTools URL: https://www.dextools.io/app/en/solana/pair-explorer/9yx5tmSrMuNezRHt5hKKXN5e7JnC9gDjUyn7cce9W7tF?t=1712770637855
- RugCheck URL: https://rugcheck.xyz/tokens/E1bcNNEiyiTGYuxbNWMsd54tom5WhWXPA6Z1G1QfsQ8d

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers) 
- [x] Is Listed on DexTools and DexScreener 

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by 4E614EBread** [comment]
Please review PR and Validate My Neighbor Totoro

**Comment by 4E614EBread** [comment]
Devs, may we please validate?

**Comment by Skaturn** [comment]
Please validated this, it would be greatly appreciated!

**Comment by TeeJxyz** [comment]
Hello please help us to continue moving forward in our project and review this PR, thank you!

**Comment by RandomRaine** [comment]
Can we please get validated? Thank you. 🖖

**Comment by 4E614EBread** [comment]
Any updates?

**Comment by 4E614EBread** [comment]
Is there any progress on getting this merged? I can rebase and submit a new PR. Volume low because we've been waiting to launch everything until we see the volatility of halving

**Comment by Skaturn** [comment]
> Is there any progress on getting this merged? I can rebase and submit a new PR. Volume low because we've been waiting to launch everything until we see the volatility of halving 

Bump ^

**Comment by 4E614EBread** [comment]
^ Bump

**Pull request closed without merging**
