### PR TITLE
Validate CATFISH

### PR DESCRIPTION
**Pull request by catfishsolana**
# Validate [CATFISH](https://solscan.io/token/AcY6RWuWKM5NU7BeSE4c4zQxBZpyU7pTLNF3g5DTWUC2)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/catfishonsol/status/1764004743960297500
- Coingecko URL: https://www.coingecko.com/en/coins/catfish
- CMC URL: https://coinmarketcap.com/currencies/catfish-so/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC
https://www.coingecko.com/en/coins/catfish
https://coinmarketcap.com/currencies/catfish-so/

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by SebaSk8r** [comment]
Confirming the above information is correct:

[x] Name: Catfish
[x] Mint address: AcY6RWuWKM5NU7BeSE4c4zQxBZpyU7pTLNF3g5DTWUC2
[x] Symbol: CATFISH
[x] Token Decimals: 6
[x] Token icon: https://bafkreihfebvqaa5tfdn3f7cqjbglrevwtbtkjdbnb5saexehiwcupjhhlm.ipfs.nftstorage.link
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by NunFung** [comment]
All correct

**Comment by NunFung** [comment]
[x] Name: Catfish
[x] Mint address: AcY6RWuWKM5NU7BeSE4c4zQxBZpyU7pTLNF3g5DTWUC2
[x] Symbol: CATFISH
[x] Token Decimals: 6
[x] Token icon: https://bafkreihfebvqaa5tfdn3f7cqjbglrevwtbtkjdbnb5saexehiwcupjhhlm.ipfs.nftstorage.link
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by Nihilor2** [comment]
Confirming the above information is correct:
[x] Name: Catfish
[x] Mint address: AcY6RWuWKM5NU7BeSE4c4zQxBZpyU7pTLNF3g5DTWUC2
[x] Symbol: CATFISH
[x] Token Decimals: 6
[x] Token icon: https://bafkreihfebvqaa5tfdn3f7cqjbglrevwtbtkjdbnb5saexehiwcupjhhlm.ipfs.nftstorage.link/
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by repsejcat** [comment]
Confirming the above information is correct:
[x] Name: Catfish
[x] Mint address: AcY6RWuWKM5NU7BeSE4c4zQxBZpyU7pTLNF3g5DTWUC2
[x] Symbol: CATFISH
[x] Token Decimals: 6
[x] Token icon: https://bafkreihfebvqaa5tfdn3f7cqjbglrevwtbtkjdbnb5saexehiwcupjhhlm.ipfs.nftstorage.link/
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by Butteredsteel** [comment]
Confirming the above information is correct:
[x] Name: Catfish
[x] Mint address: AcY6RWuWKM5NU7BeSE4c4zQxBZpyU7pTLNF3g5DTWUC2
[x] Symbol: CATFISH
[x] Token Decimals: 6
[x] Token icon: https://bafkreihfebvqaa5tfdn3f7cqjbglrevwtbtkjdbnb5saexehiwcupjhhlm.ipfs.nftstorage.link/
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by czechtexan** [comment]
Confirming the above information is correct:

[x] Name: Catfish

[x] Mint address: AcY6RWuWKM5NU7BeSE4c4zQxBZpyU7pTLNF3g5DTWUC2

[x] Symbol: CATFISH

[x] Token Decimals: 6

[x] Token icon: https://bafkreihfebvqaa5tfdn3f7cqjbglrevwtbtkjdbnb5saexehiwcupjhhlm.ipfs.nftstorage.link/

[x] On-chain metadata matches

[x] No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
your submission edits a bunch of other tokens

**Pull request closed without merging**
