### PR TITLE
Validate simbawifhat (SWH)

### PR DESCRIPTION
**Pull request by simbawifhat**
# Validate [SWH](https://solscan.io/token/ASsnSwFhGVREnuN6YmZQKietjprv731BbETDWQsreAwj)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/simbawifhat/status/1772618878973014499?s=20
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/simbawifhat/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by simbawifhat** [comment]
All necessary information has been added. Let us know if there are any questions. Thanks!

**Review by simbawifhat — COMMENTED** [review]
Reviewed and looks good.

**Review by simbawifhat — COMMENTED** [review]
Reviewed and looks good. Let us know if there are any question

**Comment by Jymfletzfur** [comment]
metadata name is simbawifhat

on the application you put Simbawifhat

can you amend so they match?

**Comment by simbawifhat** [comment]
> metadata name is simbawifhat
> 
> on the application you put Simbawifhat
> 
> can you amend so they match?

Amended to reflect the above changes

**Review by Jymfletzfur — APPROVED** [review]

**Comment by simbawifhat** [comment]
@9yoi - Would you be able to approve after reviewing? Would highly appreciate it. Thank you!

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
