### PR TITLE
Validate Bobby

### PR DESCRIPTION
**Pull request by ObjectCrypto**
# Validate [BOBBY](https://solscan.io/token/48yNDqabAvGNfnkhadsV1MAvtp44fFDdHBRBdFhvpump)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/BobbyCatOnSol/status/1806780999000302023
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/dexscan/solana/6pgNsBb4xJdfouzejx7qDYpibgRnLvopivtNGF6XJyys/

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
please come into discord

**Comment by Jymfletzfur** [comment]
ticker is BOBBY all caps

**Comment by ObjectCrypto** [comment]
Oh okay. Do i need to fix that before we can proceed?

**Comment by Jymfletzfur** [comment]
you changed the name not the ticker

**Comment by ObjectCrypto** [comment]
Agh shoot. Okay I just corrected it. 


Sent from Yahoo Mail for iPhone


On Saturday, June 29, 2024, 12:03 PM, Jymfletzfur ***@***.***> wrote:




you changed the name not the ticker

**Review by Jymfletzfur — APPROVED** [review]

**Review by 0xSoju2 — APPROVED** [review]

**Pull request merged**
