### PR TITLE
Donald Trump Jr $DTJR

### PR DESCRIPTION
**Pull request by Bmarutani**
# Validate [$DTJR] (https://solscan.io/token/7G7SMGV9nSG316ykk6iobjMZWa8GZb15Wd25kgaZGTaZ)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/YOUR_ACCOUNT_NAME_HERE/status/YOUR_TWEET_ID_HERE
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
Please come into the discord

**Comment by Bmarutani** [comment]
> Please come into the discord

I was out on vacation. Just got back and obviously saw this. Can I reopen this or do I have to reapply?

**Comment by Bmarutani** [comment]
Im going to re apply right now. Thank you. Please reach out with any questions or concerns.

**Comment by Bmarutani** [comment]
https://x.com/DTJRMemecoin/status/1799692789174903151

here is the link to the twitter (X) post requesting jupiter strict list approval and addition.

**Pull request closed without merging**
