### PR TITLE
Validate Bozo Hybrid

### PR DESCRIPTION
**Pull request by bozocode**
# Validate [Bozo Hybrid](https://solscan.io/token/{EJPtJEDogxzDbvM8qvAsqYbLmPj5n1vQeqoAzj9Yfv3q})

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/BozoSPL20/status/1743273574356377888
- Coingecko - https://www.coingecko.com/en/coins/bozo-hybrid
- Coinmarketcap - https://coinmarketcap.com/currencies/bozohybrid/
- More support - https://twitter.com/PARABOLIT/status/1749757867039563924?s=20

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by randomshinichi** [comment]
Note to team: we already have a $BOZO, we can't have a BOZO! Will update validation script

**Comment by bozocode** [comment]
Hi @randomshinichi,

Would bozoHYBRID be an acceptable name? We think our ticker `bozo` is different from $bozo but if that's a concern happy to choose something else entirely

**Comment by randomshinichi** [comment]
That would be great, thanks.

**Comment by bozocode** [comment]
Made the change. Thank you @randomshinichi 🙏

**Comment by bozocode** [comment]
@randomshinichi I see autovalidation check disappeared from this PR and it now requires 2 approvals. Do you think this is acceptable or I should create a fresh PR with the most recent change?

**Comment by randomshinichi** [comment]
Set community validated column to true please...

**Comment by bozocode** [comment]
@randomshinichi done 🙏

**Comment by CryptoUncleSam** [comment]
hope we can get the second approval soon

**Review by CryptoUncleSam — COMMENTED** [review]
Everything seems okay

**Review by FrassAsass — COMMENTED** [review]
Everything looks good. Looking forward to supporting Jupiter eco!

**Comment by CryptoUncleSam** [comment]
@benlvb can you check? we have everything set up

**Comment by bozocode** [comment]
@randomshinichi you must be super busy with the most anticipated launch from Jupiter. Would appreciate your help in getting this over the line

**Comment by CryptoUncleSam** [comment]
Hello guys. 

Will be nice if some of you are able to review and approve our PR we meet all requirements.

@9yoi @Timoon21 @raccoons-bot @0xSoju2 @ZhengYuTay @julesdamasta

**Comment by Cribsterbozo** [comment]
Hi guys. We are ready to be approved. We've done everything required. 
@9yoi @Timoon21 @raccoons-bot @0xSoju2 @ZhengYuTay @julesdamasta

**Comment by gh28coins** [comment]
Hi all, please let us know what else is needed for full verification. Thank you.

**Comment by randomshinichi** [comment]
Folks, just so you don't feel left out in the cold, there will be changes to this whole token listing process... please stay tuned.

**Comment by FrassAsass** [comment]
Hey @randomshinichi - Appreciate the notice and attention to change in process. I wanted to follow up and get an idea on this as we've had complaints about users buying the wrong bozo because if the way the strict list works. It's a bit of a headache for the end user. 

Wondered if there was anything we could do to speed the process along, especially as [bozoHybrid is now on CMC](https://coinmarketcap.com/currencies/bozohybrid/), and I have notice other coins get added to the strict list in the few days. Please let me know if theres any help I could provide. 

Respect and appreciation to the Jup team.

**Comment by bozocode** [comment]
Hello @randomshinichi. Some tickers seem to have merged recently. Why is that is a new process is being considered? 

We are on CMC, CK. Have a huge social media presence and Jupiter trade volume of over $1M. Not to mention 6000+ holders that are growing daily. Why are we not being included?

**Comment by Cribsterbozo** [comment]
There are lots of complaints regarding buying the wrong bozo. I know, you are very hardworking and jup team has my respect. But I can see lots of new tickers coming. Thank you guys.

**Comment by bozocode** [comment]
@9yoi PS

**Comment by bozocode** [comment]
@0xSoju2 PS

**Comment by bozocode** [comment]
Hey @CryptoUncleSam can you give the Jup devs another shout. Absolutely no idea why this PR is being ignored. Despite having solid growth organically

**Comment by bozocode** [comment]
CMC link added too

**Comment by 9yoi** [comment]
Hey guys your onchain name and symbol doesn't match your PR? If you're trying to validate bozohybrid, that's what the onchain name and symbol should say

**Comment by CryptoUncleSam** [comment]
Hey @9yoi !

We change the pr from bozo to bozo hybrid because 2nd comment say that you already have $BOZO and you can't add bozo
The authority is renounced so no way to change any metadata. Let's change the PR+ again to just bozo

**Comment by randomshinichi** [comment]
> Hello @randomshinichi. Some tickers seem to have merged recently. Why is that if a new process is being considered?
> 
> We are on CMC, CG. Have a huge social media presence and Jupiter trade volume of over $1M+ daily. Not to mention 6000+ holders that are growing daily. Why are we not being included?

It's nothing personal, it's just that devs have been handling token listing requests up until now, and we'd like to hand this process off to maybe a JUP DAO so devs can get back to building.

About the PR, everything LGTM, but I don't have write access to the repo - which is the way it should be, seeing as I'm supposed to work on code and all.

**Comment by CryptoUncleSam** [comment]
Hey @randomshinichi!

You were the one that complain about the symbol been bozo because $BOZO already exist and was to similar:

> Note to team: we already have a $BOZO, we can't have a BOZO! Will update validation script

Then @bozocode ask if he can change on PR as is not possible on-chain because authority is renounce

> Hi @randomshinichi,
> 
> Would bozoHYBRID be an acceptable name? We think our ticker `bozo` is different from $bozo but if that's a concern happy to choose something else entirely


You said is ok


> That would be great, thanks.

Now you say is unacceptable. Like we are trying to get the token whitelisted but seems imposible

**Comment by bozocode** [comment]
Hey @randomshinichi this is getting controversial for no reason. You asked me to change the ticker as other ticker is already taken. This is not a problem for our users. Problem is that when they search for bozo, there's already an imposter who has a lower market cap than us and has literally been a pump and dump

Why are you penalising us for that. When we are willing to take a high road and choose a different ticker on Jupiter's list altogether. On your suggestion. We simply want our users to see that we are suggested when they search for Bozo term. Come on. If you do not have write access on this repo why comment at all. What are you trying to achieve here?

**Comment by bozocode** [comment]
Why was the other bozo allowed in the Jupiter's list considering we have that symbol onchain and have been trading earlier than them?

**Comment by FrassAsass** [comment]
> EDIT: it's unacceptable that the [on-chain metadata](https://solscan.io/token/EJPtJEDogxzDbvM8qvAsqYbLmPj5n1vQeqoAzj9Yfv3q) is different from what was submitted in this PR. In fact, I was mistakenly under the impression that you had changed the symbol to match, but the Solana token's symbol is still bozo, while in this PR you stated that the symbol name is bozoHybrid.

Our ticker, bozo, is inscribed on the blockchain - like carved in stone. It was genesis'd before whatever the other bozo is. Clear as day on chain. 

In the creation of the project the contract was renounced in the interest of fairness and immutability (the ethos of this very space).. similarly one of the ethos on Jupiter listing standard is to prevent users from buying the wrong token - 

> image

...but i can attest, that is exactly what is happening. 

Its hard not to take personally as the instruction we are getting is taking us in circles. The rep literally said: 

> image

Implying to us that a process change would occur and that we should sit tight ... a week or two of silence ... but we look in the repository and see a number of tickers have been added since then. Good for them. Hard to understand for bozo.

With this context and with all due respect @9yoi - what would need to happen to get `bozo` added to the strict list? Let's collaborate a bit here.

**Comment by 9yoi** [comment]
Hey thanks for all the additional context and I'm sorry for the circles that we sent you running around and the poor communication. 

In general, ticker name and symbol should match what is on chain, and we take longer to review duplicate tickers to avoid confusing users.  

Given that your metadata has been frozen, the earlier bozo has a different icon, and you reported the name "Bozo Hybrid" on CMC and coingecko as well, I think it's fair to say that your team has no intention of confusing users. I think it's okay for your token to go in as is.

I will work with the ecosystem working group and our devs to clean up the list and criteria for tokens. Again sorry for the mess, a lot for us to improve on as the meme-coins grew in size recently and we were busy with the JUP launch.

**Review by 9yoi — APPROVED** [review]

**Comment by FrassAsass** [comment]
Thank you @9yoi - Appreciate you hearing us out and looking at the facts. Many thanks.

**Pull request merged**
