### PR TITLE
Validate FUX

### PR DESCRIPTION
**Pull request by sau00**
# Validate [FUX](https://solscan.io/token/pz8KjM9AHRu8MvjEbxHjZ6RwxQjTgxvTtRsaQtCUyQf)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/fuxnous/status/1780820205075316967
- Coingecko/ CMC URL (If available): WIP

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
decimals do not match what is on chain

**Comment by sau00** [comment]
My bad. Fixed

**Comment by sau00** [comment]
@Jymfletzfur don't you mind to recheck?

**Review by Jymfletzfur — APPROVED** [review]

**Comment by smcgrath0** [comment]
Btw there is another $fux that applied before. https://github.com/jup-ag/token-list/pull/2882

**Comment by smcgrath0** [comment]
Screenshot 2024-04-19 at 1 17 56 AM

**Comment by sau00** [comment]
Yeah there are plenty of them. Solana wasn't the first blockchain tbh

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
