### PR TITLE
Validate $SCOT

### PR DESCRIPTION
**Pull request by Muruganandham18**
# Validate [$SCOT](https://solscan.io/token/EoJEyppNNpycP1ZoPnWq6cxwA7mSYpr9T1WXPFyjEzEy)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Fat_Scot/status/1788160149045043303
- Coingecko/ CMC URL (If available): N/A
## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Muruganandham18** [comment]
@Jymfletzfur  Anything need to be done from our side?

**Comment by kawsargeek** [comment]
We want **$SCOT** to be verified on Jupiter dex!

**Comment by moshe-coh** [comment]
we want $SCOT to be verified on jupiter !

**Comment by Racinesimp** [comment]
Kindly list $SCOT jup LFG

**Comment by BigChamp0** [comment]
Kindly do well to verify $Scot on Jupiter! Let's explore new frontiers together."

**Comment by josimarrocha** [comment]
we want $SCOT to be verified on jupiter!

**Comment by 1234tsieb** [comment]
We want $SCOT to be verified on Jupiter

**Comment by pavjoker** [comment]
We want scot to be verified!

**Comment by Muruganandham18** [comment]
> submission does not match metadata exactly, please come into discord

Can you please tell us what not matching

**Comment by Jymfletzfur** [comment]
Use this link for your image:

https://bafybeicd2glggyndv23phiemxco5f3cxsvlgm2a66vrvlthvgmk4loqvra.ipfs.nftstorage.link/%D7%97%D7%AA%D7%95%D7%9C.png

**Comment by Muruganandham18** [comment]
I have updated the image url

**Comment by BigChamp0** [comment]
We want $Scot to be verified on Jupiter

**Pull request closed without merging**
