### PR TITLE
Validate Michelle Obama coin

### PR DESCRIPTION
**Pull request by stepandra**
# Validate [Michelle Obama coin](https://solscan.io/token/BVAyadYfeTQyuQ5K1T3gbdBZgCe5LzLKvYjcKufMLi9P)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/ObamaMamaCoin/status/1804894458233655445
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/dexscan/solana/TuUz1KKBfEgcQoYkPwU3EV1mTcThPbwdHXPPDDWLrKX/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

Additional Information:
- Name: Michelle Obama coin
- Symbol: ObamaMAMA
- Mint Address: BVAyadYfeTQyuQ5K1T3gbdBZgCe5LzLKvYjcKufMLi9P
- Decimals: 6
- LogoURI: https://ipfs.io/ipfs/bafkreiddqb6fpe7kwx4u6qgl5md3snn7sej2bo673glfneakdtql2glety

### CODE REVIEW

**Comment by Pivik97** [comment]
This is a legit project aimed for support of the First Lady President of the United States

**Comment by QQUITS** [comment]
Its not a pyramid or any sort of scam. Real people and real coin. No bots. No rugpulls.

**Comment by sssnya** [comment]
Goooooo ObamaMAMA

**Comment by e-camorra** [comment]
I really appreciate that community aims for real deal with holders!

**Comment by Jymfletzfur** [comment]
ticker is ObamaMAMA

not all caps

**Comment by stepandra** [comment]
> ticker is ObamaMAMA
> 
> not all caps

thanks, fixed!

**Review by stepandra — COMMENTED** [review]
Fixed ticker case

**Comment by Jymfletzfur** [comment]
token falls too much under the holder requirement(184)

**Pull request closed without merging**
