### PR TITLE
Validate EPIK

### PR DESCRIPTION
**Pull request by epikduckcoin**
# Validate [EPIK](https://solscan.io/token/3BgwJ8b7b9hHX4sgfZ2KJhv9496CoVfsMK2YePevsBRw)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: 

Attestation:

https://x.com/epikduckcoin/status/1782378957414817823

Community support:

https://x.com/osf_rekt/status/1782384203419512995
https://x.com/farokh/status/1782390262792110457
https://x.com/osf_rekt/status/1782379248587530300
https://x.com/dustmonkey_/status/1782382850249196005
https://x.com/ape6743/status/1782383893624062335
https://x.com/bosscat1313/status/1782379656097997155
https://x.com/TheSimms/status/1782384963234541899
https://x.com/JamesEdenpw/status/1782385566689960365
https://x.com/EB7/status/1782385607316295879
https://x.com/_DXVIII/status/1782381755686596766
https://x.com/brettymate92/status/1782387013678948733
https://x.com/GeorgeBTurner/status/1782387276263153728
https://x.com/bosscat1313/status/1782387159787258257
https://x.com/PatronReRenaiss/status/1782386771319300508

- Coingecko/ CMC URL (If available): 

https://www.coingecko.com/en/coins/teh-epik-duck
https://coinmarketcap.com/currencies/teh-epik-duck/

Also listed on Bitget, Poloniex, BingX

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by alboley** [comment]
Can confirm the following:

 Contract address:  3BgwJ8b7b9hHX4sgfZ2KJhv9496CoVfsMK2YePevsBRw 
 Symbol:  $EPIk
 Token Decimals:  6
 Token icon:  https://cf-ipfs.com/ipfs/QmcyHeUb7GarRXXgQzWz3dEtKjSjQPQsC2BTjgwDJg2qWs
 
 On-chain metadata matches this.
 No duplication on Jupiter's strict list as far as I can see.
 
 Should I update the original PR with these datails?

**Comment by alboley** [comment]
On reviewing the entry in the csv, this PR is okay as is.

Coingeko listing: https://www.coingecko.com/en/coins/teh-epik-duck

**Review by alboley — COMMENTED** [review]
Updated icon URL

**Review by Jymfletzfur — APPROVED** [review]

**Comment by alboley** [comment]
Info on other listings: 
- https://www.bitget.com/spot/EPIKUSDT
- https://poloniex.com/trade/EPIK_USDT
- https://bingx.com/en-sa/spot/EPIKUSDT

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
