### PR TITLE
MYRA

### PR DESCRIPTION
**Pull request by MYRAwifeofMYRO**
# Validate [{MYRA}](https://solscan.io/token/H1aN3vcvB68eaFPbMkoAss3vnfi4AhP5C2dpnrZzdBc7)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://Twitter.com/myracoinonsol/status/1746372256677421423?s=20
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/myra / https://coinmarketcap.com/currencies/myra

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by MYRAwifeofMYRO** [comment]
kindly tagged Jupiter exchange on Twitter for adding MYRA on strict mode
https://x.com/myracoinonsol/status/1747827000025153634?s=20

**Comment by MYRAwifeofMYRO** [comment]
please validate MYRA #1072

**Comment by MYRAwifeofMYRO** [comment]
@0xSoju2 Kindly Tagging and requesting update $MYRA to Jupiter Strict List , thanks

**Comment by Krelian420** [comment]
Kindly review @9yoi @Timoon21 @0xSoju2
Day 27, very strong community, cex, cmc/cg, strong partnerships.
We have been tagging Jup on twitter, in the token list on discord.

Here to stay!

**Review by Jymfletzfur — APPROVED** [review]

**Review by Jymfletzfur — APPROVED** [review]

**Review by 0xSoju2 — APPROVED** [review]

**Review by 0xSoju2 — APPROVED** [review]

**Review by Jymfletzfur — APPROVED** [review]

**Pull request merged**
