### PR TITLE
Validate LOST

### PR DESCRIPTION
**Pull request by lostonsol**
# Validate [LOST](https://solscan.io/token/4riQPy1yXQ2d1FfzgLy9eJy6yoUdZuQkMj7JsVKr4bGu)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SavingsLost/status/1755193035200065773
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/lost

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by samratsakthi** [comment]
Coingecko link - https://www.coingecko.com/en/coins/lost which got approved within 4 hours of applying for listing $LOST.

**Review by samratsakthi — COMMENTED** [review]
Really love $LOST and looking forward to get this added to the Jupiter Strict list.

**Comment by CGBrad** [comment]
$lost is a solid project.

-  The metadata provided in the PR matches what is on-chain
-  Does not duplicate the symbol of another token on Jupiter's strict list
-  Listed on Coingecko https://www.coingecko.com/en/coins/lost

**Comment by CheeseWiz6** [comment]
The metadata provided in the PR matches what is on-chain
-  Does not duplicate the symbol of another token on Jupiter's strict list
-  Listed on Coingecko https://www.coingecko.com/en/coins/lost

**Comment by 112-xyz** [comment]
Please help us get on Jupiter’s Strict List 🫶


-  The metadata provided in the PR matches what is on-chain
-  Does not duplicate the symbol of another token on Jupiter's strict list
-  Listed on Coingecko https://www.coingecko.com/en/coins/lost

**Comment by Raphcypher97** [comment]
$lost is a solid project.

The metadata provided in the PR matches what is on-chain
Does not duplicate the symbol of another token on Jupiter's strict list
Listed on Coingecko https://www.coingecko.com/en/coins/lost

**Comment by asimneo** [comment]
-  The metadata provided in the PR matches what is on-chain
-  Does not duplicate the symbol of another token on Jupiter's strict list
-  Listed on Coingecko https://www.coingecko.com/en/coins/lost

We are done!

**Comment by MSharizal** [comment]
-  The metadata provided in the PR matches what is on-chain
-  Does not duplicate the symbol of another token on Jupiter's strict list
-  Listed on Coingecko https://www.coingecko.com/en/coins/lost

**Comment by mogmen113** [comment]
This project is legit and more of them are needed to protect the investor.   Please take a look at them. 

-  The metadata provided in the PR matches what is on-chain
-  Does not duplicate the symbol of another token on Jupiter's strict list
-  Listed on Coingecko https://www.coingecko.com/en/coins/lost

**Comment by Philippe35507** [comment]
-  The metadata provided in the PR matches what is on-chain
-  Does not duplicate the symbol of another token on Jupiter's strict list
-  Listed on Coingecko https://www.coingecko.com/en/coins/lost

**Comment by JMCryptor** [comment]
Lost is very important project on Solana. Built to expose bad devs and educate investors on how to avoid bad investments.

**Comment by samratsakthi** [comment]
@9yoi @0xSoju2 @Jymfletzfur Can you help us to add $LOST to get into the strict list so that we can save more people from getting scammed and from rogue devs in-order to save the Solana ecosystem.

**Comment by lostonsol** [comment]
Hi @9yoi just wondering if anything else is needed from our side to be added to Jupiter's strict list. Thanks

**Comment by samratsakthi** [comment]
@9yoi @0xSoju2 @Jymfletzfur Can you help us to add $LOST to get into the strict list so that we can save more people from getting scammed and from rogue devs in-order to save the Solana ecosystem.

**Comment by 0xdukeburger** [comment]
Lost is changing the the SOL eco for the better. Please add!

**Pull request merged**
