### PR TITLE
Validate LOCHI

### PR DESCRIPTION
**Pull request by mdem11**
# Validate [LOCHI](https://solscan.io/token/bF61B872fKSLXGRDzcT8RpE1PeZsfeggTGBfjX5pump)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/lemondoglochi/status/1805524079727738937?t=2DCDFzTWK1headydhf9UpQ&s=19
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/dexscan/solana/8drKR9rctNGiyyDcnVKAB6oorKyvQxZMpTXSfkCEVn9w/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by benjdefi** [comment]
Put $LOCHI into the verified list. TIA

**Comment by Jymfletzfur** [comment]
insufficient mcap

**Comment by benjdefi** [comment]
Hi,

What is the MCAP needed for this?

**Comment by benjdefi** [comment]
I meant the minimum? As we had an initial pump and then it got dumped so now the community is behind it and push the project forward.

**Pull request closed without merging**
