### PR TITLE
DevWifHat

### PR DESCRIPTION
**Pull request by thedevwifhat**
# Validate [DWH](https://solscan.io/account/DEVwHJ57QMPPArD2CyjboMbdWvjEMjXRigYpaUNDTD7o)

## Attestations:
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/thedevwifhat/status/1766092573767000334
- Coingecko/ CMC URL: https://www.geckoterminal.com/solana/pools/CCnsH5aNy3bXPG7nJkguscDqSLNDdQKjayeBFxNsouqi

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by YouKnowEno** [comment]
Can confirm this is the correct mint address

**Comment by metasal1** [comment]
I can confirm this is a legit token with plenty of dev and community support

**Comment by Timadigwe** [comment]
Can confirm this is the correct mint address

**Comment by robbestad** [comment]
✅ Mint address: DEVwHJ57QMPPArD2CyjboMbdWvjEMjXRigYpaUNDTD7o
✅ Symbol: DWH 
✅ Token Decimals: 6
✅ Token icon: https://arweave.net/8axP5eu3H87THPNK3oWV0dJ_-z1zoZGhp-V8LgJ3IBU
✅ On-chain metadata matches 
✅ No duplication on Jupiter's strict list

**Review by randomshinichi — CHANGES_REQUESTED** [review]
always set "community validated" to true - it is true for all tokens not originally on Solana Foundation's token list (no longer maintained)

**Comment by uralandushka** [comment]
It is probable a scam - be aware logo link go to fishing web site in .net domain name.

**Comment by 0xNyk** [comment]
confirming too!

**Comment by thedevwifhat** [comment]
> always set "community validated" to true - it is true for all tokens not originally on Solana Foundation's token list (no longer maintained)

Done

**Comment by justBKhere** [comment]
✅ Mint address: DEVwHJ57QMPPArD2CyjboMbdWvjEMjXRigYpaUNDTD7o
✅ Symbol: DWH 
✅ Token Decimals: 6
✅ Token icon: https://arweave.net/8axP5eu3H87THPNK3oWV0dJ_-z1zoZGhp-V8LgJ3IBU
✅ On-chain metadata matches 
✅ No duplication on Jupiter's strict list

**Comment by 0xNyk** [comment]
✅ Mint address: DEVwHJ57QMPPArD2CyjboMbdWvjEMjXRigYpaUNDTD7o
✅ Symbol: DWH 
✅ Token Decimals: 6
✅ Token icon: https://arweave.net/8axP5eu3H87THPNK3oWV0dJ_-z1zoZGhp-V8LgJ3IBU
✅ On-chain metadata matches 
✅ No duplication on Jupiter's strict list

**Comment by 0xNyk** [comment]
merge pls

**Comment by 0xNyk** [comment]
bump

**Comment by ags-solutions** [comment]
✅ Mint address: DEVwHJ57QMPPArD2CyjboMbdWvjEMjXRigYpaUNDTD7o
✅ Symbol: DWH 
✅ Token Decimals: 6
✅ Token icon: https://arweave.net/8axP5eu3H87THPNK3oWV0dJ_-z1zoZGhp-V8LgJ3IBU
✅ On-chain metadata matches 
✅ No duplication on Jupiter's strict list

**Comment by justBKhere** [comment]
Confirming! Please bump it

**Comment by ghulamMustafaRaza** [comment]
@randomshinichi any update here ser

**Comment by 0xNyk** [comment]
@randomshinichi PR is merged - this one ready to go now

**Comment by thedevwifhat** [comment]
We resolved the conflict, Please merge. Thanks @randomshinichi

**Review by 0xSoju2 — APPROVED** [review]

**Review by 0xSoju2 — APPROVED** [review]

**Review by Jymfletzfur — APPROVED** [review]

**Pull request merged**
