### PR TITLE
Validate SMURF

### PR DESCRIPTION
**Pull request by smurfonsol**
# Validate [SMURF](https://solscan.io/token/EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SmurfOnSolana/status/1771936354995224598
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/real-smurf-cat-sol/

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by TraderGucc** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
[X] Symbol: SMURF
[X] Token Decimals: 6
[X] Token icon: https://dd.dexscreener.com/ds-data/tokens/solana/EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7.png
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Comment by adteth** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
- [X] Symbol: SMURF
- [X] Token Decimals: 6
- [X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
- [X] On-chain metadata matches
- [X] No duplication on Jupiter's strict list
- [X] Twitter: https://twitter.com/SmurfOnSolana/status/1771936354995224598

**Comment by cipibravo** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
- [X] Symbol: SMURF
- [X] Token Decimals: 6
- [X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
- [X] On-chain metadata matches
- [X] No duplication on Jupiter's strict list
- [X] Twitter: https://twitter.com/SmurfOnSolana/status/1771936354995224598

**Comment by SchnitzelNFT** [comment]
can hereby attest that the provided information are accurate, and the token is valid.

 Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
 Symbol: SMURF
 Token Decimals: 6
 Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
 On-chain metadata matches
 No duplication on Jupiter's strict list
 Twitter: https://twitter.com/SmurfOnSolana/status/1771936354995224598

**Comment by Chefkingpin** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
- [X] Symbol: SMURF
- [X] Token Decimals: 6
- [X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
- [X] On-chain metadata matches
- [X] No duplication on Jupiter's strict list
- [X] Twitter: https://twitter.com/SmurfOnSolana/status/1771936354995224598

**Review by TraderGucc — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

[X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
[X] Symbol: SMURF
[X] Token Decimals: 6
[X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by chaimidan — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

[X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
[X] Symbol: SMURF
[X] Token Decimals: 6
[X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Comment by NICOSISS** [comment]
I can clearly see that this token is valid

**Review by Chefkingpin — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

[X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
[X] Symbol: SMURF
[X] Token Decimals: 6
[X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Comment by NICOSISS** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
[X] Symbol: SMURF
[X] Token Decimals: 6
[X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by NICOSISS — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

[X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
[X] Symbol: SMURF
[X] Token Decimals: 6
[X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by Chefkingpin — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

[X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
[X] Symbol: SMURF
[X] Token Decimals: 6
[X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by cloudstrife1994 — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

[X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
[X] Symbol: SMURF
[X] Token Decimals: 6
[X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by Sucalakafufu — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

[X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
[X] Symbol: SMURF
[X] Token Decimals: 6
[X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by charlesbarkley420 — COMMENTED** [review]
> I can hereby attest that the provided information are accurate, and the token is valid.
> 
> [X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7 [X] Symbol: SMURF [X] Token Decimals: 6 [X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/ [X] On-chain metadata matches [X] No duplication on Jupiter's strict list
https://twitter.com/Bushdid911tho/status/1773469815258157446?t=QwCoJheTrO1bFPWEOg-TdA&s=19

**Comment by cabbienft** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
[X] Symbol: SMURF
[X] Token Decimals: 6
[X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Comment by slimboyfat989** [comment]
Smurf is the best memecoin on solana corrently with the best comunity behind it!

**Comment by slimboyfat989** [comment]
Smurf on top!

**Comment by dazed-up** [comment]
$SMURF is gonna moon! Can’t wait

**Review by dazed-up — COMMENTED** [review]
$SMURF is gonna run pretty soon

**Review by awfulvogue — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

[X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
[X] Symbol: SMURF
[X] Token Decimals: 6
[X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Comment by irvinVIII** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
[X] Symbol: SMURF
[X] Token Decimals: 6
[X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by irvinVIII — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

[X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
[X] Symbol: SMURF
[X] Token Decimals: 6
[X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Comment by yazidox** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
[X] Symbol: SMURF
[X] Token Decimals: 6
[X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by Kdog3111 — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

[X] Mint address: EArkn8uVf8YLfpF2eCdkCvDaPYpQuJzKXxaCnyxXc2P7
[X] Symbol: SMURF
[X] Token Decimals: 6
[X] Token icon: https://bafybeigz2m3cfgsmc4q4z6jfqz3t6uzrjg3a5gonza64yw3mjf7vl6oip4.ipfs.nftstorage.link/
[X] On-chain metadata matches
[X] No duplication on Jupiter's strict list

**Review by Senzer2 — COMMENTED** [review]
Huge project with an amazing community !

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
