### PR TITLE
Anita Max Wynn 

### PR DESCRIPTION
**Pull request by anitamaxwynnsol**
# Validate [WYNN](https://solscan.io/token/4vqYQTjmKjxrWGtbL2tVkbAU1EVAz9JwcYtd2VE3PbVU})

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/AMW_SOL/status/1752390245348196505?s=20}
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/anita-max-wynn}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by FooFoo-Tech** [comment]
Token is live and trading via "ALL" list, but need it PR processed to add to strict list

https://jup.ag/swap/SOL-WYNN_4vqYQTjmKjxrWGtbL2tVkbAU1EVAz9JwcYtd2VE3PbVU

**Comment by anitamaxwynnsol** [comment]
Please let me know if you need more info for strict list.

**Comment by FooFoo-Tech** [comment]
> ## Attestations (Please provide links):
> * Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: [https://x.com/AMW_SOL/status/1752390245348196505?s=20}](https://x.com/AMW_SOL/status/1752390245348196505?s=20%7D)
> * Coingecko/ CMC URL (If available): [https://www.coingecko.com/en/coins/anita-max-wynn}](https://www.coingecko.com/en/coins/anita-max-wynn%7D)

COINGECKO URL:[https://www.coingecko.com/en/coins/anita-max-wynn](url)

**Comment by anitamaxwynnsol** [comment]
Any update on this?

**Comment by 9yoi** [comment]
The image link provided does not load. 

Please use one that matches your onchain metadata

**Pull request closed without merging**
