### PR TITLE
Validate $VIDEOGAME

### PR DESCRIPTION
**Pull request by VIDEOGAMEcc**
# Validate [$VIDEOGAME](https://solscan.io/token/Cd35Zsee8atgY14q47mgN4N7xa2VpJG57ygtAXL7pump)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/videogame_cc/status/1798421693687558640
- Coingecko/ CMC URL (If available):
- https://www.geckoterminal.com/solana/pools/8NmYMvCseafWq35BbafsFzzXhQ4iCAbuKCg5PxgMGU3m
- https://coinmarketcap.com/dexscan/solana/8NmYMvCseafWq35BbafsFzzXhQ4iCAbuKCg5PxgMGU3m

## Validation (Please check off boxes):
- [ ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [ ] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [ ] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [ ] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
please come into discord

**Comment by Jymfletzfur** [comment]
name is video-game.cc

image is https://ipfs.io/ipfs/QmUefrhiyEYfU1vbP7kcetSxJUKAXDdntMjWUUh7DGf6vA

**Comment by VIDEOGAMEcc** [comment]
> name is video-game.cc
> 
> image is https://ipfs.io/ipfs/QmUefrhiyEYfU1vbP7kcetSxJUKAXDdntMjWUUh7DGf6vA

yes

name is video-game.cc
ticker/symbol is $videogame
image is https://ipfs.io/ipfs/QmUefrhiyEYfU1vbP7kcetSxJUKAXDdntMjWUUh7DGf6vA

**Comment by Jymfletzfur** [comment]
please amend the submission to reflect those

**Comment by VIDEOGAMEcc** [comment]
> please amend the submission to reflect those

its updated

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
