### PR TITLE
cok the cat - COK

### PR DESCRIPTION
**Pull request by GRL98**
# Validate [COK](https://solscan.io/token/Dnb9dLSXxAarXVexehzeH8W8nFmLMNJSuGoaddZSwtog)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/catownkimono/status/1796077120612970576
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/catownkimono

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by GRL98** [comment]
> please come into discord

joined. what ahppened? why it was closed?

**Comment by GRL98** [comment]
> use the image in your metadata:
> 
> https://45c2gwdbzh562cjyyaba5mneifist7yltgauitdoiyswqveddp2a.arweave.net/50WjWGHJ--0JOMACDrGkQVEp_wuZgURMbkYlaFSDG_Q

can you explain this to me? what is wrong? image must be in .png format? how can I change it? Thank you in advance

**Comment by GRL98** [comment]
> use the image in your metadata:
> 
> https://45c2gwdbzh562cjyyaba5mneifist7yltgauitdoiyswqveddp2a.arweave.net/50WjWGHJ--0JOMACDrGkQVEp_wuZgURMbkYlaFSDG_Q

my mistake. Can I change the link to the logo to be compatible with the metadata? This is correct one: https://arweave.net/50WjWGHJ--0JOMACDrGkQVEp_wuZgURMbkYlaFSDG_Q

**Review by Jymfletzfur — APPROVED** [review]

**Comment by 9yoi** [comment]
Merged here: https://github.com/jup-ag/token-list/pull/4163

**Pull request closed without merging**
