### PR TITLE
Validate LDZ Token

### PR DESCRIPTION
**Pull request by TD-Syndicure**
# Validate [LDZ](https://solscan.io/token/E5ZVeBMazQAYq4UEiSNRLxfMeRds9SKL31yPan7j5GJK)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/lunardollznft/status/1747474810324599258
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/voodoo

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by BzzzzzzY** [comment]
Love VOODOO! Best community ever, deserves all good things coming their way :)

**Comment by Markoshark** [comment]
$LDZ is ALPHA, LDZ is a really awesome token powering the lunardollz ecosystem, strong support and community behind it. A sleeping giant. ONE TO WATCH!!!

**Comment by justinhartman** [comment]
I've been a member of the LDZ community for some time now. This is a project that has multiple NFT projects, a strong user base, and a token that has grown even during the bearish market. I would give this my full support and would be happy to provide further reference to the project, the team, and any other context needed.

**Review by justinhartman — COMMENTED** [review]
Can confirm the token address and other info for LDZ is correct.

**Comment by bobs1221** [comment]
$Voodoo Token Contract address: E5ZVeBMazQAYq4UEiSNRLxfMeRds9SKL31yPan7j5GJK

Love me some $voodoo!!! Can we get it on please??

**Comment by SnugNZ** [comment]
- [x] Mint address: E5ZVeBMazQAYq4UEiSNRLxfMeRds9SKL31yPan7j5GJK
 - [x] Symbol: LDZ
 - [x] Token Decimals: 9
 - [x] Token icon: https://shdw-drive.genesysgo.net/5QGtUB5S2RKa2QyXYcEaXnoDEDN1VswZ5YZkgZ8Zf81S/FB062705-73CE-42C7-9C6F-4C7679DAF01A.jpeg
 - [x] On-chain metadata matches
 - [x] No duplication on Jupiter's strict list
 
 I have done dev work for the team, and they're fantastic. Great group of people to work with.

**Comment by Cheeple1** [comment]
The official $LDZ  address is below

E5ZVeBMazQAYq4UEiSNRLxfMeRds9SKL31yPan7j5GJK

Below is a screenshot of my $LDZ wallet holdings

Screenshot_20240117_162431_Phantom

I can attest to its validity

**Comment by blythyboy** [comment]
I can attest to the validity of this LDZ and the project and support the integration into JUP.

**Comment by johhnycash1** [comment]
The authenticity of this token and the community behind it is 100%! 

I’ve been trading $Voodoo on JUP for a while now and most def looking for that “Strict token” listing!

**Comment by jaymorgan90** [comment]
I support this

**Review by Kellov2222 — COMMENTED** [review]
I am a part of this community. $LDZ VOODOO token , I am putting my name on it. I stand behind it and with this community without any hesitation, instead elation. This is a solid project with strong leaders and founders. This token needs to be Validated. I feel bad for the people thar haven't had a chance to hear or about $LDZ and the Lunardollznft. We have a new mint come out  during the first week of March.  If it's not already in the works, please take a look at the stats. We would love to have you come by the Discord. I will warn you though, there's a high chance that like myself, you may not want to leave. Please validate Voodoo . I appreciate you, in advance   
Kelly Loveday

**Comment by Cyude123** [comment]
This token will bring lasting solutions to the ecosystem.

**Review by Jymfletzfur — APPROVED** [review]

**Review by 0xSoju2 — APPROVED** [review]

**Pull request merged**
