### PR TITLE
Validate $DOBI

### PR DESCRIPTION
**Pull request by Solid-Proof**
# Validate [{DOBI}](https://solscan.io/token/GzQzkt2B4Jr6whWVBF7XqkzWvoUy1jEd5z9tczzGg1rH)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/DobiOnSolana/status/1731903074233618516
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/dobi

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Review by 00Smurf — COMMENTED** [review]
[x] Symbol: DOBI
[x] Token decimals: 6
[x] Token icon: https://gateway.irys.xyz/099elCExuWO7iBY2_E-4mZVNLL21Hmj_nxHTGTdUxx0
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Review by 00Smurf — COMMENTED** [review]
*edit* double posted my review on accident.

**Comment by drakep** [comment]
[x] Symbol: DOBI
[x] Token decimals: 6
[x] Token icon: https://gateway.irys.xyz/099elCExuWO7iBY2_E-4mZVNLL21Hmj_nxHTGTdUxx0
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by Timoon21** [comment]
Duplicate: https://github.com/jup-ag/token-list/pull/501

**Pull request closed without merging**
