### PR TITLE
Validate COOL

### PR DESCRIPTION
**Pull request by Jay-Clouds**
# Validate [COOL](https://solscan.io/token/CooL79s3d23Zd2RfMXTRmUnfbAWBt4H6thn4sVkmYR9h#metadata)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/coolcat_sol/status/1776953222843990195
- Coingecko/ CMC URL (If available): -/-

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by mwhite494** [comment]
coolcat is listed on CMC now.

Link is here: https://coinmarketcap.com/currencies/coolcat/

**Comment by coki-ss** [comment]
It's listed on CMC since last week

https://coinmarketcap.com/currencies/coolcat/

**Review by coki-ss — COMMENTED** [review]
https://coinmarketcap.com/currencies/coolcat/

**Comment by coki-ss** [comment]
> # Validate [COOL](https://solscan.io/token/CooL79s3d23Zd2RfMXTRmUnfbAWBt4H6thn4sVkmYR9h#metadata)
> ## Attestations (Please provide links):
> * Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/coolcat_sol/status/1776953222843990195
> * Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/coolcat/
> 
> ## Validation (Please check off boxes):
> * [x]  The metadata provided in the PR matches what is on-chain (Mandatory)
> * [x]  Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
> * [ ]  Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)
> 
> ## Acknowledgement (Please check off boxes)
> * [x]  My change matches the format in the file (no spaces between fields).
> * [x]  My token is already live and trading on Jupiter.
> * [x]  !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
> * [x]  Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

**Comment by coki-ss** [comment]
@Jay-Clouds please validate & merge $COOL [validated-tokens.csv](https://github.com/jup-ag/token-list/blob/main/validated-tokens.csv)

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
