### PR TITLE
Add GUAP to the validated tokens list

### PR DESCRIPTION
**Pull request by guapteam**
# Validate [GUAP](https://solscan.io/token/9C7xMpQGVMMC61AHo7ejtdE2RXZDGZm6i6Kh7ak18gdJ)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/guap_solana/status/1777998462279184840
- Coingecko/ CMC URL (If available): Still working to get this on CG & CMC

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by cryptoEvlim** [comment]
[x] Mint address: 9C7xMpQGVMMC61AHo7ejtdE2RXZDGZm6i6Kh7ak18gdJ
[x] Symbol: GUAP
[x] Token Decimals: 9
[x] Token icon: https://ipfs.io/ipfs/QmSUR27sZDWUxJM2E57XD5HL69qYjgVtEMd3ybTNsfVmKc/GUAP%20logo%206.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by guapteam** [comment]
[x] Mint address: 9C7xMpQGVMMC61AHo7ejtdE2RXZDGZm6i6Kh7ak18gdJ
[x] Symbol: GUAP
[x] Token Decimals: 9
[x] Token icon: https://ipfs.io/ipfs/QmSUR27sZDWUxJM2E57XD5HL69qYjgVtEMd3ybTNsfVmKc/GUAP%20logo%206.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by cryptoEvlim** [comment]
[x] Mint address: 9C7xMpQGVMMC61AHo7ejtdE2RXZDGZm6i6Kh7ak18gdJ
[x] Symbol: GUAP
[x] Token Decimals: 9
[x] Token icon: https://ipfs.io/ipfs/QmSUR27sZDWUxJM2E57XD5HL69qYjgVtEMd3ybTNsfVmKc/GUAP%20logo%206.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by WeAreSuzume** [comment]
[x] Mint address: 9C7xMpQGVMMC61AHo7ejtdE2RXZDGZm6i6Kh7ak18gdJ
[x] Symbol: GUAP
[x] Token Decimals: 9
[x] Token icon: https://ipfs.io/ipfs/QmSUR27sZDWUxJM2E57XD5HL69qYjgVtEMd3ybTNsfVmKc/GUAP%20logo%206.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Review by WeAreSuzume — COMMENTED** [review]
[x] Mint address: 9C7xMpQGVMMC61AHo7ejtdE2RXZDGZm6i6Kh7ak18gdJ
[x] Symbol: GUAP
[x] Token Decimals: 9
[x] Token icon: https://ipfs.io/ipfs/QmSUR27sZDWUxJM2E57XD5HL69qYjgVtEMd3ybTNsfVmKc/GUAP%20logo%206.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Review by cryptoEvlim — COMMENTED** [review]
[x] Mint address: 9C7xMpQGVMMC61AHo7ejtdE2RXZDGZm6i6Kh7ak18gdJ
[x] Symbol: GUAP
[x] Token Decimals: 9
[x] Token icon: https://ipfs.io/ipfs/QmSUR27sZDWUxJM2E57XD5HL69qYjgVtEMd3ybTNsfVmKc/GUAP%20logo%206.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Pull request closed without merging**
