### PR TITLE
Validate POPDOG

### PR DESCRIPTION
**Pull request by popdogdevAcc**
# Validate [POPDOG](https://solscan.io/token/EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/POPDOGsolcoin/status/1748362543956103585
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/popdog
CMC application is pending.

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by BlockchainBuddha — COMMENTED** [review]
Looks good. Happy to be helping build this!

**Comment by Meciah** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

 [x]  Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
 [x]  Symbol: POPDOG
 [x]  Token Decimals: 6
 [x]  Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
 [x]  On-chain metadata matches
 [x]  No duplication on Jupiter's strict list

**Comment by artbyLOVECAT** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

* [x] Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
* [x]  Symbol: POPDOG
* [x]  Token Decimals: 6
* [x]  Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
* [x]  On-chain metadata matches
* [x]  No duplication on Jupiter's strict list

**Comment by Danmination** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

* [x] Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
* [x]  Symbol: POPDOG
* [x]  Token Decimals: 6
* [x]  Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
* [x]  On-chain metadata matches
* [x]  No duplication on Jupiter's strict list

**Review by rayq15 — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

* [x] Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
* [x]  Symbol: POPDOG
* [x]  Token Decimals: 6
* [x]  Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
* [x]  On-chain metadata matches
* [x]  No duplication on Jupiter's strict list

**Comment by Meciah** [comment]
> I can hereby attest that the provided information is accurate, and the token is valid.
> 
> * [x]  Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
> * [x]   Symbol: POPDOG
> * [x]   Token Decimals: 6
> * [x]   Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
> * [x]   On-chain metadata matches
> * [x]   No duplication on Jupiter's strict list

**Review by Meciah — COMMENTED** [review]
> I can hereby attest that the provided information is accurate, and the token is valid.
> 
> * [x]  Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
> * [x]   Symbol: POPDOG
> * [x]   Token Decimals: 6
> * [x]   Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
> * [x]   On-chain metadata matches
> * [x]   No duplication on Jupiter's strict list

**Comment by POPDOGsolcoin** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

 Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
 Symbol: POPDOG
 Token Decimals: 6
 Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
 On-chain metadata matches
 No duplication on Jupiter's strict list
 
 Also
 https://www.coingecko.com/en/coins/popdog
 &
 https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by Bnutz0311** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by CryptoPush99** [comment]
can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by ReachDPE** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by Kdtnyc** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by MemeCoinMaxi** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by Tdogg1990** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by iMakiev** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by CryptoLifeUntold** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by VoodooPopeye** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by VoodooPopeye** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by mrgrey-01** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by VoodooPopeye** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by mrgrey-01** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by bnutzaus** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by JoeRichi** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by DaddyGang** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by Chimaobi1914** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by cryptomac123** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by CryptotheKi** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by CryptoBossLady333** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by Alibaba1224** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by alatabala** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by Twinkieee1** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by Popdog1bil** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by Popdogtothemoon** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by streetbiker420** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by streetbiker420** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
Symbol: POPDOG
Token Decimals: 6
Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
On-chain metadata matches
No duplication on Jupiter's strict list

Also
https://www.coingecko.com/en/coins/popdog
&
https://twitter.com/POPDOGsolcoin/status/1748362543956103585

**Comment by VoodooPopeye** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

 Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
 Symbol: POPDOG
 Token Decimals: 6
 Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by Popdogrises** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

 Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
 Symbol: POPDOG
 Token Decimals: 6
 Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Review by Popdogrises — COMMENTED** [review]
I can hereby attest that the provided information is accurate, and the token is valid.

 Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
 Symbol: POPDOG
 Token Decimals: 6
 Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by TheCharder** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

 Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
 Symbol: POPDOG
 Token Decimals: 6
 Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
 On-chain metadata matches
 No duplication on Jupiter's strict list
SBZ5KM3L

**Comment by TheCharder** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

 Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
 Symbol: POPDOG
 Token Decimals: 6
 Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by Svechniko** [comment]
I can hereby attest that the provided information is accurate, and the token is valid.

 Mint address: EATGZHJViJsk7nEKkrdJicwNbfpkJfAtmrEmrjXR8NBj
 Symbol: POPDOG
 Token Decimals: 6
 Token icon: https://i.postimg.cc/SRb6fSps/SBZ5KM3L.png
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
There is something incorrect with the submission

On chain data shows name is POPDOG

In the submission, it is called $POPDOG

**Comment by VoodooPopeye** [comment]
It's called POPDOG, $POPDOG is a twitter cashtag

**Comment by Bnutz0311** [comment]
> There is something incorrect with the submission
> 
> On chain data shows name is POPDOG
> 
> In the submission, it is called $POPDOG

We’re trying to reach the team member who created the PR. If he can’t be reached to change that, do we need to create a new PR?

**Comment by streetbiker420** [comment]
Hello just saw this Sent from my iPhoneOn Feb 26, 2024, at 11:59 AM, popdogdevAcc ***@***.***> wrote:﻿
Closed #877.

**Comment by streetbiker420** [comment]
Hello Sent from my iPhoneOn Feb 25, 2024, at 8:10 PM, Bnutz0311 ***@***.***> wrote:﻿

There is something incorrect with the submission
On chain data shows name is POPDOG
In the submission, it is called $POPDOG

We’re trying to reach the team member who created the PR. If he can’t be reached to change that, do we need to create a new PR?

**Comment by streetbiker420** [comment]
Hello I am part of team Sent from my iPhoneOn Feb 26, 2024, at 11:59 AM, popdogdevAcc ***@***.***> wrote:﻿
Closed #877.

**Comment by streetbiker420** [comment]
I don’t use this email often Sent from my iPhoneOn Feb 26, 2024, at 12:04 PM, ***@***.*** wrote:﻿Hello just saw this Sent from my iPhoneOn Feb 26, 2024, at 11:59 AM, popdogdevAcc ***@***.***> wrote:﻿
Closed #877.

**Comment by popdogdevAcc** [comment]
> There is something incorrect with the submission
> 
> On chain data shows name is POPDOG
> 
> In the submission, it is called $POPDOG

I believe this issue has been corrected. Please check again and verify. Thank you.

**Comment by Jymfletzfur** [comment]
pls come into the discord

**Comment by VoodooPopeye** [comment]
I will join asap, thank you!

Nemanja3

**Review by popdogdevAcc — COMMENTED** [review]
On chain name and submission name should be the same now.

**Review by 9yoi — CHANGES_REQUESTED** [review]
Can you redo your PR or open a fresh one? Take a look at your diff, it's removing all the existing code

**Comment by popdogdevAcc** [comment]
Hey @9yoi, done.
Do you like it now?

**Comment by 9yoi** [comment]
> Hey @9yoi, done. Do you like it now?

Your PR has a bunch of unrelated changes (look at diff, expand, and see)

I made you a new PR here: https://github.com/jup-ag/token-list/pull/1761

**Pull request closed without merging**
