### PR TITLE
Validate LFGO

### PR DESCRIPTION
**Pull request by LFGOsam**
# Validate [LFGO](https://solscan.io/token/2u98MM7DMtVmNG4iAKRNMtynjmkzgD6fXAzB3wVfhQvg)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/LFGOcommunity/status/1795417530397249823
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/lets-fuckin-go/
## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
this is already on the strictlist

**Comment by Jymfletzfur** [comment]
can you use this link

https://bafybeihigmjodulnlbn6dve7nmmwpkdgno5beid3hx5ku5irfy4wjmredy.ipfs.dweb.link/

**Comment by LFGOsam** [comment]
> can you use this link
> 
> https://bafybeihigmjodulnlbn6dve7nmmwpkdgno5beid3hx5ku5irfy4wjmredy.ipfs.dweb.link/
That is what i want to change, that one is the old logo, 

https://quicknode.quicknode-ipfs.com/ipfs/QmZfiKSiph5NfCPsmC111x3WwCXpVFX5RbHndcpMKB7Vuu  this is our new logo. If you send me that picture in your link format, i will change the current format.

**Comment by Jymfletzfur** [comment]
this is what the link is in your metadata rn

https://ipfs.io/ipfs/Qmdy4TwZ3DWm5h2Yn9ePtdrjnMszXryAhJgQMMknzKe6AR

**Pull request closed without merging**
