### PR TITLE
Validate Duck

### PR DESCRIPTION
**Pull request by Selmasgib**
# Validate [Duck](https://solscan.io/token/A2PRwGdS4ho2WGfb2gbWFTXoVGoDBhLEhJ14bGouqbyZ)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SillyDuckSol/status/1754432976077955336
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/silly-duck

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Selma666** [comment]
Silly $Duck is the best token on Solana, LFG!!!

- [x] Mint address: A2PRwGdS4ho2WGfb2gbWFTXoVGoDBhLEhJ14bGouqbyZ
- [x]  Symbol: DUCK
- [x] Token Decimals: 8
- [x] Token icon: https://gateway.pinata.cloud/ipfs/QmepYYdr5kDoCDfiv8M4dVK3gDvbR82Zwunx8yy13reqfk
- [x] On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by 0xJason92** [comment]
This project is legal. Information is accurate, and the token is valid.
- [x] Mint address: A2PRwGdS4ho2WGfb2gbWFTXoVGoDBhLEhJ14bGouqbyZ
- [x]  Symbol: DUCK
- [x] Token Decimals: 8
- [x] Token icon: https://gateway.pinata.cloud/ipfs/QmepYYdr5kDoCDfiv8M4dVK3gDvbR82Zwunx8yy13reqfk
- [x] On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by youngmayorprestige** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

- [x] Mint address: A2PRwGdS4ho2WGfb2gbWFTXoVGoDBhLEhJ14bGouqbyZ
- [x]  Symbol: DUCK
- [x] Token Decimals: 8
- [x] Token icon: https://gateway.pinata.cloud/ipfs/QmepYYdr5kDoCDfiv8M4dVK3gDvbR82Zwunx8yy13reqfk
- [x] On-chain metadata matches
- [x]  No duplication on Jupiter's strict list

**Comment by Windremac** [comment]
Wow... Good project on Solana $Duck

**Comment by Cirila12** [comment]
I love Silly $DUCK !!!!

**Comment by Bbyface-ad** [comment]
All the Information are legal and correct.
Amazing Project, $DUCK on my Mind 
Most silly

**Comment by Njuuare** [comment]
$DUCK is one of the strongest memecoin on the solana, and a strong community with good potentials to make big numbers.

**Comment by Whizbeats** [comment]
The most generous $DUCK on Solana 👌

**Comment by mostermas** [comment]
Lfg

**Comment by robbestad** [comment]
Wrong file in PR. Don't submit changes to the template

**Pull request closed without merging**
