### PR TITLE
Luke Bullmar

### PR DESCRIPTION
**Pull request by ScaleWithAI**
# Validate [BELMAR](https://solscan.io/token/2NGCjWG997pz8BNCdA7XrhjfCHK67zYqtXFGbA6wjShv)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Luke_Bullmar/status/1790538937288790277
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by BelmarBrand — COMMENTED** [review]
The project looks very solid with a strong community. I reviewed the tokenmics and holders. Quite bullish on this project.

**Comment by BelmarBrand** [comment]
Quite bullish on the Belmar project.  They're always in the TG cooking up something. I've heard rumors that they're connected to Luke? Not sure if true or not.. very interesting over all! I'm holding.

**Comment by ScaleWithAI** [comment]
- [x]  On-chain metadata matches the PR
- [x]  Token address matches the tweet
- [x]  No duplication on Jupiter's strict list
- [x]  No duplication on CMC/CoinGecko
- [x]  Community validation

**Comment by Degen42069** [comment]
-   On-chain metadata matches the PR
-  Token address matches the tweet
- No duplication on Jupiter's strict list
- No duplication on CMC/CoinGecko
- Community validation

All looks solid to me.

**Comment by abdulfattalawal** [comment]
- [x]  On-chain metadata matches the PR
- [x]  Token address matches the tweet
- [x]  No duplication on Jupiter's strict list
- [x]  No duplication on CMC/CoinGecko
- [x]  Community validation

**Comment by Sally419** [comment]
- [x]  On-chain metadata matches the PR
- [x]  Token address matches the tweet
- [x]  No duplication on Jupiter's strict list
- [x]  No duplication on CMC/CoinGecko
- [x]  Community validation

**Comment by Meandyouv** [comment]
- [x]  On-chain metadata matches the PR
- [x]  Token address matches the tweet
- [x]  No duplication on Jupiter's strict list
- [x]  No duplication on CMC/CoinGecko
- [x]  Community validation
- [ ] 
$Belmar CA is the best project

**Comment by dezhugo** [comment]
Bullish project. $BELMAR is a really nice memecoin with a strong community

**Comment by dezhugo** [comment]
✅ On-chain metadata matches the PR
✅ Token address matches the tweet
✅ No duplication on Jupiter's strict list
✅ No duplication on CMC/CoinGecko
✅ Community validation

**Comment by Timiprimeking** [comment]
- [x]
PR
On-chain metadata matches the
- [x] tweet
Token address matches the
- [x]
strict list
No duplication on Jupiter's

- [x] No duplication on CMC/
CoinGecko
- [x] Community validation

**Comment by Finum124** [comment]
$BELMAR is the best Gem in the whole crypto space. Don't miss out on this tear gem

**Comment by Zainabbashir59** [comment]
- [x]  On-chain metadata matches the PR
- [x]  Token address matches the tweet
- [x]  No duplication on Jupiter's strict list
- [x]  No duplication on CMC/CoinGecko
- [x]  Community validation

**Comment by Baraksea** [comment]
- [x]  On-chain metadata matches the PR
- [x]  Token address matches the tweet
- [x]  No duplication on Jupiter's strict list
- [x]  No duplication on CMC/CoinGecko
- [x]  Community validation

**Comment by Sally419** [comment]
- [x]  On-chain metadata matches the PR
- [x]  Token address matches the tweet
- [x]  No duplication on Jupiter's strict list
- [x]  No duplication on CMC/CoinGecko
- [x]  Community validation

**Comment by Sally419** [comment]
- [x]  On-chain metadata matches the PR
- [x]  Token address matches the tweet
- [x]  No duplication on Jupiter's strict list
- [x]  No duplication on CMC/CoinGecko
- [x]  Community validation

**Comment by abdulfattalawal** [comment]
- [x]  On-chain metadata matches the PR
- [x]  Token address matches the tweet
- [x]  No duplication on Jupiter's strict list
- [x]  No duplication on CMC/CoinGecko
- [x]  Community validation

**Comment by Finum124** [comment]
- [x]  On-chain metadata matches the PR
- [x]  Token address matches the tweet
- [x]  No duplication on Jupiter's strict list
- [x]  No duplication on CMC/CoinGecko
- [x]  Community validation

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
