### PR TITLE
Validate PNDC

### PR DESCRIPTION
**Pull request by FluffyZk**
# Validate [PNDC](https://solscan.io/token/vSYAPufpX2a4HpnkXguuoTznA5r2yZan8yP2RGnkvKm)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/natepepesolana/status/1694314173096767700
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by wrstnghtmre** [comment]
Lfg $pndc.

**Comment by wrstnghtmre** [comment]
> Lfg $pndc.

Validate $pndc

**Comment by ALPHALUK3** [comment]
Noice lets gooo Validate $PNDC plz

**Comment by Timoon21** [comment]
PNDC relates to a Ethereum project (https://twitter.com/Pond0x).
You use the same symbol and logo: this can be misleading for users.

**Comment by Dolidze86** [comment]
Look at this Fake actors! I wish I can be on that level of knowledge to use it in proper way...

**Pull request closed without merging**
