### PR TITLE
update validated-tokens to include God token

### PR DESCRIPTION
**Pull request by MAXDCML**
# Validate [GOD](https://solscan.io/token/GqqjcyCSzoxtGHrfHr33JcUR3xTwNZw9T8KD4pFqStSv)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/godwifplan/status/1738823549257965820
- Coingecko URL: https://www.coingecko.com/en/coins/god

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by TheCrypt0keeper** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

 [x]   Mint address: GqqjcyCSzoxtGHrfHr33JcUR3xTwNZw9T8KD4pFqStSv
 [x]   Symbol: GOD
 [x]   Token Decimals: 6
 [x]   Token icon: https://godwifplan.com/favicon.png

**Comment by SashimiSaketoro** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

 [x]   Mint address: GqqjcyCSzoxtGHrfHr33JcUR3xTwNZw9T8KD4pFqStSv
 [x]   Symbol: GOD
 [x]   Token Decimals: 6
 [x]   Token icon: https://godwifplan.com/favicon.png

**Comment by Calciferoo** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

 [x]   Mint address: GqqjcyCSzoxtGHrfHr33JcUR3xTwNZw9T8KD4pFqStSv
 [x]   Symbol: GOD
 [x]   Token Decimals: 6
 [x]   Token icon: https://godwifplan.com/favicon.png

**Comment by he992** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: GqqjcyCSzoxtGHrfHr33JcUR3xTwNZw9T8KD4pFqStSv
[x] Symbol: GOD
[x] Token Decimals: 6
[x] Token icon: https://godwifplan.com/favicon.png

**Comment by donnydanko** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

 [x]   Mint address: GqqjcyCSzoxtGHrfHr33JcUR3xTwNZw9T8KD4pFqStSv
 [x]   Symbol: GOD
 [x]   Token Decimals: 6
 [x]   Token icon: https://godwifplan.com/favicon.png

**Comment by apealot** [comment]
I can hereby attest that the provided information are accurate, and the token is valid. 

 [x]   Mint address: GqqjcyCSzoxtGHrfHr33JcUR3xTwNZw9T8KD4pFqStSv
 [x]   Symbol: GOD
 [x]   Token Decimals: 6
 [x]   Token icon: https://godwifplan.com/favicon.png

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
