### PR TITLE
Validate WOOOO

### PR DESCRIPTION
**Pull request by four66**
# Validate [WOOOO](https://solscan.io/token/JCqsyVajfHBGjNWNmLT6Cfx1Vn9f3mRibtNSdUsVRWS5)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/enriqueflair/status/1793281474935804268
- Coingecko/ CMC URL (If available): N/A

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by hey-its-slowly** [comment]
Definitely in support of this! 

* [x]  Mint address: JCqsyVajfHBGjNWNmLT6Cfx1Vn9f3mRibtNSdUsVRWS
* [x]  Symbol: WOOOO
* [x]  Token Decimals: 6
* [x]  Token icon: https://cf-ipfs.com/ipfs/QmPjCNqjV8kEqzXp3wWhzDeN32iU9corqgXedPrcAjmvrx
* [x]  On-chain metadata matches
* [x]  No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
insufficient volume

**Comment by Jymfletzfur** [comment]
Use this as your image file


https://ipfs.io/ipfs/QmPjCNqjV8kEqzXp3wWhzDeN32iU9corqgXedPrcAjmvrx

**Comment by four66** [comment]
> Use this as your image file
> 
> https://ipfs.io/ipfs/QmPjCNqjV8kEqzXp3wWhzDeN32iU9corqgXedPrcAjmvrx

Fixed!

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
