### PR TITLE
Update PEPESOLANA

### PR DESCRIPTION
**Pull request by PEPESOLANA**
# Validate [PEPESOLANA]( https://solscan.io/token/CYuXNHURE8cF3rQc1687DZnmsWx9ATNG3mZPFmryu22S )

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: (https://twitter.com/pepesolana_pepe/status/1647915486074601472)
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by PEPESOLANA** [comment]
Name: PEPESOLANA
Symbol: PEPE
Mint Address: CYuXNHURE8cF3rQc1687DZnmsWx9ATNG3mZPFmryu22S
Decimals: 9
LogoURI: https://i.ibb.co/c1wzMqc/logopep.png
Community Validated: true

**Comment by CryptoZoneZA** [comment]
Please verify and validate PEPESOLANA 🙏🏻

**Comment by ALPHALUK3** [comment]
Please verify & validate $PEPE #PEPESOLANA

**Comment by BUDDHAAAA** [comment]
Need verification $PEPE from PEPESOLANA

**Comment by OYINDAR** [comment]
Please help verify $PEPE from PEPESOLANA

**Comment by RiffRaffRevv** [comment]
Time to list PEPESOLANA

**Review by RiffRaffRevv — COMMENTED** [review]
Please validate PEPESOLANA $PEPE time to list.

**Comment by Lonerangerrr** [comment]
Please verify and validate PEPESOLANA 🙏🏻

**Comment by joshtara55** [comment]
Please validate PEPESOLANA. Thanx

**Comment by skidoko** [comment]
Please verify and validate PEPESOLANA

**Comment by Arshad2701** [comment]
Please verify and validate PEPESOLANA 🙏🏻

**Comment by xSuoraan** [comment]
Please verify and validate PEPESOLANA

**Comment by Jrmpcl** [comment]
How does it work please ?

**Comment by Jrmpcl** [comment]
Please help verify $PEPE from PEPESOLANA

**Comment by jiggijacks** [comment]
PEPE is a solid project, verify, please

**Comment by Rosepepe** [comment]
PEPE would change the narrative about meme coins... we are more than just meme coins... Kindly verify PEPE SOLANA

**Comment by R00T0FALLEVIL** [comment]
Can we please get pepesolana validated and verified it's proven itself now

**Comment by teamcheffe13** [comment]
its time to verify $PEPE from PEPESOLANA. lets go

**Review by meijiao — CHANGES_REQUESTED** [review]
hey the logo img should match what is in the metadata, which is https://shdw-drive.genesysgo.net/85Mup8SQSvcTXsykzNTAtypV2v3zYrYu9eFTRvUUwmXK/logopep200x200.png

**Review by PEPESOLANA — COMMENTED** [review]
Please change it to https://shdw-drive.genesysgo.net/85Mup8SQSvcTXsykzNTAtypV2v3zYrYu9eFTRvUUwmXK/logopep200x200.png)

**Comment by PEPESOLANA** [comment]
> hey the logo img should match what is in the metadata, which is https://shdw-drive.genesysgo.net/85Mup8SQSvcTXsykzNTAtypV2v3zYrYu9eFTRvUUwmXK/logopep200x200.png

It's done, thank you

**Review by Timoon21 — DISMISSED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] duplicate symbol, but different token name and logo on Jupiter's strict list
- [x] duplicate symbol, but different token name and logo on CMC/CoinGecko
- [x] Community validation

**Review by meijiao — APPROVED** [review]

**Pull request merged**
