### PR TITLE
Update validated-tokens : CAT (CUTE CAT)

### PR DESCRIPTION
**Pull request by HwangBE**
New listing of ‘CUTE CAT’ cryptocurrency

# Validate [CAT](https://solscan.io/token/35NJp7WpiZzh6pajYpxyjFYDBssLtAb1XhRUrs3KG4Mb)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support : https://x.com/Kimja103/status/1784579961095152025 
- Coingecko/ CMC URL (If available): NOT YET
- Website : https://www.catcoin.shop/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by HwangBE** [comment]
New listing of ‘CUTE CAT’ cryptocurrency

**Comment by HwangBE** [comment]
New listing of ‘CUTE CAT’ cryptocurrency

**Comment by Jymfletzfur** [comment]
insufficient volume

**Comment by HwangBE** [comment]
Thank you for your reply. What is the insufficient volume of our project in your opinion, and what is the sufficient volume in your opinion?

-----Original Message-----

**Pull request closed without merging**
