### PR TITLE
Validate GEM

### PR DESCRIPTION
**Pull request by julesdamasta**
This is for GEM a Token2022 on Solana.

# Validate [GEM](https://solscan.io/token/E7BGDtpNXUTqPNbZxKHiLowgLddiAeuKcByD7tSnfYWD#holders)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/GemCoinSOL/status/1681699402317168640?s=20https://twitter.com/{your_account}/status/{your_tweet_id}
- Coingecko/ CMC URL (If available): N/A

## Validation (Please check off boxes):
- [y ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [n ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [n] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [y] My change matches the format in the file (no spaces between fields).
- [y] My token is already live and trading on Jupiter.
- [y] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by Timoon21** [comment]
Not a lot of community support (likes on attesting tweet, comments, ...). I let open the PR for now, and will review in few days.

**Comment by julesdamasta** [comment]
Thank you.. I will let the devs and community know to attest with tweets
etc.

**Comment by meijiao** [comment]
Please reopen when activity picks up

**Comment by meijiao** [comment]
Hey I didn't see much community demand yet, please reopen a new PR a little later when engagement picks up. Thanks!

**Pull request closed without merging**
