### PR TITLE
Validate ROD.AI

### PR DESCRIPTION
**Pull request by rodaisol**
# Validate [ROD.AI](https://solscan.io/token/GdbyLsNKHKLXTZVEo8QrGKVmrexEeZUYvhpSfuZ9TdkC)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/RodAISol/status/1755262566366945630
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/dexscan/solana/CzWqL4M1CzQiw45djF1xdrWHQmuJbJoZPY38ezKGb6q8/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by issacisco8** [comment]
Based project

**Comment by RojoCrypt0** [comment]
Great project!

**Comment by Tc30001** [comment]
Solid project.

**Comment by xantoshpun** [comment]
It is a solid project with solid community.

**Comment by skullrichie** [comment]
Solid project

**Comment by Suman-Chhetri** [comment]
Very nice project.

**Comment by unknown362958** [comment]
this project has potential

**Review by jsmithhayden — COMMENTED** [review]
This project is the best

**Comment by dantiyo** [comment]
Glad to be part of this great community.
Project has a great team that is constantly looking for ways to be bring the project to higher highs!

**Comment by Tc30001** [comment]
Active, positive community, with the goal of making ROD.ai an utility token other than just entertainment projects.

**Comment by vitalikyakovenko** [comment]
we just got listed on CoinMarketCap: https://coinmarketcap.com/currencies/rod-ai 🚀

**Comment by tottorr** [comment]
this is unicorn

**Comment by rodaisol** [comment]
WEN RODAI? :)

**Comment by Jymfletzfur** [comment]
insufficient volume and mcap

**Comment by rodaisol** [comment]
@Jymfletzfur what should be our target?

**Pull request closed without merging**
