### PR TITLE
validate CIKKA

### PR DESCRIPTION
**Pull request by baba7ji**
# Validate [{CKKA}](https://solscan.io/token/51pPuhLArFyrUTiLwFtoySBnELppjNdG13b86zPVBY9Z#markets})

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/cikka_sol/status/1685051403042271232?t=CnnKtcL8jlACukkt6V6GfQ&s=19) and showing community support: [(https://x.com/cikka_sol?t=dhebMumkVr7JyPlDp0Yrqw&s=09)](https://twitter.com/cikka_sol/status/1685051403042271232?t=CnnKtcL8jlACukkt6V6GfQ&s=19)}
- Coingecko/ CMC URL (If available): Still working to get coin gecko set up for CKKA

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by baba7ji** [comment]
Name: CIKKA
Symbol: CKKA
Mint Address: 51pPuhLArFyrUTiLwFtoySBnELppjNdG13b86zPVBY9Z
Decimals: 9
LogoURI: https://raw.githubusercontent.com/baba7ji/crypto/main/cikka.png.png
Community Validated: true

**Comment by marvboi** [comment]
Awesome
Ckka is gonna fly

**Comment by saifraza786** [comment]
lets go to high fly

**Comment by Timoon21** [comment]
Hey, can you add your token on the last line (end of list), not on the middle of the list?
Thanks.

**Comment by baba7ji** [comment]
update has been done plz validate @Timoon21

**Review by Timoon21 — APPROVED** [review]
- [x] On-chain metadata matches the PR
- [x] Token address matches the tweet
- [x] No duplication on Jupiter's strict list
- [x] Community validation

**Pull request merged**
