### PR TITLE
Validate ONLYFANS

### PR DESCRIPTION
**Pull request by DarkProfessional**
# Validate [ONLYFANS](https://solscan.io/token/CMUt6g8VCETaXAKfZWrKvCSRuG7Kq5dt2WULxsKPHPj9)

## Attestations:
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/onlyfansmeme/status/1781130120264110163

## Validation:
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
insufficient volume

**Comment by DarkProfessional** [comment]
> insufficient volume

@Jymfletzfur there is indeed an immediate lack of volume in the short term. 
What are the minimum requirements in terms of volume (in what timeframe), liquidity and market cap to make it to the strict list?
Thanks

**Comment by DarkProfessional** [comment]
also when such metrics are attained, do I request for this PR to be reopened or do I submit another PR?

**Comment by Kawzin** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[x]   Mint address: CMUt6g8VCETaXAKfZWrKvCSRuG7Kq5dt2WULxsKPHPj9
[x]   Name: ONLYFANS
[x]   Symbol: ONLYFANS
[x]   Token Decimals: 9
[x]   Token icon:https://ipfs.io/ipfs/QmXZCUZ8s4GReYm4MZ1c7LbDYi4AAuNfux1pzsE4HsKRX1
[x]   On-chain metadata matches
[x]   No duplication on Jupiter's strict list

**Pull request closed without merging**
