### PR TITLE
Validate KNOB$

### PR DESCRIPTION
**Pull request by rob1553**
# Validate [{KNOB$}](https://solscan.io/token/5ritAPtFPqQtEFHcHVqNjR5oFNUJqcmgKtZyPd2AyLLy})

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/{sdrawkcabknob}/status/{1735191056508174833?s=46}
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{knob}

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by rob1553** [comment]
Can you let me know if this is correct? This is my first time

**Comment by rob1553** [comment]
@Timoon21 can you help us out here? Our community is begging to be verified. Orca verified us this morning

**Comment by rob1553** [comment]
https://x.com/uni_knob/status/1736093938975736305?s=46

@9yoi

**Comment by 9yoi** [comment]
hey the links on your PR description are broken - can you fix them?

**Comment by rob1553** [comment]
> hey the links on your PR description are broken - can you fix them? also please check the example PR. the change should only be in the validated-tokens file

@9yoi @Timoon21 created a new PR #584 because I am a n00b and didn’t know how to change it. 1.7m in trading volume over last 24 hours and 1.8m market cap. Thank you for your help!!!

**Pull request closed without merging**
