### PR TITLE
VALIDATE LMEOW

### PR DESCRIPTION
**Pull request by slatteth**
# Validate LMEOW (https://solscan.io/token/72BrNKmPWiTJ3f1fzjvXqtPgDCeDvyWUdW6RTd41YMz5)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/lmeowonsol/status/1792648798809821552
- Coingecko/ CMC URL (If available): 

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by lmeowgithub** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: 72BrNKmPWiTJ3f1fzjvXqtPgDCeDvyWUdW6RTd41YMz5
[x] Symbol: LMEOW
[x] Token Decimals: 6
[x] Token icon: https://dd.dexscreener.com/ds-data/tokens/solana/72BrNKmPWiTJ3f1fzjvXqtPgDCeDvyWUdW6RTd41YMz5.png?size=lg&key=98e3a1
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by mysticpimp222** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: 72BrNKmPWiTJ3f1fzjvXqtPgDCeDvyWUdW6RTd41YMz5
[x] Symbol: LMEOW
[x] Token Decimals: 6
[x] Token icon: https://dd.dexscreener.com/ds-data/tokens/solana/72BrNKmPWiTJ3f1fzjvXqtPgDCeDvyWUdW6RTd41YMz5.png?size=lg&key=98e3a1
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Review by lmeowgithub — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: 72BrNKmPWiTJ3f1fzjvXqtPgDCeDvyWUdW6RTd41YMz5
[x] Symbol: LMEOW
[x] Token Decimals: 6
[x] Token icon: https://dd.dexscreener.com/ds-data/tokens/solana/72BrNKmPWiTJ3f1fzjvXqtPgDCeDvyWUdW6RTd41YMz5.png?size=lg&key=98e3a1
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Review by NicoleYama918 — COMMENTED** [review]
I can hereby attest that the provided information are accurate, and the token is valid.

[x] Mint address: 72BrNKmPWiTJ3f1fzjvXqtPgDCeDvyWUdW6RTd41YMz5
[x] Symbol: LMEOW
[x] Token Decimals: 6
[x] Token icon: https://dd.dexscreener.com/ds-data/tokens/solana/72BrNKmPWiTJ3f1fzjvXqtPgDCeDvyWUdW6RTd41YMz5.png?size=lg&key=98e3a1
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
PR inappropriately attempts to alter files other than the token csv

**Pull request closed without merging**
