### PR TITLE
Validate BBONK

### PR DESCRIPTION
**Pull request by bigbonkdev**
# Validate [BBONK](https://solscan.io/token/CjCvm3Pfydntyo3r4PMK1mrARxDmaTYEjHdK9q2sGenR)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/BigBonkX/status/1731298368821879010
- Coingecko/ CMC URL (If available): x

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by Waskayo18** [comment]
$BBONK is a great project is  Based Dev behind it

**Comment by bojes22216** [comment]
LFG🔥🔥🔥

**Comment by bojes22216** [comment]
Good project

**Comment by Gemfindar** [comment]
$BBONK team are hardworking team with daily update on social medial and active in the group chat.

**Comment by Ihave2GME** [comment]
Big Bonk is a solid community with a very active dev constantly building. Big Bonk things coming!!!

**Comment by Pariyadi007** [comment]
$BBONK Dev team very transparan, great jobs

**Comment by bigben89** [comment]
Great based DEV wants to build from meme culture to legit project, we need it !!

**Comment by 9yoi** [comment]
Not sure if we can validate this to the strict list so soon-- it has very similar name and icon to Bonk. In the meantime, your token is still tradeable on the 'All' list.

**Review by 0xSoju2 — APPROVED** [review]

**Pull request merged**
