### PR TITLE
Validate FalconX

### PR DESCRIPTION
**Pull request by Brothersofmetal**
# Validate [FalconX](https://solscan.io/token/Afo4NumBNHDXc7m7p6qjZ1pF3LbqYfG5k1CNrGve8rVu)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging @JupiterExchange and showing community support: https://x.com/FalxDex/status/1798692304821387380
- Coingecko/ CMC URL (If available): Coingecko: https://www.coingecko.com/en/coins/falx
- Coinmarketcap: https://coinmarketcap.com/currencies/falxdex-io/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)`
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
change name to FalconX in the submission

**Comment by Brothersofmetal** [comment]
> change name to FalconX in the submission

Thank you for the information. Requested changes have been made.

**Comment by Jymfletzfur** [comment]
no in the actual submission PR, please make it match the metadata

**Comment by Brothersofmetal** [comment]
> no in the actual submission PR, please make it match the metadata


I updated the new pr data as you requested.
Could you please add our token to your list?

Update validated-tokens.csv #4343

**Comment by Jymfletzfur** [comment]
removing bc duplicate submission

**Comment by Brothersofmetal** [comment]
Hi, What is your discord username?

**Pull request closed without merging**
