### PR TITLE
AWKWARD LOOK MONKEY CLUB - ALMC

### PR DESCRIPTION
**Pull request by TommyBrasko**
# Validate [ALMC](https://solscan.io/token/7f94zk1EgfoeG57Vj5FtDDjMmPNHM4DYs7KRiyd2T4bA)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/almc_solana/status/1800168072470581314
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/awkward-look-monkey-club

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
please come into discord

**Comment by Jymfletzfur** [comment]
name is AWKWARD LOOK MONKEY CLUB all caps

**Comment by TommyBrasko** [comment]
> name is AWKWARD LOOK MONKEY CLUB all caps

Apologies! It is indeed in all caps, how do I correct please?

**Comment by Jymfletzfur** [comment]
in the PR itself

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
