### PR TITLE
Validate Solama

### PR DESCRIPTION
**Pull request by SOLAMAHODLER**
# Validate [SOLAMA](https://solscan.io/token/AVLhahDcDQ4m4vHM4ug63oh7xc8Jtk49Dm5hoe9Sazqr)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SolamaSPL/status/1770597843264229430
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/solama
https://coinmarketcap.com/currencies/solama/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Jymfletzfur — APPROVED** [review]

**Comment by SOLAMAHODLER** [comment]
LFG SOLAMA! 🚀

**Comment by rohkyN** [comment]
SOLAMA COMMUNITY WAITING FOR THIS. LFG!

**Comment by darsim1235** [comment]
> # Validate [SOLAMA](https://solscan.io/token/AVLhahDcDQ4m4vHM4ug63oh7xc8Jtk49Dm5hoe9Sazqr)
> ## Attestations (Please provide links):
> * Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SolamaSPL/status/1770597843264229430
> * Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/solama
>   https://coinmarketcap.com/currencies/solama/
> 
> ## Validation (Please check off boxes):
> * [x]  The metadata provided in the PR matches what is on-chain (Mandatory)
> * [x]  Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
> * [x]  Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)
> 
> ## Acknowledgement (Please check off boxes)
> * [x]  My change matches the format in the file (no spaces between fields).
> * [x]  My token is already live and trading on Jupiter.
> * [x]  !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
> * [x]  Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.
Im super bullish on solama and i strongly support it LFG 🚀🚀🚀

**Comment by darsim1235** [comment]
Im super bullish on solama and i support it LFG 🚀🚀

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
