### PR TITLE
Validate Labrador

### PR DESCRIPTION
**Pull request by tongussk1**
# Validate [Labrador](https://solscan.io/token/Csden9nr1ZYJKLeHKptcusVtboWxyLAvbq8wJqirBLqm)

## Attestations (Please provide links):
- https://twitter.com/szoiPVd7hU50823/status/1735268960860299482?s=20(https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/{your_account}/status/{your_tweet_id}
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [ x ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ x ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [ x ] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [ x ] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by tongussk1** [comment]
The link to Twitter was indicated incorrectly with the mark Jupiter, here is the correct link: https://twitter.com/szoiPVd7hU50823/status/1735350197100654777

**Review by Labrador1245322723 — COMMENTED** [review]
My project, I approve

**Review by AlgoFam — COMMENTED** [review]
I saw a call on Twitter to support the project. The project is really interesting

**Comment by tongussk1** [comment]
You processed a later request by adding Gecko to the validation before my token, so the numbering overlapped, I corrected it by putting my token from line 1040 to line 1041

**Comment by Timoon21** [comment]
Hey, I dont see a lot of support on the tweet and you token is not listed on the All-list already. Please check liquidity requierements.
I close the PR for now.
Please reopen when you are ready.

**Comment by tongussk1** [comment]
> Hey, I dont see a lot of support on the tweet and you token is not listed on the All-list already. Please check liquidity requierements.
> I close the PR for now.
> Please reopen when you are ready.

the readme file states "Reminder: Tokens that meet minimum liquidity criteria will always be available for trading on the 'All' list even without immediate validation." What liquidity must be provided for listing? And what needs to be done for the token to be included in the general list? As I understand it, even if the community supports it, it won’t be possible without a certain liquidity and getting on a certain list? Thanks in advance for your answer.

**Comment by Timoon21** [comment]
> > Hey, I dont see a lot of support on the tweet and you token is not listed on the All-list already. Please check liquidity requierements.
> > I close the PR for now.
> > Please reopen when you are ready.
> 
> the readme file states "Reminder: Tokens that meet minimum liquidity criteria will always be available for trading on the 'All' list even without immediate validation." What liquidity must be provided for listing? And what needs to be done for the token to be included in the general list? As I understand it, even if the community supports it, it won’t be possible without a certain liquidity and getting on a certain list? Thanks in advance for your answer.

Hey, for the All-list there is just liquidity requirements.
Checkout: https://station.jup.ag/docs/get-your-token-onto-jup#tokens-with-sufficient-liquidity-and-on-chain-metadata-are-automatically-listed

**Pull request closed without merging**
