### PR TITLE
Validate CIKKA

### PR DESCRIPTION
**Pull request by baba7ji**
Name: CIKKA
Symbol: CKKA
Mint Address: 51pPuhLArFyrUTiLwFtoySBnELppjNdG13b86zPVBY9Z
Decimals: 9
LogoURI: https://raw.githubusercontent.com/baba7ji/crypto/main/cikka.png.png

# Validate [{Token Symbol}](https://solscan.io/token/{mint_address})

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/{your_account}/status/{your_tweet_id}
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/{id}

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by LJQZZZ123** [comment]
Do you see the task list? Could you do self-checking first and get community support for token validation?

**Comment by baba7ji** [comment]
I shaw that and I checked it also

**Comment by LJQZZZ123** [comment]
But you don't look like you have seen them. All the task boxes are empty and tweet link and CMC URL are unchanged. Also not see any proof of community support.

**Comment by Timoon21** [comment]
I close the PR. Please open it later with fulfilled links.
Please note that one of the requirements is to have your token live on jupiter (market with more than $500 liquidity)

**Pull request closed without merging**
