### PR TITLE
validate PKR2 token

### PR DESCRIPTION
**Pull request by C-e-r-b-e-r-u-s**
# Validate [pkr2](https://solscan.io/token/A1C9Shy732BThWvHAN936f33N7Wm1HbFvxb2zDSoBx8F)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/PKR2_Token/status/1783956985093697964?t=yfSAGC5lFd-9GQ2B2Jq3Iw&s=19
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [+ ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [+ ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [+ ] My change matches the format in the file (no spaces between fields).
- [ ] My token is already live and trading on Jupiter.
- [ +] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [+ ] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
please come into discord

**Comment by C-e-r-b-e-r-u-s** [comment]
hello, pkr2 didnt list on jupiter. what should i do?
best regards.

**Comment by C-e-r-b-e-r-u-s** [comment]
could you please send me invitation for discord.. ty

**Comment by C-e-r-b-e-r-u-s** [comment]
IMG_20240523_210437
Please Help... 🙏🏼❤️

**Pull request closed without merging**
