### PR TITLE
Validate $SWTS / Update validated-tokens.csv

### PR DESCRIPTION
**Pull request by Sweetscoin**
# Validate [{SWTS}](https://solscan.io/token/5SwxhEunuUUcWe4ojybdDwky6dpLxAehNmF4AA71STNh})

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: [https://twitter.com/{your_account}/status/{your_tweet_id}](https://twitter.com/sweetscoin/status/1658094324284882947?s=20)
- Coingecko/ CMC URL (If available): [https://www.coingecko.com/en/coins/{id}](https://www.coingecko.com/en/coins/sweets)

## Validation (Please check off boxes):
- [☑️] The metadata provided in the PR matches what is on-chain (Mandatory)
- [☑️] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [☑️] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [☑️] My change matches the format in the file (no spaces between fields).
- [☑️] My token is already live and trading on Jupiter.
- [☑️] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.

### CODE REVIEW

**Comment by Timoon21** [comment]
Hey, please at your token at the end of the file, not at the beginning.

**Comment by Timoon21** [comment]
Can you update to match on chain metadata:
{
  "name": "SWEETS",
  "symbol": "$SWTS",
  "image": "https://arweave.net/TIiNLtJtWuC0yxXPXXQpXalXyGaUFp4rT7h8WG5EwH4"
}

**Comment by Sweetscoin** [comment]
Please at your token at the end of the file? I dont understand what you mean

**Comment by Sweetscoin** [comment]
https://github.com/jup-ag/token-list/pull/200 - is this what you mean?

**Comment by Sweetscoin** [comment]
Im not too sure what you mean by this? What line have i replaced?

**Comment by Sweetscoin** [comment]
Please can I have an update on this?

**Comment by Timoon21** [comment]
New PR: https://github.com/jup-ag/token-list/pull/202

**Pull request closed without merging**
