### PR TITLE
Validate TITOR

### PR DESCRIPTION
**Pull request by scald**
# Validate [TITOR](https://solscan.io/token/9YV4AySt9qa56JMHfsRXRRTFfZgzS3e3Tub8sq7UR9FQ)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/titorcoin/status/1787532453927633396
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/dexscan/solana/6KyUX6WtseqyXxWmfJriiXnhkGd23pZqK5jPTuPFHa3M/

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by thomas-ae-studio** [comment]
[x] Mint address: 9YV4AySt9qa56JMHfsRXRRTFfZgzS3e3Tub8sq7UR9FQ
[x] Symbol: TITOR
[x] Token Decimals: 9
[x] Token icon: https://bafkreid5ubuppgfsv3sohrnjq5nnckvulq7rnjnv75g7waixq3lfhthjaq.ipfs.nftstorage.link
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by andborges** [comment]
[x] Address: 9YV4AySt9qa56JMHfsRXRRTFfZgzS3e3Tub8sq7UR9FQ
[x] Symbol: TITOR
[x] Decimals: 9
[x] Icon: https://bafkreid5ubuppgfsv3sohrnjq5nnckvulq7rnjnv75g7waixq3lfhthjaq.ipfs.nftstorage.link/
[x] On-chain metadata Ok
[x] No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
insufficient volume

**Comment by scald** [comment]
> insufficient volume

Thanks- what is considered sufficient?

**Pull request closed without merging**
