### PR TITLE
Add $EGG to strict list

### PR DESCRIPTION
**Pull request by MoshiMoshiIndustry**
# Validate $EGG(https://solscan.io/token/wo1zgt8rfrYpvdVi4nidoj1SYfcR4pQx69bmNv2JLhQ)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/justaneggcoin
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/justanegg-2

## Validation (Please check off boxes):
- [x ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x ] My change matches the format in the file (no spaces between fields).
- [ x] My token is already live and trading on Jupiter.
- [ x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x ] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — CHANGES_REQUESTED** [review]
please host your image file elsewhere. check out other PRs for examples

**Comment by MoshiMoshiIndustry** [comment]
Made the changes requested. Using Dexscreener hosting.

**Comment by MoshiMoshiIndustry** [comment]
I have resolved these conflicts. Thank you.

https://github.com/jup-ag/token-list/pull/2445

**Review by Jymfletzfur — APPROVED** [review]

**Comment by MoshiMoshiIndustry** [comment]
Hello it was not approved because there is another $EGG project you already
strict listed. We are a very different project with a way higher market cap
and level of legitimacy. Please let us know how we can resolve this issue.


Best,
Sam

**Review by 9yoi — APPROVED** [review]

**Pull request merged**
