### PR TITLE
GOTTI Token

### PR DESCRIPTION
**Pull request by GOTTIFOUNDER**
# Validate [GOTTI](https://solscan.io/token/FoAnSCG6CcqTq2rsTi58yyYBNk1HgsbLzS6b1kTP2ACL)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/gottitoken/status/1807856780082356361
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/gotti-token

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by RRWeb3 — COMMENTED** [review]
I attest that the provided information is accurate, and the token is valid.

Mint Address: FoAnSCG6CcqTq2rsTi58yyYBNk1HgsbLzS6b1kTP2ACL
Symbol: GOTTI
Token Decimals: 9
LogoURI: https://statics.solscan.io/cdn/imgs/s60?ref=68747470733a2f2f697066732e696f2f697066732f516d623259554476394a316d54394b3157326e535432366b3455527862774353747171356435767167396e4c3443
Community Validated: true
On-chain metadata matches
No duplication on Jupiter's strict list

**Review by Jymfletzfur — APPROVED** [review]

**Comment by GOTTIFOUNDER** [comment]
Thank you for adding GOTTI your strict list and please me know if there are any issues.  Thank you

**Comment by GOTTIFOUNDER** [comment]
Not sure if there is an image issue but you can also use this imagine if needed.  Thank you
https://img1.wsimg.com/isteam/ip/94255aae-7e21-4d58-9830-e7ebf98959ef/image0(2).jpeg/:/rs=w:1160,h:1160

**Review by GOTTIFOUNDER — COMMENTED** [review]
Alternative LOGO imagine if needed: https://img1.wsimg.com/isteam/ip/94255aae-7e21-4d58-9830-e7ebf98959ef/image0(2).jpeg/:/rs=w:1160,h:1160

**Review by 9yoi — APPROVED** [review]

**Comment by GOTTIFOUNDER** [comment]
Thank you again for adding GOTTI!

**Pull request merged**
