### PR TITLE
Validate croak token (CROAK)

### PR DESCRIPTION
**Pull request by Serge-GHSHCH**
# Validate [CROAK](https://solscan.io/token/4kGAmtFAkWnpkTzW35RD7CdfDuraur49RshoFkiHW7Md)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/croakonsol/status/1792965434075189604
- Coingecko/ CMC URL (If available): in process...

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by vaso123serg** [comment]
- [x] Mint address: 4kGAmtFAkWnpkTzW35RD7CdfDuraur49RshoFkiHW7Md
- [x] Symbol: CROAK
- [x] Token Decimals: 6
- [x] Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Croak-token/master/croak_token_logo.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list
- [x] The token from the "All" list has been verified with the information on solscan.io

**Comment by VAKaiden** [comment]
I've checked information on solscan.io and confirm:
- Mint address: 4kGAmtFAkWnpkTzW35RD7CdfDuraur49RshoFkiHW7Md
- Symbol: CROAK
- Token Decimals: 6
- Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Croak-token/master/croak_token_logo.jpg
- On-chain metadata matches
- No duplication on Jupiter's strict list

**Comment by TurlanY** [comment]
- [x] Mint address: 4kGAmtFAkWnpkTzW35RD7CdfDuraur49RshoFkiHW7Md
- [x] Symbol: CROAK
- [x] Token Decimals: 6
- [x] Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Croak-token/master/croak_token_logo.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list
- [x] The token from the "All" list has been verified with the information on solscan.io
- [x] The presence of the community has been verified

**Comment by donihellatrigger** [comment]
- [x] Mint address: 4kGAmtFAkWnpkTzW35RD7CdfDuraur49RshoFkiHW7Md
- [x] Symbol: CROAK
- [x] Token Decimals: 6
- [x] Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Croak-token/master/croak_token_logo.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by rositarall** [comment]
- [x] Mint address: 4kGAmtFAkWnpkTzW35RD7CdfDuraur49RshoFkiHW7Md
- [x] Symbol: CROAK
- [x] Token Decimals: 6
- [x] Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Croak-token/master/croak_token_logo.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list
- [x] The presence of the community has been verified
- [x] The token from the "All" list has been verified with the information on solscan.io

**Comment by Danimantl** [comment]
✔️ Mint address: 5aFGUjEAr4kWnpkTzW35RD7CdfDuraur49RshoFkiHW7Md
✔️ Symbol: FROG
✔️ Token Decimals: 8
✔️ Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Frog-token/master/frog_token_logo.jpg
✔️ On-chain metadata matches
✔️ No duplication on Jupiter's strict list
✔️ Community engagement has been checked
✔️ Verified on solscan.io with "All" list details

**Comment by Briansoller** [comment]
- [x] Mint address: 7kDSJkL3HF4nmkTzW35RD7CdfDuraur49RshoFkiHW7Md
- [x] Symbol: HOP
- [x] Token Decimals: 9
- [x] Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Hop-token/master/hop_token_logo.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list
- [x] Community activity has been validated
- [x] Information cross-checked with solscan.io "All" list

**Comment by gtanjayw** [comment]
Mint address: 3hHJTgPQr2kWnpkTzW35RD7CdfDuraur49RshoFkiHW7Md
 Symbol: RIBBIT
 Token Decimals: 7
 Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Ribbit-token/master/ribbit_token_logo.jpg
 On-chain metadata matches
 No duplication on Jupiter's strict list
 Community presence has been confirmed
 Verified with solscan.io "All" list data

**Comment by hodlmodels** [comment]
- [x] Mint address: 9jHLSpA2JQ3mkTzW35RD7CdfDuraur49RshoFkiHW7Md
 - [x] Symbol: LILYPAD
 - [x] Token Decimals: 10
 - [x] Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Lilypad-token/master/lilypad_token_logo.jpg
 - [x] On-chain metadata matches
 - [x] No duplication on Jupiter's strict list
 - [x] Community involvement verified
 - [x] Matched with solscan.io "All" list

**Comment by tikonostrad** [comment]
- [x]  Mint address: 2mGHKvYQF1kWnpkTzW35RD7CdfDuraur49RshoFkiHW7Md
- [x]  Symbol: TADPOLE
- [x]  Token Decimals: 12
- [x]  Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Tadpole-token/master/tadpole_token_logo.jpg
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list
- [x]  Community authenticity checked
- [x]  Confirmed with solscan.io against "All" list

**Comment by artfulclara** [comment]
- [x]  Mint address: 8nJKHyP4HF5kWnpkTzW35RD7CdfDuraur49RshoFkiHW7Md
- [x]  Symbol: SWAMP
- [x]  Token Decimals: 11
- [x]  Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Swamp-token/master/swamp_token_logo.jpg
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list
- [x]  Community checked for activity

**Comment by wenimrick** [comment]
✔️ Mint address: 6aJSXzPQr6kWnpkTzW35RD7CdfDuraur49RshoFkiHW7Md
✔️ Symbol: BUG
✔️ Token Decimals: 13
✔️ Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Bug-token/master/bug_token_logo.jpg
✔️ On-chain metadata matches
✔️ No duplication on Jupiter's strict list
✔️ Community presence validated
✔️ Solscan.io data matched with "All" list

**Comment by healingheart** [comment]
- [x]  Symbol: PAD
- [x]  Token Decimals: 5
- [x]  Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Pad-token/master/pad_token_logo.jpg
- [x]  On-chain metadata matches
- [x]  No duplication on Jupiter's strict list
- [x]  Community interaction verified
- [x]  Information validated with solscan.io "All" list

**Comment by vitasbutya** [comment]
- [x] Mint address: 4rJSXyR4QF7kWnpkTzW35RD7CdfDuraur49RshoFkiHW7Md
 - [x] Symbol: POLLYWOG
 - [x] Token Decimals: 14
 - [x] Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Pollywog-token/master/pollywog_token_logo.jpg
 - [x] On-chain metadata matches
 - [x] No duplication on Jupiter's strict list
 - [x] Verified community involvement

**Comment by finmaestrogit** [comment]
Mint address: 3kSJYqP2JF8kWnpkTzW35RD7CdfDuraur49RshoFkiHW7Md
 Symbol: TAD
 Token Decimals: 6
 Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Tad-token/master/tad_token_logo.jpg
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by WeltraumJager** [comment]
Checked!
- [x] Mint address: 4kGAmtFAkWnpkTzW35RD7CdfDuraur49RshoFkiHW7Md
- [x] Symbol: CROAK
- [x] Token Decimals: 6
- [x] Token icon: https://raw.githubusercontent.com/UNITED-CRYPTO/Croak-token/master/croak_token_logo.jpg
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by Jymfletzfur** [comment]
insufficient volume

**Comment by Serge-GHSHCH** [comment]
> insufficient volume

@Jymfletzfur could you please provide all relevant requirements for successful validation?

**Pull request closed without merging**
