### PR TITLE
validate Any Inu (Wormhole)

### PR DESCRIPTION
**Pull request by anyinu**
# Validate AI (https://solscan.io/token/ACeWC77UeW2DBZMe7YBsuXoxLvk4dHMnPzneApau1Au6)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/AnyInuCoin/status/1762406096491167931
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/any-inu

## Validation (Please check off boxes):
- [ ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [ x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [ x] My change matches the format in the file (no spaces between fields).
- [x ] My token is already live and trading on Jupiter.
- [x ] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x ] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by 9yoi** [comment]
@anyinu we are unable to merge this quickly because your ticker duplicates another AI ticker that's already in the list. Is there any chance your team will change your ticker? Otherwise, the ticket review will be delayed

**Comment by anyinu** [comment]
Changing the ticker would be confusing for users, there's other fake tokens on solana with metadata with our ticker. We have that same ticker on 16 other chains; The strict list is an effort to prevent our users from getting scammed. It looks like the socials and website for the existing AI ticker on the strict list are dead.

**Comment by anyinu** [comment]
@9yoi

**Comment by 9yoi** [comment]
> @9yoi

**Comment by 9yoi** [comment]
> Changing the ticker would be confusing for users, there's other fake tokens on solana with metadata with our ticker. We have that same ticker on 16 other chains; The strict list is an effort to prevent our users from getting scammed. It looks like the socials and website for the existing AI ticker on the strict list are dead.

I will get a dev to look at it -- they have to add code to manually bypass symbols with duplicates for safety reasons

**Comment by randomshinichi** [comment]
Added exception, should work now. Please rebase

**Review by 9yoi — APPROVED** [review]

**Comment by randomshinichi** [comment]
@9yoi if I add an exception on main for a PR, it breaks the validator on main until we merge the PR because the validator says "there are more allowed exceptions than actual exceptions!"

**Comment by randomshinichi** [comment]
` incoming token AI (sanitized: AI) is similar to an existing symbol wDAI_v1, advise them to change`
ugh i knew this check would be bad news one day

**Review by Jymfletzfur — APPROVED** [review]

**Pull request merged**
