### PR TITLE
nub bird - nubbird

### PR DESCRIPTION
**Pull request by NeelClaudel**
# Validate [nubbird](https://solscan.io/token/2UkffpXpqkjJ1twocUE7MpZDN1ico5fvkTsG3jwLmGhk)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/NubBird888/status/1794351487759609941?s=19
- Coingecko/ CMC URL (If available):

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by facemanfacey** [comment]
Name: nub bird
Symbol: NUBBIRD
Mint Address: 2UkffpXpqkjJ1twocUE7MpZDN1ico5fvkTsG3jwLmGhk
Decimals: 18
LogoURI: https://cf-ipfs.com/ipfs/QmcNMdEQ4gs8AGETdsjJqd2pm2QFaJcNreBU5MgNJmRbHx
Community Validated: true

**Review by sholmes121 — COMMENTED** [review]
I can confirm the following details are correct and current:

Name: nub bird
Symbol: NUBBIRD
Mint Address: 2UkffpXpqkjJ1twocUE7MpZDN1ico5fvkTsG3jwLmGhk
Decimals: 6
LogoURI: https://cf-ipfs.com/ipfs/QmcNMdEQ4gs8AGETdsjJqd2pm2QFaJcNreBU5MgNJmRbHx
Community Validated: true

**Review by Morgz888 — COMMENTED** [review]
I can confirm the following details are correct and current:

Name: nub bird
Symbol: NUBBIRD
Mint Address: 2UkffpXpqkjJ1twocUE7MpZDN1ico5fvkTsG3jwLmGhk
Decimals: 6
LogoURI: https://cf-ipfs.com/ipfs/QmcNMdEQ4gs8AGETdsjJqd2pm2QFaJcNreBU5MgNJmRbHx
Community Validated: true

**Review by facemanfacey — COMMENTED** [review]
Name: nub bird
Symbol: NUBBIRD
Mint Address: 2UkffpXpqkjJ1twocUE7MpZDN1ico5fvkTsG3jwLmGhk
Decimals: 6
LogoURI: https://cf-ipfs.com/ipfs/QmcNMdEQ4gs8AGETdsjJqd2pm2QFaJcNreBU5MgNJmRbHx
Community Validated: true

**Review by NeelClaudel — COMMENTED** [review]
URL fixed

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
