### PR TITLE
Add LIQUIDATED (LIQQ) to strict list

### PR DESCRIPTION
**Pull request by Xlr8qwik**
# Validate [LIQQ](https://solscan.io/token/BoisYJqhMhgpD5291J6HRC3u1jeDkF8uSLyFy3fKb5o5)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/LIQQ_the_Coin/status/1792176228956623053
- Coingecko/ CMC URL (If available): NA

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by bdd89** [comment]
Please add LIQQ! This coin is not the usual meme. Its special and I love the character.

**Comment by danweb66** [comment]
Everything checks out. Please approve.

**Review by danweb66 — COMMENTED** [review]
Contract and Everything is legit.

**Comment by Danny-Ill** [comment]
everything Checks out, I approve and support this project

**Comment by HEAT-SOLDIER** [comment]
This project checks out please approve

**Comment by Jymfletzfur** [comment]
PR inappropriately attempts to remove 5 other tokens

**Pull request closed without merging**
