### PR TITLE
Validate WUT

### PR DESCRIPTION
**Pull request by nderman**
# Validate [WUT](https://solscan.io/token/DG5bH1BnfjB5YL7Vt3GjykkUKf6maDUW3jYvdNa9eEVa)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/WUTNOWMEOW/status/1749153893596991968
- Coingecko listing https://www.coingecko.com/en/coins/wut

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by robbestad** [comment]
Token image in coingecko doesn't match submitted token image

**Comment by nderman** [comment]
> 👎 Token image in coingecko doesn't match submitted token image

Corrected

**Review by 9yoi — APPROVED** [review]

**Comment by 9yoi** [comment]
Metadata looks correct to me, final approval goes to working group, which will be announced soon

**Comment by nderman** [comment]
> Metadata looks correct to me, final approval goes to working group, which will be announced soon

Great! Looking forward to it!

**Review by Jymfletzfur — APPROVED** [review]

**Pull request merged**
