### PR TITLE
validate FFR

### PR DESCRIPTION
**Pull request by alkinemk**
# Validate [FFR](https://solscan.io/token/ChEsTBFtT4PNEDTEfpvREFUoALMjaUhM5HyCh1jJnQn2)

## Attestations (Please provide links):
- tweet from a community member https://x.com/alkineee/status/1782050132290118046 with community support
- no CMC/coingecko listing

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by opptylabs** [comment]
Would be so easier for FFF holders

**Comment by devNepenthe** [comment]
Free the chests

**Comment by GicxHas** [comment]
Verify the chests please!

**Comment by JohnnyMcAwesome** [comment]
This would be really helpful for FFF holders as well as anyone else who wants to participate in the Fox Chest ecosystem in general, please merge these commits for my friend Alkine

**Pull request closed without merging**
