### PR TITLE
Validate BULB

### PR DESCRIPTION
**Pull request by BULB-Holdings**
# Validate [BULB](https://solscan.io/token/A6JVLMAjR1aeCfz3X2z4vVQ9GafYWVT75tC5V5qefja2)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/bulbappio/status/1764580310283665669
- Coingecko / CMC URL (If available): N/A

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by johnsonchau-bulb** [comment]
[X] On-chain metadata matches the PR
[X] Token address matches the tweet
[X] No duplication on Jupiter's strict list
[X] No duplication on CMC/CoinGecko
[X] Community validation

**Comment by olizhang27** [comment]
- [x]  On-chain metadata matches the PR
- [x]  Token address matches the tweet
- [x]  No duplication on Jupiter's strict list
- [x]  No duplication on CMC/CoinGecko
- [x]  Community validation

**Comment by yanwu-bulb** [comment]
- [ ] On-chain metadata matches the PR
- [ ] Token address matches the tweet
- [ ] No duplication on Jupiter's strict list
- [ ] No duplication on CMC/CoinGecko
- [ ] Community validation

**Comment by uesu** [comment]
* [x]  On-chain metadata matches the PR
* [x]  Token address matches the tweet
* [x]  No duplication on Jupiter's strict list
* [x]  No duplication on CMC/CoinGecko
* [x]  Community validation

**Review by 9yoi — APPROVED** [review]

**Review by 0xSoju2 — APPROVED** [review]

**Pull request merged**
