### PR TITLE
Validate 9to5io

### PR DESCRIPTION
**Pull request by Wastedgetech**
# Validate [9to5](https://solscan.io/token/2fNexKk1XFVRqRmuak4hFcgfpTSJf3HE6BH6f6bjkxz7)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/9to5iolol/status/1795686275435151551
- Coingecko/ CMC URL (If available): coingecko.com/en/coins/9to5io

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Jymfletzfur** [comment]
duplicate submission

**Comment by Wastedgetech** [comment]
> duplicate submission

Hey the previous person who submitted isn't involved in the project anymore so I cant do anything with their request can you please use mine?

**Comment by Wastedgetech** [comment]
> duplicate submission

The previous submission I saw said the coin was too new and to try again in two weeks, so I waited for the two week mark and submitted again, can you elaborate on why you closed it with "duplicate submission" please

**Comment by Wastedgetech** [comment]
Hey do I saw the original request for 9to5io but it was closed and you guys
said to try again in 2 weeks. That person is gone from the project. Can you
reopen mine?

**Comment by Wastedgetech** [comment]
Sorry, typos. How can I go about getting on the jup Strict List for 9to5io?
The person who originally opened the request is no longer on the project.
Mine was closed because it was duplicate?

Thanks

**Comment by Wastedgetech** [comment]
> duplicate submission

Hi can you please explain further why this was closed as duplicate? The original request was done by a person who's no longer working on the project. It was also closed stating the token was to new and to try again in 2 weeks. I waited until the two week mark and opened my pull request. Please explain how I can best approach getting 9to5io on the Jup Strict List. Please

**Comment by Jymfletzfur** [comment]
use this image please

https://ipfs.io/ipfs/QmRyR726nnZx62GzYVVRgYfJ7pA3nQJCtUFzb9XxqW2uHj

**Comment by Jymfletzfur** [comment]
insufficient volume

**Pull request closed without merging**
