### PR TITLE
Pepe on Sol - PEPE

### PR DESCRIPTION
**Pull request by Pepenakamoto69**
# Validate [PEPE](https://solscan.io/token/ox698TZsZAN2miNQj1FQb48A58FZ546c4sWqq9Y9vmU)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/Pepeonsolana698/status/1800571146951340050
- Coingecko/ CMC URL (If available): https://coinmarketcap.com/currencies/pepe-on-sol/
## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [Very unique character, easy to differentiate based on logo] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Pepenakamoto69** [comment]
Hi Jymfletzfur, I have am in discord. Thanks

**Comment by Jymfletzfur** [comment]
your metadata does not match what you entered into the PR

**Comment by Pepenakamoto69** [comment]
Hey, thanks Jymfletzfur. All our metadata should be correct minus a slight difference in our logo. We had a subtle rebrand post launch, but for safety our contract was already made immutable prior to the logo upgrade. Not sure if this is the issue, but I would be happy to help however I can.

**Comment by Pepenakamoto69** [comment]
Hi Jymfletzfur, I have made the amendment to our pull request to accurately reflect the meta data. Is there anything further that we need to do?

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Comment by Pepenakamoto69** [comment]
Thanks Jup Team!!

**Pull request merged**
