### PR TITLE
BER (Bougie Ber)

### PR DESCRIPTION
**Pull request by Ber2024**
# Validate [BER](https://solscan.io/token/4gb2DyZBApzz18bDGFc6gfQWQQcJn3fK6CCKrjqf4heA)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/BougieBer/status/1750352989045313592
- Coingecko/ CMC URL (If available)

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [X] My change matches the format in the file (no spaces between fields).
- [X] My token is already live and trading on Jupiter.
- [X] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by Ber2024** [comment]
https://www.geckoterminal.com/solana/pools/GStCK5ZMqi41LWVoEj811nKQXQPWhedcMwB9AjkgwmTF?utm_source=coingecko&utm_medium=referral&utm_campaign=searchresults

**Comment by Jymfletzfur** [comment]
incorrect submission

**Comment by Ber2024** [comment]
> incorrect submission

Can you please explain to me what was incorrect. Thank you

**Comment by Ber2024** [comment]
> incorrect submission

https://github.com/jup-ag/token-list/pull/1520

**Pull request closed without merging**
