### PR TITLE
BRETT GOLD - BRETTGOLD

### PR DESCRIPTION
**Pull request by mrcurseman**
# Validate [BRETTGOLD](https://solscan.io/token/F6ExBzKdLRcJkCAknQgfbhRXX78EhqoNxPnegJWPpump)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/GOLDENBRETTSOL/status/1806872385812902190
- Coingecko/ CMC URL (If available): https://www.coingecko.com/tr/coins/brett-gold / 

## Validation (Please check off boxes):
- [X] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [X] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Review by OnwardsBRETTGOLD — COMMENTED** [review]
Solid Meme with a solid community driving the project, 100% community take over thats staying 100% transparent right till we hit 1 billion MC.

**Comment by OnwardsBRETTGOLD** [comment]
Brettgold is a the next meme that will hit 1 billion marketcap because its 100% community driven, 24/7 live spaces, holding support lines strong, 100% transparent, 100% trust within the community, constantly educating and showing up everyday working for our bags.

**Comment by J3rryP** [comment]
I am part of this community and have observed that they are completely legitimate and looking to build something really great on the Solana blockchain. I can vouch for their authenticity and they are doing things the right way.

**Comment by walfs** [comment]
Comunidad transparente, apasionada y con gran conocimiento. Desarrolladores y principales pilares fieles a la misma. Token con gran potencial de crecimiento 💛✊️ $BRETTGOLD

**Comment by Celestia-NFT** [comment]
Brettgold is the New memecoin that will reach the moon !
Strong community very convicted ! Great leaders ! 
Emerging leaders in each community !
Together as one and WACMI !
#WHYNOTUS 
kob2aw

**Comment by TtocssamohT** [comment]
WHY NOT US! #BrettGold

Wen strict List; Protect out community please and TY

**Comment by Mezz420** [comment]
Brettgold is different from the average, we are a community of communities and can do nothing but grow 👍
IMG_5919

**Comment by JC1618** [comment]
Brett Gold is an organic, decentralized community with a dedicated and trustworthy core / dev team and a highly committed holder base.  This project checks all boxes as the ideal community token — truly the epitome of an open arms culture building in a transparent manner, 24-7/365.

The ticker is $BRETTGOLD!
#WhyNotUs

**Comment by Wraithwall** [comment]
BRETTDREAM

**Review by Jymfletzfur — APPROVED** [review]

**Review by 9yoi — APPROVED** [review]

**Comment by 9yoi** [comment]
https://github.com/jup-ag/token-list/pull/4886

**Pull request closed without merging**
