### PR TITLE
validate RARE

### PR DESCRIPTION
**Pull request by SuperRareBears**
# Validate [RARE](https://solscan.io/token/HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/SuperRare_Bears/status/1751180861377065139
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/superrarebears-rare

## Validation (Please check off boxes):
- [x] The metadata provided in the PR matches what is on-chain (Mandatory)
- [x] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [x] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)  

## Acknowledgement (Please check off boxes)
- [x] My change matches the format in the file (no spaces between fields).
- [x] My token is already live and trading on Jupiter.
- [x] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [x] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by ayushvasisht** [comment]
https://solscan.io/token/HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K

**Comment by YeasinAlii** [comment]
Validate [RARE](https://solscan.io/token/HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K) (https://solscan.io/token/HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K)

https://www.coingecko.com/en/coins/superrarebears-rare

**Comment by techlearnx** [comment]
Validate [RARE] (https://solscan.io/token/HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K)

CoinGecko Profile :-
https://www.coingecko.com/en/coins/superrarebears-rare

**Comment by Tartopom0** [comment]
Validate [[RARE](https://solscan.io/token/HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K)]
CoinGecko Profile :
https://www.coingecko.com/en/coins/superrarebears-rare

**Comment by Mujahidul313** [comment]
Validate [RARE](https://solscan.io/token/HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K)
https://www.coingecko.com/en/coins/superrarebears-rare

**Comment by Richman717** [comment]
https://solscan.io/token/HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K

**Comment by Mujahidul313** [comment]
Validate [[RARE](https://solscan.io/token/HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K)](https://solscan.io/token/HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K)

Coingecko
https://www.coingecko.com/en/coins/superrarebears-rare

**Comment by BalooSuperRareBears** [comment]
[x] Mint address: HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K
[x] Symbol: RARE
[x]Token Decimals: 9
[x] Token icon: https://raw.githubusercontent.com/SuperRareBears/srb-assets/main/tokens/rare/logo.png
[x] On-chain metadata matches
[x] No duplication on Jupiter's strict list

**Comment by BalooSuperRareBears** [comment]
- [x] Mint address: HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K
- [x] Symbol: RARE
- [x]Token Decimals: 9
- [x] Token icon: https://raw.githubusercontent.com/SuperRareBears/srb-assets/main/tokens/rare/logo.png
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by BalooSuperRareBears** [comment]
- [x] Mint address: HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K
- [x] Symbol: RARE
- [x] Token Decimals: 9
- [x] Token icon: https://raw.githubusercontent.com/SuperRareBears/srb-assets/main/tokens/rare/logo.png
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by ozilboss** [comment]
Validate [RARE]

https://solscan.io/token/HmLspvjpQtQEnArUyJoBSF GS38gNJwBuxAeqSV9SZ66K

CoinGecko Profile:

https://www.coingecko.com/en/coins/superrarebear s-rare

**Comment by BalooSuperRareBears** [comment]
- [x] Mint address: HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K
- [x] Symbol: RARE
- [x] Token Decimals: 9
- [x] Token icon: https://raw.githubusercontent.com/SuperRareBears/srb-assets/main/tokens/rare/logo.png
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by imon6578** [comment]
- [x] Mint address: HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K
- [x] Symbol: RARE
- [x] Token Decimals: 9
- [x] Token icon: https://raw.githubusercontent.com/SuperRareBears/srb-assets/main/tokens/rare/logo.png
- [x] On-chain metadata matches
- [x] No duplication on Jupiter's strict list

**Comment by mizanur010** [comment]
Validate [RARE]

https://solscan.io/token/HmLspvjpQtQEnArUyJoBSF GS38gNJwBuxAeqSV9SZ66K

CoinGecko Profile:

https://www.coingecko.com/en/coins/superrarebears-rare

 Mint address: HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K
 Symbol: RARE
 Token Decimals: 9
 Token icon: https://raw.githubusercontent.com/SuperRareBears/srb-assets/main/tokens/rare/logo.png
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Review by mizanur010 — COMMENTED** [review]
Validate [RARE]

https://solscan.io/token/HmLspvjpQtQEnArUyJoBSF GS38gNJwBuxAeqSV9SZ66K

CoinGecko Profile:

https://www.coingecko.com/en/coins/superrarebears-rare

 Mint address: HmLspvjpQtQEnArUyJoBSFGS38gNJwBuxAeqSV9SZ66K
 Symbol: RARE
 Token Decimals: 9
 Token icon: https://raw.githubusercontent.com/SuperRareBears/srb-assets/main/tokens/rare/logo.png
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by SuperRareBears** [comment]
Reopen, closed in error

**Comment by SuperRareBears** [comment]
Reopen, closed in error

**Comment by BalooSuperRareBears** [comment]
Hello, @9yoi can you please check our PR? Thanks!

**Pull request closed without merging**
